/*
 * sc_pd.c -- FUSB302B USB-PD negotiate hooks (impl)
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power/power.py (regulator chain)
 *   carrier/subsystems/power_mon/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#include "zynq_carrier_contract.h"
#include "sc_hal.h"
#include "sc_pd.h"

/* FUSB302B 7-bit address straight from the hardware contract.         */
#define SC_PD_FUSB302B_ADDR  ZC_I2C_ADDR_FUSB302B

int sc_pd_init(void) {
    /* A 1-byte read of the Device ID register (0x01) probes presence.  */
    uint8_t reg = 0x01;
    uint8_t id = 0;
    if (sc_i2c_write(SC_PD_FUSB302B_ADDR, &reg, 1) != 0) return -1;
    if (sc_i2c_read(SC_PD_FUSB302B_ADDR, &id, 1) != 0) return -1;
    sc_log("FUSB302B present");
    return 0;
}

int sc_pd_request(uint32_t min_mv, uint32_t min_ma) {
    /* TODO(port): drive a PD Request through the FUSB302B for a source */
    /* capability that meets (min_mv, min_ma).  Until a PD stack runs   */
    /* this, +VIN stays at the 5 V default contract (BRINGUP.md St.1).  */
    (void)min_mv; (void)min_ma;
    return -1;
}

void sc_pd_on_irq(void) {
    /* SC_INT_N is the wire-OR of FUSB302B INT and TCA9535 INT#; the    */
    /* handler reads BOTH devices' status registers (contract note).    */
    /* TODO(port): read FUSB302B Interrupt regs and dispatch to policy. */
}
