/*
 * sc_tables.h -- netlist-derived SC tables (rails, I2C, EN map, monitors)
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power/power.py (regulator chain)
 *   carrier/subsystems/power_mon/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#ifndef SC_TABLES_H
#define SC_TABLES_H

#include <stdint.h>
#include <stdbool.h>
#include "sc_hal.h"

/* ======================================================================== */
/* Rail bring-up step table (order = the regulator chain)                   */
/* ======================================================================== */
/* The order below IS the power.py regulator chain: each stage's     */
/* input is the previous stage's output, so it is not optional       */
/* (BRINGUP.md Stage 2).  The always-on rails (+3V3_SC + the inlet)   */
/* are listed separately -- they are up before any sequencing runs.  */
typedef enum {
    SC_RAIL_P5V,
    SC_RAIL_P3V3,
    SC_RAIL_P1V8,
    SC_RAIL_COUNT  /* = 3 */
} sc_rail_id_t;

/* One sequenced rail stage.  `en_override` is the SC's VETO GPIO on   */
/* the EN cell (EN = DIP AND override): drive it LOW to force the rail */
/* OFF, leave it HIGH/Hi-Z to let the DIP rule.  Software can NEVER    */
/* force a rail ON with its DIP open (bringup_en semantics).  `pg_*`   */
/* is the INA3221 telemetry the stepper polls to confirm the rail.     */
typedef struct {
    sc_rail_id_t id;
    const char  *name;          /* rail net, e.g. "+5V" */
    uint32_t     vout_mv;       /* expected setpoint [mV] */
    const char  *en_net;        /* EN_* cell output net */
    sc_gpio_t    en_override;   /* SC veto GPIO (port=0 if none) */
    uint16_t     settle_ms;     /* wait after enable before PG poll */
    uint8_t      pmon_addr7;    /* INA3221 7-bit addr (0 = no telem) */
    uint8_t      pmon_channel;  /* INA3221 channel 1..3 */
    uint16_t     shunt_mohm;    /* sense-shunt value [mOhm] */
} sc_rail_step_t;

extern const sc_rail_step_t sc_rail_steps[SC_RAIL_COUNT];

/* The always-on rails -- present before any sequencing (BRINGUP.md    */
/* Stage 1: +3V3_SC is generated from VIN before PD negotiation).      */
#define SC_ALWAYS_ON_COUNT 2
extern const char *const sc_always_on_rails[SC_ALWAYS_ON_COUNT];

/* ======================================================================== */
/* Module load-switch gate table (SY6280, current-limited)                  */
/* ======================================================================== */
/* Each module rail is gated by a SY6280 behind its own EN cell and  */
/* current limit (BRINGUP.md Stage 3/4).  These are enabled AFTER    */
/* the core rails, one at a time, with the same veto semantics.      */
typedef enum {
    SC_MOD_HDMI_TX,
    SC_MOD_HDMI_RX,
    SC_MOD_LCD,
    SC_MOD_CAM,
    SC_MOD_SD,
    SC_MOD_USB,
    SC_MOD_PMOD,
    SC_MOD_USER_LED,
    SC_MOD_HDMI_TX_5V,
    SC_MOD_LCD_5V,
    SC_MOD_COUNT  /* = 10 */
} sc_module_id_t;

/* `tca_bit` is the bit index in the TCA9535 16-bit output word that   */
/* drives this module's override (P00=0 .. P17=15); 0xFF = direct GPIO */
/* (none routed through the expander).                                 */
typedef struct {
    sc_module_id_t id;
    const char    *module;      /* "HDMI_TX" ... */
    const char    *rail_in;     /* source rail */
    const char    *rail_out;    /* gated rail */
    const char    *en_net;      /* EN_* cell output */
    uint16_t       ilim_ma;     /* SY6280 current limit [mA] */
    uint8_t        tca_bit;     /* TCA9535 output bit (0xFF if direct) */
} sc_module_gate_t;

extern const sc_module_gate_t sc_module_gates[SC_MOD_COUNT];

/* ======================================================================== */
/* I2C device map (bus = STM32_I2C2; 7-bit addresses)                       */
/* ======================================================================== */
/* The bus is a firmware BIT-BANG on PA4/PA5 (the contract's         */
/* ZC_I2C_BITBANG_* lines): the real I2C2 AF pins are the on-module  */
/* SC<->Zynq link.  Addresses come straight from the contract header.*/
typedef struct {
    const char *name;
    uint8_t     addr7;
} sc_i2c_dev_t;

#define SC_I2C_DEV_COUNT 7
extern const sc_i2c_dev_t sc_i2c_devices[SC_I2C_DEV_COUNT];

#endif /* SC_TABLES_H */
