"""CP2102N-A02-GQFN24R — CP2102N-A02-GQFN24R (QFN-24_L4.0-W4.0-P0.50-TL-EP2.6)

Generated by `schgen part add C969151` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'CP2102N-A02-GQFN24R'
SAFE_NAME = 'CP2102N-A02-GQFN24R'
LCSC = 'C969151'
DESCRIPTION = 'CP2102N-A02-GQFN24R (QFN-24_L4.0-W4.0-P0.50-TL-EP2.6)'
MANUFACTURER = 'SKYWORKS/SILICON LABS(芯科)'
PACKAGE = 'QFN-24_L4.0-W4.0-P0.50-TL-EP2.6'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C969151.pdf'
PRODUCT_URL = ''
LIB_ID = 'CP2102N-A02-GQFN24R:CP2102N-A02-GQFN24R'
FOOTPRINT = 'CP2102N-A02-GQFN24R:CP2102N-A02-GQFN24R'
MODELS_3D = ['CP2102N-A02-GQFN24R.wrl', 'CP2102N-A02-GQFN24R.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'RI/CLK', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'D+', 'passive'),
    ('4', 'D-', 'passive'),
    ('5', 'VIO', 'passive'),
    ('6', 'VDD', 'passive'),
    ('7', 'VREGIN', 'passive'),
    ('8', 'VBUS', 'passive'),
    ('9', 'RSTb', 'passive'),
    ('10', 'NC', 'passive'),
    ('11', 'GPIO.3/WAKEUP', 'passive'),
    ('12', 'GPIO.2/RS485', 'passive'),
    ('13', 'GPIO.1/RXT', 'passive'),
    ('14', 'GPIO.0/TXT', 'passive'),
    ('15', 'SUSPENDb', 'passive'),
    ('16', 'NC', 'passive'),
    ('17', 'SUSPEND', 'passive'),
    ('18', 'CTS', 'passive'),
    ('19', 'RTS', 'passive'),
    ('20', 'RXD', 'passive'),
    ('21', 'TXD', 'passive'),
    ('22', 'DSR', 'passive'),
    ('23', 'DTR', 'passive'),
    ('24', 'DCD', 'passive'),
    ('25', 'GND', 'passive'),
]
