"""24AA025E48T-I/OT — 24AA025E48T-I/OT (SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BR)

Generated by `schgen part add C129895` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = '24AA025E48T-I/OT'
SAFE_NAME = '24AA025E48T-I_OT'
LCSC = 'C129895'
DESCRIPTION = '24AA025E48T-I/OT (SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BR)'
MANUFACTURER = 'MICROCHIP(美国微芯)'
PACKAGE = 'SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BR'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C129895.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/EEPROM_MICROCHIP_24AA025E48T-I-OT_24AA025E48T-I-OT_C129895.html'
LIB_ID = '24AA025E48T-I_OT:24AA025E48T-I_OT'
FOOTPRINT = '24AA025E48T-I_OT:24AA025E48T-I_OT'
MODELS_3D = ['24AA025E48T-I_OT.wrl', '24AA025E48T-I_OT.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'SCL', 'passive'),
    ('2', 'VSS', 'power_in'),
    ('3', 'SDA', 'bidirectional'),
    ('4', 'A1', 'passive'),
    ('5', 'A0', 'passive'),
    ('6', 'VCC', 'power_in'),
]
