"""AO3400A — AO3400A

Generated by `schgen part add C20917` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'AO3400A'
SAFE_NAME = 'AO3400A'
LCSC = 'C20917'
DESCRIPTION = 'AO3400A'
MANUFACTURER = 'AOS'
PACKAGE = 'SOT-23-3_L2.9-W1.3-P1.90-LS2.4-BR'
JLC_CLASS = 'Basic Part'
PREFIX = 'Q'
DATASHEET = 'https://www.lcsc.com/datasheet/C20917.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/MOSFET_AOS_AO3400A_AO3400A_C20917.html'
LIB_ID = 'AO3400A:AO3400A'
FOOTPRINT = 'AO3400A:AO3400A'
MODELS_3D = ['AO3400A.wrl', 'AO3400A.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('3', 'D', 'passive'),
    ('1', 'G', 'passive'),
    ('2', 'S', 'passive'),
]
