"""TPD12S016PWR — TPD12S016PWR (TSSOP-24_L7.8-W4.4-P0.65-LS6.4-BL)

Generated by `schgen part add C201665` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPD12S016PWR'
SAFE_NAME = 'TPD12S016PWR'
LCSC = 'C201665'
DESCRIPTION = 'TPD12S016PWR (TSSOP-24_L7.8-W4.4-P0.65-LS6.4-BL)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'TSSOP-24_L7.8-W4.4-P0.65-LS6.4-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C201665.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/_TI_TPD12S016PWR_TPD12S016PWR_C201665.html'
LIB_ID = 'TPD12S016PWR:TPD12S016PWR'
FOOTPRINT = 'TPD12S016PWR:TPD12S016PWR'
MODELS_3D = ['TPD12S016PWR.wrl', 'TPD12S016PWR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'CEC_A', 'passive'),
    ('2', 'SCL_A', 'passive'),
    ('3', 'SDA_A', 'passive'),
    ('4', 'HPD_A-', 'passive'),
    ('5', 'LS_OE', 'passive'),
    ('6', 'GND', 'passive'),
    ('7', 'CEC_B', 'passive'),
    ('8', 'SCL_B', 'passive'),
    ('9', 'SDA_B', 'passive'),
    ('10', 'HPD_B-', 'passive'),
    ('11', 'VCC5V', 'passive'),
    ('12', 'CT_HPD', 'passive'),
    ('13', '5V_OUT', 'passive'),
    ('14', 'GND', 'passive'),
    ('15', 'CLK-', 'passive'),
    ('16', 'CLK+', 'passive'),
    ('17', 'D0-', 'passive'),
    ('18', 'D0+', 'passive'),
    ('19', 'GND', 'passive'),
    ('20', 'D1-', 'passive'),
    ('21', 'D1+', 'passive'),
    ('22', 'D2-', 'passive'),
    ('23', 'D2+', 'passive'),
    ('24', 'VCCA', 'passive'),
]
