"""TF-01A — TF-01A (TF-SMD_TF-01A)

Generated by `schgen part add C91145` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TF-01A'
SAFE_NAME = 'TF-01A'
LCSC = 'C91145'
DESCRIPTION = 'TF-01A (TF-SMD_TF-01A)'
MANUFACTURER = '韩国韩荣'
PACKAGE = 'TF-SMD_TF-01A'
JLC_CLASS = 'Extended Part'
PREFIX = 'Card'
DATASHEET = 'https://www.lcsc.com/datasheet/C91145.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Card-Sockets_TF-01A_C91145.html'
LIB_ID = 'TF-01A:TF-01A'
FOOTPRINT = 'TF-01A:TF-01A'
MODELS_3D = ['TF-01A.wrl', 'TF-01A.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'DAT2(RSV)', 'bidirectional'),
    ('2', 'CDDAT3(CS)', 'bidirectional'),
    ('3', 'CMD(DI)', 'input'),
    ('4', 'VDD', 'input'),
    ('5', 'CLK(SCLK)', 'input'),
    ('6', 'VSS', 'input'),
    ('7', 'DAT0(D0)', 'bidirectional'),
    ('8', 'DAT1(RSV)', 'bidirectional'),
    ('13', 'GND', 'input'),
    ('10', 'GND', 'input'),
    ('11', 'GND', 'input'),
    ('12', 'GND', 'input'),
    ('9', 'CD', 'input'),
]
