"""RLM12FTCMR010 — RLM12FTCMR010 (R1206)

Generated by `schgen part add C188070` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'RLM12FTCMR010'
SAFE_NAME = 'RLM12FTCMR010'
LCSC = 'C188070'
DESCRIPTION = 'RLM12FTCMR010 (R1206)'
MANUFACTURER = '大毅科技'
PACKAGE = 'R1206'
JLC_CLASS = 'Extended Part'
PREFIX = 'R'
DATASHEET = 'https://www.lcsc.com/datasheet/C188070.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Low-Resistors-Current-Sense-Resistors-Surface-Mount_TA-I-Tech-RLM12FTCMR010_C188070.html'
LIB_ID = 'RLM12FTCMR010:RLM12FTCMR010'
FOOTPRINT = 'RLM12FTCMR010:RLM12FTCMR010'
MODELS_3D = ['RLM12FTCMR010.wrl', 'RLM12FTCMR010.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('2', '2', 'passive'),
    ('1', '1', 'passive'),
]
