"""KH-CR1220-2 — KH-CR1220-2 (BAT-SMD_CR1220-2)

Generated by `schgen part add C5365933` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'KH-CR1220-2'
SAFE_NAME = 'KH-CR1220-2'
LCSC = 'C5365933'
DESCRIPTION = 'KH-CR1220-2 (BAT-SMD_CR1220-2)'
MANUFACTURER = 'kinghelm(金航标)'
PACKAGE = 'BAT-SMD_CR1220-2'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C5365933.pdf'
PRODUCT_URL = ''
LIB_ID = 'KH-CR1220-2:KH-CR1220-2'
FOOTPRINT = 'KH-CR1220-2:KH-CR1220-2'
MODELS_3D = ['KH-CR1220-2.wrl', 'KH-CR1220-2.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('2', '2', 'passive'),
    ('1', '1', 'passive'),
]
