"""TPD4E1U06DBVR — 4 通道高速 ESD 保护器件 SOT-23-6

Generated by `schgen part add C124691` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPD4E1U06DBVR'
SAFE_NAME = 'TPD4E1U06DBVR'
LCSC = 'C124691'
DESCRIPTION = '4 通道高速 ESD 保护器件 SOT-23-6'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BR'
JLC_CLASS = 'Extended Part'
PREFIX = 'D'
DATASHEET = 'https://www.lcsc.com/datasheet/C124691.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Others_Texas-Instruments_TPD4E1U06DBVR_Texas-Instruments-TI-TPD4E1U06DBVR_C124691.html'
LIB_ID = 'TPD4E1U06DBVR:TPD4E1U06DBVR'
FOOTPRINT = 'TPD4E1U06DBVR:TPD4E1U06DBVR'
MODELS_3D = ['TPD4E1U06DBVR.wrl', 'TPD4E1U06DBVR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'D1+', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'D2+', 'passive'),
    ('6', 'D1-', 'passive'),
    ('5', 'NC', 'passive'),
    ('4', 'D2-', 'passive'),
]
