"""SN74LVC125ADR — SN74LVC125ADR (SOIC-14_L8.7-W3.9-P1.27-LS6.0-BL)

Generated by `schgen part add C7661` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'SN74LVC125ADR'
SAFE_NAME = 'SN74LVC125ADR'
LCSC = 'C7661'
DESCRIPTION = 'SN74LVC125ADR (SOIC-14_L8.7-W3.9-P1.27-LS6.0-BL)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'SOIC-14_L8.7-W3.9-P1.27-LS6.0-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C7661.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/74-Series_TI_SN74LVC125ADRG4_SN74LVC125ADRG4_C7661.html'
LIB_ID = 'SN74LVC125ADR:SN74LVC125ADR'
FOOTPRINT = 'SN74LVC125ADR:SN74LVC125ADR'
MODELS_3D = ['SN74LVC125ADR.wrl', 'SN74LVC125ADR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1OE#', 'passive'),
    ('2', '1A', 'passive'),
    ('3', '1Y', 'passive'),
    ('4', '2OE#', 'passive'),
    ('5', '2A', 'passive'),
    ('6', '2Y', 'passive'),
    ('7', 'GND', 'passive'),
    ('8', '3Y', 'passive'),
    ('9', '3A', 'passive'),
    ('10', '3OE#', 'passive'),
    ('11', '4Y', 'passive'),
    ('12', '4A', 'passive'),
    ('13', '4OE#', 'passive'),
    ('14', 'VCC', 'passive'),
]
