"""1C208000BC0R — DSX321G 8MHz (CRYSTAL-SMD_4P-L3.2-W2.5-BL-1)

Generated by `schgen part add C57131` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = '1C208000BC0R'
SAFE_NAME = '1C208000BC0R'
LCSC = 'C57131'
DESCRIPTION = 'DSX321G 8MHz (CRYSTAL-SMD_4P-L3.2-W2.5-BL-1)'
MANUFACTURER = 'KDS(大真空)'
PACKAGE = 'CRYSTAL-SMD_4P-L3.2-W2.5-BL-1'
JLC_CLASS = 'Extended Part'
PREFIX = 'X'
DATASHEET = 'https://www.lcsc.com/datasheet/C57131.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/SMD-Crystals_KDS_DSX321G-8MHz_8MHz-12pF-20ppm_C57131.html'
LIB_ID = '1C208000BC0R:1C208000BC0R'
FOOTPRINT = '1C208000BC0R:1C208000BC0R'
MODELS_3D = ['1C208000BC0R.wrl', '1C208000BC0R.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('3', 'OSC2', 'passive'),
    ('2', 'NC', 'passive'),
    ('4', 'NC', 'passive'),
    ('1', 'OSC1', 'passive'),
]
