"""TPD4E05U06DQAR — TPD4E05U06DQAR_C138714 (USON-10_L2.5-W1.0-P0.50-BL)

Generated by `schgen part add C138714` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPD4E05U06DQAR'
SAFE_NAME = 'TPD4E05U06DQAR'
LCSC = 'C138714'
DESCRIPTION = 'TPD4E05U06DQAR_C138714 (USON-10_L2.5-W1.0-P0.50-BL)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'USON-10_L2.5-W1.0-P0.50-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'D'
DATASHEET = 'https://www.lcsc.com/datasheet/C138714.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/TVS_TI_TPD4E05U06DQAR_TPD4E05U06DQAR_C138714.html'
LIB_ID = 'TPD4E05U06DQAR:TPD4E05U06DQAR'
FOOTPRINT = 'TPD4E05U06DQAR:TPD4E05U06DQAR'
MODELS_3D = ['TPD4E05U06DQAR.wrl', 'TPD4E05U06DQAR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'D1+', 'passive'),
    ('2', 'D1-', 'passive'),
    ('3', 'GND', 'passive'),
    ('4', 'D2+', 'passive'),
    ('5', 'D2-', 'passive'),
    ('6', 'NC', 'passive'),
    ('7', 'NC', 'passive'),
    ('8', 'GND', 'passive'),
    ('9', 'NC', 'passive'),
    ('10', 'NC', 'passive'),
]
