"""HX JN1.27-2x5 TP H4.9 — HX JN1.27-2X5 TP H4.9 (IDC-SMD_10P-P1.27-3220-10-0300-00)

Generated by `schgen part add C42372555` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'HX JN1.27-2x5 TP H4.9'
SAFE_NAME = 'HX_JN1.27-2x5_TP_H4.9'
LCSC = 'C42372555'
DESCRIPTION = 'HX JN1.27-2X5 TP H4.9 (IDC-SMD_10P-P1.27-3220-10-0300-00)'
MANUFACTURER = 'hanxia(韩下)'
PACKAGE = 'IDC-SMD_10P-P1.27-3220-10-0300-00'
JLC_CLASS = 'Extended Part'
PREFIX = 'CN'
DATASHEET = 'https://www.lcsc.com/datasheet/C42372555.pdf'
PRODUCT_URL = ''
LIB_ID = 'HX_JN1.27-2x5_TP_H4.9:HX_JN1.27-2x5_TP_H4.9'
FOOTPRINT = 'HX_JN1.27-2x5_TP_H4.9:HX_JN1.27-2x5_TP_H4.9'
MODELS_3D = ['HX_JN1.27-2x5_TP_H4.9.wrl', 'HX_JN1.27-2x5_TP_H4.9.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('10', '10', 'passive'),
    ('3', '3', 'passive'),
    ('8', '8', 'passive'),
    ('5', '5', 'passive'),
    ('6', '6', 'passive'),
    ('7', '7', 'passive'),
    ('4', '4', 'passive'),
    ('9', '9', 'passive'),
    ('2', '2', 'passive'),
]
