"""878311420 — 87831-1420 (CONN-TH_14P-P2.00_87831-1420)

Generated by `schgen part add C240854` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = '878311420'
SAFE_NAME = '878311420'
LCSC = 'C240854'
DESCRIPTION = '87831-1420 (CONN-TH_14P-P2.00_87831-1420)'
MANUFACTURER = 'MOLEX'
PACKAGE = 'CONN-TH_14P-P2.00_87831-1420'
JLC_CLASS = 'Extended Part'
PREFIX = 'CN'
DATASHEET = 'https://www.lcsc.com/datasheet/C240854.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Others_MOLEX_87831-1420_MOLEX-87831-1420_C240854.html'
LIB_ID = '878311420:878311420'
FOOTPRINT = '878311420:878311420'
MODELS_3D = ['878311420.wrl', '878311420.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('3', '3', 'passive'),
    ('5', '5', 'passive'),
    ('7', '7', 'passive'),
    ('9', '9', 'passive'),
    ('11', '11', 'passive'),
    ('13', '13', 'passive'),
    ('14', '14', 'passive'),
    ('12', '12', 'passive'),
    ('10', '10', 'passive'),
    ('8', '8', 'passive'),
    ('6', '6', 'passive'),
    ('4', '4', 'passive'),
    ('2', '2', 'passive'),
]
