"""HX PZ2.54-3x8P ZZ — HX PZ2.54-3X8P ZZ (HDR-TH_24P-P2.54-V-M-R3-C8-S2.54_1)

Generated by `schgen part add C32713295` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'HX PZ2.54-3x8P ZZ'
SAFE_NAME = 'HX_PZ2.54-3x8P_ZZ'
LCSC = 'C32713295'
DESCRIPTION = 'HX PZ2.54-3X8P ZZ (HDR-TH_24P-P2.54-V-M-R3-C8-S2.54_1)'
MANUFACTURER = 'hanxia(韩下)'
PACKAGE = 'HDR-TH_24P-P2.54-V-M-R3-C8-S2.54_1'
JLC_CLASS = 'Extended Part'
PREFIX = 'H'
DATASHEET = 'https://www.lcsc.com/datasheet/C32713295.pdf'
PRODUCT_URL = ''
LIB_ID = 'HX_PZ2.54-3x8P_ZZ:HX_PZ2.54-3x8P_ZZ'
FOOTPRINT = 'HX_PZ2.54-3x8P_ZZ:HX_PZ2.54-3x8P_ZZ'
MODELS_3D = []

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('24', '24', 'passive'),
    ('23', '23', 'passive'),
    ('22', '22', 'passive'),
    ('21', '21', 'passive'),
    ('20', '20', 'passive'),
    ('19', '19', 'passive'),
    ('18', '18', 'passive'),
    ('17', '17', 'passive'),
    ('16', '16', 'passive'),
    ('15', '15', 'passive'),
    ('14', '14', 'passive'),
    ('13', '13', 'passive'),
    ('12', '12', 'passive'),
    ('11', '11', 'passive'),
    ('10', '10', 'passive'),
    ('9', '9', 'passive'),
    ('8', '8', 'passive'),
    ('7', '7', 'passive'),
    ('6', '6', 'passive'),
    ('5', '5', 'passive'),
    ('4', '4', 'passive'),
    ('3', '3', 'passive'),
    ('2', '2', 'passive'),
    ('1', '1', 'passive'),
]
