##############################################################################
# Zynq_Carrier_pins.xdc — GENERATED by `schgen xdc`. DO NOT EDIT.
# Device: XC7Z020-CLG484 (U2 on the SoM)
# Sources (all programmatic, zero hand-typed pins):
#   ball map : som/Zynq_SoM.kicad_sch netlist (kicad-cli, at generation time)
#   contract : carrier/som_interface.json (cross-checked pin-for-pin, stale = build FAIL)
#   types    : carrier subsystems' typed-port registry
# VCCO rail map (carrier/PLAN.md): bank 13 = +3V3, bank 33 = +3V3, bank 34 = +3V3, bank 35 = +2V5_VADJ
# 156 pins, banks 13/33/34/35, 30 clock-capable (MRCC/SRCC)
# Ports named IO_* are the bound SoM contract nets not yet claimed
# by a function sheet; the wave-3 function map renames them here
# automatically on the next `schgen board`.
##############################################################################

# ---- bank 13 — VCCO = +3V3 (43 pins) --------------------
set_property -dict {PACKAGE_PIN AA9  IOSTANDARD LVCMOS33} [get_ports {DBG_UART_RXD}]  ;# J2.42 IO_L11P_T1_SRCC_13 <- usb_jtag
#   ^ SRCC-capable: # create_clock -name DBG_UART_RXD -period <ns> [get_ports {DBG_UART_RXD}]
set_property -dict {PACKAGE_PIN AA8  IOSTANDARD LVCMOS33} [get_ports {DBG_UART_TXD}]  ;# J2.40 IO_L11N_T1_SRCC_13 <- usb_jtag
set_property -dict {PACKAGE_PIN U7   IOSTANDARD LVCMOS33} [get_ports {IO_25_13}]  ;# J2.23 IO_25_13 <- user_io
set_property -dict {PACKAGE_PIN Y10  IOSTANDARD LVCMOS33} [get_ports {IO_L10_N_13}]  ;# J2.51 IO_L10N_T1_13 <- pmod
set_property -dict {PACKAGE_PIN Y11  IOSTANDARD LVCMOS33} [get_ports {IO_L10_P_13}]  ;# J2.53 IO_L10P_T1_13 <- pmod
set_property -dict {PACKAGE_PIN AB2  IOSTANDARD LVCMOS33} [get_ports {IO_L15_P_13}]  ;# J2.9 IO_L15P_T2_DQS_13 <- user_io
set_property -dict {PACKAGE_PIN R6   IOSTANDARD LVCMOS33} [get_ports {IO_L19_P_13}]  ;# J2.12 IO_L19P_T3_13 <- user_io
set_property -dict {PACKAGE_PIN V10  IOSTANDARD LVCMOS33} [get_ports {IO_L1P_13}]  ;# J2.57 IO_L1P_T0_13 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN V9   IOSTANDARD LVCMOS33} [get_ports {IO_L1_N_13}]  ;# J2.37 IO_L1N_T0_13 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN V5   IOSTANDARD LVCMOS33} [get_ports {IO_L21_P_13}]  ;# J2.13 IO_L21P_T3_DQS_13 <- user_io
set_property -dict {PACKAGE_PIN U6   IOSTANDARD LVCMOS33} [get_ports {IO_L22_P_13}]  ;# J2.19 IO_L22P_T3_13 <- user_io
set_property -dict {PACKAGE_PIN W5   IOSTANDARD LVCMOS33} [get_ports {IO_L24_N_13}]  ;# J2.7 IO_L24N_T3_13 <- user_io
set_property -dict {PACKAGE_PIN W6   IOSTANDARD LVCMOS33} [get_ports {IO_L24_P_13}]  ;# J2.10 IO_L24P_T3_13 <- user_io
set_property -dict {PACKAGE_PIN W8   IOSTANDARD LVCMOS33} [get_ports {IO_L2_N_13}]  ;# J2.14 IO_L2N_T0_13 <- pmod
set_property -dict {PACKAGE_PIN V8   IOSTANDARD LVCMOS33} [get_ports {IO_L2_P_13}]  ;# J2.20 IO_L2P_T0_13 <- pmod
set_property -dict {PACKAGE_PIN W10  IOSTANDARD LVCMOS33} [get_ports {IO_L3_N_13}]  ;# J2.43 IO_L3N_T0_DQS_13 <- pmod
set_property -dict {PACKAGE_PIN W11  IOSTANDARD LVCMOS33} [get_ports {IO_L3_P_13}]  ;# J2.18 IO_L3P_T0_DQS_13 <- pmod
set_property -dict {PACKAGE_PIN W12  IOSTANDARD LVCMOS33} [get_ports {IO_L4_N_13}]  ;# J2.63 IO_L4N_T0_13 <- pmod
set_property -dict {PACKAGE_PIN V12  IOSTANDARD LVCMOS33} [get_ports {IO_L4_P_13}]  ;# J2.61 IO_L4P_T0_13 <- pmod
set_property -dict {PACKAGE_PIN U12  IOSTANDARD LVCMOS33} [get_ports {IO_L5P_13}]  ;# J2.38 IO_L5P_T0_13 <- pmod
set_property -dict {PACKAGE_PIN U11  IOSTANDARD LVCMOS33} [get_ports {IO_L5_N_13}]  ;# J2.24 IO_L5N_T0_13 <- pmod
set_property -dict {PACKAGE_PIN U10  IOSTANDARD LVCMOS33} [get_ports {IO_L6_P_13}]  ;# J2.21 IO_L6P_T0_13 <- user_io
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS33} [get_ports {IO_L7_N_13}]  ;# J2.64 IO_L7N_T1_13 <- pmod
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS33} [get_ports {IO_L7_P_13}]  ;# J2.62 IO_L7P_T1_13 <- pmod
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports {IO_L8_N_13}]  ;# J2.60 IO_L8N_T1_13 <- pmod
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVCMOS33} [get_ports {IO_L8_P_13}]  ;# J2.58 IO_L8P_T1_13 <- pmod
set_property -dict {PACKAGE_PIN AB9  IOSTANDARD LVCMOS33} [get_ports {IO_L9_DQS_N_13}]  ;# J2.48 IO_L9N_T1_DQS_13 <- pmod
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports {IO_L9_DQS_P_13}]  ;# J2.50 IO_L9P_T1_DQS_13 <- pmod
set_property -dict {PACKAGE_PIN AB6  IOSTANDARD LVCMOS33} [get_ports {LCD_CTP_INT}]  ;# J2.32 IO_L17N_T2_13 <- lcd
set_property -dict {PACKAGE_PIN AB7  IOSTANDARD LVCMOS33} [get_ports {LCD_CTP_RST}]  ;# J2.34 IO_L17P_T2_13 <- lcd
set_property -dict {PACKAGE_PIN AB4  IOSTANDARD LVCMOS33} [get_ports {LCD_CTP_SCL}]  ;# J2.28 IO_L16N_T2_13 <- lcd
set_property -dict {PACKAGE_PIN AB5  IOSTANDARD LVCMOS33} [get_ports {LCD_CTP_SDA}]  ;# J2.30 IO_L16P_T2_13 <- lcd
set_property -dict {PACKAGE_PIN Y6   IOSTANDARD LVCMOS33} [get_ports {PMODX_IO1}]  ;# J2.29 IO_L13P_T2_MRCC_13 <- pmod_expansion
#   ^ MRCC-capable: # create_clock -name PMODX_IO1 -period <ns> [get_ports {PMODX_IO1}]
set_property -dict {PACKAGE_PIN Y5   IOSTANDARD LVCMOS33} [get_ports {PMODX_IO2}]  ;# J2.27 IO_L13N_T2_MRCC_13 <- pmod_expansion
set_property -dict {PACKAGE_PIN V7   IOSTANDARD LVCMOS33} [get_ports {PMODX_IO3}]  ;# J2.33 IO_L23P_T3_13 <- pmod_expansion
set_property -dict {PACKAGE_PIN W7   IOSTANDARD LVCMOS33} [get_ports {PMODX_IO4}]  ;# J2.31 IO_L23N_T3_13 <- pmod_expansion
set_property -dict {PACKAGE_PIN AA7  IOSTANDARD LVCMOS33} [get_ports {PMODX_IO5}]  ;# J2.41 IO_L14P_T2_SRCC_13 <- pmod_expansion
#   ^ SRCC-capable: # create_clock -name PMODX_IO5 -period <ns> [get_ports {PMODX_IO5}]
set_property -dict {PACKAGE_PIN AA6  IOSTANDARD LVCMOS33} [get_ports {PMODX_IO6}]  ;# J2.39 IO_L14N_T2_SRCC_13 <- pmod_expansion
set_property -dict {PACKAGE_PIN Y9   IOSTANDARD LVCMOS33} [get_ports {PMODX_IO7}]  ;# J2.49 IO_L12P_T1_MRCC_13 <- pmod_expansion
#   ^ MRCC-capable: # create_clock -name PMODX_IO7 -period <ns> [get_ports {PMODX_IO7}]
set_property -dict {PACKAGE_PIN Y8   IOSTANDARD LVCMOS33} [get_ports {PMODX_IO8}]  ;# J2.47 IO_L12N_T1_MRCC_13 <- pmod_expansion
set_property -dict {PACKAGE_PIN U9   IOSTANDARD LVCMOS33} [get_ports {SD_CARD_DETECT}]  ;# J2.17 IO_L6N_T0_VREF_13 <- microsd
set_property -dict {PACKAGE_PIN Y4   IOSTANDARD LVCMOS33} [get_ports {ZYNQ_PS_UART0_CTS_N}]  ;# J2.11 IO_L18P_T2_13 <- uart_bridge
set_property -dict {PACKAGE_PIN AA4  IOSTANDARD LVCMOS33} [get_ports {ZYNQ_PS_UART0_RTS_N}]  ;# J2.8 IO_L18N_T2_13 <- uart_bridge

# ---- bank 33 — VCCO = +3V3 (39 pins) --------------------
set_property -dict {PACKAGE_PIN T22  IOSTANDARD LVCMOS33} [get_ports {CAM_EN}]  ;# J3.85 IO_L2P_T0_33 <- camera
set_property -dict {PACKAGE_PIN U22  IOSTANDARD LVCMOS33} [get_ports {CAM_LED}]  ;# J3.87 IO_L2N_T0_33 <- camera
set_property -dict {PACKAGE_PIN T21  IOSTANDARD LVCMOS33} [get_ports {CAM_SCL}]  ;# J3.86 IO_L1P_T0_33 <- camera
set_property -dict {PACKAGE_PIN U21  IOSTANDARD LVCMOS33} [get_ports {CAM_SDA}]  ;# J3.89 IO_L1N_T0_33 <- camera
set_property -dict {PACKAGE_PIN V18  IOSTANDARD LVCMOS33} [get_ports {FMC_PRSNT_N}]  ;# J2.89 IO_L6P_T0_33 <- fmc
set_property -dict {PACKAGE_PIN W13  IOSTANDARD LVCMOS33} [get_ports {HDMI_RX_5V_DET}]  ;# J2.44 IO_L20N_T3_33 <- hdmi_rx
set_property -dict {PACKAGE_PIN V13  IOSTANDARD LVCMOS33} [get_ports {HDMI_RX_CEC}]  ;# J2.59 IO_L20P_T3_33 <- hdmi_rx
# tmds_pair (100R): HDMI_RX_CLK_P / HDMI_RX_CLK_N
set_property -dict {PACKAGE_PIN Y18  IOSTANDARD TMDS_33} [get_ports {HDMI_RX_CLK_P}]  ;# J2.90 IO_L12P_T1_MRCC_33 <- hdmi_rx, hdmi_rx_term
#   ^ MRCC-capable: # create_clock -name HDMI_RX_CLK_P -period <ns> [get_ports {HDMI_RX_CLK_P}]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD TMDS_33} [get_ports {HDMI_RX_CLK_N}]  ;# J2.88 IO_L12N_T1_MRCC_33 <- hdmi_rx, hdmi_rx_term
# tmds_pair (100R): HDMI_RX_D0_P / HDMI_RX_D0_N
set_property -dict {PACKAGE_PIN AB19 IOSTANDARD TMDS_33} [get_ports {HDMI_RX_D0_P}]  ;# J2.92 IO_L10P_T1_33 <- hdmi_rx, hdmi_rx_term
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD TMDS_33} [get_ports {HDMI_RX_D0_N}]  ;# J2.94 IO_L10N_T1_33 <- hdmi_rx, hdmi_rx_term
# tmds_pair (100R): HDMI_RX_D1_P / HDMI_RX_D1_N
set_property -dict {PACKAGE_PIN AA17 IOSTANDARD TMDS_33} [get_ports {HDMI_RX_D1_P}]  ;# J2.82 IO_L17P_T2_33 <- hdmi_rx, hdmi_rx_term
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD TMDS_33} [get_ports {HDMI_RX_D1_N}]  ;# J2.84 IO_L17N_T2_33 <- hdmi_rx, hdmi_rx_term
# tmds_pair (100R): HDMI_RX_D2_P / HDMI_RX_D2_N
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD TMDS_33} [get_ports {HDMI_RX_D2_P}]  ;# J2.78 IO_L18P_T2_33 <- hdmi_rx, hdmi_rx_term
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD TMDS_33} [get_ports {HDMI_RX_D2_N}]  ;# J2.80 IO_L18N_T2_33 <- hdmi_rx, hdmi_rx_term
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33} [get_ports {IO_L11_SRCC_N_33}]  ;# J2.91 IO_L11N_T1_SRCC_33 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN Y19  IOSTANDARD LVCMOS33} [get_ports {IO_L11_SRCC_P_33}]  ;# J2.93 IO_L11P_T1_SRCC_33 <- unclaimed (wave-3 function map)
#   ^ SRCC-capable: # create_clock -name IO_L11_SRCC_P_33 -period <ns> [get_ports {IO_L11_SRCC_P_33}]
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD LVCMOS33} [get_ports {IO_L14_SRCC_N_33}]  ;# J2.83 IO_L14N_T2_SRCC_33 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN W16  IOSTANDARD LVCMOS33} [get_ports {IO_L14_SRCC_P_33}]  ;# J2.81 IO_L14P_T2_SRCC_33 <- unclaimed (wave-3 function map)
#   ^ SRCC-capable: # create_clock -name IO_L14_SRCC_P_33 -period <ns> [get_ports {IO_L14_SRCC_P_33}]
set_property -dict {PACKAGE_PIN W22  IOSTANDARD LVCMOS33} [get_ports {IO_L3_DQS_N_33}]  ;# J3.93 IO_L3N_T0_DQS_33 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN V22  IOSTANDARD LVCMOS33} [get_ports {IO_L3_DQS_P_33}]  ;# J3.91 IO_L3P_T0_DQS_33 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN V20  IOSTANDARD LVCMOS33} [get_ports {IO_L5_N_33}]  ;# J3.94 IO_L5N_T0_33 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN U20  IOSTANDARD LVCMOS33} [get_ports {IO_L5_P_33}]  ;# J3.92 IO_L5P_T0_33 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN U14  IOSTANDARD LVCMOS33} [get_ports {PL_BTN0}]  ;# J2.79 IO_25_33 <- bringup_rails
set_property -dict {PACKAGE_PIN V17  IOSTANDARD LVCMOS33} [get_ports {PL_BTN1}]  ;# J2.87 IO_L16N_T2_33 <- bringup_rails
set_property -dict {PACKAGE_PIN W21  IOSTANDARD LVCMOS33} [get_ports {WATCHDOG_KICK}]  ;# J3.96 IO_L4N_T0_33 <- board_services
set_property -dict {PACKAGE_PIN W20  IOSTANDARD LVCMOS33} [get_ports {WATCHDOG_RST_N}]  ;# J3.98 IO_L4P_T0_33 <- board_services
set_property -dict {PACKAGE_PIN V15  IOSTANDARD LVCMOS33} [get_ports {ZYNQ_HDMI_TX_CEC}]  ;# J2.77 IO_L19N_T3_VREF_33 <- hdmi_tx
set_property -dict {PACKAGE_PIN U16  IOSTANDARD LVCMOS33} [get_ports {ZYNQ_HDMI_TX_HPD}]  ;# J2.54 IO_L15N_T2_DQS_33 <- hdmi_tx
set_property -dict {PACKAGE_PIN V14  IOSTANDARD LVCMOS33} [get_ports {ZYNQ_HDMI_TX_SCL}]  ;# J2.22 IO_L19P_T3_33 <- hdmi_tx
set_property -dict {PACKAGE_PIN U15  IOSTANDARD LVCMOS33} [get_ports {ZYNQ_HDMI_TX_SDA}]  ;# J2.52 IO_L15P_T2_DQS_33 <- hdmi_tx
# tmds_pair (100R): ZYNQ_HDMI_TX_TMDS_0_P / ZYNQ_HDMI_TX_TMDS_0_N
set_property -dict {PACKAGE_PIN Y14  IOSTANDARD TMDS_33} [get_ports {ZYNQ_HDMI_TX_TMDS_0_P}]  ;# J2.67 IO_L22P_T3_33 <- hdmi_tx
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD TMDS_33} [get_ports {ZYNQ_HDMI_TX_TMDS_0_N}]  ;# J2.69 IO_L22N_T3_33 <- hdmi_tx
# tmds_pair (100R): ZYNQ_HDMI_TX_TMDS_1_P / ZYNQ_HDMI_TX_TMDS_1_N
set_property -dict {PACKAGE_PIN Y13  IOSTANDARD TMDS_33} [get_ports {ZYNQ_HDMI_TX_TMDS_1_P}]  ;# J2.70 IO_L23P_T3_33 <- hdmi_tx
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD TMDS_33} [get_ports {ZYNQ_HDMI_TX_TMDS_1_N}]  ;# J2.68 IO_L23N_T3_33 <- hdmi_tx
# tmds_pair (100R): ZYNQ_HDMI_TX_TMDS_2_P / ZYNQ_HDMI_TX_TMDS_2_N
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD TMDS_33} [get_ports {ZYNQ_HDMI_TX_TMDS_2_P}]  ;# J2.72 IO_L24P_T3_33 <- hdmi_tx
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD TMDS_33} [get_ports {ZYNQ_HDMI_TX_TMDS_2_N}]  ;# J2.74 IO_L24N_T3_33 <- hdmi_tx
# tmds_pair (100R): ZYNQ_HDMI_TX_TMDS_CLK_P / ZYNQ_HDMI_TX_TMDS_CLK_N
set_property -dict {PACKAGE_PIN W15  IOSTANDARD TMDS_33} [get_ports {ZYNQ_HDMI_TX_TMDS_CLK_P}]  ;# J2.71 IO_L21P_T3_DQS_33 <- hdmi_tx
set_property -dict {PACKAGE_PIN Y15  IOSTANDARD TMDS_33} [get_ports {ZYNQ_HDMI_TX_TMDS_CLK_N}]  ;# J2.73 IO_L21N_T3_DQS_33 <- hdmi_tx

# ---- bank 34 — VCCO = +3V3 (34 pins) --------------------
set_property -dict {PACKAGE_PIN T19  IOSTANDARD LVCMOS33} [get_ports {IO_L22_N_34}]  ;# J3.84 IO_L22N_T3_34 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN R18  IOSTANDARD LVCMOS33} [get_ports {IO_L23_P_34}]  ;# J3.88 IO_L23P_T3_34 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN P16  IOSTANDARD LVCMOS33} [get_ports {IO_L24_P_34}]  ;# J3.82 IO_L24P_T3_34 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN L22  IOSTANDARD LVCMOS33} [get_ports {LCD_B0}]  ;# J3.65 IO_L10N_T1_34 <- lcd
set_property -dict {PACKAGE_PIN M19  IOSTANDARD LVCMOS33} [get_ports {LCD_B1}]  ;# J3.66 IO_L13P_T2_MRCC_34 <- lcd
#   ^ MRCC-capable: # create_clock -name LCD_B1 -period <ns> [get_ports {LCD_B1}]
set_property -dict {PACKAGE_PIN L21  IOSTANDARD LVCMOS33} [get_ports {LCD_B2}]  ;# J3.67 IO_L10P_T1_34 <- lcd
set_property -dict {PACKAGE_PIN M22  IOSTANDARD LVCMOS33} [get_ports {LCD_B3}]  ;# J3.69 IO_L15N_T2_DQS_34 <- lcd
set_property -dict {PACKAGE_PIN N20  IOSTANDARD LVCMOS33} [get_ports {LCD_B4}]  ;# J3.70 IO_L14N_T2_SRCC_34 <- lcd
set_property -dict {PACKAGE_PIN M21  IOSTANDARD LVCMOS33} [get_ports {LCD_B5}]  ;# J3.71 IO_L15P_T2_DQS_34 <- lcd
set_property -dict {PACKAGE_PIN N19  IOSTANDARD LVCMOS33} [get_ports {LCD_B6}]  ;# J3.72 IO_L14P_T2_SRCC_34 <- lcd
#   ^ SRCC-capable: # create_clock -name LCD_B6 -period <ns> [get_ports {LCD_B6}]
set_property -dict {PACKAGE_PIN P21  IOSTANDARD LVCMOS33} [get_ports {LCD_B7}]  ;# J3.74 IO_L18N_T2_34 <- lcd
set_property -dict {PACKAGE_PIN R21  IOSTANDARD LVCMOS33} [get_ports {LCD_BL_PWM}]  ;# J3.81 IO_L17N_T2_34 <- lcd
set_property -dict {PACKAGE_PIN M16  IOSTANDARD LVCMOS33} [get_ports {LCD_DE}]  ;# J3.78 IO_L6N_T0_VREF_34 <- lcd
set_property -dict {PACKAGE_PIN R20  IOSTANDARD LVCMOS33} [get_ports {LCD_DISP}]  ;# J3.79 IO_L17P_T2_34 <- lcd
set_property -dict {PACKAGE_PIN J21  IOSTANDARD LVCMOS33} [get_ports {LCD_G0}]  ;# J3.55 IO_L8P_T1_34 <- lcd
set_property -dict {PACKAGE_PIN K20  IOSTANDARD LVCMOS33} [get_ports {LCD_G1}]  ;# J3.56 IO_L11N_T1_SRCC_34 <- lcd
set_property -dict {PACKAGE_PIN J22  IOSTANDARD LVCMOS33} [get_ports {LCD_G2}]  ;# J3.57 IO_L8N_T1_34 <- lcd
set_property -dict {PACKAGE_PIN J20  IOSTANDARD LVCMOS33} [get_ports {LCD_G3}]  ;# J3.59 IO_L9P_T1_DQS_34 <- lcd
set_property -dict {PACKAGE_PIN N17  IOSTANDARD LVCMOS33} [get_ports {LCD_G4}]  ;# J3.60 IO_L5P_T0_34 <- lcd
set_property -dict {PACKAGE_PIN K21  IOSTANDARD LVCMOS33} [get_ports {LCD_G5}]  ;# J3.61 IO_L9N_T1_DQS_34 <- lcd
set_property -dict {PACKAGE_PIN L19  IOSTANDARD LVCMOS33} [get_ports {LCD_G6}]  ;# J3.62 IO_L12N_T1_MRCC_34 <- lcd
set_property -dict {PACKAGE_PIN M20  IOSTANDARD LVCMOS33} [get_ports {LCD_G7}]  ;# J3.64 IO_L13N_T2_MRCC_34 <- lcd
set_property -dict {PACKAGE_PIN P18  IOSTANDARD LVCMOS33} [get_ports {LCD_HSYNC}]  ;# J3.76 IO_L20N_T3_34 <- lcd
set_property -dict {PACKAGE_PIN N22  IOSTANDARD LVCMOS33} [get_ports {LCD_PCLK}]  ;# J3.75 IO_L16P_T2_34 <- lcd
set_property -dict {PACKAGE_PIN J18  IOSTANDARD LVCMOS33} [get_ports {LCD_R0}]  ;# J3.19 IO_L7P_T1_34 <- lcd
set_property -dict {PACKAGE_PIN R16  IOSTANDARD LVCMOS33} [get_ports {LCD_R1}]  ;# J3.21 IO_L24N_T3_34 <- lcd
set_property -dict {PACKAGE_PIN P17  IOSTANDARD LVCMOS33} [get_ports {LCD_R2}]  ;# J3.30 IO_L20P_T3_34 <- lcd
set_property -dict {PACKAGE_PIN N18  IOSTANDARD LVCMOS33} [get_ports {LCD_R3}]  ;# J3.36 IO_L5N_T0_34 <- lcd
set_property -dict {PACKAGE_PIN K18  IOSTANDARD LVCMOS33} [get_ports {LCD_R4}]  ;# J3.40 IO_L7N_T1_34 <- lcd
set_property -dict {PACKAGE_PIN M17  IOSTANDARD LVCMOS33} [get_ports {LCD_R5}]  ;# J3.41 IO_L4N_T0_34 <- lcd
set_property -dict {PACKAGE_PIN L18  IOSTANDARD LVCMOS33} [get_ports {LCD_R6}]  ;# J3.46 IO_L12P_T1_MRCC_34 <- lcd
#   ^ MRCC-capable: # create_clock -name LCD_R6 -period <ns> [get_ports {LCD_R6}]
set_property -dict {PACKAGE_PIN K19  IOSTANDARD LVCMOS33} [get_ports {LCD_R7}]  ;# J3.54 IO_L11P_T1_SRCC_34 <- lcd
#   ^ SRCC-capable: # create_clock -name LCD_R7 -period <ns> [get_ports {LCD_R7}]
set_property -dict {PACKAGE_PIN P22  IOSTANDARD LVCMOS33} [get_ports {LCD_VSYNC}]  ;# J3.77 IO_L16N_T2_34 <- lcd
set_property -dict {PACKAGE_PIN K16  IOSTANDARD LVCMOS33} [get_ports {PUDC_34}]  ;# J3.39 IO_L3P_T0_DQS_PUDC_B_34 <- bringup_rails

# ---- bank 35 — VCCO = +2V5_VADJ (40 pins) --------------------
# diff_pair (100R): CAM_CLK_P / CAM_CLK_N
set_property -dict {PACKAGE_PIN B19  IOSTANDARD LVDS_25} [get_ports {CAM_CLK_P}]  ;# J3.9 IO_L13P_T2_MRCC_35 <- camera
#   ^ MRCC-capable: # create_clock -name CAM_CLK_P -period <ns> [get_ports {CAM_CLK_P}]
set_property -dict {PACKAGE_PIN B20  IOSTANDARD LVDS_25} [get_ports {CAM_CLK_N}]  ;# J3.11 IO_L13N_T2_MRCC_35 <- camera
# diff_pair (100R): CAM_D0_P / CAM_D0_N
set_property -dict {PACKAGE_PIN A18  IOSTANDARD LVDS_25} [get_ports {CAM_D0_P}]  ;# J3.5 IO_L10P_T1_AD11P_35 <- camera
set_property -dict {PACKAGE_PIN A19  IOSTANDARD LVDS_25} [get_ports {CAM_D0_N}]  ;# J3.7 IO_L10N_T1_AD11N_35 <- camera
# diff_pair (100R): CAM_D1_P / CAM_D1_N
set_property -dict {PACKAGE_PIN A21  IOSTANDARD LVDS_25} [get_ports {CAM_D1_P}]  ;# J3.17 IO_L15P_T2_DQS_AD12P_35 <- camera
set_property -dict {PACKAGE_PIN A22  IOSTANDARD LVDS_25} [get_ports {CAM_D1_N}]  ;# J3.15 IO_L15N_T2_DQS_AD12N_35 <- camera
# diff_pair (100R): FMC_CLK0_M2C_P / FMC_CLK0_M2C_N
set_property -dict {PACKAGE_PIN D18  IOSTANDARD LVDS_25} [get_ports {FMC_CLK0_M2C_P}]  ;# J3.14 IO_L12P_T1_MRCC_35 <- fmc
#   ^ MRCC-capable: # create_clock -name FMC_CLK0_M2C_P -period <ns> [get_ports {FMC_CLK0_M2C_P}]
set_property -dict {PACKAGE_PIN C19  IOSTANDARD LVDS_25} [get_ports {FMC_CLK0_M2C_N}]  ;# J3.16 IO_L12N_T1_MRCC_35 <- fmc
# diff_pair (100R): FMC_CLK1_M2C_P / FMC_CLK1_M2C_N
set_property -dict {PACKAGE_PIN C17  IOSTANDARD LVDS_25} [get_ports {FMC_CLK1_M2C_P}]  ;# J3.8 IO_L11P_T1_SRCC_35 <- fmc
#   ^ SRCC-capable: # create_clock -name FMC_CLK1_M2C_P -period <ns> [get_ports {FMC_CLK1_M2C_P}]
set_property -dict {PACKAGE_PIN C18  IOSTANDARD LVDS_25} [get_ports {FMC_CLK1_M2C_N}]  ;# J3.10 IO_L11N_T1_SRCC_35 <- fmc
# diff_pair (100R): FMC_LA00_CC_P / FMC_LA00_CC_N
set_property -dict {PACKAGE_PIN D20  IOSTANDARD LVDS_25} [get_ports {FMC_LA00_CC_P}]  ;# J3.22 IO_L14P_T2_AD4P_SRCC_35 <- fmc
#   ^ SRCC-capable: # create_clock -name FMC_LA00_CC_P -period <ns> [get_ports {FMC_LA00_CC_P}]
set_property -dict {PACKAGE_PIN C20  IOSTANDARD LVDS_25} [get_ports {FMC_LA00_CC_N}]  ;# J3.20 IO_L14N_T2_AD4N_SRCC_35 <- fmc
# diff_pair (100R): FMC_LA01_CC_P / FMC_LA01_CC_N
set_property -dict {PACKAGE_PIN E19  IOSTANDARD LVDS_25} [get_ports {FMC_LA01_CC_P}]  ;# J3.24 IO_L21P_T3_DQS_AD14P_35 <- fmc
set_property -dict {PACKAGE_PIN E20  IOSTANDARD LVDS_25} [get_ports {FMC_LA01_CC_N}]  ;# J3.26 IO_L21N_T3_DQS_AD14N_35 <- fmc
# diff_pair (100R): FMC_LA02_P / FMC_LA02_N
set_property -dict {PACKAGE_PIN E21  IOSTANDARD LVDS_25} [get_ports {FMC_LA02_P}]  ;# J3.37 IO_L17P_T2_AD5P_35 <- fmc
set_property -dict {PACKAGE_PIN D21  IOSTANDARD LVDS_25} [get_ports {FMC_LA02_N}]  ;# J3.35 IO_L17N_T2_AD5N_35 <- fmc
# diff_pair (100R): FMC_LA03_P / FMC_LA03_N
set_property -dict {PACKAGE_PIN G19  IOSTANDARD LVDS_25} [get_ports {FMC_LA03_P}]  ;# J3.34 IO_L20P_T3_AD6P_35 <- fmc
set_property -dict {PACKAGE_PIN F19  IOSTANDARD LVDS_25} [get_ports {FMC_LA03_N}]  ;# J3.32 IO_L20N_T3_AD6N_35 <- fmc
# diff_pair (100R): FMC_LA04_P / FMC_LA04_N
set_property -dict {PACKAGE_PIN G20  IOSTANDARD LVDS_25} [get_ports {FMC_LA04_P}]  ;# J3.42 IO_L22P_T3_AD7P_35 <- fmc
set_property -dict {PACKAGE_PIN G21  IOSTANDARD LVDS_25} [get_ports {FMC_LA04_N}]  ;# J3.44 IO_L22N_T3_AD7N_35 <- fmc
# diff_pair (100R): FMC_LA05_P / FMC_LA05_N
set_property -dict {PACKAGE_PIN F21  IOSTANDARD LVDS_25} [get_ports {FMC_LA05_P}]  ;# J3.47 IO_L23P_T3_35 <- fmc
set_property -dict {PACKAGE_PIN F22  IOSTANDARD LVDS_25} [get_ports {FMC_LA05_N}]  ;# J3.45 IO_L23N_T3_35 <- fmc
# diff_pair (100R): FMC_LA06_P / FMC_LA06_N
set_property -dict {PACKAGE_PIN H22  IOSTANDARD LVDS_25} [get_ports {FMC_LA06_P}]  ;# J3.51 IO_L24P_T3_AD15P_35 <- fmc
set_property -dict {PACKAGE_PIN G22  IOSTANDARD LVDS_25} [get_ports {FMC_LA06_N}]  ;# J3.49 IO_L24N_T3_AD15N_35 <- fmc
# diff_pair (100R): FMC_LA07_P / FMC_LA07_N
set_property -dict {PACKAGE_PIN H19  IOSTANDARD LVDS_25} [get_ports {FMC_LA07_P}]  ;# J3.50 IO_L19P_T3_35 <- fmc
set_property -dict {PACKAGE_PIN H20  IOSTANDARD LVDS_25} [get_ports {FMC_LA07_N}]  ;# J3.52 IO_L19N_T3_VREF_35 <- fmc
# diff_pair (100R): FMC_LA08_P / FMC_LA08_N
set_property -dict {PACKAGE_PIN F16  IOSTANDARD LVDS_25} [get_ports {FMC_LA08_P}]  ;# J1.74 IO_L1P_T0_AD0P_35 <- fmc
set_property -dict {PACKAGE_PIN E16  IOSTANDARD LVDS_25} [get_ports {FMC_LA08_N}]  ;# J1.92 IO_L1N_T0_AD0N_35 <- fmc
# diff_pair (100R): FMC_LA09_P / FMC_LA09_N
set_property -dict {PACKAGE_PIN G15  IOSTANDARD LVDS_25} [get_ports {FMC_LA09_P}]  ;# J1.80 IO_L4P_T0_35 <- fmc
set_property -dict {PACKAGE_PIN G16  IOSTANDARD LVDS_25} [get_ports {FMC_LA09_N}]  ;# J1.84 IO_L4N_T0_35 <- fmc
# diff_pair (100R): FMC_LA10_P / FMC_LA10_N
set_property -dict {PACKAGE_PIN F18  IOSTANDARD LVDS_25} [get_ports {FMC_LA10_P}]  ;# J1.90 IO_L5P_T0_AD9P_35 <- fmc
set_property -dict {PACKAGE_PIN E18  IOSTANDARD LVDS_25} [get_ports {FMC_LA10_N}]  ;# J1.88 IO_L5N_T0_AD9N_35 <- fmc
# diff_pair (100R): FMC_LA11_P / FMC_LA11_N
set_property -dict {PACKAGE_PIN G17  IOSTANDARD LVDS_25} [get_ports {FMC_LA11_P}]  ;# J1.78 IO_L6P_T0_35 <- fmc
set_property -dict {PACKAGE_PIN F17  IOSTANDARD LVDS_25} [get_ports {FMC_LA11_N}]  ;# J1.76 IO_L6N_T0_VREF_35 <- fmc
set_property -dict {PACKAGE_PIN H17  IOSTANDARD LVCMOS25} [get_ports {IO_0_35}]  ;# J1.86 IO_0_35 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN C22  IOSTANDARD LVCMOS25} [get_ports {IO_L16_N_35}]  ;# J3.29 IO_L16N_T2_35 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN D22  IOSTANDARD LVCMOS25} [get_ports {IO_L16_P_35}]  ;# J3.31 IO_L16P_T2_35 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN B22  IOSTANDARD LVCMOS25} [get_ports {IO_L18_N_35}]  ;# J3.25 IO_L18N_T2_AD13N_35 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN B21  IOSTANDARD LVCMOS25} [get_ports {IO_L18_P_35}]  ;# J3.27 IO_L18P_T2_AD13P_35 <- unclaimed (wave-3 function map)
set_property -dict {PACKAGE_PIN D17  IOSTANDARD LVCMOS25} [get_ports {IO_L2_N_35}]  ;# J1.100 IO_L2N_T0_AD8N_35 <- unclaimed (wave-3 function map)
