"""HX5008NLT — HX5008NLT (SOP-24_L13.2-W15.1-P0.99-LS18.7-BL)

Generated by `schgen part add C962544` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'HX5008NLT'
SAFE_NAME = 'HX5008NLT'
LCSC = 'C962544'
DESCRIPTION = 'HX5008NLT (SOP-24_L13.2-W15.1-P0.99-LS18.7-BL)'
MANUFACTURER = 'PULSE(普思)'
PACKAGE = 'SOP-24_L13.2-W15.1-P0.99-LS18.7-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'L'
DATASHEET = 'https://www.lcsc.com/datasheet/C962544.pdf'
PRODUCT_URL = ''
LIB_ID = 'HX5008NLT:HX5008NLT'
FOOTPRINT = 'HX5008NLT:HX5008NLT'
MODELS_3D = ['HX5008NLT.wrl', 'HX5008NLT.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'TCT1', 'passive'),
    ('2', 'TD1+', 'passive'),
    ('3', 'TD1-', 'passive'),
    ('4', 'TCT2', 'passive'),
    ('5', 'TD2+', 'passive'),
    ('6', 'TD2-', 'passive'),
    ('7', 'TCT3', 'passive'),
    ('8', 'TD3+', 'passive'),
    ('9', 'TD3-', 'passive'),
    ('10', 'TCT4', 'passive'),
    ('11', 'TD4+', 'passive'),
    ('12', 'TD4-', 'passive'),
    ('13', 'MX4-', 'passive'),
    ('14', 'MX4+', 'passive'),
    ('15', 'MCT4', 'passive'),
    ('16', 'MX3-', 'passive'),
    ('17', 'MX3+', 'passive'),
    ('18', 'MCT3', 'passive'),
    ('19', 'MX2-', 'passive'),
    ('20', 'MX2+', 'passive'),
    ('21', 'MCT2', 'passive'),
    ('22', 'MX1-', 'passive'),
    ('23', 'MX1+', 'passive'),
    ('24', 'MCT1', 'passive'),
]
