"""PCA9306DCUR — PCA9306DCUR (SSOP-8_L2.0-W2.3-P0.50-LS3.1-BR)

Generated by `schgen part add C33196` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'PCA9306DCUR'
SAFE_NAME = 'PCA9306DCUR'
LCSC = 'C33196'
DESCRIPTION = 'PCA9306DCUR (SSOP-8_L2.0-W2.3-P0.50-LS3.1-BR)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'SSOP-8_L2.0-W2.3-P0.50-LS3.1-BR'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C33196.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Interface-ICs_TI_PCA9306DCUR_PCA9306DCUR_C33196.html'
LIB_ID = 'PCA9306DCUR:PCA9306DCUR'
FOOTPRINT = 'PCA9306DCUR:PCA9306DCUR'
MODELS_3D = ['PCA9306DCUR.wrl', 'PCA9306DCUR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'GND', 'passive'),
    ('2', 'VREF1', 'passive'),
    ('3', 'SCL1', 'passive'),
    ('4', 'SDA1', 'passive'),
    ('5', 'SDA2', 'passive'),
    ('6', 'SCL2', 'passive'),
    ('7', 'VREF2', 'passive'),
    ('8', 'EN', 'passive'),
]
