"""DSHP08TSGER — DSHP08TSGER_C3293147 (SW-SMD_16P-L11.7-W5.4-P1.27-LS8.5)

Generated by `schgen part add C3293147` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'DSHP08TSGER'
SAFE_NAME = 'DSHP08TSGER'
LCSC = 'C3293147'
DESCRIPTION = 'DSHP08TSGER_C3293147 (SW-SMD_16P-L11.7-W5.4-P1.27-LS8.5)'
MANUFACTURER = '康深'
PACKAGE = 'SW-SMD_16P-L11.7-W5.4-P1.27-LS8.5'
JLC_CLASS = 'Extended Part'
PREFIX = 'SW'
DATASHEET = 'https://www.lcsc.com/datasheet/C3293147.pdf'
PRODUCT_URL = ''
LIB_ID = 'DSHP08TSGER:DSHP08TSGER'
FOOTPRINT = 'DSHP08TSGER:DSHP08TSGER'
MODELS_3D = ['DSHP08TSGER.wrl', 'DSHP08TSGER.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'PIN1', 'passive'),
    ('2', 'PIN2', 'passive'),
    ('3', 'PIN3', 'passive'),
    ('4', 'PIN4', 'passive'),
    ('5', 'PIN5', 'passive'),
    ('6', 'PIN6', 'passive'),
    ('7', 'PIN7', 'passive'),
    ('8', 'PIN8', 'passive'),
    ('9', 'PIN9', 'passive'),
    ('10', 'PIN10', 'passive'),
    ('11', 'PIN11', 'passive'),
    ('12', 'PIN12', 'passive'),
    ('13', 'PIN13', 'passive'),
    ('14', 'PIN14', 'passive'),
    ('15', '15', 'passive'),
    ('16', '16', 'passive'),
]
