"""SN74HCT245PWR — 74系列逻辑芯片

Generated by `schgen part add C6779` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'SN74HCT245PWR'
SAFE_NAME = 'SN74HCT245PWR'
LCSC = 'C6779'
DESCRIPTION = '74系列逻辑芯片'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'TSSOP-20_L6.5-W4.4-P0.65-LS6.4-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C6779.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/74-Series_TI_SN74HCT245PWR_SN74HCT245PWR_C6779.html'
LIB_ID = 'SN74HCT245PWR:SN74HCT245PWR'
FOOTPRINT = 'SN74HCT245PWR:SN74HCT245PWR'
MODELS_3D = ['SN74HCT245PWR.wrl', 'SN74HCT245PWR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'DIR', 'passive'),
    ('2', 'A1', 'passive'),
    ('3', 'A2', 'passive'),
    ('4', 'A3', 'passive'),
    ('5', 'A4', 'passive'),
    ('6', 'A5', 'passive'),
    ('7', 'A6', 'passive'),
    ('8', 'A7', 'passive'),
    ('9', 'A8', 'passive'),
    ('10', 'GND', 'passive'),
    ('11', 'B8', 'passive'),
    ('12', 'B7', 'passive'),
    ('13', 'B6', 'passive'),
    ('14', 'B5', 'passive'),
    ('15', 'B4', 'passive'),
    ('16', 'B3', 'passive'),
    ('17', 'B2', 'passive'),
    ('18', 'B1', 'passive'),
    ('19', '#OE', 'passive'),
    ('20', 'VCC', 'passive'),
]
