##############################################################################
# create_project.tcl — GENERATED by `schgen vivado`. DO NOT EDIT.
#
# One-shot Vivado project from the schgen-generated pin constraints:
#     cd carrier/fpga
#     vivado -mode batch -source create_project.tcl
#
# Device: xc7z020clg400-1 (U2 on the SoM, live kicad-cli extraction — never hard-coded)
# Pin constraints: pins.xdc (4 ports, generated by `schgen xdc`)
# Determinism: device + pins + clocks all derive from the SoM netlist;
# no timestamps, sorted ordering -> byte-identical on re-run.
##############################################################################

# Resolve paths relative to THIS script so it sources from any cwd.
set script_dir [file dirname [file normalize [info script]]]

set project_name zynq_carrier
set part xc7z020clg400-1

# ---- project ----------------------------------------------------
# In-memory project under the script dir; -force overwrites a prior run.
create_project -force $project_name $script_dir/$project_name -part $part
set_property part $part [current_project]

# ---- pin + IO constraints (schgen xdc, proved against the SoM) --
set xdc_file [file normalize $script_dir/pins.xdc]
if {![file exists $xdc_file]} {
    error "missing constraints: $xdc_file — run `schgen xdc` (or `schgen board`) first"
}
add_files -fileset constrs_1 -norecurse $xdc_file
read_xdc $xdc_file

# ---- clocks -----------------------------------------------------
# MRCC/SRCC-capable PL ports the XDC flags as clock candidates.
# Promoted to real constraints (documented fixed source period):
create_clock -name A_P -period 10 [get_ports {A_P}]  ;# J1.2 IO_L1P_MRCC_34 (MRCC)
# No documented fixed period for these (source-synchronous / recovered /
# FPGA-driven). Left as TEMPLATES — uncomment and set <ns> for the real
# source frequency before timing closure (matches the XDC templates).
# create_clock -name B_P -period <ns> [get_ports {B_P}]  ;# J1.4 IO_L2P_SRCC_34 (SRCC)

# ---- Zynq7 Processing System (PS) — COMMENTED STUB ---------------
# The PS DDR/MIO preset is SoM-revision intent and does NOT live in
# the carrier netlist, so the PS is left for you to instantiate.
# Uncomment to start a block design with a PS7, then APPLY THE SoM'S
# PS PRESET (DDR3 timing, MIO, clocks) before generating the wrapper.
#
# create_bd_design system
# set ps [create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0]
# # TODO: apply the SoM PS7 preset (board-specific DDR3/MIO/clock config):
# #   set_property -dict [list CONFIG.preset {<SoM_preset.xml or board file>}] $ps
# #   or: apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
# #         -config {make_external "FIXED_IO, DDR" apply_board_preset "1"} $ps
# validate_bd_design
# save_bd_design
# make_wrapper -files [get_files system.bd] -top
# add_files -norecurse $script_dir/$project_name/$project_name.srcs/sources_1/bd/system/hdl/system_wrapper.v

puts "schgen: project '$project_name' created for part $part; pin constraints loaded from [file tail $xdc_file]."
