##############################################################################
# Zynq_Carrier_pins.xdc — GENERATED by `schgen xdc`. DO NOT EDIT.
# Device: XC7Z020-CLG400 (U2 on the SoM)
# Sources (all programmatic, zero hand-typed pins):
#   ball map : som/Zynq_SoM.kicad_sch netlist (kicad-cli, at generation time)
#   contract : carrier/som_interface.json (cross-checked pin-for-pin, stale = build FAIL)
#   types    : carrier subsystems' typed-port registry
# VCCO rail map (project fpga.bank_rails): bank 13 = +1V8, bank 34 = +2V5, bank 35 = +3V3
# 7 pins, banks 13/34/35, 3 clock-capable (MRCC/SRCC)
# Ports named IO_* are the bound SoM contract nets not yet claimed
# by a function sheet; the wave-3 function map renames them here
# automatically on the next `schgen board`.
##############################################################################

# ---- bank 13 — VCCO = +1V8 (1 pins) --------------------
set_property -dict {PACKAGE_PIN A10  IOSTANDARD LVCMOS18} [get_ports {IO_GPIO}]  ;# J2.3 IO_L2P_SRCC_13 <- unclaimed (wave-3 function map)
#   ^ SRCC-capable: # create_clock -name IO_GPIO -period <ns> [get_ports {IO_GPIO}]

# ---- bank 34 — VCCO = +2V5 (3 pins) --------------------
# diff_pair (100R): DATA_P / DATA_N
set_property -dict {PACKAGE_PIN B1   IOSTANDARD LVDS_25} [get_ports {DATA_P}]  ;# J1.1 IO_L1P_T0_MRCC_34 <- lvds, observer
#   ^ MRCC-capable: # create_clock -name DATA_P -period <ns> [get_ports {DATA_P}]
set_property -dict {PACKAGE_PIN B2   IOSTANDARD LVDS_25} [get_ports {DATA_N}]  ;# J1.2 IO_L1N_T0_34 <- lvds
set_property -dict {PACKAGE_PIN C1   IOSTANDARD LVCMOS25} [get_ports {STATUS}]  ;# J1.10 IO_L2N_MRCC_34 <- monitor, debug

# ---- bank 35 — VCCO = +3V3 (3 pins) --------------------
# tmds_pair (100R): HDMI_P / HDMI_N
set_property -dict {PACKAGE_PIN D1   IOSTANDARD TMDS_33} [get_ports {HDMI_P}]  ;# J2.1 IO_L1P_T0_35 <- video
set_property -dict {PACKAGE_PIN D2   IOSTANDARD TMDS_33} [get_ports {HDMI_N}]  ;# J2.2 IO_L1N_T0_35 <- video
set_property -dict {PACKAGE_PIN E1   IOSTANDARD LVCMOS33} [get_ports {RESET}]  ;# J2.4 IO_1_35 <- unclaimed (wave-3 function map)
