"""SY7201ABC — SY7201ABC

Generated by `schgen part add C82173` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'SY7201ABC'
SAFE_NAME = 'SY7201ABC'
LCSC = 'C82173'
DESCRIPTION = 'SY7201ABC'
MANUFACTURER = 'Silergy(矽力杰)'
PACKAGE = 'SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BR'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C82173.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/LED-Drivers_Silergy_SY7201ABC_SY7201ABC_C82173.html'
LIB_ID = 'SY7201ABC:SY7201ABC'
FOOTPRINT = 'SY7201ABC:SY7201ABC'
MODELS_3D = ['SY7201ABC.wrl', 'SY7201ABC.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'LX', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'FB', 'passive'),
    ('4', 'EN/PWM', 'passive'),
    ('5', 'OVP', 'passive'),
    ('6', 'IN', 'passive'),
]
