"""TPS26631PWPR — TPS26631PWPR (HTSSOP-20_L6.5-W4.4-P0.65-LS6.4-BL-EP)

Generated by `schgen part add C2866319` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPS26631PWPR'
SAFE_NAME = 'TPS26631PWPR'
LCSC = 'C2866319'
DESCRIPTION = 'TPS26631PWPR (HTSSOP-20_L6.5-W4.4-P0.65-LS6.4-BL-EP)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'HTSSOP-20_L6.5-W4.4-P0.65-LS6.4-BL-EP'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C2866319.pdf'
PRODUCT_URL = ''
LIB_ID = 'TPS26631PWPR:TPS26631PWPR'
FOOTPRINT = 'TPS26631PWPR:TPS26631PWPR'
MODELS_3D = ['TPS26631PWPR.wrl', 'TPS26631PWPR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'IN', 'passive'),
    ('2', 'IN', 'passive'),
    ('3', 'IN', 'passive'),
    ('4', 'B_GATE', 'passive'),
    ('5', 'DRV', 'passive'),
    ('6', 'IN_SYS', 'passive'),
    ('7', 'UVLO', 'passive'),
    ('8', 'OVP', 'passive'),
    ('9', 'GND', 'passive'),
    ('10', 'dVdT', 'passive'),
    ('11', 'ILIM', 'passive'),
    ('12', 'MODE', 'passive'),
    ('13', 'SHDN#', 'passive'),
    ('14', 'IMON', 'passive'),
    ('15', 'FLT#', 'passive'),
    ('16', 'PGTH', 'passive'),
    ('17', 'PGOOD', 'passive'),
    ('18', 'OUT', 'passive'),
    ('19', 'OUT', 'passive'),
    ('20', 'OUT', 'passive'),
    ('21', 'EP', 'passive'),
]
