"""0603WAF2702T5E — 27KΩ (2702) ±1%

Generated by `schgen part add C22967` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = '0603WAF2702T5E'
SAFE_NAME = '0603WAF2702T5E'
LCSC = 'C22967'
DESCRIPTION = '27KΩ (2702) ±1%'
MANUFACTURER = 'UNI-ROYAL(厚声)'
PACKAGE = 'R0603'
JLC_CLASS = 'Basic Part'
PREFIX = 'R'
DATASHEET = 'https://www.lcsc.com/datasheet/C22967.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_27KR-2702-1_C22967.html'
LIB_ID = '0603WAF2702T5E:0603WAF2702T5E'
FOOTPRINT = '0603WAF2702T5E:0603WAF2702T5E'
MODELS_3D = ['0603WAF2702T5E.wrl', '0603WAF2702T5E.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('2', '2', 'passive'),
    ('1', '1', 'passive'),
]
