"""symbol_law — the HARD "0 hand-built symbols" gate (user decree).

LAW (user, 2026-06-15): the board may carry NO schgen-LOCAL real-part symbol.
Every active part's symbol must come either from a stock KiCad library (e.g.
``Regulator_Switching:TPS54302``) or from a FAITHFUL ``parts/<MPN>/`` dossier
generated by ``schgen part add`` — never a hand-drawn copy in
``schgen/lib/schgen.kicad_sym``. The ONLY schgen-local symbols allowed on the
board are POWER / RAIL flags (``+VIN``, ``+3V3_SC``, ``CHASSIS_GND``,
``+VCCO_*`` …): those are legitimate generator-owned net flags, not part
drawings.

DETECTION is by the symbol's own KiCad ``(power)`` marker — every rail flag in
schgen.kicad_sym carries it; a hand-built part drawing does not. So the rule is
mechanical and cannot drift: a ``schgen:`` lib_id whose symbol is NOT a
``(power)`` flag is a hand-built real-part symbol and FAILS the board.

A small, EXPLICIT ``PENDING`` allowlist names the hand-built real-part symbols
that have a documented, tracked migration still open (their dossier exists but
the placement engine cannot yet lay the dossier box out cleanly). Each entry is
a deliberate, visible exception — NOT a softening of the law: a symbol not on
the list and not a ``(power)`` flag is killed unconditionally, and adding a NEW
hand-built symbol fails immediately (the selftest mutant proves it).
"""

from __future__ import annotations

from dataclasses import dataclass, field

from schgen.core.model import Circuit
from schgen.core.symbols import Library, SymbolError

# Hand-built schgen-local real-part symbols with a documented, OPEN migration
# (their parts/<MPN>/ dossier exists; the placement engine cannot yet lay the
# faithful box symbol out cleanly on these dense sheets — see the build report).
# Tracked, visible exceptions; everything else is killed. Drive this list to
# EMPTY as the engine learns each box topology.
#
# EMPTY (2026-06-15): the board carries 0 hand-built real-part symbols. The last
# two — schgen:LM61460 (power.py U1 buck) and schgen:HDMI_A_RX (hdmi_rx.py J1
# receptacle) — were migrated to their faithful parts/<MPN>/ dossier box symbols
# once the placement engine learned to lay a faithful box out cleanly:
#   * _buck_box_stage left-edge pins now escape with an UP/DOWN adaptive islet
#     (short left stub, else a vertical drop beyond the body's near edge), so the
#     FB column never blocks BIAS/RT; the VCC-on-top local-drop cap is purged
#     from self.hang so it is not double-placed.
#   * trunk top/bottom DIRECT taps whose chosen zone faces away from the pin now
#     route via the orthogonal escape (around the body) instead of a straight
#     drop through the part body — the HDMI-RX cable-5V trunk (top-edge EEPROM
#     VCC vs flipped-connector +5V) routes clean.
# Both swaps are NETLIST-NEUTRAL (same pin numbers + footprint); only the drawing
# changed. A new hand-built symbol still fails the board (the selftest mutant
# proves it) — this allowlist is the documented escape hatch, now unused.
PENDING_MIGRATION: dict[str, str] = {}


@dataclass
class SymbolLawResult:
    violations: list[str] = field(default_factory=list)   # HARD failures
    pending: list[str] = field(default_factory=list)      # tracked exceptions

    @property
    def ok(self) -> bool:
        return not self.violations

    def summary(self) -> str:
        out = [f"SYMBOL-LAW GATE: {'PASS' if self.ok else 'FAIL'} "
               f"(0 hand-built real-part symbols on the board"
               + (f"; {len(self.pending)} tracked-pending" if self.pending
                  else "") + ")"]
        for v in self.violations:
            out.append(f"  VIOLATION: {v}")
        for p in self.pending:
            out.append(f"  pending (tracked exception): {p}")
        return "\n".join(out)


def _is_power_flag(lib: Library, lib_id: str) -> bool:
    """True iff the symbol is a KiCad (power) net flag — the only schgen-local
    symbol kind the board may carry. Reads the symbol's own (power) marker."""
    try:
        sdef = lib.get(lib_id)
    except SymbolError:
        return False
    return any(isinstance(x, list) and x and str(x[0]) == "power"
               for x in sdef.raw)


def check(circuits: list[Circuit], lib: Library) -> SymbolLawResult:
    """Scan every board part: a ``schgen:``-lib_id symbol that is NOT a
    ``(power)`` flag is a hand-built real-part symbol. FAIL unless it is on the
    documented PENDING_MIGRATION allowlist (then reported as a tracked
    exception, not a failure)."""
    res = SymbolLawResult()
    seen: set[str] = set()
    for c in circuits:
        for ref, part in sorted(c.parts.items()):
            lib_id = part.lib_id
            if not lib_id.startswith("schgen:"):
                continue
            if _is_power_flag(lib, lib_id):
                continue                       # legitimate rail/power flag
            if lib_id in PENDING_MIGRATION:
                tag = f"{lib_id} ({c.name}.{ref}) — {PENDING_MIGRATION[lib_id]}"
                if lib_id not in seen:
                    res.pending.append(tag)
                    seen.add(lib_id)
                continue
            res.violations.append(
                f"{c.name}.{ref} uses hand-built schgen-local real-part symbol "
                f"{lib_id!r} — migrate to a parts/<MPN>/ dossier (use_part "
                f"WITHOUT lib_id=) or a stock KiCad symbol; schgen.kicad_sym "
                f"may hold only (power) rail flags.")
    return res
