"""AFC07-S40FCA-00 — AFC07-S40FCA-00 (FPC-SMD_AFC07-S40FCA-00)

Generated by `schgen part add C262572` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'AFC07-S40FCA-00'
SAFE_NAME = 'AFC07-S40FCA-00'
LCSC = 'C262572'
DESCRIPTION = 'AFC07-S40FCA-00 (FPC-SMD_AFC07-S40FCA-00)'
MANUFACTURER = 'JS(钜硕电子)'
PACKAGE = 'FPC-SMD_AFC07-S40FCA-00'
JLC_CLASS = 'Extended Part'
PREFIX = 'FPC'
DATASHEET = 'https://www.lcsc.com/datasheet/C262572.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Others_JUSHUO-AFC07-S40FCA-00_C262572.html'
LIB_ID = 'AFC07-S40FCA-00:AFC07-S40FCA-00'
FOOTPRINT = 'AFC07-S40FCA-00:AFC07-S40FCA-00'
MODELS_3D = ['AFC07-S40FCA-00.wrl', 'AFC07-S40FCA-00.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('2', '2', 'passive'),
    ('3', '3', 'passive'),
    ('4', '4', 'passive'),
    ('5', '5', 'passive'),
    ('6', '6', 'passive'),
    ('7', '7', 'passive'),
    ('8', '8', 'passive'),
    ('9', '9', 'passive'),
    ('10', '10', 'passive'),
    ('11', '11', 'passive'),
    ('12', '12', 'passive'),
    ('13', '13', 'passive'),
    ('14', '14', 'passive'),
    ('15', '15', 'passive'),
    ('16', '16', 'passive'),
    ('17', '17', 'passive'),
    ('18', '18', 'passive'),
    ('19', '19', 'passive'),
    ('20', '20', 'passive'),
    ('21', '21', 'passive'),
    ('22', '22', 'passive'),
    ('23', '23', 'passive'),
    ('24', '24', 'passive'),
    ('25', '25', 'passive'),
    ('26', '26', 'passive'),
    ('27', '27', 'passive'),
    ('28', '28', 'passive'),
    ('29', '29', 'passive'),
    ('30', '30', 'passive'),
    ('31', '31', 'passive'),
    ('32', '32', 'passive'),
    ('33', '33', 'passive'),
    ('34', '34', 'passive'),
    ('35', '35', 'passive'),
    ('36', '36', 'passive'),
    ('37', '37', 'passive'),
    ('38', '38', 'passive'),
    ('39', '39', 'passive'),
    ('40', '40', 'passive'),
    ('41', '41', 'passive'),
    ('42', '42', 'passive'),
]
