"""0603WAF1502T5E — 15KΩ (1502) ±1%

Generated by `schgen part add C22809` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = '0603WAF1502T5E'
SAFE_NAME = '0603WAF1502T5E'
LCSC = 'C22809'
DESCRIPTION = '15KΩ (1502) ±1%'
MANUFACTURER = 'UNI-ROYAL(厚声)'
PACKAGE = 'R0603'
JLC_CLASS = 'Basic Part'
PREFIX = 'R'
DATASHEET = 'https://www.lcsc.com/datasheet/C22809.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_15KR-1502-1_C22809.html'
LIB_ID = '0603WAF1502T5E:0603WAF1502T5E'
FOOTPRINT = '0603WAF1502T5E:0603WAF1502T5E'
MODELS_3D = ['0603WAF1502T5E.wrl', '0603WAF1502T5E.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('2', '2', 'passive'),
    ('1', '1', 'passive'),
]
