"""INA3221AIRGVR — INA3221AIRGVR (QFN-16_L4.0-W4.0-P0.65-TL-EP2.2)

Generated by `schgen part add C181255` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'INA3221AIRGVR'
SAFE_NAME = 'INA3221AIRGVR'
LCSC = 'C181255'
DESCRIPTION = 'INA3221AIRGVR (QFN-16_L4.0-W4.0-P0.65-TL-EP2.2)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'QFN-16_L4.0-W4.0-P0.65-TL-EP2.2'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C181255.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/PMIC-Current-Power-Monitors-Regulators_TI_INA3221AIRGVR_INA3221AIRGVR_C181255.html'
LIB_ID = 'INA3221AIRGVR:INA3221AIRGVR'
FOOTPRINT = 'INA3221AIRGVR:INA3221AIRGVR'
MODELS_3D = ['INA3221AIRGVR.wrl', 'INA3221AIRGVR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'IN-3', 'passive'),
    ('2', 'IN+3', 'passive'),
    ('3', 'GND', 'passive'),
    ('4', 'VS', 'passive'),
    ('5', 'A0', 'passive'),
    ('6', 'SCL', 'passive'),
    ('7', 'SDA', 'passive'),
    ('8', 'WARNING', 'passive'),
    ('9', 'CRITICAL', 'passive'),
    ('10', 'PV', 'passive'),
    ('11', 'IN-1', 'passive'),
    ('12', 'IN+1', 'passive'),
    ('13', 'TC', 'passive'),
    ('14', 'IN-2', 'passive'),
    ('15', 'IN+2', 'passive'),
    ('16', 'VPU', 'passive'),
    ('17', 'PAD', 'passive'),
]
