"""TCA9535PWR — TCA9535PWR_C130204 (TSSOP-24_L7.8-W4.4-P0.65-LS6.4-BL)

Generated by `schgen part add C130204` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TCA9535PWR'
SAFE_NAME = 'TCA9535PWR'
LCSC = 'C130204'
DESCRIPTION = 'TCA9535PWR_C130204 (TSSOP-24_L7.8-W4.4-P0.65-LS6.4-BL)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'TSSOP-24_L7.8-W4.4-P0.65-LS6.4-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C130204.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Interface-ICs_TI_TCA9535PWR_TCA9535PWR_C130204.html'
LIB_ID = 'TCA9535PWR:TCA9535PWR'
FOOTPRINT = 'TCA9535PWR:TCA9535PWR'
MODELS_3D = ['TCA9535PWR.wrl', 'TCA9535PWR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'INT#', 'passive'),
    ('2', 'A1', 'passive'),
    ('3', 'A2', 'passive'),
    ('4', 'P00', 'passive'),
    ('5', 'P01', 'passive'),
    ('6', 'P02', 'passive'),
    ('7', 'P03', 'passive'),
    ('8', 'P04', 'passive'),
    ('9', 'P05', 'passive'),
    ('10', 'P06', 'passive'),
    ('11', 'P07', 'passive'),
    ('12', 'GND', 'passive'),
    ('13', 'P10', 'passive'),
    ('14', 'P11', 'passive'),
    ('15', 'P12', 'passive'),
    ('16', 'P13', 'passive'),
    ('17', 'P14', 'passive'),
    ('18', 'P15', 'passive'),
    ('19', 'P16', 'passive'),
    ('20', 'P17', 'passive'),
    ('21', 'A0', 'passive'),
    ('22', 'SCL', 'passive'),
    ('23', 'SDA', 'passive'),
    ('24', 'VCC', 'passive'),
]
