"""KH-5224-8P8C-D — KH-5224-8P8C-D (RJ45-TH_KH-5224-8P8C-D)

Generated by `schgen part add C2828085` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'KH-5224-8P8C-D'
SAFE_NAME = 'KH-5224-8P8C-D'
LCSC = 'C2828085'
DESCRIPTION = 'KH-5224-8P8C-D (RJ45-TH_KH-5224-8P8C-D)'
MANUFACTURER = 'kinghelm(金航标)'
PACKAGE = 'RJ45-TH_KH-5224-8P8C-D'
JLC_CLASS = 'Extended Part'
PREFIX = 'RJ'
DATASHEET = 'https://www.lcsc.com/datasheet/C2828085.pdf'
PRODUCT_URL = ''
LIB_ID = 'KH-5224-8P8C-D:KH-5224-8P8C-D'
FOOTPRINT = 'KH-5224-8P8C-D:KH-5224-8P8C-D'
MODELS_3D = ['KH-5224-8P8C-D.wrl', 'KH-5224-8P8C-D.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('10', 'LED-L-', 'passive'),
    ('9', 'LED-L+', 'passive'),
    ('8', '8', 'passive'),
    ('7', '7', 'passive'),
    ('1', '1', 'passive'),
    ('2', '2', 'passive'),
    ('3', '3', 'passive'),
    ('4', '4', 'passive'),
    ('5', '5', 'passive'),
    ('6', '6', 'passive'),
    ('11', 'LED-R+', 'passive'),
    ('12', 'LED-R-', 'passive'),
    ('13', 'SHELL', 'passive'),
]
