/*
 * sc_app.c -- example bring-up app (portable, HAL-backed)
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power.py (regulator chain)
 *   carrier/subsystems/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#include "sc_hal.h"
#include "sc_seq.h"
#include "sc_pd.h"
#include "sc_wdt.h"

/* A reference bring-up flow that ties the scaffold together.  A real  */
/* app supplies its own main() / Zephyr thread and the sc_hal port;    */
/* this shows the C2-correct ORDER: rails -> modules -> THEN arm WDT.  */
int sc_bringup_main(void) {
    sc_log("SC bring-up: sequencing rails (DIP-gated, SC veto only)");
    /* PD negotiation is optional here: the board runs reduced on the  */
    /* 5 V default contract until a PD stack lifts +VIN.               */
    (void)sc_pd_init();

    /* C2: the watchdog is NOT armed yet -- sequence first. */
    if (sc_seq_run(/*policy=*/NULL) != 0) {
        sc_log("bring-up FAULT -- leaving watchdog disarmed");
        return -1;
    }

    /* Bring-up complete: NOW it is safe to arm the watchdog (C2). */
    sc_wdt_arm();
    sc_log("SC bring-up complete; watchdog armed");
    return 0;
}
