/*
 * sc_hal.h -- SC firmware HAL abstraction (platform ops)
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power/power.py (regulator chain)
 *   carrier/subsystems/power_mon/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#ifndef SC_HAL_H
#define SC_HAL_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ======================================================================== */
/* HAL contract                                                             */
/* ======================================================================== */
/* The portable bring-up code (sc_seq.c / sc_pd.c / sc_wdt.c) NEVER    */
/* touches a register or a Zephyr API directly: it calls the ops      */
/* below.  A platform port (sc_hal_zephyr.c for a Zephyr app, or a    */
/* bare-metal sc_hal_stm32.c) provides the bodies.  GPIOs are named   */
/* by the ('port' letter, pin number) pair the hardware contract      */
/* (zynq_carrier_contract.h) already exposes, so the HAL maps a STM32  */
/* (port,pin) onto whatever handle the platform uses.                 */

/* A GPIO line as the contract names it: STM32 port letter 'A'..'G'   */
/* and pin number, exactly the ZC_*_GPIO_PORT / ZC_*_GPIO_PIN pair.   */
typedef struct {
    char port;       /* 'A' .. 'G' (ZC_*_GPIO_PORT) */
    uint8_t pin;     /* 0 .. 15    (ZC_*_GPIO_PIN)  */
} sc_gpio_t;

/* I2C transfer direction. */
typedef enum { SC_I2C_WRITE = 0, SC_I2C_READ = 1 } sc_i2c_dir_t;

/* The platform ops table.  All return 0 on success, <0 on error.     */
/* A Zephyr port fills this from devicetree handles (see sc_hal.h     */
/* footer); a bare-metal port from LL/HAL register writes.            */
typedef struct {
    /* --- timing --- */
    void (*delay_ms)(uint32_t ms);
    uint32_t (*uptime_ms)(void);
    /* --- GPIO --- */
    int (*gpio_configure_output)(sc_gpio_t io, bool open_drain);
    int (*gpio_configure_input)(sc_gpio_t io, bool pull_up);
    int (*gpio_set)(sc_gpio_t io, bool level);
    int (*gpio_get)(sc_gpio_t io, bool *level);
    /* --- I2C (7-bit addressing; bit-bang or peripheral) --- */
    int (*i2c_xfer)(uint8_t addr7, sc_i2c_dir_t dir,
                    uint8_t *buf, size_t len);
    /* --- watchdog (TPS3823 WDI strobe; see sc_wdt.h, C2) --- */
    int (*wdt_strobe)(void);
    /* --- diagnostics (optional; may be NULL) --- */
    void (*log)(const char *msg);
} sc_hal_t;

/* The single HAL instance the portable code calls.  The platform port */
/* sets this before sc_seq_run()/sc_pd_*; the portable code treats it   */
/* as read-only.                                                        */
extern const sc_hal_t *sc_hal;

/* Convenience wrappers (header-only) so call sites stay terse and the  */
/* NULL-op guards live in exactly one place.                            */
static inline void sc_delay_ms(uint32_t ms) { sc_hal->delay_ms(ms); }
static inline uint32_t sc_uptime_ms(void) { return sc_hal->uptime_ms(); }
static inline int sc_gpio_set(sc_gpio_t io, bool lvl) {
    return sc_hal->gpio_set(io, lvl);
}
static inline int sc_gpio_get(sc_gpio_t io, bool *lvl) {
    return sc_hal->gpio_get(io, lvl);
}
static inline int sc_i2c_write(uint8_t a, uint8_t *b, size_t n) {
    return sc_hal->i2c_xfer(a, SC_I2C_WRITE, b, n);
}
static inline int sc_i2c_read(uint8_t a, uint8_t *b, size_t n) {
    return sc_hal->i2c_xfer(a, SC_I2C_READ, b, n);
}
static inline void sc_log(const char *msg) {
    if (sc_hal->log) sc_hal->log(msg);
}

/* ======================================================================== */
/* ZEPHYR PORT NOTE  (how this drops into a Zephyr app)                     */
/* ======================================================================== */
/*
 * The portable code is Zephyr-agnostic; a Zephyr port is one .c file
 * (sc_hal_zephyr.c, shipped here as a COMMENTED reference) plus the
 * board glue below.  Nothing in this directory includes a zephyr/
 * header.
 *
 * 1. Kconfig: the SC app selects
 *      CONFIG_GPIO=y
 *      CONFIG_I2C=y          (or bit-bang: CONFIG_I2C_GPIO=y, since the
 *                             contract bit-bangs I2C2 on PA4/PA5 -- see
 *                             ZC_I2C_BITBANG_ in the contract header)
 *      CONFIG_WATCHDOG=n      (the TPS3823 is EXTERNAL; the SC only
 *                             strobes WDI through a GPIO -- C2)
 *
 * 2. Devicetree overlay (app.overlay): expose the buses/lines the HAL
 *    port resolves with DEVICE_DT_GET / GPIO_DT_SPEC_GET.  A minimal
 *    overlay for THIS board's contract (// = overlay remarks):
 *
 *      / {
 *          sc_ctrl {
 *              compatible = "zynq,carrier-sc";
 *              i2c = <&i2c_sc>;          // bit-bang I2C2 (PA4/PA5)
 *              wdi-gpios = <&gpioX PIN GPIO_ACTIVE_HIGH>;  // TPS3823 WDI
 *          };
 *      };
 *      // GPIO bit-bang I2C on the DAC pins, per ZC_I2C_BITBANG_
 *      i2c_sc: i2c-gpio {
 *          compatible = "i2c-gpio";
 *          sda-gpios = <&gpioa 4 (GPIO_OPEN_DRAIN | GPIO_PULL_UP)>;
 *          scl-gpios = <&gpioa 5 (GPIO_OPEN_DRAIN | GPIO_PULL_UP)>;
 *          #address-cells = <1>;
 *          #size-cells = <0>;
 *      };
 *
 * 3. HAL port (sc_hal_zephyr.c): implement sc_hal_t over the Zephyr
 *    GPIO + I2C APIs and publish `sc_hal`.  The ('port','pin') pair in
 *    sc_gpio_t maps onto a Zephyr gpio_dt_spec via a small lookup the
 *    port owns (one DEVICE_DT_GET per GPIO bank).  A skeleton ships as
 *    sc_hal_zephyr.c.txt in this directory (commented so the tree stays
 *    toolchain-agnostic).
 */

#endif /* SC_HAL_H */
