/*
 * sc_rtc.h -- RV-3028 RTC trickle charger (ML1220 backup)
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power/power.py (regulator chain)
 *   carrier/subsystems/power_mon/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#ifndef SC_RTC_H
#define SC_RTC_H

#include "sc_hal.h"

/* board_services fits a RECHARGEABLE ML1220 (Mn-Li) on the RV-3028's    */
/* VBACKUP for a maintenance-free RTC.  A rechargeable cell only stays    */
/* charged if firmware ENABLES the RV-3028's internal trickle charger     */
/* (TCE + a series resistance in the EEPROM Backup register) -- so the    */
/* cell tops up whenever the board is powered (contract ZC_I2C_ADDR_RTC). */
/* This is the netlist-anchored entry point that makes the ML1220 choice  */
/* real; without it the cell would slowly deplete.                        */

/* Probe the RV-3028 on the AUX I2C and enable the trickle charger.       */
/* Returns 0 on success.  Best-effort: the RTC is on the gated +3V3_AUX   */
/* rail, so call it once that rail + its I2C isolator are up.             */
int sc_rtc_init(void);

/* Enable the trickle charger only (TCE + ~3k + backup switchover),       */
/* committing it to the config EEPROM.  Returns 0 on success.            */
int sc_rtc_trickle_enable(void);

#endif /* SC_RTC_H */
