/*
 * sc_seq.h -- portable rail-sequencing state machine
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power/power.py (regulator chain)
 *   carrier/subsystems/power_mon/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#ifndef SC_SEQ_H
#define SC_SEQ_H

#include <stdint.h>
#include <stdbool.h>
#include "sc_tables.h"

/* The bring-up state machine -- mirrors BRINGUP.md staging:        */
/*   IDLE -> always-on assumed up -> sequence core rails -> modules */
/* Each step enables one rail/gate, waits settle_ms, then confirms  */
/* via telemetry before advancing.  C2: the watchdog is NOT armed   */
/* anywhere in this sequence (see sc_wdt.h).                         */
typedef enum {
    SC_SEQ_IDLE = 0,
    SC_SEQ_RAILS,        /* sequencing the core regulator chain */
    SC_SEQ_MODULES,      /* enabling the module load switches */
    SC_SEQ_DONE,
    SC_SEQ_FAULT,
} sc_seq_phase_t;

typedef struct {
    sc_seq_phase_t phase;
    uint8_t        index;     /* step within the current phase */
    const char    *fault_net; /* set when phase == SC_SEQ_FAULT */
} sc_seq_state_t;

/* Enable policy for a rail/module: the SC VETO defaults to "let the */
/* DIP rule" (override HIGH/Hi-Z).  A caller may force a rail OFF by */
/* returning false here; it can never force one ON (DIP AND ovr).   */
typedef bool (*sc_enable_policy_t)(const char *en_net);

/* Initialise the sequencer state (does NOT touch hardware). */
void sc_seq_init(sc_seq_state_t *st);

/* Advance the sequence by one step.  Returns true while more steps   */
/* remain (call again after the returned settle), false when DONE or  */
/* FAULT.  `policy` may be NULL (then every rail follows its DIP).    */
bool sc_seq_step(sc_seq_state_t *st, sc_enable_policy_t policy);

/* Drive the whole sequence to completion (blocking, uses the HAL     */
/* delay for the per-stage settle).  Returns 0 on SC_SEQ_DONE, <0 on  */
/* SC_SEQ_FAULT.  This is the simplest entry point for a bring-up app.*/
int sc_seq_run(sc_enable_policy_t policy);

#endif /* SC_SEQ_H */
