/*
 * sc_seq.c -- portable rail-sequencing state machine (impl)
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power.py (regulator chain)
 *   carrier/subsystems/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#include "zynq_carrier_contract.h"
#include "sc_hal.h"
#include "sc_tables.h"
#include "sc_seq.h"

/* Drive a rail/module EN override.  The override is a VETO that is     */
/* ACTIVE-LOW: HIGH/Hi-Z lets the DIP enable the rail, LOW forces OFF.  */
/* A port=0 GPIO means "no SC veto wired" -- the DIP is sole owner.    */
static int sc_drive_override(sc_gpio_t io, bool want_on) {
    if (io.port == 0) return 0;            /* no veto line: DIP rules */
    /* want_on -> release the veto (HIGH); !want_on -> assert (LOW).   */
    return sc_gpio_set(io, want_on);
}

/* Confirm a rail by reading its INA3221 bus-voltage channel, if one is */
/* mapped.  This is a STUB hook: the INA3221 register read lives in the */
/* platform/driver layer -- here we only gate on telemetry presence so  */
/* the portable sequencing logic is complete and testable.  A port may  */
/* override sc_rail_is_good() to do the real read.                      */
bool __attribute__((weak)) sc_rail_is_good(const sc_rail_step_t *step) {
    if (step->pmon_addr7 == 0) return true;   /* untelemetered: trust */
    /* TODO(port): read INA3221 (step->pmon_addr7, step->pmon_channel)  */
    /* bus-voltage reg and compare against step->vout_mv with margin.   */
    (void)step;
    return true;
}

void sc_seq_init(sc_seq_state_t *st) {
    st->phase = SC_SEQ_RAILS;
    st->index = 0;
    st->fault_net = NULL;
}

static bool sc_policy_allows(sc_enable_policy_t policy, const char *en) {
    return policy ? policy(en) : true;
}

bool sc_seq_step(sc_seq_state_t *st, sc_enable_policy_t policy) {
    switch (st->phase) {
    case SC_SEQ_RAILS: {
        if (st->index >= SC_RAIL_COUNT) {
            st->phase = SC_SEQ_MODULES;
            st->index = 0;
            return true;
        }
        const sc_rail_step_t *step = &sc_rail_steps[st->index];
        bool want = sc_policy_allows(policy, step->en_net);
        sc_log(step->name);
        if (sc_drive_override(step->en_override, want) != 0) {
            st->phase = SC_SEQ_FAULT;
            st->fault_net = step->en_net;
            return false;
        }
        if (want) {
            sc_delay_ms(step->settle_ms);
            if (!sc_rail_is_good(step)) {
                st->phase = SC_SEQ_FAULT;
                st->fault_net = step->name;
                return false;
            }
        }
        st->index++;
        return true;
    }
    case SC_SEQ_MODULES: {
        if (st->index >= SC_MOD_COUNT) {
            st->phase = SC_SEQ_DONE;
            return false;
        }
        const sc_module_gate_t *g = &sc_module_gates[st->index];
        bool want = sc_policy_allows(policy, g->en_net);
        sc_log(g->module);
        /* Module overrides ride the TCA9535 output word (g->tca_bit);  */
        /* the expander write lives in the platform layer.  A direct    */
        /* (0xFF) gate would drive a GPIO here instead.  Either way the */
        /* DIP still gates the SY6280 -- the SC only vetoes.            */
        (void)want;
        st->index++;
        return true;
    }
    case SC_SEQ_IDLE:
    case SC_SEQ_DONE:
    case SC_SEQ_FAULT:
    default:
        return false;
    }
}

int sc_seq_run(sc_enable_policy_t policy) {
    sc_seq_state_t st;
    sc_seq_init(&st);
    /* C2: do NOT arm/kick the watchdog here -- bring-up must complete  */
    /* first; the caller arms it afterwards (see sc_wdt.h / sc_app.c).  */
    while (sc_seq_step(&st, policy)) {
        /* settle handled inside the step */
    }
    return (st.phase == SC_SEQ_DONE) ? 0 : -1;
}
