/*
 * sc_tables.c -- netlist-derived SC tables (data)
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power.py (regulator chain)
 *   carrier/subsystems/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#include "zynq_carrier_contract.h"
#include "sc_tables.h"

const sc_rail_step_t sc_rail_steps[SC_RAIL_COUNT] = {
    {
        .id = SC_RAIL_P5V,
        .name = "+5V",
        .vout_mv = 5020,
        .en_net = "EN_5V0",
        .en_override = { .port = ZC_RAIL0_OVERRIDE_GPIO_PORT, .pin = ZC_RAIL0_OVERRIDE_GPIO_PIN },
        .settle_ms = 5,
        .pmon_addr7 = ZC_I2C_ADDR_INA3221_1,
        .pmon_channel = 2,
        .shunt_mohm = 10,
    },
    {
        .id = SC_RAIL_P3V3,
        .name = "+3V3",
        .vout_mv = 3210,
        .en_net = "EN_3V3",
        .en_override = { .port = ZC_RAIL1_OVERRIDE_GPIO_PORT, .pin = ZC_RAIL1_OVERRIDE_GPIO_PIN },
        .settle_ms = 5,
        .pmon_addr7 = ZC_I2C_ADDR_INA3221_1,
        .pmon_channel = 3,
        .shunt_mohm = 10,
    },
    {
        .id = SC_RAIL_P1V8,
        .name = "+1V8",
        .vout_mv = 1800,
        .en_net = "EN_1V8",
        .en_override = { .port = ZC_RAIL2_OVERRIDE_GPIO_PORT, .pin = ZC_RAIL2_OVERRIDE_GPIO_PIN },
        .settle_ms = 5,
        .pmon_addr7 = ZC_I2C_ADDR_INA3221_2,
        .pmon_channel = 1,
        .shunt_mohm = 20,
    },
};

const char *const sc_always_on_rails[SC_ALWAYS_ON_COUNT] = {
    "+3V3_SC",
    "+VIN",
};

const sc_module_gate_t sc_module_gates[SC_MOD_COUNT] = {
    {
        .id = SC_MOD_HDMI_TX,
        .module = "HDMI_TX",
        .rail_in = "+3V3",
        .rail_out = "+3V3_HDMI_TX",
        .en_net = "EN_HDMI_TX",
        .ilim_ma = 523,
        .tca_bit = 0,
    },
    {
        .id = SC_MOD_HDMI_RX,
        .module = "HDMI_RX",
        .rail_in = "+3V3",
        .rail_out = "+3V3_HDMI_RX",
        .en_net = "EN_HDMI_RX",
        .ilim_ma = 523,
        .tca_bit = 1,
    },
    {
        .id = SC_MOD_LCD,
        .module = "LCD",
        .rail_in = "+3V3",
        .rail_out = "+3V3_LCD",
        .en_net = "EN_LCD",
        .ilim_ma = 1000,
        .tca_bit = 2,
    },
    {
        .id = SC_MOD_CAM,
        .module = "CAM",
        .rail_in = "+3V3",
        .rail_out = "+3V3_CAM",
        .en_net = "EN_CAM",
        .ilim_ma = 523,
        .tca_bit = 3,
    },
    {
        .id = SC_MOD_SD,
        .module = "SD",
        .rail_in = "+3V3",
        .rail_out = "+3V3_SD",
        .en_net = "EN_SD",
        .ilim_ma = 1000,
        .tca_bit = 4,
    },
    {
        .id = SC_MOD_USB,
        .module = "USB",
        .rail_in = "+5V",
        .rail_out = "+5V_USB",
        .en_net = "EN_USB",
        .ilim_ma = 1000,
        .tca_bit = 5,
    },
    {
        .id = SC_MOD_PMOD,
        .module = "PMOD",
        .rail_in = "+3V3",
        .rail_out = "+3V3_PMOD",
        .en_net = "EN_PMOD",
        .ilim_ma = 523,
        .tca_bit = 6,
    },
    {
        .id = SC_MOD_USER_LED,
        .module = "USER_LED",
        .rail_in = "+3V3",
        .rail_out = "+3V3_USER_LED",
        .en_net = "EN_USER_LED",
        .ilim_ma = 523,
        .tca_bit = 7,
    },
    {
        .id = SC_MOD_HDMI_TX_5V,
        .module = "HDMI_TX_5V",
        .rail_in = "+5V",
        .rail_out = "+5V_HDMI_TX",
        .en_net = "EN_HDMI_TX_5V",
        .ilim_ma = 523,
        .tca_bit = 10,
    },
    {
        .id = SC_MOD_LCD_5V,
        .module = "LCD_5V",
        .rail_in = "+5V",
        .rail_out = "+5V_LCD",
        .en_net = "EN_LCD_5V",
        .ilim_ma = 1000,
        .tca_bit = 11,
    },
};

const sc_i2c_dev_t sc_i2c_devices[SC_I2C_DEV_COUNT] = {
    { "bring-up override expander (TCA9535)", ZC_I2C_ADDR_TCA9535 },
    { "USB-PD PHY (FUSB302B)", ZC_I2C_ADDR_FUSB302B },
    { "rail monitor #1 (INA3221)", ZC_I2C_ADDR_INA3221_1 },
    { "rail monitor #2 (INA3221)", ZC_I2C_ADDR_INA3221_2 },
    { "FMC mezzanine ID EEPROM", ZC_I2C_ADDR_FMC_EEPROM },
    { "board-ID EEPROM (EUI-48 MAC; AUX bus)", ZC_I2C_ADDR_ID_EEPROM },
    { "RTC RV-3028 (AUX bus)", ZC_I2C_ADDR_RTC },
};
