/*
 * sc_wdt.c -- TPS3823 external watchdog (impl)
 *
 * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
 * regenerate: PYTHONPATH=. python -m schgen scfw
 *
 * system controller: STM32G431CBUx (from the SoM U9 netlist)
 *
 * Portable C behind the sc_hal abstraction -- this file #includes NO
 * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.
 * sources:
 *   carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)
 *   carrier/subsystems/power.py (regulator chain)
 *   carrier/subsystems/power_mon.py (INA3221 monitors + shunts)
 *   carrier/subsystems/bringup_en.py (rail EN cells)
 *   carrier/subsystems/bringup_modules.py (SY6280 module gates)
 *   carrier/subsystems/bringup_rails.py (TCA9535 override expander)
 *   carrier/subsystems/usb_pd.py (FUSB302B PD PHY)
 *   carrier/subsystems/board_services.py (TPS3823 watchdog)
 *   carrier/docs/BRINGUP.md (the staged procedure this automates)
 */
#include "sc_hal.h"
#include "sc_wdt.h"

/* C2 latch: false until sc_wdt_arm(); kicks before arming are no-ops. */
static bool s_wdt_armed = false;

void sc_wdt_arm(void) {
    s_wdt_armed = true;
    sc_log("watchdog armed (post-bring-up)");
}

bool sc_wdt_is_armed(void) {
    return s_wdt_armed;
}

void sc_wdt_kick(void) {
    if (!s_wdt_armed) return;          /* C2: no kicks during power-up */
    if (sc_hal->wdt_strobe) sc_hal->wdt_strobe();
}
