string(RANDOM LENGTH 16 suffix)
set(scratch "${OUTPUT_DIR}/mutation-${suffix}")
file(MAKE_DIRECTORY "${scratch}")
foreach(probe IN ITEMS helper defined_edge board)
    if(probe STREQUAL "defined_edge")
        set(fixture "legacy-edge.txt")
    else()
        set(fixture "legacy-${probe}.txt")
    endif()
    file(READ "${FIXTURES}/${fixture}" original)
    file(WRITE "${scratch}/${fixture}" "mutated:${original}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DPROBE=${probe}" "-DFIXTURES=${scratch}"
        -P "${RUNNER}" RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(status STREQUAL "0" OR NOT err MATCHES "Search9 immutable fixture hash mismatch")
        message(FATAL_ERROR "${probe} fixture mutation escaped exact immutable hash check: ${out}${err}")
    endif()
endforeach()
