if(PROBE STREQUAL "helper")
    set(fixture "legacy-helper.txt")
    set(expected "1ee7af1cd0ef4f10d62b7853ec778e9af657130ecdce1ab40fd4fb174bad47d4")
elseif(PROBE STREQUAL "defined_edge")
    set(fixture "legacy-edge.txt")
    set(expected "45754f69f5aca49c8661a7e60454064dcd3144b752f3b6318434c6e5389c4912")
elseif(PROBE STREQUAL "board")
    set(fixture "legacy-board.txt")
    set(expected "8b6e524085a49780b42a623f29c35acccb2f8fb52089c992e736cd7713b58e09")
else()
    message(FATAL_ERROR "unknown Search9 proof")
endif()
file(SHA256 "${FIXTURES}/${fixture}" actual_hash)
if(NOT actual_hash STREQUAL expected)
    message(FATAL_ERROR "Search9 immutable fixture hash mismatch")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(output "${OUTPUT_DIR}/${PROBE}.txt")
if(PROBE STREQUAL "board")
    execute_process(COMMAND "${PROGRAM}" "${ROOT}" OUTPUT_FILE "${output}" RESULT_VARIABLE status)
else()
    execute_process(COMMAND "${PROGRAM}" OUTPUT_FILE "${output}" RESULT_VARIABLE status)
endif()
if(NOT status STREQUAL "0")
    message(FATAL_ERROR "Search9 proof failed: ${status}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${output}" "${FIXTURES}/${fixture}" RESULT_VARIABLE same)
if(NOT same STREQUAL "0")
    message(FATAL_ERROR "Search9 complete frozen output mismatch: ${output}")
endif()
