"""TPD4E02B04DQAR — 4-Channel ESD Protection Diode for USB Type-C and HDMI 2.0 10-USON -40 to 125

Generated by `schgen part add C106794` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPD4E02B04DQAR'
SAFE_NAME = 'TPD4E02B04DQAR'
LCSC = 'C106794'
DESCRIPTION = '4-Channel ESD Protection Diode for USB Type-C and HDMI 2.0 10-USON -40 to 125'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'USON-10_L2.5-W1.0-P0.50-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'D'
DATASHEET = 'https://www.lcsc.com/datasheet/C106794.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Others_Texas-Instruments_TPD4E02B04DQAR_Texas-Instruments-TI-TPD4E02B04DQAR_C106794.html'
LIB_ID = 'TPD4E02B04DQAR:TPD4E02B04DQAR'
FOOTPRINT = 'TPD4E02B04DQAR:TPD4E02B04DQAR'
MODELS_3D = ['TPD4E02B04DQAR.wrl', 'TPD4E02B04DQAR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'IO1', 'passive'),
    ('8', 'GND', 'passive'),
    ('2', 'IO2', 'passive'),
    ('4', 'IO3', 'passive'),
    ('5', 'IO4', 'passive'),
    ('6', 'NC', 'passive'),
    ('7', 'NC', 'passive'),
    ('9', 'NC', 'passive'),
    ('10', 'NC', 'passive'),
    ('3', 'GND', 'passive'),
]
