"""SWPA4030S100MT — 10uH ±20%

Generated by `schgen part add C38117` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'SWPA4030S100MT'
SAFE_NAME = 'SWPA4030S100MT'
LCSC = 'C38117'
DESCRIPTION = '10uH ±20%'
MANUFACTURER = 'Sunlord(顺络)'
PACKAGE = 'IND-SMD_L4.0-W4.0'
JLC_CLASS = 'Extended Part'
PREFIX = 'L'
DATASHEET = 'https://www.lcsc.com/datasheet/C38117.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Power-Inductors_10uH-20_C38117.html'
LIB_ID = 'SWPA4030S100MT:SWPA4030S100MT'
FOOTPRINT = 'SWPA4030S100MT:SWPA4030S100MT'
MODELS_3D = ['SWPA4030S100MT.wrl', 'SWPA4030S100MT.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('2', '2', 'passive'),
    ('1', '1', 'passive'),
]
