#pragma once
#include "schgen/native_audit_state.hpp"
#include "schgen/output_precision.hpp"
namespace output_precision_fixture {
inline void register_operations(schgen::NativeQuantizations& r) {
// Parent-owned integration: include schgen/output_precision.hpp, then append
// inside register_native_quantizations. Every source cover names a scalar only.
// 19 registrations; affine SVG arity 3, others arity 1. Add output_precision.cpp to both audit source lists.
r.declare({"floorplan_svg_extent_trunc","native/src/output_precision.cpp::schgen::floorplan_svg_extent_trunc","int(value)","SVG canvas dimensions truncate after the existing finite/range validation; no layout or diagnostic spelling changes.","pre-proof",1,[](const std::vector<double>& a){return schgen::floorplan_svg_extent_trunc(a[0]);}});
r.declare({"floorplan_svg_grid_trunc","native/src/output_precision.cpp::schgen::floorplan_svg_grid_trunc","int(value)","Grid loop bounds truncate on every condition evaluation including termination; do not hoist or infer counts from line count.","pre-proof",1,[](const std::vector<double>& a){return schgen::floorplan_svg_grid_trunc(a[0]);}});
r.declare({"floorplan_svg_coordinate_precision1dp","native/src/output_precision.cpp::schgen::floorplan_svg_coordinate_precision1dp","round(origin + value * scale, 1)","SVG coordinate projection rounds origin plus coordinate times scale at the original svg_map boundary; cached strings do not count.","pre-proof",3,[](const std::vector<double>& a){return schgen::floorplan_svg_coordinate_precision1dp(a[0],a[1],a[2]);}});
r.declare({"pcb_project_integer_trunc","native/src/output_precision.cpp::schgen::pcb_project_integer_trunc","trunc(value)","JSON integer classification truncates only when float-token metadata does not short-circuit; original integer spelling remains intact.","pre-proof",1,[](const std::vector<double>& a){return schgen::pcb_project_integer_trunc(a[0]);}});
r.declare({"pcb_project_class_precision4dp","native/src/output_precision.cpp::schgen::pcb_project_class_precision4dp","round(value, 4)","Each netclass clearance, gap, differential width and track width rounds independently before serialization.","pre-proof",1,[](const std::vector<double>& a){return schgen::pcb_project_class_precision4dp(a[0]);}});
r.declare({"pcb_silk_position_precision3dp","native/src/output_precision.cpp::schgen::pcb_silk_position_precision3dp","round(value, 3)","Accepted descriptor x and y round only at emitted text creation; rejected seat candidates do not fabricate these entries.","pre-proof",1,[](const std::vector<double>& a){return schgen::pcb_silk_position_precision3dp(a[0]);}});
r.declare({"pcb_silk_stroke_precision3dp","native/src/output_precision.cpp::schgen::pcb_silk_stroke_precision3dp","round(value, 3)","Descriptor stroke width rounds after max(0.12,size*0.16) without changing expression ordering.","pre-proof",1,[](const std::vector<double>& a){return schgen::pcb_silk_stroke_precision3dp(a[0]);}});
r.declare({"ratsnest_pad_precision3dp","native/src/output_precision.cpp::schgen::ratsnest_pad_precision3dp","round(value, 3)","Each eligible connected pad position rounds after rotation/translation; supplied positions skip this work.","pre-proof",1,[](const std::vector<double>& a){return schgen::ratsnest_pad_precision3dp(a[0]);}});
r.declare({"ratsnest_area_precision1dp","native/src/output_precision.cpp::schgen::ratsnest_area_precision1dp","round(value, 1)","Cluster hull area rounds only for the result record; dispersion comparisons retain unrounded operands.","pre-proof",1,[](const std::vector<double>& a){return schgen::ratsnest_area_precision1dp(a[0]);}});
r.declare({"ratsnest_dispersion_precision2dp","native/src/output_precision.cpp::schgen::ratsnest_dispersion_precision2dp","round(value, 2)","Cluster dispersion rounds for result ordering and reporting; the existing legality comparison remains unrounded.","pre-proof",1,[](const std::vector<double>& a){return schgen::ratsnest_dispersion_precision2dp(a[0]);}});
r.declare({"ratsnest_budget_precision1dp","native/src/output_precision.cpp::schgen::ratsnest_budget_precision1dp","round(value, 1)","Cross-budget rounding remains before cross_ok comparison; preserve rounded gate semantics.","pre-proof",1,[](const std::vector<double>& a){return schgen::ratsnest_budget_precision1dp(a[0]);}});
r.declare({"escape_ground_precision4dp","native/src/output_precision.cpp::schgen::escape_ground_precision4dp","round(value, 4)","Ground-pad local coordinates round on both ladder construction and independent self-check passes.","pre-proof",1,[](const std::vector<double>& a){return schgen::escape_ground_precision4dp(a[0]);}});
r.declare({"escape_scan_precision3dp","native/src/output_precision.cpp::schgen::escape_scan_precision3dp","round(value, 3)","Every input scan coordinate rounds before set insertion, including inputs subsequently deduplicated.","pre-proof",1,[](const std::vector<double>& a){return schgen::escape_scan_precision3dp(a[0]);}});
r.declare({"escape_copper_precision4dp","native/src/output_precision.cpp::schgen::escape_copper_precision4dp","round(value, 4)","Each emitted escape via/segment coordinate rounds after board-frame transformation; final gates remain authoritative.","pre-proof",1,[](const std::vector<double>& a){return schgen::escape_copper_precision4dp(a[0]);}});
r.declare({"escape_coverage_precision4dp","native/src/output_precision.cpp::schgen::escape_coverage_precision4dp","round(value, 4)","Per-pad coverage and maximum coverage round after maximum accumulation, retaining the original unrounded maximum.","pre-proof",1,[](const std::vector<double>& a){return schgen::escape_coverage_precision4dp(a[0]);}});
r.declare({"escape_region_precision4dp","native/src/output_precision.cpp::schgen::escape_region_precision4dp","round(value, 4)","Escape-region metadata rounds each bound in x0,y0,x1,y1 order; geometric checks still use the original zone.","pre-proof",1,[](const std::vector<double>& a){return schgen::escape_region_precision4dp(a[0]);}});
r.declare({"escape_port_precision4dp","native/src/output_precision.cpp::schgen::escape_port_precision4dp","round(value, 4)","Lane port coordinates round after board transformation before lane insertion.","pre-proof",1,[](const std::vector<double>& a){return schgen::escape_port_precision4dp(a[0]);}});
r.declare({"escape_width_precision4dp","native/src/output_precision.cpp::schgen::escape_width_precision4dp","round(value, 4)","Each lane width rounds before insertion; failed later pair checks retain the executed prefix.","pre-proof",1,[](const std::vector<double>& a){return schgen::escape_width_precision4dp(a[0]);}});
r.declare({"escape_corridor_precision4dp","native/src/output_precision.cpp::schgen::escape_corridor_precision4dp","round(value, 4)","Corridor extrema round after min/min/max/max corner selection in the original ordering.","pre-proof",1,[](const std::vector<double>& a){return schgen::escape_corridor_precision4dp(a[0]);}});

}
}
