#include "schgen/pcb_checks.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <regex>
#include <sstream>

namespace {
using namespace schgen;
namespace fs=std::filesystem;
std::size_t checks=0;
void require(bool pass,const std::string& why){++checks;if(!pass)throw std::runtime_error(why);}
std::string read(const fs::path& p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot read fixture "+p.string());return {std::istreambuf_iterator<char>(f),{}};}
void equal(const std::string& a,const std::string& b,const std::string& why){++checks;if(a!=b){std::size_t i=0;while(i<a.size()&&i<b.size()&&a[i]==b[i])++i;throw std::runtime_error(why+" differs at byte "+std::to_string(i)+"\nactual: "+a.substr(i,300)+"\nexpect: "+b.substr(i,300));}}
bool has(const std::vector<std::string>& lines,const std::string& s){return std::any_of(lines.begin(),lines.end(),[&](const auto& l){return l.find(s)!=l.npos;});}
template<class F>void rejects(F fn,const std::string& why){bool threw=false;try{fn();}catch(const std::exception&){threw=true;}require(threw,why);}
const SexprList& ls(const Sexpr& n){return std::get<SexprList>(n.v);}
std::string atom(const Sexpr& n){if(auto p=std::get_if<std::string>(&n.v))return *p;if(auto p=std::get_if<Sexpr::Sym>(&n.v))return p->name;return sexpr_fmt_num(std::get<double>(n.v));}
bool tag(const Sexpr& n,const std::string& s){auto p=std::get_if<SexprList>(&n.v);return p&&!p->empty()&&atom(p->front())==s;}
const Sexpr* sub(const Sexpr& n,const std::string& s){for(const auto& c:ls(n))if(tag(c,s))return &c;return nullptr;}
Sexpr* mut_sub(Sexpr& n,const std::string& s){for(auto& c:std::get<SexprList>(n.v))if(tag(c,s))return &c;return nullptr;}
double num(const Sexpr& n,std::size_t i){return std::get<double>(ls(n).at(i).v);}
std::string prop(const Sexpr& fp,const std::string& key){for(const auto& c:ls(fp))if(tag(c,"property")&&atom(ls(c).at(1))==key)return atom(ls(c).at(2));return {};}
const JsonNode& field(const JsonNode& n,const std::string& k){auto p=object_field(n,k);if(!p)throw std::runtime_error("fixture field missing "+k);return *p;}
PcbCheckFootprintPtr small(){return pcb_check_footprint("fixture.kicad_mod",R"((footprint "fixture" (fp_rect (start -1 -1) (end 1 1) (layer "F.CrtYd")) (pad "1" smd rect (at -0.5 0) (size 0.3 0.6)) (pad "2" smd rect (at 0.5 0) (size 0.3 0.6))))");}
PcbCheckInstance part(std::string ref,double x,double y,int pins,std::string sheet="s"){PcbCheckInstance i;i.ref=ref;i.x=x;i.y=y;i.sheet=sheet;i.mod=small();for(int n=1;n<=pins;++n)i.pad_nets[std::to_string(n)]={n,"N"+std::to_string(n)};return i;}
void synthetic(){
    equal(pcb_sha256(""),"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","empty SHA-256");equal(pcb_sha256("abc"),"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad","abc SHA-256");equal(pcb_sha256(std::string(1000000,'a')),"cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0","multi-block SHA-256");
    PcbCheckModel m;m.board_w=100;m.board_h=100;m.insts={part("J1",50,124,2)};m.insts[0].value="HDMI-019S";
    auto good=check_placement_mech(PcbCheckInput(m));require(good.ok&&good.connectors[0].edge=="S","mechanical baseline");
    m.insts[0].rotation=180;require(has(check_placement_mech(PcbCheckInput(m)).bad_connectors,"faces inward"),"inward connector");m.insts[0].rotation=0;m.insts[0].y=90;require(has(check_placement_mech(PcbCheckInput(m)).bad_connectors,"interior"),"recessed connector");
    m.insts={part("R1",50,50,2)};m.som_core=Box4{45,45,55,55};require(check_placement_mech(PcbCheckInput(m)).top_under_som.size()==1,"top passive keepout");m.insts[0].side="bottom";require(check_placement_mech(PcbCheckInput(m)).ok,"bottom passive allowed");m.insts[0].ref="SW1";require(has(check_placement_mech(PcbCheckInput(m)).face_top_on_bottom,"emits B.Cu"),"face-down switch");m.insts[0].side="top";require(check_placement_mech(PcbCheckInput(m)).controls_under_som.size()==1,"buried control");
    m.som_core.reset();m.insts={part("J1",40,40,2),part("J2",60,40,2)};for(auto& i:m.insts)i.value="HDMI-019S";auto spacing=check_connector_spacing(PcbCheckInput(m));require(spacing.ok&&spacing.pairs.size()==1,"spacing green");m.insts[1].x=57;require(!check_connector_spacing(PcbCheckInput(m)).ok,"overmold mutant");m.insts[1].value="TF-01A";m.insts[1].x=44;require(!check_connector_spacing(PcbCheckInput(m)).ok,"one-sided gap mutant");m.insts[1].x=40;require(has(check_connector_spacing(PcbCheckInput(m)).violations,"OVERLAP"),"stacked connectors");
    auto partial=PcbCheckModel{};partial.board_w=partial.board_h=100;partial.insts={part("J1",40,124,2),part("J2",70,124,2),part("U9",50,50,8)};partial.insts[0].value=partial.insts[1].value="HDMI-019S";partial.insts[2].mod.reset();PcbCheckInput partial_input(partial);
    require(check_connector_spacing(partial_input).ok,"spacing ignores unresolved nonconnector");require(check_placement_mech(partial_input).ok,"mechanical without core ignores unused nonconnector geometry");rejects([&]{check_fanout(partial_input,0);},"fanout retains its all-courtyards requirement");partial.som_core=Box4{45,45,55,55};rejects([&]{check_placement_mech(PcbCheckInput(partial));},"mechanical core actually requires every courtyard");partial.som_core.reset();partial.insts[0].mod.reset();rejects([&]{check_connector_spacing(PcbCheckInput(partial));},"spacing requires connector geometry");
    for(double z:{0.,180.,-180.,360.,90.,270.,45.}){m.insts.resize(1);m.insts[0].mod=pcb_check_footprint("test","(footprint \"test\" (model \"x\" (rotate (xyz 0 0 "+sexpr_fmt_num(z)+"))))");auto r=check_connector_models(m);require(r.ok==(std::fmod(z,180)==0),"model Z orientation");}
    m.insts[0].mod.reset();require(check_connector_models(m).missing_model.size()==1,"unresolved model informational");rejects([&]{PcbCheckInput in(m);in.courtyard_at(0);},"required unresolved geometry cannot pass silently");
    m.insts[0].mod=pcb_check_footprint("tail",R"((footprint "tail" (pad "1" smd rect (at 0 2) (size 1 1)) (pad "2" smd rect (at 1 2) (size 1 1)) (pad "3" smd rect (at 0 -2) (size 1 1))))");require(check_connector_models(m).geom_conflicts.size()==1,"dense tail sign mutant");
    require(check_connector_models(m,{{"HDMI-019S","-Y"}}).geom_conflicts.empty(),"explicit mating-face policy respected");
    require(check_connector_models(m,{{"HDMI-019S","+Y"}}).geom_conflicts.size()==1,"policy mutation remains detectable");
    m.insts={part("U1",10,10,8),part("R2",12.5,10,2,"other")};auto fan=check_fanout(PcbCheckInput(m),0);require(!fan.ok&&fan.n_starved==1&&fan.records[0].clearance==0.5,"fanout foreign passive");m.insts[1].sheet="s";require(check_fanout(PcbCheckInput(m),0).ok,"own cluster ignored");m.insts[1].sheet="other";m.insts[1].side="bottom";require(check_fanout(PcbCheckInput(m),0).ok,"opposite side ignored");m.insts[1].side="top";m.insts[1].ref="TP2";require(check_fanout(PcbCheckInput(m),0).ok,"TP excluded");m.insts[1].ref="R2";require(check_fanout(PcbCheckInput(m),std::nullopt).ok,"first-run ratchet");require(pcb_fanout_ratchet(5,3)==3&&pcb_fanout_ratchet(1,3)==1,"ratchet never increases");require(pcb_is_df40_part("som_j7",1)&&pcb_is_df40_part("x",40)&&!pcb_is_df40_part("som_jx",3),"DF40 recognition");
    auto board=sexpr_loads(R"((kicad_pcb (footprint "x" (at 5 5 90) (property "Reference" "R1" (at 1 0) (layer "F.SilkS"))) (footprint "y" (at 5 4) (property "Reference" "R2" (at 0 0) (layer "F.SilkS")))))");auto refs=check_refdes_overlap(board);require(!refs.ok&&refs.top_pairs==std::vector<std::pair<std::string,std::string>>{{"R1","R2"}},"rotated refdes overlap");
    auto bottom=sexpr_loads(R"((kicad_pcb (footprint "x" (at 0 0) (property "Reference" "B1" (at 0 0) (layer "B.SilkS"))) (footprint "x" (at 0 0) (property "Reference" "B2" (at 0 0) (layer "B.SilkS"))) (footprint "x" (at 0 0) (property "Reference" "H1" (at 0 0) (layer "F.SilkS") (hide yes)))))");require(check_refdes_overlap(bottom).ok&&check_refdes_overlap(bottom).bottom_pairs==1&&!check_refdes_overlap(bottom,true).ok,"bottom enforcement and hidden refs");
    std::map<std::string,std::vector<ReturnPathContact>> contacts{{"J9",{{"J9","1",0,0,0,0,"X_P","SIGNAL"},{"J9","2",0,1,1,0,"X_N","SIGNAL"},{"J9","3",0,2,2,0,"GND","GND"}}}};require(check_return_path(contacts).ok,"adjacent return ground");contacts["J9"][2].klass="SIGNAL";auto rp=check_return_path(contacts);require(!rp.ok&&rp.n_fail()==2&&!rp.worst_distance,"missing return ground");equal(rp.violations[0].as_line(),"J9 pad 2 net X_N (pair X_*): nearest GND at none-on-connector steps > K=2","return path failure diagnostic");
    contacts["J9"].push_back({"J9","4",1,0,0,1,"GND","GND"});require(check_return_path(contacts).ok,"facing ground");require(pcb_pair_partner("IO_L14_N_SRCC_13")==std::optional<std::string>("IO_L14_P_SRCC_13")&&!pcb_pair_partner("X_N_P"),"PN token pairing");
    PcbCheckModel empty;auto missing=check_escape_lanes(empty,{},"contract");require(!missing.ok&&missing.violations.size()==1,"absent escape plan is red");
    auto signed_zero=PcbCheckModel{};signed_zero.insts={part("J1",1000000,0,1,"som_j1")};auto zero_key=pcb_escape_content_key(signed_zero,"contract");signed_zero.insts[0].rotation=-0.0;require(pcb_escape_content_key(signed_zero,"contract")==zero_key,"rotation or-zero content-key convention");
    PcbEscapePlan plan;plan.lanes["J1"]={{1,0,"outward","A",0,0,0.2,{}},{1,1,"outward","B",1,0,0.2,{}},{1,2,"outward","C",2,0,0.2,{}}};plan.netted_counts["J1"]=3;plan.pairs={{"X_*","J1","GENUINE",true,2}};plan.genuine_pairs={"X_*"};empty.escape_plan=plan;empty.escape_plan->content_key=pcb_escape_content_key(empty,"contract");PcbEscapePopulation pop;pop.netted_contacts=std::map<std::string,int>{{"J1",3}};pop.genuine_pairs=1;require(check_escape_lanes(empty,pop,"contract").ok,"escape baseline");auto em=empty;em.escape_plan->pairs[0].delta_lane=3;require(has(check_escape_lanes(em,pop,"contract").violations,"hard terms"),"pair separation mutant");em=empty;em.escape_plan->lanes["J1"][1].port_x=3;require(has(check_escape_lanes(em,pop,"contract").violations,"ports not monotonic"),"lane port order mutant");em=empty;em.escape_plan->lanes["J1"][0].width=0.4;require(has(check_escape_lanes(em,pop,"contract").violations,"adjacent-lane gap"),"lane width mutant");require(has(check_escape_lanes(empty,pop,"changed").violations,"STALE"),"interface byte mutation");require(!check_escape_lanes(empty,{},"contract").ok,"unbooked population cannot pass");
    SomInterface iface;SomConnector conn;conn.pins={{"1","+5V"},{"2","+5V"}};iface.connectors={{"J1",conn}};ProjectCircuit sc;sc.name="som_j1";sc.circuit.loads={{"+5V",0.4,"test"}};auto rail=analyze_rail_ampacity({sc},iface,{});require(rail.ok()&&rail.rails[0].capacity_a()==0.48,"rated contact capacity");sc.circuit.loads[0].amps=0.49;require(!analyze_rail_ampacity({sc},iface,{}).ok(),"over-current mutant");sc.name="carrier_load";require(analyze_rail_ampacity({sc},iface,{}).findings.size()==1,"only delivered loads");
}

struct Live {
    PcbCheckModel model;
    PcbEmittedBoard board;
    SomInterface iface;
    std::string iface_bytes;
    LinkMapping mapping;
    PcbEscapePopulation population;
    std::vector<ProjectCircuit> sheets;
    std::map<std::string,PcbCheckFootprintPtr> pool,return_footprints;
};
Live load_live(const fs::path& root,const std::string& project){
    Live live;auto dir=root/project;live.board={"Zynq_Carrier.kicad_pcb",sexpr_loads(read(dir/"Zynq_Carrier.kicad_pcb"))};live.iface_bytes=read(dir/"som_interface.json");live.iface=load_som_interface(dir/"som_interface.json");live.mapping=link_mapping_from_json(parse_json_file((dir/"som_mapping.json").string()));auto config=parse_json_file((dir/"project.json").string());live.population=pcb_escape_population_from_json(field(config,"escape"));auto block=parse_json_file((dir/"escape_block.json").string());live.model.escape_plan=pcb_escape_plan_from_json(block);live.model.escape_interface_sha256=field(field(block,"escape_meta"),"som_interface_sha256").string_value;
    auto index=parse_json_file((dir/"sheet_index.json").string());std::map<int,std::string> bands;for(const auto& [name,n]:index.object_value)bands[static_cast<int>(n.number_value)]=name;
    for(const auto& [band,name]:bands){(void)band;auto path=dir/"subsystems"/name/"circuit.json";if(fs::exists(path))live.sheets.push_back({name,path,load_circuit_json(path)});}
    auto footprint=[&](const std::string& id){auto it=live.pool.find(id);if(it!=live.pool.end())return it->second;auto colon=id.find(':');auto lib=id.substr(0,colon),name=id.substr(colon+1);fs::path path=root/"parts"/name/(name+".kicad_mod");if(!fs::exists(path))for(const auto& base:{fs::path("/Applications/KiCad/KiCad.app/Contents/SharedSupport/footprints"),fs::path("/usr/share/kicad/footprints"),fs::path("/usr/local/share/kicad/footprints")}){auto candidate=base/(lib+".pretty")/(name+".kicad_mod");if(fs::exists(candidate)){path=candidate;break;}}auto fp=pcb_check_footprint(path.string(),read(path));live.pool[id]=fp;return fp;};
    double xmax=25,ymax=25;
    for(const auto& n:ls(live.board.document)){
        if(tag(n,"net"))live.model.net_numbers[atom(ls(n)[2])]=static_cast<int>(num(n,1));
        if(tag(n,"gr_line")){auto layer=sub(n,"layer");if(layer&&atom(ls(*layer)[1])=="Edge.Cuts")for(auto key:{"start","end"}){auto p=sub(n,key);xmax=std::max(xmax,num(*p,1));ymax=std::max(ymax,num(*p,2));}}
        if(!tag(n,"footprint"))continue;PcbCheckInstance inst;inst.ref=prop(n,"Reference");inst.value=prop(n,"Value");inst.footprint=atom(ls(n)[1]);auto at=sub(n,"at");inst.x=num(*at,1);inst.y=num(*at,2);inst.rotation=ls(*at).size()>3?num(*at,3):0;inst.side=atom(ls(*sub(n,"layer"))[1])=="B.Cu"?"bottom":"top";inst.mod=footprint(inst.footprint);std::smatch match;if(std::regex_search(inst.ref,match,std::regex("[0-9]+$"))){auto b=bands.find(std::stoi(match.str())/1000);if(b!=bands.end())inst.sheet=b->second;}
        // The source PcbModel books every numbered pad, including NC pads
        // that KiCad omits from emitted (net ...) clauses.
        if(inst.footprint.find("Fiducial")==std::string::npos)for(const auto& p:inst.mod->pads)if(!std::get<0>(p).empty())inst.pad_nets[std::get<0>(p)]={0,""};
        for(const auto& p:ls(n))if(tag(p,"pad")){auto net=sub(p,"net");if(net)inst.pad_nets[atom(ls(p)[1])]={static_cast<int>(num(*net,1)),atom(ls(*net)[2])};}
        live.model.insts.push_back(inst);
    }
    live.model.board_w=xmax-25;live.model.board_h=ymax-25;
    // Pinned module-body geometry from the existing project placement contract.
    live.model.som_core=project=="carrier"?Box4{73.23,90.93,124.77,134.07}:Box4{49.23,53.43,100.77,96.57};
    for(const auto& [ref,conn]:live.iface.connectors){(void)conn;live.return_footprints[ref]=footprint("DF40C-100DS-0.4V_51:DF40C-100DS-0.4V_51");}
    for(const auto& [name,net]:live.model.net_numbers){(void)net;if(!name.empty()&&name[0]=='+')live.model.netclass_of[name]="POWER";}
    PcbCheckInput prepared(live.model);std::map<std::string,std::size_t> plugs;for(std::size_t i=0;i<live.model.insts.size();++i){auto s=live.model.insts[i].sheet;if(s=="som_j1"||s=="som_j2"||s=="som_j3")plugs["J"+s.substr(5)]=i;}
    for(const auto& n:ls(live.board.document)){
        if((!tag(n,"via")&&!tag(n,"segment"))||!sub(n,"locked"))continue;PcbCheckCopper c;c.kind=atom(ls(n)[0]);c.group="som_escape";c.net=static_cast<int>(num(*sub(n,"net"),1));for(const auto& [name,id]:live.model.net_numbers)if(id==c.net)c.net_name=name;
        double x,y;if(c.kind=="via"){c.x=x=num(*sub(n,"at"),1);c.y=y=num(*sub(n,"at"),2);c.size=num(*sub(n,"size"),1);c.drill=num(*sub(n,"drill"),1);c.role="stitch";}else{c.x1=num(*sub(n,"start"),1);c.y1=num(*sub(n,"start"),2);c.x2=num(*sub(n,"end"),1);c.y2=num(*sub(n,"end"),2);c.width=num(*sub(n,"width"),1);c.layer=atom(ls(*sub(n,"layer"))[1]);x=(c.x1+c.x2)/2;y=(c.y1+c.y2)/2;c.role="spine";}
        double best=std::numeric_limits<double>::infinity();std::size_t chosen=0;for(const auto& [ref,i]:plugs){auto& p=live.model.insts[i];double d=std::hypot(x-p.x,y-p.y);if(d<best){best=d;c.conn=ref;chosen=i;}}
        // Metadata recovery is test-only: the frozen PCB has locked escape
        // copper but no role/group properties. A stub's endpoint copper must
        // touch an actual GND pad (paired stubs lie between two GND columns).
        // No synthetic segment/via is ever introduced.
        if(c.kind=="segment")for(const auto& [pad,b]:prepared.geometry_at(chosen).pad_boxes){auto p=live.model.insts[chosen].pad_nets.find(pad);double r=c.width/2;if(p!=live.model.insts[chosen].pad_nets.end()&&p->second.second=="GND")if((b.x0-r<=c.x1&&c.x1<=b.x1+r&&b.y0-r<=c.y1&&c.y1<=b.y1+r)||(b.x0-r<=c.x2&&c.x2<=b.x1+r&&b.y0-r<=c.y2&&c.y2<=b.y1+r))c.role="stub";}
        live.model.copper.push_back(c);
    }
    return live;
}
std::map<std::string,ReturnStitchClass> triage(const ReturnPathResult& v1,const LinkMapping& mapping){
    std::map<std::string,ReturnStitchClass> out;for(const auto& v:v1.violations){auto it=mapping.function_map.find(v.net);auto fn=it==mapping.function_map.end()?v.net:it->second;int rank=2;std::string klass="LOW";if(std::regex_match(fn,std::regex("HDMI_RX_(D[0-9]|CLK)_[PN]|ZYNQ_HDMI_TX_TMDS_([0-9]|CLK)_[PN]"))){rank=0;klass="GENUINE";}else if(fn.compare(0,4,"FMC_")==0){rank=1;klass="MODERATE";}else require(std::regex_match(fn,std::regex("IO_.*|LCD_CTP_.*|PMODX?_IO[0-9]|DBG_UART_.*|ZYNQ_PS_UART0_.*|HDMI_RX_CEC|ESC_PWM_IN[0-9]")),"curated fixture triage "+fn);out[v.net]={rank,klass,fn};}return out;
}
void real_project(const fs::path& root,const std::string& name){
    auto live=load_live(root,name);PcbCheckInput input(live.model);auto fixture=root/"native/tests/data/pcb_checks";auto snapshot=[&](const std::string& gate,const std::string& report){equal(report+"\n",read(fixture/(name+"_"+gate+".txt")),name+" "+gate);};
    auto v1=check_return_path(live.iface,live.return_footprints);require(!v1.ok&&v1.n_pairs==69&&v1.n_pair_contacts==138&&v1.n_fail()==29&&v1.worst_distance==4,name+" pinned v1 failure");auto expected=read(fixture/(name+"_return_path.txt"));equal(v1.summary()+"\n",expected.substr(expected.find("RETURN-PATH GATE")),name+" return-path exact report");
    snapshot("connector_model",check_connector_models(live.model).summary());snapshot("connector_spacing",check_connector_spacing(input).summary());snapshot("placement_mech",check_placement_mech(input).summary());snapshot("fanout",check_fanout(input,0).summary());snapshot("rail_ampacity",analyze_rail_ampacity(live.sheets,live.iface,live.mapping).report());
    snapshot("escape_lanes",check_escape_lanes(live.model,live.population,live.iface_bytes).summary());auto classes=triage(v1,live.mapping);auto stitch=check_return_stitch(input,v1,classes,live.iface_bytes,&live.board);require(stitch.ok,stitch.summary());snapshot("return_stitch",stitch.summary());require(check_refdes_overlap(live.board.document).ok,name+" emitted refdes baseline");
    auto mutated=live.model;mutated.copper.clear();auto red=check_return_stitch(PcbCheckInput(mutated),v1,classes,live.iface_bytes);require(!red.ok&&red.n_contacts==29&&red.n_covered==0&&red.per_conn.at("J2").second==28,name+" remove all actual return copper");
    mutated=live.model;mutated.copper.front().net_name="SIGNAL";require(has(check_return_stitch(PcbCheckInput(mutated),v1,classes,live.iface_bytes).violations,"LAW 0"),name+" wrong copper net");
    mutated=live.model;mutated.escape_interface_sha256="stale";require(!check_return_stitch(PcbCheckInput(mutated),v1,classes,live.iface_bytes).hash_ok,name+" stale stitch hash");
    mutated=live.model;mutated.copper.front().x=0;mutated.copper.front().y=0;require(has(check_return_stitch(PcbCheckInput(mutated),v1,classes,live.iface_bytes).violations,"outside the canonical"),name+" off-plane via");
    mutated=live.model;bool placed=false;for(std::size_t i=0;i<mutated.insts.size()&&!placed;++i)if(mutated.insts[i].sheet=="som_j2")for(const auto& [pad,b]:input.geometry_at(i).pad_boxes){auto net=mutated.insts[i].pad_nets.find(pad);if(net!=mutated.insts[i].pad_nets.end()&&net->second.second!="GND"){mutated.copper.front().x=(b.x0+b.x1)/2;mutated.copper.front().y=(b.y0+b.y1)/2;placed=true;break;}}require(placed,"actual foreign pad for clearance mutation");require(has(check_return_stitch(PcbCheckInput(mutated),v1,classes,live.iface_bytes).violations,"vs foreign"),name+" via in actual foreign copper");
    mutated=live.model;auto via=std::max_element(mutated.copper.begin(),mutated.copper.end(),[](const auto& a,const auto& b){return (a.kind=="via"?a.x:-1)<(b.kind=="via"?b.x:-1);});mutated.copper.erase(via);require(!check_return_stitch(PcbCheckInput(mutated),v1,classes,live.iface_bytes).ok,name+" remove actual farthest stitch via");
    mutated=live.model;mutated.copper.erase(std::remove_if(mutated.copper.begin(),mutated.copper.end(),[](const auto& c){return c.kind=="segment"&&c.role=="spine";}),mutated.copper.end());require(has(check_return_stitch(PcbCheckInput(mutated),v1,classes,live.iface_bytes).violations,"components"),name+" missing spines");
    auto pcb=live.board;auto& nodes=std::get<SexprList>(pcb.document.v);nodes.erase(std::remove_if(nodes.begin(),nodes.end(),[](const auto& n){auto p=tag(n,"zone")?sub(n,"name"):nullptr;return p&&atom(ls(*p)[1])=="GND_plane_In1";}),nodes.end());require(has(check_return_stitch(input,v1,classes,live.iface_bytes,&pcb).violations,"canonical GND_plane_In1 zone absent"),name+" emitted plane deletion");
    pcb=live.board;auto& deleted=std::get<SexprList>(pcb.document.v);auto emitted_via=std::find_if(deleted.begin(),deleted.end(),[](const auto& n){return tag(n,"via")&&sub(n,"locked");});require(emitted_via!=deleted.end(),"actual emitted stitch via");deleted.erase(emitted_via);require(has(check_return_stitch(input,v1,classes,live.iface_bytes,&pcb).violations,"absent from"),name+" emitted via deletion");
    mutated=live.model;auto plug=std::find_if(mutated.insts.begin(),mutated.insts.end(),[](const auto& i){return i.sheet=="som_j2";});plug->x+=0.1;require(has(check_escape_lanes(mutated,live.population,live.iface_bytes).violations,"STALE"),name+" moved live DF40");mutated=live.model;mutated.escape_plan->pairs.front().same_row=false;require(!check_escape_lanes(mutated,live.population,live.iface_bytes).ok,name+" real genuine-pair corruption");
    auto changed=live.iface;for(auto& [ref,c]:changed.connectors){(void)ref;for(auto& [pin,net]:c.pins){(void)pin;if(net=="GND")net="LOST_GND_SIGNAL";}}auto changed_v1=check_return_path(changed,live.return_footprints);require(changed_v1.n_fail()==138&&!changed_v1.worst_distance,name+" remove all SoM grounds");
    auto drift=v1;drift.n_pairs=68;require(has(check_return_stitch(input,drift,classes,live.iface_bytes).violations,"v1 population drift"),name+" pinned v1 alarm");
    auto low=classes;for(auto& [net,c]:low){(void)net;c.klass="LOW";c.rank=2;}mutated=live.model;mutated.copper.clear();require(check_return_stitch(PcbCheckInput(mutated),v1,low,live.iface_bytes).n_covered==0,name+" triage never waives uncovered contacts");
    rejects([&]{check_return_stitch(input,v1,{},live.iface_bytes);},name+" missing curated class cannot silently pass");
    auto sheets=live.sheets;for(auto& sc:sheets)if(sc.name=="som_j1")sc.circuit.loads.push_back({"+5V_SOM",10,"mutation"});require(!analyze_rail_ampacity(sheets,live.iface,live.mapping).ok(),name+" real load overload");
    mutated=live.model;auto conn=std::find_if(mutated.insts.begin(),mutated.insts.end(),[](const auto& i){return i.value=="TYPE-C-31-M-12";});require(conn!=mutated.insts.end(),"actual USB connector");conn->rotation+=180;require(!check_placement_mech(PcbCheckInput(mutated)).ok,name+" real connector reversed");
    auto mod=conn->mod->document;auto model_node=mut_sub(mod,"model");auto rotate=mut_sub(*model_node,"rotate");auto xyz=mut_sub(*rotate,"xyz");std::get<SexprList>(xyz->v)[3]=Sexpr{90.};conn->mod=pcb_check_footprint(conn->mod->source,sexpr_dumps(mod),mod);require(!check_connector_models(mutated).ok,name+" actual connector model rotated 90 degrees");require(check_connector_models(live.model).ok,name+" immutable footprint sharing preserves baseline");
    mutated=live.model;std::vector<std::size_t> usb;for(std::size_t i=0;i<mutated.insts.size();++i)if(mutated.insts[i].value=="TYPE-C-31-M-12")usb.push_back(i);require(usb.size()>=2,"two actual USB connectors");mutated.insts[usb[1]].x=mutated.insts[usb[0]].x;mutated.insts[usb[1]].y=mutated.insts[usb[0]].y;mutated.insts[usb[1]].rotation=mutated.insts[usb[0]].rotation;require(has(check_connector_spacing(PcbCheckInput(mutated)).violations,"OVERLAP"),name+" actual connector stack");
    pcb=live.board;std::vector<std::pair<Sexpr*,Sexpr*>> silk;for(auto& fp:std::get<SexprList>(pcb.document.v))if(tag(fp,"footprint"))for(auto& p:std::get<SexprList>(fp.v))if(tag(p,"property")&&atom(ls(p)[1])=="Reference"){auto lay=sub(p,"layer");if(lay&&atom(ls(*lay)[1])=="F.SilkS"&&!sub(p,"hide"))silk.emplace_back(&fp,&p);}require(silk.size()>=2,"two actual visible refs");*mut_sub(*silk[1].first,"at")=*sub(*silk[0].first,"at");*mut_sub(*silk[1].second,"at")=*sub(*silk[0].second,"at");require(!check_refdes_overlap(pcb.document).ok,name+" actual emitted refdes collision");
    mutated=live.model;auto subject=std::find_if(mutated.insts.begin(),mutated.insts.end(),[](const auto& i){return i.ref[0]=='U'&&i.pad_nets.size()>=3&&i.pad_nets.size()<40;});auto crowder=std::find_if(mutated.insts.begin(),mutated.insts.end(),[&](const auto& i){return i.ref[0]=='R'&&i.sheet!=subject->sheet;});require(crowder!=mutated.insts.end(),"actual fanout crowder");crowder->x=subject->x;crowder->y=subject->y;crowder->side=subject->side;require(!check_fanout(PcbCheckInput(mutated),0).ok,name+" real fanout crowding");
    std::cout<<name<<": eight exact report snapshots and real PCB/interface mutations passed\n";
}
}
int main(int argc,char** argv){try{fs::path root=argc>1?argv[1]:fs::current_path();synthetic();real_project(root,"carrier");real_project(root,"devkit_mini");std::cout<<"PCB checks: "<<checks<<" independent contracts passed\n";return 0;}catch(const std::exception& e){std::cerr<<"PCB checks contract FAILED: "<<e.what()<<"\n";return 1;}}
