#pragma once
#include "schgen/native_audit_state.hpp"
#include "schgen/stage_precision.hpp"
// Parent integration specification; this test helper is NOT production census.
namespace stage_precision_fixture {
inline void register_operations(schgen::NativeQuantizations& registry){
    registry.declare({"stage_shift_precision4dp","native/src/stage_precision.cpp::schgen::stage_shift_precision4dp","round(value, 4)","Each coordinate addition performed by shifted, including trial layouts and renormalization, retains its four-decimal boundary.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_shift_precision4dp(a[0]);}});
    registry.declare({"stage_root_pose_precision4dp","native/src/stage_precision.cpp::schgen::stage_root_pose_precision4dp","round(value, 4)","Contract-graph root placement retains the cursor-minus-body-edge four-decimal boundary at every widening trial.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_root_pose_precision4dp(a[0]);}});
    registry.declare({"stage_connector_alignment_delta_precision4dp","native/src/stage_precision.cpp::schgen::stage_connector_alignment_delta_precision4dp","round(value, 4)","Connector-bearing frame alignment retains target-minus-face rounding before testing whether a shift is needed.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_connector_alignment_delta_precision4dp(a[0]);}});
    registry.declare({"stage_connector_clearance_line_precision4dp","native/src/stage_precision.cpp::schgen::stage_connector_clearance_line_precision4dp","round(value, 4)","The connector clearance line retains addition of the signed seat slide before four-decimal rounding.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_connector_clearance_line_precision4dp(a[0]);}});
    registry.declare({"stage_connector_clearance_delta_precision4dp","native/src/stage_precision.cpp::schgen::stage_connector_clearance_delta_precision4dp","round(value, 4)","Nonconnector frame clearance retains line-minus-edge rounding before the existing min/max clamp and conditional shift.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_connector_clearance_delta_precision4dp(a[0]);}});
    registry.declare({"stage_ldo_pose_precision4dp","native/src/stage_precision.cpp::schgen::stage_ldo_pose_precision4dp","round(value, 4)","Each LDO capacitor trial retains its independent x and pin-center y rounding, including rejected scales.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_ldo_pose_precision4dp(a[0]);}});
    registry.declare({"stage_power_mirror_pose_precision4dp","native/src/stage_precision.cpp::schgen::stage_power_mirror_pose_precision4dp","round(value, 4)","Every mirrored power-layout candidate retains center/subtract/subtract arithmetic and four-decimal rounding before selection.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_power_mirror_pose_precision4dp(a[0]);}});
    registry.declare({"stage_layout_width_precision4dp","native/src/stage_precision.cpp::schgen::stage_layout_width_precision4dp","round(value, 4)","Only eligible power-layout widths enter the existing four-decimal ranking boundary; eligibility and tuple ordering are unchanged.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_layout_width_precision4dp(a[0]);}});
    registry.declare({"stage_hot_leftover_pose_precision4dp","native/src/stage_precision.cpp::schgen::stage_hot_leftover_pose_precision4dp","round(value, 4)","Power-zone leftover coordinates retain separate x and translated-y rounding.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_hot_leftover_pose_precision4dp(a[0]);}});
    registry.declare({"stage_hot_extent_precision4dp","native/src/stage_precision.cpp::schgen::stage_hot_extent_precision4dp","round(value, 4)","Power-zone leftover-expanded dimensions retain their existing maximum and four-decimal rounding boundaries.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_hot_extent_precision4dp(a[0]);}});
    registry.declare({"stage_proximity_leftover_pose_precision4dp","native/src/stage_precision.cpp::schgen::stage_proximity_leftover_pose_precision4dp","round(value, 4)","Proximity-zone leftover coordinates retain offset additions before four-decimal rounding.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_proximity_leftover_pose_precision4dp(a[0]);}});
    registry.declare({"stage_proximity_rebase_precision4dp","native/src/stage_precision.cpp::schgen::stage_proximity_rebase_precision4dp","round(value, 4)","Proximity-zone rebasing rounds each coordinate only when the existing gx/gy condition executes.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_proximity_rebase_precision4dp(a[0]);}});
    registry.declare({"stage_proximity_extent_precision4dp","native/src/stage_precision.cpp::schgen::stage_proximity_extent_precision4dp","round(value, 4)","Proximity-zone dimensions retain both leftover extent rounds and final rounds as distinct actual calls.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_proximity_extent_precision4dp(a[0]);}});
    registry.declare({"stage_proximity_face_shift_precision4dp","native/src/stage_precision.cpp::schgen::stage_proximity_face_shift_precision4dp","round(value, 4)","Negative connector-edge alignment retains each actually shifted proximity coordinate rounding.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_proximity_face_shift_precision4dp(a[0]);}});
    registry.declare({"stage_refit_pad_precision3dp","native/src/stage_precision.cpp::schgen::stage_refit_pad_precision3dp","round(value, 3)","Each evaluated facing-refit airwire pad center retains center-then-translate and three-decimal rounding, including losing candidates.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_refit_pad_precision3dp(a[0]);}});
    registry.declare({"stage_candidate_radius_trunc","native/src/stage_precision.cpp::schgen::stage_candidate_radius_trunc","int(value)","Candidate radius preserves the caller quotient then truncation toward zero, before the existing cap of 60; undefined narrowing rejects.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_candidate_radius_trunc(a[0]);}});
    registry.declare({"stage_seat_radius_trunc","native/src/stage_precision.cpp::schgen::stage_seat_radius_trunc","int(value)","Seat radius preserves the caller quotient then truncation toward zero; undefined narrowing rejects without replacing caller arithmetic.","pre-proof",1,[](const std::vector<double>& a){return schgen::stage_seat_radius_trunc(a[0]);}});
}
}
