"""RVT1C101M0605 100UF 16V — RVT1C101M0605_C970684 (CAP-SMD_BD6.3-L6.6-W6.6-LS7.2-FD)

Generated by `schgen part add C970684` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'RVT1C101M0605 100UF 16V'
SAFE_NAME = 'RVT1C101M0605_100UF_16V'
LCSC = 'C970684'
DESCRIPTION = 'RVT1C101M0605_C970684 (CAP-SMD_BD6.3-L6.6-W6.6-LS7.2-FD)'
MANUFACTURER = 'DMBJ(振宝佳)'
PACKAGE = 'CAP-SMD_BD6.3-L6.6-W6.6-LS7.2-FD'
JLC_CLASS = 'Extended Part'
PREFIX = 'C'
DATASHEET = 'https://www.lcsc.com/datasheet/C970684.pdf'
PRODUCT_URL = ''
LIB_ID = 'RVT1C101M0605_100UF_16V:RVT1C101M0605_100UF_16V'
FOOTPRINT = 'RVT1C101M0605_100UF_16V:RVT1C101M0605_100UF_16V'
MODELS_3D = ['RVT1C101M0605_100UF_16V.wrl', 'RVT1C101M0605_100UF_16V.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('2', '2', 'passive'),
]
