"""hdmi_tx — HDMI source port: host TMDS -> TPD12S016 -> HDMI Type-A receptacle.

PROJECT-AGNOSTIC, REUSABLE subsystem (the ``subsystems/<name>/`` library layout;
see ``subsystems/usb_pd/`` for the worked exemplar). It declares its interface as
ABSTRACT port + rail names and knows NOTHING about any consuming board — no
carrier net names. A project consumes it by calling :func:`circuit` with the
STANDARD ``meta`` dict (see :mod:`schgen.core.subsystem`): ``bind`` rebinds every
externally-visible net to its real board name, ``expects`` adds per-port linker
deferrals, ``buses`` renames the DDC bus group, ``notes`` restores house-style
prose. Standalone (``meta=None``) it keeps the abstract names so this package's
``test_hdmi_tx.py`` runs offline.

Reference circuit per TI TPD12S016 (SLLSE96F) Figure 15, "HDMI source using
one GPIO", with CT_HPD and LS_OE strapped HIGH (10k to V_CCA) so the level
shifters and the on-chip 55 mA +5V load switch are always on:

  * The 8 TMDS lines flow THROUGH the TPD's clamp pads to the receptacle.
    The faithful TPD12S016 dossier symbol carries each TMDS clamp as its own
    A-side/B-side pin number (15..23, datasheet pin map); the port nets below
    join the A pin and the receptacle so the lane is one net per TMDS line
    (proven against kicad-cli netlist export, re-proven by the netlist gate).
  * DDC (SCL/SDA), CEC and HPD pass through the TPD's level shifters:
    A-side nets (DDC_SCL/SDA, CEC, HPD) are V_CCA-domain ports to the host;
    B-side nets (HDMI_TX_CON_*) run at the cable's 5 V to the receptacle.
    All DDC/CEC/HPD pull-ups are integrated (DS Sec 7.3.9/7.3.15) — no
    external resistors, and no EDID EEPROM (a SOURCE reads the sink's EDID).
  * +5V (the current-limited switch output) sources receptacle pin 18;
    100n HF + 1u bulk at the connector per HDMI 1.4 Sec 4.2.7.
  * Rails: +VDD_IO on V_CCA (controller side) and +5V on V_CC5V (cable side),
    each decoupled 100n (DS Fig 15). A consuming board can gate them upstream.
  * Receptacle: SOFNG HDMI-019S; shield/CK..D2 ground pins to GND, the four
    shell legs to CHASSIS_GND (star-bonded by the consuming board). Pin 14
    (HEC/Utility) is reserved -> author no-connect (HDMI 1.4: N.C. on
    non-HEAC devices).

Pin maps are the LCSC/EasyEDA tables fetched by `schgen part add C201665` /
`add C111617` (parts/TPD12S016PWR, parts/HDMI-019S) — the schgen symbols are
asserted against them at generation time, and `c.validate` + the netlist
gate re-check every pin on every build.
"""

from __future__ import annotations

from schgen.core.model import Circuit
from schgen.core.subsystem import Meta

# FAITHFUL dossier symbols (no lib_id override — the "0 hand-built symbols"
# law): the box symbols generated by `schgen part add` from parts/TPD12S016PWR/
# + parts/HDMI-019S/ are used directly. Their pin NUMBERS match the datasheet,
# so the by-number netting below is unchanged (LAW 0 — same netlist).
R_FP = "Resistor_SMD:R_0603_1608Metric"
C_FP = "Capacitor_SMD:C_0603_1608Metric"

LCSC_100N = "C14663"     # CC0603KRX7R9BB104 100n 0603 X7R 50V (JLC Basic)
LCSC_1U = "C15849"      # CL10A105KB8NNNC 1u 0603 X5R 25V (JLC Basic)
LCSC_10K = "C25804"     # 0603WAF1002T5E 10k 1% (JLC Basic)

# ---- the abstract interface (the REUSE contract) ------------------------------
# Externally-visible net names a consuming project binds. RAILS classify as
# POWER/GROUND by name (a leading '+' = POWER; GND/CHASSIS_GND = GROUND), exactly
# as the bound carrier rails do, so a standalone build and a bound build share
# net classes. PORTS are the host-side (A-side) level-shifted + TMDS lines that
# cross the sheet boundary to the source SoC; the connector-side (B-side) lanes
# are PRIVATE SIGNAL wiring (HDMI_TX_CON_*) and are never part of the contract.
RAILS = ("+VDD_IO", "+5V", "GND", "CHASSIS_GND")
# host-side TMDS pairs (the V_CCA-domain differential lines from the source SoC)
TMDS_PORTS = (
    "TMDS_D2_P", "TMDS_D2_N",
    "TMDS_D1_P", "TMDS_D1_N",
    "TMDS_D0_P", "TMDS_D0_N",
    "TMDS_CLK_P", "TMDS_CLK_N",
)
# host-side level-shifted control lines (DDC I2C, CEC, hot-plug detect)
CTRL_PORTS = ("CEC", "DDC_SCL", "DDC_SDA", "HPD")
PORTS = TMDS_PORTS + CTRL_PORTS
INTERFACE = RAILS + PORTS

# The DDC bus this source sits on (HDMI 1.4 DDC = I2C, 100 kHz). The bus NAME is
# a project-level grouping (the linker groups SCL/SDA by it) and may be
# overridden via meta["buses"]["ddc"]; the default is the abstract name for
# standalone use.
DDC_BUS = "HDMI_TX_DDC"
DDC_SPEED_HZ = 100_000

# Default power-tree draw notes. A project may override the prose via
# meta["notes"]["draws_vcca"] / ["draws_5v"] to cite its own dossier wording.
DRAWS_VCCA_NOTE = "TPD12S016 ICCA + LS_OE/CT_HPD straps"
DRAWS_VCCA_A = 0.002
DRAWS_5V_NOTE = ("HDMI source +5V to cable — TPD12S016 switch limit 55 mA "
                 "(DS 7.3.10)")
DRAWS_5V_A = 0.055

# TMDS lane -> (abstract host port, TPD flow-through pad, receptacle pin).
# Sources: TI SLLSE96F Sec 5 pin map; HDMI 1.4 Sec 4.2.2 connector pinout (both
# re-checked against the parts/<MPN>/part.py LCSC tables).
TMDS_LANES = (
    ("TMDS_D2_P", "23", "1"), ("TMDS_D2_N", "22", "3"),
    ("TMDS_D1_P", "21", "4"), ("TMDS_D1_N", "20", "6"),
    ("TMDS_D0_P", "18", "7"), ("TMDS_D0_N", "17", "9"),
    ("TMDS_CLK_P", "16", "10"), ("TMDS_CLK_N", "15", "12"),
)
# the four differential pairs (P/N) of the above, for c.port_type pairing
TMDS_PAIRS = (
    ("TMDS_D2_P", "TMDS_D2_N"),
    ("TMDS_D1_P", "TMDS_D1_N"),
    ("TMDS_D0_P", "TMDS_D0_N"),
    ("TMDS_CLK_P", "TMDS_CLK_N"),
)
# level-shifted lines: (abstract host port, internal B-side net, TPD A pin,
# TPD B pin, receptacle pin)
SHIFTED = (
    ("CEC", "HDMI_TX_CON_CEC", "1", "7", "13"),
    ("DDC_SCL", "HDMI_TX_CON_SCL", "2", "8", "15"),
    ("DDC_SDA", "HDMI_TX_CON_SDA", "3", "9", "16"),
    ("HPD", "HDMI_TX_CON_HPD", "4", "10", "19"),
)


def circuit(meta: "Meta | dict | None" = None) -> Circuit:
    """Build the hdmi_tx subsystem netlist with ABSTRACT port/rail names.

    ``meta`` is the STANDARD subsystem adapter contract (see
    :mod:`schgen.core.subsystem`) — a single dict a consuming project's adapter
    declares. Keys this subsystem reads (all optional; ``meta=None`` ->
    standalone abstract names for the local test):

      ``bind``    ``{abstract_name: project_net}`` rebinds the externally-visible
                  nets (the :data:`INTERFACE` names) to a project's real board
                  names. Applied last (order-preserving => byte-identical sheet).
      ``expects`` ``{abstract_port: deferral}`` attaches an EXPLICIT linker
                  deferral to a port — a project declares which of its sheets
                  will bind a deferred port (e.g. the host TMDS/DDC/CEC/HPD lines
                  that bind on a generated connector sheet).
      ``buses``   ``{"ddc": name}`` the DDC bus-group NAME for SCL/SDA (a
                  project-level grouping; defaults to the abstract
                  :data:`DDC_BUS`).
      ``notes``   ``{"draws_vcca"/"draws_5v": prose}`` the power-tree draw-note
                  prose (a project may cite its own dossier wording; defaults to
                  :data:`DRAWS_VCCA_NOTE` / :data:`DRAWS_5V_NOTE`).
    """
    meta = Meta(meta)
    ddc_bus = meta.bus("ddc", DDC_BUS)
    draws_vcca = meta.note("draws_vcca", DRAWS_VCCA_NOTE)
    draws_5v = meta.note("draws_5v", DRAWS_5V_NOTE)

    c = Circuit("hdmi_tx", "HDMI TX: TPD12S016 + HDMI-A receptacle (source)")
    c.use_part("TPD12S016PWR", ref="U1")
    c.use_part("HDMI-019S", ref="J1")

    # rails + DS Fig 15 decoupling (a consuming board may gate them upstream)
    c.net("+VDD_IO", "U1.24")                       # V_CCA, controller side
    c.net("+5V", "U1.11")                           # V_CC5V, load-switch input
    for cap in c.decouple("U1.24", "100n", footprint=C_FP):       # C1
        cap.fields["LCSC"] = LCSC_100N
    for cap in c.decouple("U1.11", "100n", footprint=C_FP):       # C2
        cap.fields["LCSC"] = LCSC_100N
    # bulk on the +VDD_IO rail (each module owns its bulk; matches camera/microsd
    # 10u peers). C5: C3/C4 are hardcoded further down, so an explicit free ref
    # avoids a collision.
    c.part("C5", "Device:C", "10u",
           "Capacitor_SMD:C_0805_2012Metric", LCSC="C15850")
    c.net("+VDD_IO", "C5.1")
    c.net("GND", "C5.2")

    # TMDS: host port -> TPD clamp pad (flow-through) -> receptacle. The
    # tmds_pair typing (and its linker deferral) is attached on the P net; the
    # reciprocal N type is registered automatically, so a project's expects[]
    # need only name the P line of each pair.
    for port, upin, jpin in TMDS_LANES:
        c.port(port, f"U1.{upin}", f"J1.{jpin}")
    for p_pos, p_neg in TMDS_PAIRS:
        c.port_type(p_pos, kind="tmds_pair", pair_with=p_neg,
                    **meta.expect_kw(p_pos))

    # DDC/CEC/HPD: A-side ports (host), B-side wired nets (receptacle)
    c.port("CEC", "U1.1", **meta.expect_kw("CEC"))
    c.port("DDC_SCL", "U1.2", kind="i2c", role="scl",
           bus=ddc_bus, speed_hz=DDC_SPEED_HZ, **meta.expect_kw("DDC_SCL"))
    c.port("DDC_SDA", "U1.3", kind="i2c", role="sda",
           bus=ddc_bus, speed_hz=DDC_SPEED_HZ, **meta.expect_kw("DDC_SDA"))
    c.port("HPD", "U1.4", **meta.expect_kw("HPD"))
    for _name, bnet, _a, bpin, jpin in SHIFTED:
        c.net(bnet, f"U1.{bpin}", f"J1.{jpin}")

    # switched cable +5V: 5V_OUT -> pin 18, 100n HF + 1u bulk at the connector
    c.net("HDMI_TX_CON_5V0", "U1.13", "J1.18")
    for ref, val, lcsc in (("C3", "100n", LCSC_100N), ("C4", "1u", LCSC_1U)):
        c.part(ref, "Device:C", val, C_FP, LCSC=lcsc)
        c.net("HDMI_TX_CON_5V0", f"{ref}.1")
        c.net("GND", f"{ref}.2")

    # always-on straps: LS_OE + CT_HPD 10k to V_CCA (DS Fig 15 / Sec 8.2.1)
    c.net("HDMI_TX_LS_OE", "U1.5")
    c.net("HDMI_TX_CT_HPD", "U1.12")
    c.pullup("U1.5", "10k", "+VDD_IO", footprint=R_FP).fields["LCSC"] = LCSC_10K   # R1
    c.pullup("U1.12", "10k", "+VDD_IO", footprint=R_FP).fields["LCSC"] = LCSC_10K  # R2

    # grounds: TPD GND pins + receptacle TMDS shields/DDC ground; the four
    # shell legs bond to the chassis island (separate net, star-bond elsewhere)
    c.net("GND", "U1.6", "U1.14", "U1.19",
          "J1.2", "J1.5", "J1.8", "J1.11", "J1.17")
    c.net("CHASSIS_GND", "J1.20", "J1.21", "J1.22", "J1.23")

    # pin 14 = HEC/Utility, reserved (N.C. on non-HEAC devices, HDMI 1.4)
    c.nc("J1.14")

    # round-4 coverage gate: the cable-5V feed rail + the DDC bus this sheet owns
    c.testpoint("+5V")
    c.testpoint("DDC_SCL")
    c.testpoint("DDC_SDA")

    # power-tree budget (round 4): TPD12S016 ICCA < 1 mA + the two 10k
    # straps; the cable's +5V is the TPD's integrated 55 mA-limited switch
    # (DS Sec 7.3.10) fed from +5V
    c.draws("+VDD_IO", DRAWS_VCCA_A, draws_vcca)
    c.draws("+5V", DRAWS_5V_A, draws_5v)
    # design-rule waiver (verification P1): the DDC I2C pull-ups are INTEGRATED
    # in the TPD12S016 (DS 7.3.9/7.3.15 — "no external pull-ups"), so the
    # DDC SCL/SDA nets carry none on-board by design.
    c.waive_pull("DDC_SCL",
                 "DDC pull-ups integrated in TPD12S016 (DS 7.3.9/7.3.15)")
    c.waive_pull("DDC_SDA",
                 "DDC pull-ups integrated in TPD12S016 (DS 7.3.9/7.3.15)")
    # Pairs are typed in abstract names above; Circuit.bind (via meta.finish)
    # rebinds each PortType's pair_with complement through the rename map, so the
    # bound TMDS pairs stay consistent (the SI-constraints pair-join keys on
    # pair_with). The library stays a pure rename-equivalent — no pair fixup here.
    return meta.finish(c)
