"""TPS2051CDBVR — TPS2051CDBVR (SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BR)

Generated by `schgen part add C129581` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPS2051CDBVR'
SAFE_NAME = 'TPS2051CDBVR'
LCSC = 'C129581'
DESCRIPTION = 'TPS2051CDBVR (SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BR)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BR'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C129581.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/PMIC-Power-Distribution-Switches_TI_TPS2051CDBVR_TPS2051CDBVR_C129581.html'
LIB_ID = 'TPS2051CDBVR:TPS2051CDBVR'
FOOTPRINT = 'TPS2051CDBVR:TPS2051CDBVR'
MODELS_3D = ['TPS2051CDBVR.wrl', 'TPS2051CDBVR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'OUT', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'FLT#', 'passive'),
    ('4', 'EN(EN#)', 'passive'),
    ('5', 'IN', 'passive'),
]
