from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

from schgen.core.link import all_subsystem_paths, load_subsystem
from schgen.core.project import IS_DEFAULT_PROJECT, PROJECT_ROOT

REPO_ROOT = Path(__file__).resolve().parents[2]
RENDERS = PROJECT_ROOT / "renders"
DIAGRAM = REPO_ROOT / "docs" / "block_diagram.svg"
_PROJ_REL = (PROJECT_ROOT.relative_to(REPO_ROOT).as_posix()
             if PROJECT_ROOT.is_relative_to(REPO_ROOT) else PROJECT_ROOT.name)

BEGIN = "<!-- schgen:gallery -->"
END = "<!-- /schgen:gallery -->"
THUMB_W = 220
COLS = 3

RENDER3D_VIEWS = [
    ("3d_persp", "Perspective (front)"),
    ("3d_persp_rear", "Perspective (rear)"),
    ("3d_top", "Top"),
    ("3d_bottom", "Bottom"),
    ("3d_front", "Front edge"),
    ("3d_back", "Back edge"),
    ("3d_left", "Left edge"),
    ("3d_right", "Right edge"),
]
RENDER3D_HERO = "3d_persp"
RENDER3D_COLS = 4
RENDER3D_THUMB_W = 200

RATSNEST_DIR = RENDERS / "ratsnest"
RATSNEST_BOARD = [
    ("ratsnest_top", "Board (top)"),
    ("ratsnest_bottom", "Board (bottom)"),
]
RATSNEST_HERO = "ratsnest_top"
RATSNEST_ANCHOR = "ratsnest-views"
RATSNEST_BOARD_W = 420
RATSNEST_COLS = 4
RATSNEST_THUMB_W = 200


def _thumb_grid(cells_md: list[str], cols: int) -> list[str]:
    L = ["| " + " | ".join([" "] * cols) + " |", "|" + "---|" * cols]
    for i in range(0, len(cells_md), cols):
        chunk = cells_md[i:i + cols]
        chunk = chunk + [" "] * (cols - len(chunk))
        L.append("| " + " | ".join(chunk) + " |")
    return L


def _render3d_lines(rel) -> list[str]:
    have = [(stem, label) for stem, label in RENDER3D_VIEWS
            if (RENDERS / f"{stem}.png").exists()]
    L: list[str] = ["## Generated 3D board views", ""]
    if not have:
        L += ["*(3D board renders pending — run `schgen board`.)*", ""]
        return L
    L.append(f"The placed board rendered from {len(have)} angles by "
             f"`schgen board` (kicad-cli, the real component 3D models) — "
             f"regenerated and committed every build, just like the sheets "
             f"below.")
    L.append("")
    cells = []
    for stem, label in have:
        png = rel(f"{_PROJ_REL}/renders/{stem}.png")
        cells.append(f"[<img src=\"{png}\" width=\"{RENDER3D_THUMB_W}\" "
                     f"alt=\"{label}\">]({png})<br>**{label}**")
    L += _thumb_grid(cells, RENDER3D_COLS)
    L.append("")
    return L


def _wired_sheets() -> frozenset[str]:
    p = PROJECT_ROOT / "project.json"
    if not p.exists():
        return frozenset()
    placement = json.loads(p.read_text()).get("placement", {})
    return frozenset(placement.get("wired_sheets", []))


def _ratsnest_lines(rel) -> list[str]:
    L: list[str] = ["## Ratsnest views", ""]
    board = [(f"{_PROJ_REL}/renders/{stem}.png", label)
             for stem, label in RATSNEST_BOARD
             if (RENDERS / f"{stem}.png").exists()]
    if (RATSNEST_DIR / "som.png").exists():
        board.append((f"{_PROJ_REL}/renders/ratsnest/som.png", "SoM region"))
    sheets = (sorted(p.stem for p in RATSNEST_DIR.glob("*.png")
                     if p.stem != "som")
              if RATSNEST_DIR.is_dir() else [])
    if not board and not sheets:
        L += ["*(ratsnest renders pending — run `schgen board`.)*", ""]
        return L
    L.append("Placed-board airwires, regenerated by `schgen board`: "
             "blue/orange = the subsystem's parts (top/bottom side), "
             "steel = SoM, green = intra-subsystem, red = to the SoM. "
             "`wired` = in `placement.wired_sheets`.")
    L.append("")
    if board:
        cells = [f"[<img src=\"{rel(t)}\" width=\"{RATSNEST_BOARD_W}\" "
                 f"alt=\"{label}\">]({rel(t)})<br>**{label}**"
                 for t, label in board]
        L += _thumb_grid(cells, 2)
        L.append("")
    if sheets:
        wired = _wired_sheets()
        cells = []
        for name in sheets:
            png = rel(f"{_PROJ_REL}/renders/ratsnest/{name}.png")
            mark = " `wired`" if name in wired else ""
            cells.append(f"[<img src=\"{png}\" width=\"{RATSNEST_THUMB_W}\" "
                         f"alt=\"{name}\">]({png})<br>**{name}**{mark}")
        L += _thumb_grid(cells, RATSNEST_COLS)
        L.append("")
    return L


def _sheet_rows() -> list[tuple[str, str, bool]]:
    rows = []
    for p in all_subsystem_paths():
        c = load_subsystem(p.stem).circuit
        rows.append((c.name, c.title, (RENDERS / f"{c.name}.png").exists()))
    return sorted(rows)


def _full_section(readme_dir: Path) -> str:
    def rel(target: str) -> str:
        return os.path.relpath(REPO_ROOT / target, readme_dir)

    rows = _sheet_rows()
    n = len(rows)
    L: list[str] = []
    L.append(BEGIN)
    L.append("<!-- GENERATED by `schgen gallery` — edits between these "
             "markers are overwritten -->")
    L += _render3d_lines(rel)
    L += _ratsnest_lines(rel)
    L.append("## Generated schematics")
    L.append("")
    L.append(f"Block diagram and all {n} {_PROJ_REL} sheets, regenerated by "
             f"`schgen board` —")
    L.append("every PNG below passed the netlist, ERC and visual gates.")
    L.append("")
    L.append(f'<img src="{rel("docs/block_diagram.svg")}" '
             f'alt="Generated block diagram" width="900">')
    L.append("")
    L.append("| " + " | ".join([" "] * COLS) + " |")
    L.append("|" + "---|" * COLS)
    for i in range(0, n, COLS):
        chunk = rows[i:i + COLS]
        cells = []
        for name, _title, has_png in chunk:
            png = rel(f"{_PROJ_REL}/renders/{name}.png")
            if has_png:
                cells.append(f"[<img src=\"{png}\" width=\"{THUMB_W}\" "
                             f"alt=\"{name}\">]({png})<br>**{name}**")
            else:
                cells.append(f"**{name}**<br>*(render pending)*")
        cells += [" "] * (COLS - len(chunk))
        L.append("| " + " | ".join(cells) + " |")
    L.append("")
    L.append("| sheet | description |")
    L.append("|---|---|")
    for name, title, has_png in rows:
        link = (f"[{name}]({rel(f'{_PROJ_REL}/renders/{name}.png')})"
                if has_png else name)
        L.append(f"| {link} | {title.replace('|', '\\|')} |")
    L.append(END)
    return "\n".join(L)


def _compact_section(readme_dir: Path) -> str:
    def rel(target: str) -> str:
        return os.path.relpath(REPO_ROOT / target, readme_dir)

    n = len(_sheet_rows())
    nv = sum((RENDERS / f"{s}.png").exists() for s, _ in RENDER3D_VIEWS)
    L: list[str] = [
        BEGIN,
        "<!-- GENERATED by `schgen gallery` — edits between these markers "
        "are overwritten -->",
        "## Generated board + schematics",
        "",
        f"`schgen board` regenerates the placed-board 3D views, the block "
        f"diagram and all {n} {_PROJ_REL} sheets,",
        "each PNG passing the netlist, ERC and visual gates.",
        "",
    ]
    hero = RENDERS / f"{RENDER3D_HERO}.png"
    if hero.exists():
        L += [f'<img src="{rel(f"{_PROJ_REL}/renders/{RENDER3D_HERO}.png")}" '
              f'alt="Generated 3D board render (perspective)" width="900">',
              ""]
    L += [
        f'<img src="{rel("docs/block_diagram.svg")}" '
        f'alt="Generated block diagram" width="900">',
        "",
    ]
    if (RENDERS / f"{RATSNEST_HERO}.png").exists():
        carrier_md = rel(f"{_PROJ_REL}/README.md")
        L += [f'[<img src="{rel(f"{_PROJ_REL}/renders/{RATSNEST_HERO}.png")}" '
              f'alt="Board ratsnest (top)" width="{RATSNEST_BOARD_W}">]'
              f'({carrier_md}#{RATSNEST_ANCHOR})<br>'
              f'**[Ratsnest views]({carrier_md}#{RATSNEST_ANCHOR})** — '
              f'airwires per subsystem.',
              ""]
    L += [
        f"See **[{_PROJ_REL}/README.md]({rel(f'{_PROJ_REL}/README.md')}#generated-3d-"
        f"board-views)** for all {nv} board views + the full sheet gallery "
        f"(thumbnails + descriptions).",
        END,
    ]
    return "\n".join(L)


def _splice(readme: Path, section: str) -> bool:
    text = readme.read_text() if readme.exists() else ""
    if BEGIN in text and END in text:
        head, _, rest = text.partition(BEGIN)
        _, _, tail = rest.partition(END)
        new = head + section + tail
    else:
        new = text.rstrip("\n") + ("\n\n" if text.strip() else "") \
            + section + "\n"
    if new != text:
        readme.write_text(new)
        return True
    return False


def generate() -> list[Path]:
    changed = []
    project_md = PROJECT_ROOT / "README.md"
    if IS_DEFAULT_PROJECT:
        root = REPO_ROOT / "README.md"
        if _splice(root, _compact_section(root.parent)):
            changed.append(root)
    if _splice(project_md, _full_section(project_md.parent)):
        changed.append(project_md)
    return changed


def readme_targets() -> str:
    return (f"README.md + {_PROJ_REL}/README.md" if IS_DEFAULT_PROJECT
            else f"{_PROJ_REL}/README.md")


def cmd_gallery(args: argparse.Namespace) -> int:
    changed = generate()
    n = len(_sheet_rows())
    which = (", ".join(str(p.relative_to(REPO_ROOT)) for p in changed)
             or "unchanged")
    print(f"GALLERY: {n} sheets -> {readme_targets()} ({which})")
    return 0
