"""README render gallery (PLAN.md round 4: "the repo demos itself").

``schgen gallery`` (also run by ``schgen board``) regenerates a marked
section in two READMEs, WITHOUT duplicating the giant table:

- ``carrier/README.md`` gets the FULL gallery (it lives next to the
  renders): a thumbnail grid of the placed-board 3D views, the block diagram
  inline, a thumbnail grid of every sheet, and a name->description table.
- the root ``README.md`` gets a COMPACT block: a 3D board hero + the block
  diagram inline + one line linking to the carrier README for the full
  galleries.

Idempotent: content lives between ``<!-- schgen:gallery --> ...
<!-- /schgen:gallery -->`` markers and is replaced in place (appended on
first run). Deterministic: sheets sorted by name, no timestamps. Thumbnails
use GitHub-flavored-markdown-safe inline HTML (``<img width=...>`` inside a
pipe table, relative links).
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from schgen.core.link import all_subsystem_paths, load_subsystem
from schgen.core.project import PROJECT_ROOT

REPO_ROOT = Path(__file__).resolve().parents[2]
RENDERS = PROJECT_ROOT / "renders"
DIAGRAM = REPO_ROOT / "docs" / "block_diagram.svg"

BEGIN = "<!-- schgen:gallery -->"
END = "<!-- /schgen:gallery -->"
THUMB_W = 220
COLS = 3

# Placed-board 3D views written by ``render3d`` on every ``schgen board`` (see
# schgen/output/render3d.py), in display order: the two hero perspectives, the
# two faces, then the four edge profiles. (stem -> friendly label.)
RENDER3D_VIEWS = [
    ("3d_persp", "Perspective (front)"),
    ("3d_persp_rear", "Perspective (rear)"),
    ("3d_top", "Top"),
    ("3d_bottom", "Bottom"),
    ("3d_front", "Front edge"),
    ("3d_back", "Back edge"),
    ("3d_left", "Left edge"),
    ("3d_right", "Right edge"),
]
RENDER3D_HERO = "3d_persp"   # the one inlined into the root README compact block
RENDER3D_COLS = 4
RENDER3D_THUMB_W = 200


def _thumb_grid(cells_md: list[str], cols: int) -> list[str]:
    """A GFM pipe-table thumbnail grid from pre-rendered cell markdown (each
    cell is the full ``[<img ...>](link)<br>**label**`` string)."""
    L = ["| " + " | ".join([" "] * cols) + " |", "|" + "---|" * cols]
    for i in range(0, len(cells_md), cols):
        chunk = cells_md[i:i + cols]
        chunk = chunk + [" "] * (cols - len(chunk))
        L.append("| " + " | ".join(chunk) + " |")
    return L


def _render3d_lines(rel) -> list[str]:
    """The '## Generated 3D board views' subsection: a thumbnail grid of the
    placed-board 3D renders (``carrier/renders/3d_*.png``), mirroring the sheet
    grid. ``rel`` maps a repo-relative target to a README-relative link."""
    have = [(stem, label) for stem, label in RENDER3D_VIEWS
            if (RENDERS / f"{stem}.png").exists()]
    L: list[str] = ["## Generated 3D board views", ""]
    if not have:
        L += ["*(3D board renders pending — run `schgen board`.)*", ""]
        return L
    L.append(f"The placed board rendered from {len(have)} angles by "
             f"`schgen board` (kicad-cli, the real component 3D models) — "
             f"regenerated and committed every build, just like the sheets "
             f"below.")
    L.append("")
    cells = []
    for stem, label in have:
        png = rel(f"carrier/renders/{stem}.png")
        cells.append(f"[<img src=\"{png}\" width=\"{RENDER3D_THUMB_W}\" "
                     f"alt=\"{label}\">]({png})<br>**{label}**")
    L += _thumb_grid(cells, RENDER3D_COLS)
    L.append("")
    return L


def _sheet_rows() -> list[tuple[str, str, bool]]:
    """(name, description, has_render) per subsystem, sorted by name."""
    rows = []
    for p in all_subsystem_paths():
        c = load_subsystem(p.stem).circuit
        rows.append((c.name, c.title, (RENDERS / f"{c.name}.png").exists()))
    return sorted(rows)


def _full_section(readme_dir: Path) -> str:
    """The FULL gallery (carrier/README.md): block diagram + thumbnail grid
    + description table, links relative to the README's directory."""
    def rel(target: str) -> str:
        return os.path.relpath(REPO_ROOT / target, readme_dir)

    rows = _sheet_rows()
    n = len(rows)
    L: list[str] = []
    L.append(BEGIN)
    L.append("<!-- GENERATED by `schgen gallery` — edits between these "
             "markers are overwritten -->")
    L += _render3d_lines(rel)
    L.append("## Generated schematics")
    L.append("")
    L.append(f"Block diagram and all {n} carrier sheets, regenerated by "
             f"`schgen board` —")
    L.append("every PNG below passed the netlist, ERC and visual gates.")
    L.append("")
    L.append(f'<img src="{rel("docs/block_diagram.svg")}" '
             f'alt="Generated block diagram" width="900">')
    L.append("")
    # thumbnail grid: COLS sheets per table row (GFM pipe table + <img>)
    L.append("| " + " | ".join([" "] * COLS) + " |")
    L.append("|" + "---|" * COLS)
    for i in range(0, n, COLS):
        chunk = rows[i:i + COLS]
        cells = []
        for name, _title, has_png in chunk:
            png = rel(f"carrier/renders/{name}.png")
            if has_png:
                cells.append(f"[<img src=\"{png}\" width=\"{THUMB_W}\" "
                             f"alt=\"{name}\">]({png})<br>**{name}**")
            else:
                cells.append(f"**{name}**<br>*(render pending)*")
        cells += [" "] * (COLS - len(chunk))
        L.append("| " + " | ".join(cells) + " |")
    L.append("")
    L.append("| sheet | description |")
    L.append("|---|---|")
    for name, title, has_png in rows:
        link = (f"[{name}]({rel(f'carrier/renders/{name}.png')})"
                if has_png else name)
        L.append(f"| {link} | {title.replace('|', '\\|')} |")
    L.append(END)
    return "\n".join(L)


def _compact_section(readme_dir: Path) -> str:
    """The COMPACT block (root README.md): block diagram inline + one line
    linking to the carrier README's full sheet gallery (no duplicated
    table)."""
    def rel(target: str) -> str:
        return os.path.relpath(REPO_ROOT / target, readme_dir)

    n = len(_sheet_rows())
    nv = sum((RENDERS / f"{s}.png").exists() for s, _ in RENDER3D_VIEWS)
    L: list[str] = [
        BEGIN,
        "<!-- GENERATED by `schgen gallery` — edits between these markers "
        "are overwritten -->",
        "## Generated board + schematics",
        "",
        f"`schgen board` regenerates the placed-board 3D views, the block "
        f"diagram and all {n} carrier sheets,",
        "each PNG passing the netlist, ERC and visual gates.",
        "",
    ]
    hero = RENDERS / f"{RENDER3D_HERO}.png"
    if hero.exists():
        L += [f'<img src="{rel(f"carrier/renders/{RENDER3D_HERO}.png")}" '
              f'alt="Generated 3D board render (perspective)" width="900">',
              ""]
    L += [
        f'<img src="{rel("docs/block_diagram.svg")}" '
        f'alt="Generated block diagram" width="900">',
        "",
        f"See **[carrier/README.md]({rel('carrier/README.md')}#generated-3d-"
        f"board-views)** for all {nv} board views + the full sheet gallery "
        f"(thumbnails + descriptions).",
        END,
    ]
    return "\n".join(L)


def _splice(readme: Path, section: str) -> bool:
    """Replace the marked section (or append it). True if the file changed."""
    text = readme.read_text() if readme.exists() else ""
    if BEGIN in text and END in text:
        head, _, rest = text.partition(BEGIN)
        _, _, tail = rest.partition(END)
        new = head + section + tail
    else:
        new = text.rstrip("\n") + ("\n\n" if text.strip() else "") \
            + section + "\n"
    if new != text:
        readme.write_text(new)
        return True
    return False


def generate() -> list[Path]:
    """De-duplicated: the FULL gallery goes ONLY into carrier/README.md
    (next to the renders); the root README.md gets the COMPACT block."""
    changed = []
    root = REPO_ROOT / "README.md"
    carrier = PROJECT_ROOT / "README.md"
    if _splice(root, _compact_section(root.parent)):
        changed.append(root)
    if _splice(carrier, _full_section(carrier.parent)):
        changed.append(carrier)
    return changed


def cmd_gallery(args: argparse.Namespace) -> int:
    changed = generate()
    n = len(_sheet_rows())
    which = (", ".join(str(p.relative_to(REPO_ROOT)) for p in changed)
             or "unchanged")
    print(f"GALLERY: {n} sheets -> README.md + carrier/README.md ({which})")
    return 0
