"""GEOMETRY PIPELINE DOC — ``docs/GEOMETRY_PIPELINE.md`` generated from the
stage manifest + quantization registry + fallback registry/baselines
(governance U4, the FLOORPLAN.md pattern: the map is emitted from the same
data the engine executes, so it cannot rot).

Deterministic: content is a pure function of the committed code + the
committed per-project fallback baselines (live counts print in the build
report and land in ``board_verdicts.json``, never here — so the doc is
byte-stable across projects and consecutive builds). Rewritten only when the
content changes.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DOC_PATH = REPO_ROOT / "docs" / "GEOMETRY_PIPELINE.md"


def _project_baselines() -> dict[str, dict[str, int]]:
    out: dict[str, dict[str, int]] = {}
    for pj in sorted(REPO_ROOT.glob("*/project.json")):
        bp = pj.parent / "reports" / "fallback_baseline.json"
        try:
            raw = json.loads(bp.read_text())
            out[pj.parent.name] = {str(k): int(v)
                                   for k, v in raw["counts"].items()}
        except Exception:  # noqa: BLE001 — unpinned project: no column
            continue
    return out


def render() -> str:
    from schgen.core.fallbacks import REGISTRY as FB
    from schgen.core.quantize import REGISTRY as QT
    from schgen.generate.pcb.stages import PLACEMENT_STAGES

    L: list[str] = [
        "# GEOMETRY PIPELINE",
        "",
        "GENERATED by `schgen board` from the live stage manifest "
        "(`schgen/generate/pcb/stages.py`), the quantization registry "
        "(`schgen/core/quantize.py`) and the fallback registry "
        "(`schgen/core/fallbacks.py`). Do not edit by hand — edit the "
        "registries and rebuild.",
        "",
        "## Placement stages (`build_model`, declared order)",
        "",
        "Movement in a `may_move: no` stage raises `StageMovementError` at "
        "build time (always-on tripwire; one snapshot hash per boundary). "
        "`tracked: no` stages run before absolute positions exist.",
        "",
        "| # | stage | may_move | tracked | validated by |",
        "|---|-------|----------|---------|--------------|",
    ]
    for i, s in enumerate(PLACEMENT_STAGES, start=1):
        L.append(f"| {i} | `{s.name}` — {s.desc} | "
                 f"{'yes' if s.may_move else 'NO'} | "
                 f"{'yes' if s.tracked else 'no'} ({s.domain}) | "
                 f"{s.validated_by} |")
    L += [
        "",
        "## Quantization registry",
        "",
        "Every live geometry-touching snap/round/pad/credit is a NAMED "
        "transform; the census lint "
        "(`schgen/verify/quantize_census.py`) hard-fails the board on any "
        "raw quantization site in the geometry data flow outside this "
        "registry (baseline: empty).",
        "",
        "| name | value | class | basis |",
        "|------|-------|-------|-------|",
    ]
    for name in sorted(QT):
        q = QT[name]
        L.append(f"| `{q.name}` | `{q.value}` | {q.klass} | {q.basis} |")
    bl = _project_baselines()
    projs = sorted(bl)
    L += [
        "",
        "## Fallback registry + committed ratchet baselines",
        "",
        "Every degraded path is a NAMED event; the ratchet gate "
        "(`schgen/verify/fallback_gate.py`) fails the board when any count "
        "exceeds its committed per-project ceiling (ceilings only ever "
        "decrease). Live counts print in the build report and in "
        "`board_verdicts.json` (`fallbacks`).",
        "",
        "| name | stage | " + " | ".join(f"{p} ceiling" for p in projs)
        + " | meaning |",
        "|------|-------|" + "|".join("-" * 9 for _ in projs)
        + "|---------|",
    ]
    for name in sorted(FB):
        f = FB[name]
        cells = " | ".join(str(bl[p].get(name, 0)) for p in projs)
        L.append(f"| `{f.name}` | {f.stage} | {cells} | {f.meaning} |")
    L.append("")
    return "\n".join(L)


def generate() -> tuple[Path, bool]:
    text = render()
    old = DOC_PATH.read_text() if DOC_PATH.exists() else None
    if old == text:
        return DOC_PATH, False
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(text)
    return DOC_PATH, True
