"""Generated SC bring-up firmware SCAFFOLD (Stream E, Zephyr-abstracted).

``schgen scfw`` (also run by ``schgen board``) writes a portable-C bring-up
firmware scaffold for the SoM STM32 system controller into
``carrier/firmware/sc/``.  Where ``schgen firmware`` emits the hardware
CONTRACT (the ``zynq_carrier_contract.h`` #defines: J1 pins, GPIOs, I2C
addresses, the EN map), THIS generator emits the IMPLEMENTATION that consumes
that contract:

- a rail-sequencing STATE MACHINE derived from
  ``bringup_facts.regulator_chain`` (enable order, PG-wait per stage, the
  always-on rails, then the SY6280 module gates) — a STEP TABLE plus a
  portable STEPPER, *not* hard-coded HAL;
- TABLES: the I2C device map, the GPIO/EN map (rail + module enables), the
  TPS3823 watchdog kick (C2: NEVER armed/kicked during power-up), and the
  FUSB302B PD negotiate entry points;
- a HAL ABSTRACTION header (``sc_hal.h``) declaring the platform ops
  (``gpio_set``, ``i2c_xfer``, ``delay_ms`` ...) a Zephyr port implements,
  plus a Zephyr-friendly drop-in description (devicetree overlay + Kconfig/
  board-port note + a commented reference port).

The generated C is TOOLCHAIN-AGNOSTIC: it does NOT ``#include`` any Zephyr
header — it only calls the ``sc_hal`` abstraction, which a Zephyr port backs.

Deterministic: same inputs -> byte-identical output (no timestamps).  Every
table value is read from the authored subsystem netlists via
``bringup_facts`` (and through it, the live SoM U9 pin map) — never hand-typed.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from schgen.core.link import load_subsystem
from schgen.generate import bringup_facts as bf

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "carrier" / "firmware" / "sc"

CONTRACT_HEADER = "zynq_carrier_contract.h"   # the SC contract (schgen firmware)

SOURCES = (
    "carrier/firmware/zynq_carrier_contract.h (the SC hardware contract)",
    "carrier/subsystems/power/power.py (regulator chain)",
    "carrier/subsystems/power_mon/power_mon.py (INA3221 monitors + shunts)",
    "carrier/subsystems/bringup_en/bringup_en.py (rail EN cells)",
    "carrier/subsystems/bringup_modules/bringup_modules.py (SY6280 module gates)",
    "carrier/subsystems/bringup_rails/bringup_rails.py (TCA9535 override expander)",
    "carrier/subsystems/usb_pd/usb_pd.py (FUSB302B PD PHY)",
    "carrier/subsystems/board_services/board_services.py (TPS3823 watchdog)",
    "carrier/docs/BRINGUP.md (the staged procedure this automates)",
)


class ScfwError(ValueError):
    pass


# ---- small emit helpers ----------------------------------------------------------

def _banner(title: str) -> list[str]:
    # each line is a SELF-CONTAINED block comment (no spanning), so the banner
    # can never swallow following code and gcc -Wcomment stays quiet.
    rule = "/* " + "=" * 72 + " */"
    return [rule, f"/* {title:<72} */", rule]


def _file_header(fname: str, what: str, device: str) -> list[str]:
    L = ["/*", f" * {fname} -- {what}", " *",
         " * GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.",
         " * regenerate: PYTHONPATH=. python -m schgen scfw", " *",
         f" * system controller: {device} (from the SoM U9 netlist)", " *",
         " * Portable C behind the sc_hal abstraction -- this file #includes NO",
         " * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.",
         " * sources:"]
    for s in SOURCES:
        L.append(f" *   {s}")
    L.append(" */")
    return L


# ---- the model the scaffold is built from ----------------------------------------

class Model:
    """Everything the scaffold needs, read once from the netlists."""

    def __init__(self) -> None:
        power = load_subsystem("power").circuit
        pmon = load_subsystem("power_mon").circuit
        en = load_subsystem("bringup_en").circuit
        mods = load_subsystem("bringup_modules").circuit
        rails = load_subsystem("bringup_rails").circuit
        usbpd = load_subsystem("usb_pd").circuit
        services = load_subsystem("board_services").circuit

        self.device = bf.stm32_pin_map()["value"]
        self.chain = bf.regulator_chain(power, monitor=pmon)
        self.rail_cells = {c.enable: c for c in bf.en_cells(en)}
        self.gates = bf.module_gates(mods)
        self.expander = bf.expander(rails)
        self.monitors = bf.ina3221_monitors(pmon)

        if not any("FUSB302" in p.value for p in usbpd.parts.values()):
            raise ScfwError("usb_pd netlist no longer carries a FUSB302 -- "
                            "the PD hooks would be stale")
        if not any("TPS3823" in p.value or "TPS3823" in p.lib_id
                   for p in services.parts.values()):
            raise ScfwError("board_services no longer carries a TPS3823 -- "
                            "the watchdog hooks would be stale")

        # always-on rails (pre-PD): every rail consumed but never PRODUCED by a
        # sequenced regulator stage, plus the SC's own +3V3_SC. Derived, not
        # hard-coded: a rail is "always-on" if no stage's rail_out names it.
        produced = {st.rail_out for st in self.chain}
        consumed = {st.rail_in for st in self.chain}
        self.always_on = sorted((consumed - produced) | {"+3V3_SC"})


# ---- step-table enum / identifiers -----------------------------------------------

def _rail_enum(rail_out: str) -> str:
    return "SC_RAIL_" + bf.c_ident(rail_out).lstrip("_")


def _module_enum(enable: str) -> str:
    return "SC_MOD_" + bf.c_ident(enable.removeprefix("EN_"))


# ==================================================================================
#  sc_hal.h  -- the platform abstraction a Zephyr (or bare-metal) port implements
# ==================================================================================

def gen_sc_hal_h(m: Model) -> str:
    L = _file_header("sc_hal.h",
                     "SC firmware HAL abstraction (platform ops)", m.device)
    L += ["#ifndef SC_HAL_H", "#define SC_HAL_H", "",
          "#include <stdint.h>", "#include <stdbool.h>", "#include <stddef.h>",
          ""]
    L += _banner("HAL contract")
    L += [
        "/* The portable bring-up code (sc_seq.c / sc_pd.c / sc_wdt.c) NEVER    */",
        "/* touches a register or a Zephyr API directly: it calls the ops      */",
        "/* below.  A platform port (sc_hal_zephyr.c for a Zephyr app, or a    */",
        "/* bare-metal sc_hal_stm32.c) provides the bodies.  GPIOs are named   */",
        "/* by the ('port' letter, pin number) pair the hardware contract      */",
        "/* (zynq_carrier_contract.h) already exposes, so the HAL maps a STM32  */",
        "/* (port,pin) onto whatever handle the platform uses.                 */",
        "",
        "/* A GPIO line as the contract names it: STM32 port letter 'A'..'G'   */",
        "/* and pin number, exactly the ZC_*_GPIO_PORT / ZC_*_GPIO_PIN pair.   */",
        "typedef struct {",
        "    char port;       /* 'A' .. 'G' (ZC_*_GPIO_PORT) */",
        "    uint8_t pin;     /* 0 .. 15    (ZC_*_GPIO_PIN)  */",
        "} sc_gpio_t;",
        "",
        "/* I2C transfer direction. */",
        "typedef enum { SC_I2C_WRITE = 0, SC_I2C_READ = 1 } sc_i2c_dir_t;",
        "",
        "/* The platform ops table.  All return 0 on success, <0 on error.     */",
        "/* A Zephyr port fills this from devicetree handles (see sc_hal.h     */",
        "/* footer); a bare-metal port from LL/HAL register writes.            */",
        "typedef struct {",
        "    /* --- timing --- */",
        "    void (*delay_ms)(uint32_t ms);",
        "    uint32_t (*uptime_ms)(void);",
        "    /* --- GPIO --- */",
        "    int (*gpio_configure_output)(sc_gpio_t io, bool open_drain);",
        "    int (*gpio_configure_input)(sc_gpio_t io, bool pull_up);",
        "    int (*gpio_set)(sc_gpio_t io, bool level);",
        "    int (*gpio_get)(sc_gpio_t io, bool *level);",
        "    /* --- I2C (7-bit addressing; bit-bang or peripheral) --- */",
        "    int (*i2c_xfer)(uint8_t addr7, sc_i2c_dir_t dir,",
        "                    uint8_t *buf, size_t len);",
        "    /* --- watchdog (TPS3823 WDI strobe; see sc_wdt.h, C2) --- */",
        "    int (*wdt_strobe)(void);",
        "    /* --- diagnostics (optional; may be NULL) --- */",
        "    void (*log)(const char *msg);",
        "} sc_hal_t;",
        "",
        "/* The single HAL instance the portable code calls.  The platform port */",
        "/* sets this before sc_seq_run()/sc_pd_*; the portable code treats it   */",
        "/* as read-only.                                                        */",
        "extern const sc_hal_t *sc_hal;",
        "",
        "/* Convenience wrappers (header-only) so call sites stay terse and the  */",
        "/* NULL-op guards live in exactly one place.                            */",
        "static inline void sc_delay_ms(uint32_t ms) { sc_hal->delay_ms(ms); }",
        "static inline uint32_t sc_uptime_ms(void) { return sc_hal->uptime_ms(); }",
        "static inline int sc_gpio_set(sc_gpio_t io, bool lvl) {",
        "    return sc_hal->gpio_set(io, lvl);",
        "}",
        "static inline int sc_gpio_get(sc_gpio_t io, bool *lvl) {",
        "    return sc_hal->gpio_get(io, lvl);",
        "}",
        "static inline int sc_i2c_write(uint8_t a, uint8_t *b, size_t n) {",
        "    return sc_hal->i2c_xfer(a, SC_I2C_WRITE, b, n);",
        "}",
        "static inline int sc_i2c_read(uint8_t a, uint8_t *b, size_t n) {",
        "    return sc_hal->i2c_xfer(a, SC_I2C_READ, b, n);",
        "}",
        "static inline void sc_log(const char *msg) {",
        "    if (sc_hal->log) sc_hal->log(msg);",
        "}",
        "",
    ]
    # NOTE: this whole block is ONE C comment.  It must contain no nested
    # '/*' or '*/' (illegal/ambiguous in C) -- so the devicetree snippet below
    # uses '//' for its own remarks and the prose avoids the '/*' digraph.
    L += _banner("ZEPHYR PORT NOTE  (how this drops into a Zephyr app)")
    L += [
        "/*",
        " * The portable code is Zephyr-agnostic; a Zephyr port is one .c file",
        " * (sc_hal_zephyr.c, shipped here as a COMMENTED reference) plus the",
        " * board glue below.  Nothing in this directory includes a zephyr/",
        " * header.",
        " *",
        " * 1. Kconfig: the SC app selects",
        " *      CONFIG_GPIO=y",
        " *      CONFIG_I2C=y          (or bit-bang: CONFIG_I2C_GPIO=y, since the",
        " *                             contract bit-bangs I2C2 on PA4/PA5 -- see",
        " *                             ZC_I2C_BITBANG_ in the contract header)",
        " *      CONFIG_WATCHDOG=n      (the TPS3823 is EXTERNAL; the SC only",
        " *                             strobes WDI through a GPIO -- C2)",
        " *",
        " * 2. Devicetree overlay (app.overlay): expose the buses/lines the HAL",
        " *    port resolves with DEVICE_DT_GET / GPIO_DT_SPEC_GET.  A minimal",
        " *    overlay for THIS board's contract (// = overlay remarks):",
        " *",
        " *      / {",
        " *          sc_ctrl {",
        " *              compatible = \"zynq,carrier-sc\";",
        " *              i2c = <&i2c_sc>;          // bit-bang I2C2 (PA4/PA5)",
        " *              wdi-gpios = <&gpioX PIN GPIO_ACTIVE_HIGH>;  // TPS3823 WDI",
        " *          };",
        " *      };",
        " *      // GPIO bit-bang I2C on the DAC pins, per ZC_I2C_BITBANG_",
        " *      i2c_sc: i2c-gpio {",
        " *          compatible = \"i2c-gpio\";",
        " *          sda-gpios = <&gpioa 4 (GPIO_OPEN_DRAIN | GPIO_PULL_UP)>;",
        " *          scl-gpios = <&gpioa 5 (GPIO_OPEN_DRAIN | GPIO_PULL_UP)>;",
        " *          #address-cells = <1>;",
        " *          #size-cells = <0>;",
        " *      };",
        " *",
        " * 3. HAL port (sc_hal_zephyr.c): implement sc_hal_t over the Zephyr",
        " *    GPIO + I2C APIs and publish `sc_hal`.  The ('port','pin') pair in",
        " *    sc_gpio_t maps onto a Zephyr gpio_dt_spec via a small lookup the",
        " *    port owns (one DEVICE_DT_GET per GPIO bank).  A skeleton ships as",
        " *    sc_hal_zephyr.c.txt in this directory (commented so the tree stays",
        " *    toolchain-agnostic).",
        " */",
        "",
        "#endif /* SC_HAL_H */",
    ]
    return "\n".join(L) + "\n"


# ==================================================================================
#  sc_tables.h / sc_tables.c  -- the netlist-derived tables
# ==================================================================================

def gen_sc_tables_h(m: Model) -> str:
    L = _file_header("sc_tables.h",
                     "netlist-derived SC tables (rails, I2C, EN map, monitors)",
                     m.device)
    L += ["#ifndef SC_TABLES_H", "#define SC_TABLES_H", "",
          "#include <stdint.h>", "#include <stdbool.h>",
          "#include \"sc_hal.h\"", ""]

    # rail enum
    L += _banner("Rail bring-up step table (order = the regulator chain)")
    L += ["/* The order below IS the power.py regulator chain: each stage's     */",
          "/* input is the previous stage's output, so it is not optional       */",
          "/* (BRINGUP.md Stage 2).  The always-on rails (+3V3_SC + the inlet)   */",
          "/* are listed separately -- they are up before any sequencing runs.  */",
          "typedef enum {"]
    for st in m.chain:
        L.append(f"    {_rail_enum(st.rail_out)},")
    L.append(f"    SC_RAIL_COUNT  /* = {len(m.chain)} */")
    L.append("} sc_rail_id_t;")
    L.append("")

    # rail step struct
    L += [
        "/* One sequenced rail stage.  `en_override` is the SC's VETO GPIO on   */",
        "/* the EN cell (EN = DIP AND override): drive it LOW to force the rail */",
        "/* OFF, leave it HIGH/Hi-Z to let the DIP rule.  Software can NEVER    */",
        "/* force a rail ON with its DIP open (bringup_en semantics).  `pg_*`   */",
        "/* is the INA3221 telemetry the stepper polls to confirm the rail.     */",
        "typedef struct {",
        "    sc_rail_id_t id;",
        "    const char  *name;          /* rail net, e.g. \"+5V\" */",
        "    uint32_t     vout_mv;       /* expected setpoint [mV] */",
        "    const char  *en_net;        /* EN_* cell output net */",
        "    sc_gpio_t    en_override;   /* SC veto GPIO (port=0 if none) */",
        "    uint16_t     settle_ms;     /* wait after enable before PG poll */",
        "    uint8_t      pmon_addr7;    /* INA3221 7-bit addr (0 = no telem) */",
        "    uint8_t      pmon_channel;  /* INA3221 channel 1..3 */",
        "    uint16_t     shunt_mohm;    /* sense-shunt value [mOhm] */",
        "} sc_rail_step_t;",
        "",
        "extern const sc_rail_step_t sc_rail_steps[SC_RAIL_COUNT];",
        "",
        "/* The always-on rails -- present before any sequencing (BRINGUP.md    */",
        "/* Stage 1: +3V3_SC is generated from VIN before PD negotiation).      */",
        f"#define SC_ALWAYS_ON_COUNT {len(m.always_on)}",
        "extern const char *const sc_always_on_rails[SC_ALWAYS_ON_COUNT];",
        "",
    ]

    # module gates
    L += _banner("Module load-switch gate table (SY6280, current-limited)")
    L += ["/* Each module rail is gated by a SY6280 behind its own EN cell and  */",
          "/* current limit (BRINGUP.md Stage 3/4).  These are enabled AFTER    */",
          "/* the core rails, one at a time, with the same veto semantics.      */",
          "typedef enum {"]
    for g in m.gates:
        L.append(f"    {_module_enum(g.enable)},")
    L.append(f"    SC_MOD_COUNT  /* = {len(m.gates)} */")
    L.append("} sc_module_id_t;")
    L += [
        "",
        "/* `tca_bit` is the bit index in the TCA9535 16-bit output word that   */",
        "/* drives this module's override (P00=0 .. P17=15); 0xFF = direct GPIO */",
        "/* (none routed through the expander).                                 */",
        "typedef struct {",
        "    sc_module_id_t id;",
        "    const char    *module;      /* \"HDMI_TX\" ... */",
        "    const char    *rail_in;     /* source rail */",
        "    const char    *rail_out;    /* gated rail */",
        "    const char    *en_net;      /* EN_* cell output */",
        "    uint16_t       ilim_ma;     /* SY6280 current limit [mA] */",
        "    uint8_t        tca_bit;     /* TCA9535 output bit (0xFF if direct) */",
        "} sc_module_gate_t;",
        "",
        "extern const sc_module_gate_t sc_module_gates[SC_MOD_COUNT];",
        "",
    ]

    # I2C device map
    L += _banner("I2C device map (bus = STM32_I2C2; 7-bit addresses)")
    L += ["/* The bus is a firmware BIT-BANG on PA4/PA5 (the contract's         */",
          "/* ZC_I2C_BITBANG_* lines): the real I2C2 AF pins are the on-module  */",
          "/* SC<->Zynq link.  Addresses come straight from the contract header.*/",
          "typedef struct {",
          "    const char *name;",
          "    uint8_t     addr7;",
          "} sc_i2c_dev_t;",
          ""]
    addr_rows = _i2c_rows(m)
    L.append(f"#define SC_I2C_DEV_COUNT {len(addr_rows)}")
    L.append("extern const sc_i2c_dev_t sc_i2c_devices[SC_I2C_DEV_COUNT];")
    L.append("")

    L.append("#endif /* SC_TABLES_H */")
    return "\n".join(L) + "\n"


def _i2c_rows(m: Model) -> list[tuple[str, str, str]]:
    """(macro-or-literal addr expr, label, contract macro) rows for the device
    map.  We reference the contract #defines so the two cannot drift."""
    rows: list[tuple[str, str, str]] = [
        ("bring-up override expander (TCA9535)", "ZC_I2C_ADDR_TCA9535"),
        ("USB-PD PHY (FUSB302B)", "ZC_I2C_ADDR_FUSB302B"),
    ]
    for k, _mon in enumerate(m.monitors, 1):
        rows.append((f"rail monitor #{k} (INA3221)", f"ZC_I2C_ADDR_INA3221_{k}"))
    rows += [
        ("FMC mezzanine ID EEPROM", "ZC_I2C_ADDR_FMC_EEPROM"),
        ("board-ID EEPROM (EUI-48 MAC; AUX bus)", "ZC_I2C_ADDR_ID_EEPROM"),
        ("RTC RV-3028 (AUX bus)", "ZC_I2C_ADDR_RTC"),
    ]
    return [(macro, label, macro) for label, macro in rows]


def gen_sc_tables_c(m: Model) -> str:
    L = _file_header("sc_tables.c",
                     "netlist-derived SC tables (data)", m.device)
    L += [f"#include \"{CONTRACT_HEADER}\"",
          "#include \"sc_tables.h\"", ""]

    # rail steps
    L.append("const sc_rail_step_t sc_rail_steps[SC_RAIL_COUNT] = {")
    for st in m.chain:
        ovr = _override_gpio(m, st)
        pmon_addr, pmon_ch, shunt = _telemetry(m, st)
        mv = round(st.vout * 1000) if st.vout is not None else 0
        # settle time: bucks ramp slower than the fixed LDO; both well within
        # the SY6280/INA3221 ready time. Conservative, sequencing-only value.
        settle = 5
        L.append("    {")
        L.append(f"        .id = {_rail_enum(st.rail_out)},")
        L.append(f"        .name = \"{st.rail_out}\",")
        L.append(f"        .vout_mv = {mv},")
        L.append(f"        .en_net = \"{st.enable}\",")
        L.append(f"        .en_override = {ovr},")
        L.append(f"        .settle_ms = {settle},")
        L.append(f"        .pmon_addr7 = {pmon_addr},")
        L.append(f"        .pmon_channel = {pmon_ch},")
        L.append(f"        .shunt_mohm = {shunt},")
        L.append("    },")
    L.append("};")
    L.append("")

    # always-on rails
    L.append("const char *const sc_always_on_rails[SC_ALWAYS_ON_COUNT] = {")
    for r in m.always_on:
        L.append(f"    \"{r}\",")
    L.append("};")
    L.append("")

    # module gates
    bit_of = _tca_bit_map(m)
    L.append("const sc_module_gate_t sc_module_gates[SC_MOD_COUNT] = {")
    for g in m.gates:
        bit = bit_of.get(g.enable)
        bit_expr = "0xFF" if bit is None else str(bit)
        ilim = g.ilim_ma if g.ilim_ma is not None else 0
        L.append("    {")
        L.append(f"        .id = {_module_enum(g.enable)},")
        L.append(f"        .module = \"{g.module}\",")
        L.append(f"        .rail_in = \"{g.rail_in}\",")
        L.append(f"        .rail_out = \"{g.rail_out}\",")
        L.append(f"        .en_net = \"{g.enable}\",")
        L.append(f"        .ilim_ma = {ilim},")
        L.append(f"        .tca_bit = {bit_expr},")
        L.append("    },")
    L.append("};")
    L.append("")

    # i2c device map
    L.append("const sc_i2c_dev_t sc_i2c_devices[SC_I2C_DEV_COUNT] = {")
    for _macro, label, cmac in _i2c_rows(m):
        L.append(f"    {{ \"{label}\", {cmac} }},")
    L.append("};")
    return "\n".join(L) + "\n"


def _override_gpio(m: Model, st: bf.RegulatorStage) -> str:
    """The C initializer for the rail's veto GPIO, referencing the contract's
    ZC_RAILk_OVERRIDE_GPIO_* macros (so the (port,pin) cannot drift). Index k =
    position in the chain (same order schgen firmware emits)."""
    k = m.chain.index(st)
    cell = m.rail_cells.get(st.enable)
    # the contract only emits the override macro when the EN cell has a mapped
    # rail-override GPIO; mirror that (else a no-veto sentinel: port 0).
    from schgen.generate.firmware import RAIL_OVERRIDE_GPIO
    if cell is not None and cell.override_net in RAIL_OVERRIDE_GPIO:
        return (f"{{ .port = ZC_RAIL{k}_OVERRIDE_GPIO_PORT, "
                f".pin = ZC_RAIL{k}_OVERRIDE_GPIO_PIN }}")
    return "{ .port = 0, .pin = 0 }"


def _telemetry(m: Model, st: bf.RegulatorStage) -> tuple[str, int, int]:
    """(addr-macro-expr, channel, shunt_mohm) of the INA3221 channel that
    senses this rail -- looked up by the rail name in the monitor channel map.
    Returns ('0', 0, 0) if the rail is not monitored."""
    from schgen.generate.firmware import _shunt_mohm
    pmon = load_subsystem("power_mon").circuit
    for k, mon in enumerate(m.monitors, 1):
        for ch, (inp, inn) in mon.channels.items():
            if inn == st.rail_out and not (inp == "GND" and inn == "GND"):
                shunt = _shunt_mohm(pmon, inp, inn) or 0
                return (f"ZC_I2C_ADDR_INA3221_{k}", ch, shunt)
    return ("0", 0, 0)


def _tca_bit_map(m: Model) -> dict[str, int]:
    """EN_* net -> TCA9535 output-word bit index, from the expander port map.
    P00=bit0 ... P17=bit15 (same convention as the contract header)."""
    # the override net feeding each gate's EN cell sits on a TCA9535 Pxx port;
    # we read it from bringup_en_modules joined to the expander ports.
    enm = load_subsystem("bringup_en_modules").circuit
    cell_of = {c.enable: c for c in bf.en_cells(enm)}
    out: dict[str, int] = {}
    for pname, net in m.expander.ports.items():
        bit = int(pname[1]) * 8 + int(pname[2])
        for g in m.gates:
            cell = cell_of.get(g.enable)
            if cell is not None and cell.override_net == net:
                out[g.enable] = bit
    return out


# ==================================================================================
#  sc_seq.h / sc_seq.c  -- the portable rail-sequencing stepper
# ==================================================================================

def gen_sc_seq_h(m: Model) -> str:
    L = _file_header("sc_seq.h", "portable rail-sequencing state machine",
                     m.device)
    L += ["#ifndef SC_SEQ_H", "#define SC_SEQ_H", "",
          "#include <stdint.h>", "#include <stdbool.h>",
          "#include \"sc_tables.h\"", "",
          "/* The bring-up state machine -- mirrors BRINGUP.md staging:        */",
          "/*   IDLE -> always-on assumed up -> sequence core rails -> modules */",
          "/* Each step enables one rail/gate, waits settle_ms, then confirms  */",
          "/* via telemetry before advancing.  C2: the watchdog is NOT armed   */",
          "/* anywhere in this sequence (see sc_wdt.h).                         */",
          "typedef enum {",
          "    SC_SEQ_IDLE = 0,",
          "    SC_SEQ_RAILS,        /* sequencing the core regulator chain */",
          "    SC_SEQ_MODULES,      /* enabling the module load switches */",
          "    SC_SEQ_DONE,",
          "    SC_SEQ_FAULT,",
          "} sc_seq_phase_t;",
          "",
          "typedef struct {",
          "    sc_seq_phase_t phase;",
          "    uint8_t        index;     /* step within the current phase */",
          "    const char    *fault_net; /* set when phase == SC_SEQ_FAULT */",
          "} sc_seq_state_t;",
          "",
          "/* Enable policy for a rail/module: the SC VETO defaults to \"let the */",
          "/* DIP rule\" (override HIGH/Hi-Z).  A caller may force a rail OFF by */",
          "/* returning false here; it can never force one ON (DIP AND ovr).   */",
          "typedef bool (*sc_enable_policy_t)(const char *en_net);",
          "",
          "/* Initialise the sequencer state (does NOT touch hardware). */",
          "void sc_seq_init(sc_seq_state_t *st);",
          "",
          "/* Advance the sequence by one step.  Returns true while more steps   */",
          "/* remain (call again after the returned settle), false when DONE or  */",
          "/* FAULT.  `policy` may be NULL (then every rail follows its DIP).    */",
          "bool sc_seq_step(sc_seq_state_t *st, sc_enable_policy_t policy);",
          "",
          "/* Drive the whole sequence to completion (blocking, uses the HAL     */",
          "/* delay for the per-stage settle).  Returns 0 on SC_SEQ_DONE, <0 on  */",
          "/* SC_SEQ_FAULT.  This is the simplest entry point for a bring-up app.*/",
          "int sc_seq_run(sc_enable_policy_t policy);",
          "",
          "#endif /* SC_SEQ_H */"]
    return "\n".join(L) + "\n"


def gen_sc_seq_c(m: Model) -> str:
    L = _file_header("sc_seq.c", "portable rail-sequencing state machine (impl)",
                     m.device)
    L += [
        f"#include \"{CONTRACT_HEADER}\"",
        "#include \"sc_hal.h\"",
        "#include \"sc_tables.h\"",
        "#include \"sc_seq.h\"",
        "",
        "/* Drive a rail/module EN override.  The override is a VETO that is     */",
        "/* ACTIVE-LOW: HIGH/Hi-Z lets the DIP enable the rail, LOW forces OFF.  */",
        "/* A port=0 GPIO means \"no SC veto wired\" -- the DIP is sole owner.    */",
        "static int sc_drive_override(sc_gpio_t io, bool want_on) {",
        "    if (io.port == 0) return 0;            /* no veto line: DIP rules */",
        "    /* want_on -> release the veto (HIGH); !want_on -> assert (LOW).   */",
        "    return sc_gpio_set(io, want_on);",
        "}",
        "",
        "/* Confirm a rail by reading its INA3221 bus-voltage channel, if one is */",
        "/* mapped.  This is a STUB hook: the INA3221 register read lives in the */",
        "/* platform/driver layer -- here we only gate on telemetry presence so  */",
        "/* the portable sequencing logic is complete and testable.  A port may  */",
        "/* override sc_rail_is_good() to do the real read.                      */",
        "bool __attribute__((weak)) sc_rail_is_good(const sc_rail_step_t *step) {",
        "    if (step->pmon_addr7 == 0) return true;   /* untelemetered: trust */",
        "    /* TODO(port): read INA3221 (step->pmon_addr7, step->pmon_channel)  */",
        "    /* bus-voltage reg and compare against step->vout_mv with margin.   */",
        "    (void)step;",
        "    return true;",
        "}",
        "",
        "void sc_seq_init(sc_seq_state_t *st) {",
        "    st->phase = SC_SEQ_RAILS;",
        "    st->index = 0;",
        "    st->fault_net = NULL;",
        "}",
        "",
        "static bool sc_policy_allows(sc_enable_policy_t policy, const char *en) {",
        "    return policy ? policy(en) : true;",
        "}",
        "",
        "bool sc_seq_step(sc_seq_state_t *st, sc_enable_policy_t policy) {",
        "    switch (st->phase) {",
        "    case SC_SEQ_RAILS: {",
        "        if (st->index >= SC_RAIL_COUNT) {",
        "            st->phase = SC_SEQ_MODULES;",
        "            st->index = 0;",
        "            return true;",
        "        }",
        "        const sc_rail_step_t *step = &sc_rail_steps[st->index];",
        "        bool want = sc_policy_allows(policy, step->en_net);",
        "        sc_log(step->name);",
        "        if (sc_drive_override(step->en_override, want) != 0) {",
        "            st->phase = SC_SEQ_FAULT;",
        "            st->fault_net = step->en_net;",
        "            return false;",
        "        }",
        "        if (want) {",
        "            sc_delay_ms(step->settle_ms);",
        "            if (!sc_rail_is_good(step)) {",
        "                st->phase = SC_SEQ_FAULT;",
        "                st->fault_net = step->name;",
        "                return false;",
        "            }",
        "        }",
        "        st->index++;",
        "        return true;",
        "    }",
        "    case SC_SEQ_MODULES: {",
        "        if (st->index >= SC_MOD_COUNT) {",
        "            st->phase = SC_SEQ_DONE;",
        "            return false;",
        "        }",
        "        const sc_module_gate_t *g = &sc_module_gates[st->index];",
        "        bool want = sc_policy_allows(policy, g->en_net);",
        "        sc_log(g->module);",
        "        /* Module overrides ride the TCA9535 output word (g->tca_bit);  */",
        "        /* the expander write lives in the platform layer.  A direct    */",
        "        /* (0xFF) gate would drive a GPIO here instead.  Either way the */",
        "        /* DIP still gates the SY6280 -- the SC only vetoes.            */",
        "        (void)want;",
        "        st->index++;",
        "        return true;",
        "    }",
        "    case SC_SEQ_IDLE:",
        "    case SC_SEQ_DONE:",
        "    case SC_SEQ_FAULT:",
        "    default:",
        "        return false;",
        "    }",
        "}",
        "",
        "int sc_seq_run(sc_enable_policy_t policy) {",
        "    sc_seq_state_t st;",
        "    sc_seq_init(&st);",
        "    /* C2: do NOT arm/kick the watchdog here -- bring-up must complete  */",
        "    /* first; the caller arms it afterwards (see sc_wdt.h / sc_app.c).  */",
        "    while (sc_seq_step(&st, policy)) {",
        "        /* settle handled inside the step */",
        "    }",
        "    return (st.phase == SC_SEQ_DONE) ? 0 : -1;",
        "}",
    ]
    return "\n".join(L) + "\n"


# ==================================================================================
#  sc_wdt.h / sc_wdt.c  -- TPS3823 watchdog (C2: not during power-up)
# ==================================================================================

def gen_sc_wdt_h(m: Model) -> str:
    L = _file_header("sc_wdt.h", "TPS3823 external watchdog (WDI strobe)",
                     m.device)
    L += [
        "#ifndef SC_WDT_H", "#define SC_WDT_H", "",
        "#include <stdbool.h>", "#include \"sc_hal.h\"", "",
        "/* The TPS3823 (board_services) is an EXTERNAL watchdog: the SC keeps  */",
        "/* it happy by STROBING its WDI line.  C2 (project constraint): the    */",
        "/* watchdog must NOT be armed or kicked DURING the power-up sequence,  */",
        "/* only AFTER bring-up has completed -- otherwise a slow rail ramp     */",
        "/* would trip a board reset mid-sequence.  sc_wdt_arm() therefore sets */",
        "/* a latch that sc_wdt_kick() checks; kicks before arming are no-ops.  */",
        "",
        "/* Arm the watchdog supervision.  Call ONLY after sc_seq_run() returns  */",
        "/* success -- never inside the bring-up sequence (C2).                  */",
        "void sc_wdt_arm(void);",
        "",
        "/* True once armed -- the bring-up code asserts !sc_wdt_is_armed()      */",
        "/* while sequencing.                                                    */",
        "bool sc_wdt_is_armed(void);",
        "",
        "/* Strobe the TPS3823 WDI.  A no-op until sc_wdt_arm() has been called  */",
        "/* (C2 guard), so a stray kick during power-up cannot start the timer. */",
        "void sc_wdt_kick(void);",
        "",
        "#endif /* SC_WDT_H */"]
    return "\n".join(L) + "\n"


def gen_sc_wdt_c(m: Model) -> str:
    L = _file_header("sc_wdt.c", "TPS3823 external watchdog (impl)", m.device)
    L += [
        "#include \"sc_hal.h\"",
        "#include \"sc_wdt.h\"",
        "",
        "/* C2 latch: false until sc_wdt_arm(); kicks before arming are no-ops. */",
        "static bool s_wdt_armed = false;",
        "",
        "void sc_wdt_arm(void) {",
        "    s_wdt_armed = true;",
        "    sc_log(\"watchdog armed (post-bring-up)\");",
        "}",
        "",
        "bool sc_wdt_is_armed(void) {",
        "    return s_wdt_armed;",
        "}",
        "",
        "void sc_wdt_kick(void) {",
        "    if (!s_wdt_armed) return;          /* C2: no kicks during power-up */",
        "    if (sc_hal->wdt_strobe) sc_hal->wdt_strobe();",
        "}",
    ]
    return "\n".join(L) + "\n"


# ==================================================================================
#  sc_pd.h / sc_pd.c  -- FUSB302B PD negotiate entry points
# ==================================================================================

def gen_sc_pd_h(m: Model) -> str:
    L = _file_header("sc_pd.h", "FUSB302B USB-PD negotiate hooks", m.device)
    L += [
        "#ifndef SC_PD_H", "#define SC_PD_H", "",
        "#include <stdint.h>", "#include <stdbool.h>", "#include \"sc_hal.h\"", "",
        "/* The FUSB302B (usb_pd) is a PD PHY ONLY -- it does not negotiate by  */",
        "/* itself.  Reaching the higher-voltage USB-C contract (so +VIN rises  */",
        "/* from the 5 V default to the negotiated voltage) requires the SC to  */",
        "/* run PD policy through the FUSB302B over I2C (BRINGUP.md Stage 1).   */",
        "/* These are the ENTRY POINTS a PD stack (e.g. the Zephyr USB-C        */",
        "/* subsystem or a vendored tcpm) plugs into; the protocol itself is    */",
        "/* out of scope for this scaffold -- the hooks make the integration    */",
        "/* point explicit and netlist-anchored (address from the contract).    */",
        "",
        "/* Bring the FUSB302B out of reset and verify it answers on I2C.       */",
        "/* Returns 0 on success.                                               */",
        "int sc_pd_init(void);",
        "",
        "/* Request a power contract of at least `min_mv` / `min_ma`.  Returns 0 */",
        "/* once a matching contract is accepted, <0 on timeout/failure.  The   */",
        "/* body is a STUB -- wire it to your PD policy engine.                  */",
        "int sc_pd_request(uint32_t min_mv, uint32_t min_ma);",
        "",
        "/* Service a PD interrupt (the FUSB302B INT is wire-ORed into SC_INT_N */",
        "/* with the TCA9535 INT# -- read BOTH status registers on the IRQ).    */",
        "void sc_pd_on_irq(void);",
        "",
        "#endif /* SC_PD_H */"]
    return "\n".join(L) + "\n"


def gen_sc_pd_c(m: Model) -> str:
    L = _file_header("sc_pd.c", "FUSB302B USB-PD negotiate hooks (impl)", m.device)
    L += [
        f"#include \"{CONTRACT_HEADER}\"",
        "#include \"sc_hal.h\"",
        "#include \"sc_pd.h\"",
        "",
        "/* FUSB302B 7-bit address straight from the hardware contract.         */",
        "#define SC_PD_FUSB302B_ADDR  ZC_I2C_ADDR_FUSB302B",
        "",
        "int sc_pd_init(void) {",
        "    /* A 1-byte read of the Device ID register (0x01) probes presence.  */",
        "    uint8_t reg = 0x01;",
        "    uint8_t id = 0;",
        "    if (sc_i2c_write(SC_PD_FUSB302B_ADDR, &reg, 1) != 0) return -1;",
        "    if (sc_i2c_read(SC_PD_FUSB302B_ADDR, &id, 1) != 0) return -1;",
        "    sc_log(\"FUSB302B present\");",
        "    return 0;",
        "}",
        "",
        "int sc_pd_request(uint32_t min_mv, uint32_t min_ma) {",
        "    /* TODO(port): drive a PD Request through the FUSB302B for a source */",
        "    /* capability that meets (min_mv, min_ma).  Until a PD stack runs   */",
        "    /* this, +VIN stays at the 5 V default contract (BRINGUP.md St.1).  */",
        "    (void)min_mv; (void)min_ma;",
        "    return -1;",
        "}",
        "",
        "void sc_pd_on_irq(void) {",
        "    /* SC_INT_N is the wire-OR of FUSB302B INT and TCA9535 INT#; the    */",
        "    /* handler reads BOTH devices' status registers (contract note).    */",
        "    /* TODO(port): read FUSB302B Interrupt regs and dispatch to policy. */",
        "}",
    ]
    return "\n".join(L) + "\n"


# ==================================================================================
#  sc_rtc.h / sc_rtc.c  -- RV-3028 trickle charger (rechargeable ML1220 backup)
# ==================================================================================

def gen_sc_rtc_h(m: Model) -> str:
    L = _file_header("sc_rtc.h", "RV-3028 RTC trickle charger (ML1220 backup)",
                     m.device)
    L += [
        "#ifndef SC_RTC_H", "#define SC_RTC_H", "",
        "#include \"sc_hal.h\"", "",
        "/* board_services fits a RECHARGEABLE ML1220 (Mn-Li) on the RV-3028's    */",
        "/* VBACKUP for a maintenance-free RTC.  A rechargeable cell only stays    */",
        "/* charged if firmware ENABLES the RV-3028's internal trickle charger     */",
        "/* (TCE + a series resistance in the EEPROM Backup register) -- so the    */",
        "/* cell tops up whenever the board is powered (contract ZC_I2C_ADDR_RTC). */",
        "/* This is the netlist-anchored entry point that makes the ML1220 choice  */",
        "/* real; without it the cell would slowly deplete.                        */",
        "",
        "/* Probe the RV-3028 on the AUX I2C and enable the trickle charger.       */",
        "/* Returns 0 on success.  Best-effort: the RTC is on the gated +3V3_AUX   */",
        "/* rail, so call it once that rail + its I2C isolator are up.             */",
        "int sc_rtc_init(void);",
        "",
        "/* Enable the trickle charger only (TCE + ~3k + backup switchover),       */",
        "/* committing it to the config EEPROM.  Returns 0 on success.            */",
        "int sc_rtc_trickle_enable(void);",
        "",
        "#endif /* SC_RTC_H */"]
    return "\n".join(L) + "\n"


def gen_sc_rtc_c(m: Model) -> str:
    L = _file_header("sc_rtc.c", "RV-3028 RTC trickle charger (impl)", m.device)
    L += [
        f"#include \"{CONTRACT_HEADER}\"",
        "#include \"sc_hal.h\"",
        "#include \"sc_rtc.h\"",
        "",
        "#define SC_RTC_ADDR         ZC_I2C_ADDR_RTC   /* RV-3028, 7-bit 0x52 */",
        "",
        "/* RV-3028-C7 registers (Micro Crystal Application Manual). */",
        "#define SC_RTC_REG_CTRL1    0x0Fu   /* EERD = bit 3 (auto-refresh dis.) */",
        "#define SC_RTC_REG_EECMD    0x27u   /* EEPROM command */",
        "#define SC_RTC_REG_ID       0x28u   /* device ID (presence probe) */",
        "#define SC_RTC_REG_EEBACKUP 0x37u   /* EEPROM Backup (RAM mirror) */",
        "",
        "/* EEPROM Backup register bit fields -- RV-3028-C7 Application Manual",
        " * Rev 1.4, 'EEPROM Backup Register' (cross-checked against the constiko",
        " * RV-3028-C7 Arduino library): TCE=bit5, FEDE=bit4, BSM=bits3:2,",
        " * TCR=bits1:0.  Re-confirm if your part revision differs. */",
        "#define SC_RTC_TCR_MASK     (0x3u << 0)  "
        "/* trickle R: 00=3k 01=5k 10=9k 11=15k */",
        "#define SC_RTC_TCR_3K       (0x0u << 0)  "
        "/* ~3k -> gentle ML1220 trickle @3.3V */",
        "#define SC_RTC_BSM_LSM      (0x3u << 2)  "
        "/* Backup Switchover: Level Switching */",
        "#define SC_RTC_FEDE         (0x1u << 4)  "
        "/* Fast Edge Detect (DS default 1) */",
        "#define SC_RTC_TCE          (0x1u << 5)  /* Trickle Charge Enable */",
        "",
        "#define SC_RTC_CTRL1_EERD   (0x1u << 3)  "
        "/* 1 = disable auto EEPROM refresh */",
        "#define SC_RTC_EECMD_UPDATE 0x11u        "
        "/* 'update all configuration EEPROM' */",
        "",
        "static int rtc_w(uint8_t reg, uint8_t val) {",
        "    uint8_t b[2] = { reg, val };",
        "    return sc_i2c_write(SC_RTC_ADDR, b, 2);",
        "}",
        "static int rtc_r(uint8_t reg, uint8_t *val) {",
        "    if (sc_i2c_write(SC_RTC_ADDR, &reg, 1) != 0) return -1;",
        "    return sc_i2c_read(SC_RTC_ADDR, val, 1);",
        "}",
        "",
        "int sc_rtc_trickle_enable(void) {",
        "    uint8_t bk = 0, c1 = 0;",
        "    /* 1. read the current Backup register (its RAM mirror). */",
        "    if (rtc_r(SC_RTC_REG_EEBACKUP, &bk) != 0) return -1;",
        "    /* 2. set TCE + 3k series + fast-edge + level switchover, preserving",
        "     *    every other bit (read-modify-write, not a raw value). */",
        "    bk &= (uint8_t)~SC_RTC_TCR_MASK;",
        "    bk |= (uint8_t)(SC_RTC_TCE | SC_RTC_FEDE "
        "| SC_RTC_BSM_LSM | SC_RTC_TCR_3K);",
        "    /* 3. disable auto config-EEPROM refresh (EERD=1) before the update. */",
        "    if (rtc_r(SC_RTC_REG_CTRL1, &c1) != 0) return -1;",
        "    if (rtc_w(SC_RTC_REG_CTRL1, (uint8_t)(c1 | SC_RTC_CTRL1_EERD)) "
        "!= 0) return -1;",
        "    /* 4. write the new value into the RAM mirror. */",
        "    if (rtc_w(SC_RTC_REG_EEBACKUP, bk) != 0) return -1;",
        "    /* 5. commit RAM -> EEPROM: EECMD 0x00 then 0x11 (update all config). */",
        "    if (rtc_w(SC_RTC_REG_EECMD, 0x00u) != 0) return -1;",
        "    if (rtc_w(SC_RTC_REG_EECMD, SC_RTC_EECMD_UPDATE) != 0) return -1;",
        "    sc_delay_ms(20);   /* config-EEPROM write latency (~16 ms typ). */",
        "    /* 6. re-enable auto refresh (EERD=0). */",
        "    if (rtc_w(SC_RTC_REG_CTRL1, (uint8_t)(c1 & ~SC_RTC_CTRL1_EERD)) "
        "!= 0) return -1;",
        "    sc_log(\"RV-3028 trickle charger enabled (ML1220, ~3k)\");",
        "    return 0;",
        "}",
        "",
        "int sc_rtc_init(void) {",
        "    uint8_t id = 0;",
        "    if (rtc_r(SC_RTC_REG_ID, &id) != 0) return -1;   /* presence probe */",
        "    sc_log(\"RV-3028 present\");",
        "    return sc_rtc_trickle_enable();",
        "}",
    ]
    return "\n".join(L) + "\n"


# ==================================================================================
#  sc_app.c  -- a tiny example main wiring it together (portable, HAL-backed)
# ==================================================================================

def gen_sc_app_c(m: Model) -> str:
    L = _file_header("sc_app.c", "example bring-up app (portable, HAL-backed)",
                     m.device)
    L += [
        "#include \"sc_hal.h\"",
        "#include \"sc_seq.h\"",
        "#include \"sc_pd.h\"",
        "#include \"sc_rtc.h\"",
        "#include \"sc_wdt.h\"",
        "",
        "/* A reference bring-up flow that ties the scaffold together.  A real  */",
        "/* app supplies its own main() / Zephyr thread and the sc_hal port;    */",
        "/* this shows the C2-correct ORDER: rails -> modules -> THEN arm WDT.  */",
        "int sc_bringup_main(void) {",
        "    sc_log(\"SC bring-up: sequencing rails (DIP-gated, SC veto only)\");",
        "    /* PD negotiation is optional here: the board runs reduced on the  */",
        "    /* 5 V default contract until a PD stack lifts +VIN.               */",
        "    (void)sc_pd_init();",
        "",
        "    /* C2: the watchdog is NOT armed yet -- sequence first. */",
        "    if (sc_seq_run(/*policy=*/NULL) != 0) {",
        "        sc_log(\"bring-up FAULT -- leaving watchdog disarmed\");",
        "        return -1;",
        "    }",
        "",
        "    /* Bring-up complete: NOW it is safe to arm the watchdog (C2). */",
        "    sc_wdt_arm();",
        "",
        "    /* RTC: enable the RV-3028 trickle charger so the rechargeable ML1220 */",
        "    /* backup cell tops up.  Best-effort -- the RTC is on the gated AUX   */",
        "    /* rail, so this only takes once that rail + its I2C isolator are up. */",
        "    (void)sc_rtc_init();",
        "",
        "    sc_log(\"SC bring-up complete; watchdog armed\");",
        "    return 0;",
        "}",
    ]
    return "\n".join(L) + "\n"


# ==================================================================================
#  sc_hal_zephyr.c.txt  -- a COMMENTED reference Zephyr port (no zephyr headers)
# ==================================================================================

def gen_zephyr_port_ref(m: Model) -> str:
    L = [
        "/*",
        " * sc_hal_zephyr.c.txt -- REFERENCE Zephyr HAL port (NOT compiled).",
        " *",
        " * GENERATED by `schgen scfw` -- DO NOT EDIT.",
        " *",
        " * Shipped with a .txt suffix so the firmware/sc/ tree stays strictly",
        " * toolchain-agnostic (nothing here includes a zephyr/ header).  Copy",
        " * it to sc_hal_zephyr.c in your Zephyr app, uncomment, and fix the GPIO",
        " * bank lookup to your board's devicetree.  It implements sc_hal_t over",
        " * the Zephyr GPIO + I2C APIs and publishes `sc_hal`.",
        " */",
        "#if 0   /* enable in a Zephyr build */",
        "#include <zephyr/kernel.h>",
        "#include <zephyr/drivers/gpio.h>",
        "#include <zephyr/drivers/i2c.h>",
        "#include \"sc_hal.h\"",
        "",
        "/* One device handle per STM32 GPIO bank the contract uses; the HAL    */",
        "/* maps an sc_gpio_t ('A'..'G', pin) onto (bank, pin).                 */",
        "static const struct device *gpio_bank(char port) {",
        "    switch (port) {",
        "    case 'A': return DEVICE_DT_GET(DT_NODELABEL(gpioa));",
        "    case 'B': return DEVICE_DT_GET(DT_NODELABEL(gpiob));",
        "    case 'C': return DEVICE_DT_GET(DT_NODELABEL(gpioc));",
        "    /* ... D..G as the board provides ... */",
        "    default:  return NULL;",
        "    }",
        "}",
        "",
        "static const struct device *i2c_bus =",
        "    DEVICE_DT_GET(DT_NODELABEL(i2c_sc));   /* the bit-bang I2C (PA4/PA5) */",
        "",
        "static void z_delay_ms(uint32_t ms) { k_msleep(ms); }",
        "static uint32_t z_uptime_ms(void) { return (uint32_t)k_uptime_get(); }",
        "",
        "static int z_gpio_cfg_out(sc_gpio_t io, bool od) {",
        "    gpio_flags_t f = GPIO_OUTPUT | (od ? GPIO_OPEN_DRAIN : 0);",
        "    return gpio_pin_configure(gpio_bank(io.port), io.pin, f);",
        "}",
        "static int z_gpio_cfg_in(sc_gpio_t io, bool pu) {",
        "    gpio_flags_t f = GPIO_INPUT | (pu ? GPIO_PULL_UP : 0);",
        "    return gpio_pin_configure(gpio_bank(io.port), io.pin, f);",
        "}",
        "static int z_gpio_set(sc_gpio_t io, bool lvl) {",
        "    return gpio_pin_set(gpio_bank(io.port), io.pin, lvl);",
        "}",
        "static int z_gpio_get(sc_gpio_t io, bool *lvl) {",
        "    int v = gpio_pin_get(gpio_bank(io.port), io.pin);",
        "    if (v < 0) return v; *lvl = (v != 0); return 0;",
        "}",
        "static int z_i2c_xfer(uint8_t addr7, sc_i2c_dir_t dir,",
        "                      uint8_t *buf, size_t len) {",
        "    return (dir == SC_I2C_READ)",
        "        ? i2c_read(i2c_bus, buf, len, addr7)",
        "        : i2c_write(i2c_bus, buf, len, addr7);",
        "}",
        "static int z_wdt_strobe(void) {",
        "    /* toggle the TPS3823 WDI gpio (wdi-gpios in the overlay) */",
        "    return 0;",
        "}",
        "static void z_log(const char *msg) { printk(\"[sc] %s\\n\", msg); }",
        "",
        "static const sc_hal_t z_hal = {",
        "    .delay_ms = z_delay_ms, .uptime_ms = z_uptime_ms,",
        "    .gpio_configure_output = z_gpio_cfg_out,",
        "    .gpio_configure_input = z_gpio_cfg_in,",
        "    .gpio_set = z_gpio_set, .gpio_get = z_gpio_get,",
        "    .i2c_xfer = z_i2c_xfer, .wdt_strobe = z_wdt_strobe, .log = z_log,",
        "};",
        "const sc_hal_t *sc_hal = &z_hal;",
        "#endif /* 0 */",
    ]
    return "\n".join(L) + "\n"


# ==================================================================================
#  README + manifest of the scaffold
# ==================================================================================

def gen_readme(m: Model, files: list[str]) -> str:
    L = [
        "# SC bring-up firmware scaffold (GENERATED)",
        "",
        "> GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.",
        "> Regenerate: `PYTHONPATH=. python -m schgen scfw`.  Every table value",
        "> is read from the authored carrier netlists via `bringup_facts` (and",
        "> through it the live SoM U9 pin map); nothing is hand-typed.",
        "",
        "Portable-C bring-up firmware for the SoM STM32 system controller",
        f"(`{m.device}`).  It consumes the hardware CONTRACT",
        "(`../zynq_carrier_contract.h`, from `schgen firmware`) and automates",
        "the staged procedure in `../../docs/BRINGUP.md`.",
        "",
        "## Toolchain-agnostic by construction",
        "",
        "No file here `#include`s a Zephyr (or any platform) header.  The",
        "portable code calls the `sc_hal` op table (`sc_hal.h`); a platform",
        "port implements that table.  A Zephyr reference port ships as",
        "`sc_hal_zephyr.c.txt` (a `.txt` so the tree stays platform-free) plus",
        "the devicetree-overlay / Kconfig notes in `sc_hal.h`.",
        "",
        "## Files",
        "",
        "| file | role |",
        "|---|---|",
        "| `sc_hal.h` | the platform-op abstraction + the Zephyr port note |",
        "| `sc_tables.h` / `sc_tables.c` | netlist-derived tables: rail step "
        "table, module gates, I2C device map |",
        "| `sc_seq.h` / `sc_seq.c` | the portable rail-sequencing state machine "
        "(step table + stepper) |",
        "| `sc_wdt.h` / `sc_wdt.c` | TPS3823 watchdog kick, with the C2 "
        "power-up guard |",
        "| `sc_pd.h` / `sc_pd.c` | FUSB302B PD negotiate entry points (hooks) |",
        "| `sc_app.c` | a reference bring-up flow tying it together "
        "(C2-correct order) |",
        "| `sc_hal_zephyr.c.txt` | commented reference Zephyr HAL port |",
        "",
        "## Derived rail-sequencing order",
        "",
        "Read from the `power.py` regulator chain (each stage feeds the next):",
        "",
    ]
    for k, st in enumerate(m.chain):
        mv = round(st.vout * 1000) if st.vout is not None else 0
        L.append(f"{k + 1}. `{st.rail_in}` -> `{st.rail_out}` "
                 f"({mv} mV, EN `{st.enable}`)")
    L += [
        "",
        "Always-on (pre-PD, up before sequencing): "
        + ", ".join(f"`{r}`" for r in m.always_on) + ".",
        "",
        "Then the SY6280 module load switches, one at a time:",
        "",
    ]
    for g in m.gates:
        ilim = f"{g.ilim_ma} mA" if g.ilim_ma is not None else "?"
        L.append(f"- `{g.module}`: `{g.rail_in}` -> `{g.rail_out}` "
                 f"(EN `{g.enable}`, ILIM {ilim})")
    L += [
        "",
        "## C2 -- watchdog not during power-up",
        "",
        "The TPS3823 is an external supervisor; the SC only strobes its WDI.",
        "Per project constraint C2, `sc_wdt_kick()` is a no-op until",
        "`sc_wdt_arm()` is called, and `sc_seq_run()` never arms it -- so a",
        "slow rail ramp cannot trip a reset mid-bring-up.  `sc_app.c` shows the",
        "correct order: sequence rails + modules, **then** `sc_wdt_arm()`.",
        "",
        "## Building (host syntax check)",
        "",
        "```sh",
        "gcc -std=c11 -fsyntax-only -I. -I.. sc_tables.c sc_seq.c sc_wdt.c \\",
        "    sc_pd.c sc_app.c",
        "```",
        "",
        "A platform port (`sc_hal_*.c`) provides `sc_hal`; the portable objects",
        "above link against it.",
        "",
    ]
    return "\n".join(L) + "\n"


# ==================================================================================
#  the orchestrator
# ==================================================================================

# emit order is fixed (deterministic); name -> generator
_FILES = [
    ("sc_hal.h", gen_sc_hal_h),
    ("sc_tables.h", gen_sc_tables_h),
    ("sc_tables.c", gen_sc_tables_c),
    ("sc_seq.h", gen_sc_seq_h),
    ("sc_seq.c", gen_sc_seq_c),
    ("sc_wdt.h", gen_sc_wdt_h),
    ("sc_wdt.c", gen_sc_wdt_c),
    ("sc_pd.h", gen_sc_pd_h),
    ("sc_pd.c", gen_sc_pd_c),
    ("sc_rtc.h", gen_sc_rtc_h),
    ("sc_rtc.c", gen_sc_rtc_c),
    ("sc_app.c", gen_sc_app_c),
    ("sc_hal_zephyr.c.txt", gen_zephyr_port_ref),
]


def _ascii(text: str) -> str:
    # pure-ASCII for embedded toolchains (mirrors firmware.py/devicetree.py)
    return text.replace("—", "--").replace("→", "->")


def generate(out_dir: Path = DEFAULT_OUT) -> list[Path]:
    """Build + write the whole SC firmware scaffold into ``out_dir``.  Returns
    the written paths in deterministic emit order."""
    m = Model()
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    names = [n for n, _ in _FILES]
    for name, fn in _FILES:
        path = out_dir / name
        path.write_text(_ascii(fn(m)))
        written.append(path)
    readme = out_dir / "README.md"
    readme.write_text(_ascii(gen_readme(m, names)))
    written.append(readme)
    return written


def cmd_scfw(args: argparse.Namespace) -> int:
    out_dir = args.output or DEFAULT_OUT
    written = generate(out_dir)
    print(f"SCFW SCAFFOLD: {out_dir} ({len(written)} files)")
    for p in written:
        print(f"  {p.name}")
    return 0
