from __future__ import annotations

import argparse
import tempfile
from pathlib import Path

from schgen.core.project import PROJECT_ROOT
from schgen.core.som_interface import extract_zynq
from schgen.generate import xdc

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOM = REPO_ROOT / "som" / "Zynq_SoM.kicad_sch"
DEFAULT_CONTRACT = PROJECT_ROOT / "som_interface.json"
DEFAULT_OUT = PROJECT_ROOT / "fpga" / "create_project.tcl"
DEFAULT_XDC = PROJECT_ROOT / "fpga" / "Zynq_Carrier_pins.xdc"

PROJECT_NAME = "zynq_carrier"
BD_NAME = "system"
PS_IP_VLNV = "xilinx.com:ip:processing_system7:5.5"

KNOWN_CLOCK_PERIODS_NS: dict[str, float] = {}


class VivadoError(ValueError):
    pass


def _rel(target: Path, start: Path) -> str:
    try:
        rel = Path(target).resolve().relative_to(start.resolve())
        return rel.as_posix()
    except ValueError:
        import os
        return Path(os.path.relpath(Path(target).resolve(),
                                    start.resolve())).as_posix()


def _fmt_period(p: float) -> str:
    if p == int(p):
        return str(int(p))
    return f"{p:g}"


def generate(sheets, out_path: Path = DEFAULT_OUT, *,
             som_sch: Path = DEFAULT_SOM,
             contract_path: Path = DEFAULT_CONTRACT,
             xdc_path: Path = DEFAULT_XDC,
             refs: tuple[str, ...] = ("J1", "J2", "J3")) -> Path:
    live = extract_zynq(som_sch, jrefs=tuple(refs))
    device = live["value"]
    if not device:
        raise VivadoError(
            f"SoM Zynq {live['zynq_ref']} carries no value field in "
            f"{som_sch} — cannot determine the Vivado part")

    with tempfile.TemporaryDirectory(prefix="schgen_vivado_") as td:
        xres = xdc.generate(sheets, Path(td) / "pins.xdc",
                            som_sch=som_sch, contract_path=contract_path,
                            refs=refs)
    entries = xres.entries

    clk_entries = sorted(
        (e for e in entries if e.clock_capable and e.p_side),
        key=lambda e: e.net)
    promoted = [e for e in clk_entries
                if e.net in KNOWN_CLOCK_PERIODS_NS]
    templated = [e for e in clk_entries
                 if e.net not in KNOWN_CLOCK_PERIODS_NS]

    xdc_rel = _rel(xdc_path, out_path.parent)

    lines: list[str] = []
    lines += [
        "#" * 78,
        "# create_project.tcl — GENERATED by `schgen vivado`. DO NOT EDIT.",
        "#",
        "# One-shot Vivado project from the schgen-generated pin constraints:",
        "#     cd carrier/fpga",
        "#     vivado -mode batch -source create_project.tcl",
        "#",
        f"# Device: {device} ({live['zynq_ref']} on the SoM, "
        f"live kicad-cli extraction — never hard-coded)",
        f"# Pin constraints: {xdc_rel} "
        f"({len(entries)} ports, generated by `schgen xdc`)",
        "# Determinism: device + pins + clocks all derive from the SoM "
        "netlist;",
        "# no timestamps, sorted ordering -> byte-identical on re-run.",
        "#" * 78,
        "",
        "# Resolve paths relative to THIS script so it sources from any cwd.",
        "set script_dir [file dirname [file normalize [info script]]]",
        "",
        f"set project_name {PROJECT_NAME}",
        f"set part {device}",
        "",
        "# ---- project ----------------------------------------------------",
        "# In-memory project under the script dir; -force overwrites a prior "
        "run.",
        "create_project -force $project_name $script_dir/$project_name "
        "-part $part",
        "set_property part $part [current_project]",
        "",
        "# ---- pin + IO constraints (schgen xdc, proved against the SoM) --",
        f'set xdc_file [file normalize $script_dir/{xdc_rel}]',
        "if {![file exists $xdc_file]} {",
        '    error "missing constraints: $xdc_file — run `schgen xdc` '
        '(or `schgen board`) first"',
        "}",
        "add_files -fileset constrs_1 -norecurse $xdc_file",
        "read_xdc $xdc_file",
        "",
    ]

    lines.append("# ---- clocks -----------------------------------------------------")
    lines.append("# MRCC/SRCC-capable PL ports the XDC flags as clock candidates.")
    if promoted:
        lines.append("# Promoted to real constraints (documented fixed source "
                     "period):")
        for e in promoted:
            period = KNOWN_CLOCK_PERIODS_NS[e.net]
            lines.append(
                f"create_clock -name {e.net} -period {_fmt_period(period)} "
                f"[get_ports {{{e.net}}}]"
                f"  ;# {e.jpin} {e.pin_name} ({e.clock_capable})")
    if templated:
        lines.append(
            "# No documented fixed period for these (source-synchronous / "
            "recovered /")
        lines.append(
            "# FPGA-driven). Left as TEMPLATES — uncomment and set <ns> for "
            "the real")
        lines.append(
            "# source frequency before timing closure (matches the XDC "
            "templates).")
        for e in templated:
            lines.append(
                f"# create_clock -name {e.net} -period <ns> "
                f"[get_ports {{{e.net}}}]"
                f"  ;# {e.jpin} {e.pin_name} ({e.clock_capable})")
    if not clk_entries:
        lines.append("# (no clock-capable PL ports bound through "
                     f"{'/'.join(refs)})")
    lines.append("")

    lines += [
        "# ---- Zynq7 Processing System (PS) — COMMENTED STUB ---------------",
        "# The PS DDR/MIO preset is SoM-revision intent and does NOT live in",
        "# the carrier netlist, so the PS is left for you to instantiate.",
        "# Uncomment to start a block design with a PS7, then APPLY THE SoM'S",
        "# PS PRESET (DDR3 timing, MIO, clocks) before generating the "
        "wrapper.",
        "#",
        f"# create_bd_design {BD_NAME}",
        f"# set ps [create_bd_cell -type ip -vlnv {PS_IP_VLNV} "
        "processing_system7_0]",
        "# # TODO: apply the SoM PS7 preset (board-specific DDR3/MIO/clock "
        "config):",
        "# #   set_property -dict [list CONFIG.preset {<SoM_preset.xml or "
        "board file>}] $ps",
        "# #   or: apply_bd_automation -rule "
        "xilinx.com:bd_rule:processing_system7 \\",
        "# #         -config {make_external \"FIXED_IO, DDR\" apply_board_"
        "preset \"1\"} $ps",
        "# validate_bd_design",
        "# save_bd_design",
        f"# make_wrapper -files [get_files {BD_NAME}.bd] -top",
        f"# add_files -norecurse "
        "$script_dir/$project_name/$project_name.srcs/sources_1/bd/"
        f"{BD_NAME}/hdl/{BD_NAME}_wrapper.v",
        "",
        "puts \"schgen: project '$project_name' created for part $part; "
        "pin constraints loaded from [file tail $xdc_file].\"",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    out_path.write_text(text)
    return out_path


def cmd_vivado(args: argparse.Namespace) -> int:
    from schgen.core.link import all_subsystem_paths, load_subsystem
    names = args.subsystems or [p.stem for p in all_subsystem_paths()]
    sheets = [load_subsystem(n) for n in names]
    refs = tuple(r.strip() for r in args.refs.split(",") if r.strip())
    try:
        out = generate(sheets, args.output or DEFAULT_OUT,
                       som_sch=args.som or DEFAULT_SOM,
                       xdc_path=args.xdc or DEFAULT_XDC, refs=refs)
    except (VivadoError, xdc.XdcError) as exc:
        print(f"VIVADO: FAIL — {exc}")
        return 1
    n_clk = sum(1 for ln in out.read_text().splitlines()
                if ln.startswith("create_clock"))
    print(f"VIVADO: {out} ({n_clk} real create_clock lines)")
    return 0
