"""SY6280AAC — SY6280AAC (SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BL)

Generated by `schgen part add C55136` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'SY6280AAC'
SAFE_NAME = 'SY6280AAC'
LCSC = 'C55136'
DESCRIPTION = 'SY6280AAC (SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BL)'
MANUFACTURER = 'Silergy(矽力杰)'
PACKAGE = 'SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C55136.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/PMIC-Power-Distribution-Switches_Silergy_SY6280AAC_SY6280AAC_C55136.html'
LIB_ID = 'SY6280AAC:SY6280AAC'
FOOTPRINT = 'SY6280AAC:SY6280AAC'
MODELS_3D = ['SY6280AAC.wrl', 'SY6280AAC.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'OUT', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'ISET', 'passive'),
    ('4', 'EN', 'passive'),
    ('5', 'IN', 'passive'),
]
