"""README render gallery (PLAN.md round 4: "the repo demos itself").

``schgen gallery`` (also run by ``schgen board``) regenerates a marked
section in two READMEs, WITHOUT duplicating the giant table:

- ``carrier/README.md`` gets the FULL gallery (it lives next to the
  renders): the block diagram inline, a thumbnail grid of every sheet, and
  a name->description table.
- the root ``README.md`` gets a COMPACT block: the block diagram inline +
  one line linking to the carrier README for the full sheet gallery.

Idempotent: content lives between ``<!-- schgen:gallery --> ...
<!-- /schgen:gallery -->`` markers and is replaced in place (appended on
first run). Deterministic: sheets sorted by name, no timestamps. Thumbnails
use GitHub-flavored-markdown-safe inline HTML (``<img width=...>`` inside a
pipe table, relative links).
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from schgen.link import all_subsystem_paths, load_subsystem

REPO_ROOT = Path(__file__).resolve().parents[1]
RENDERS = REPO_ROOT / "carrier" / "renders"
DIAGRAM = REPO_ROOT / "docs" / "block_diagram.svg"

BEGIN = "<!-- schgen:gallery -->"
END = "<!-- /schgen:gallery -->"
THUMB_W = 220
COLS = 3


def _sheet_rows() -> list[tuple[str, str, bool]]:
    """(name, description, has_render) per subsystem, sorted by name."""
    rows = []
    for p in all_subsystem_paths():
        c = load_subsystem(p.stem).circuit
        rows.append((c.name, c.title, (RENDERS / f"{c.name}.png").exists()))
    return sorted(rows)


def _full_section(readme_dir: Path) -> str:
    """The FULL gallery (carrier/README.md): block diagram + thumbnail grid
    + description table, links relative to the README's directory."""
    def rel(target: str) -> str:
        return os.path.relpath(REPO_ROOT / target, readme_dir)

    rows = _sheet_rows()
    n = len(rows)
    L: list[str] = []
    L.append(BEGIN)
    L.append("<!-- GENERATED by `schgen gallery` — edits between these "
             "markers are overwritten -->")
    L.append("## Generated schematics")
    L.append("")
    L.append(f"Block diagram and all {n} carrier sheets, regenerated by "
             f"`schgen board` —")
    L.append("every PNG below passed the netlist, ERC and visual gates.")
    L.append("")
    L.append(f'<img src="{rel("docs/block_diagram.svg")}" '
             f'alt="Generated block diagram" width="900">')
    L.append("")
    # thumbnail grid: COLS sheets per table row (GFM pipe table + <img>)
    L.append("| " + " | ".join([" "] * COLS) + " |")
    L.append("|" + "---|" * COLS)
    for i in range(0, n, COLS):
        chunk = rows[i:i + COLS]
        cells = []
        for name, _title, has_png in chunk:
            png = rel(f"carrier/renders/{name}.png")
            if has_png:
                cells.append(f"[<img src=\"{png}\" width=\"{THUMB_W}\" "
                             f"alt=\"{name}\">]({png})<br>**{name}**")
            else:
                cells.append(f"**{name}**<br>*(render pending)*")
        cells += [" "] * (COLS - len(chunk))
        L.append("| " + " | ".join(cells) + " |")
    L.append("")
    L.append("| sheet | description |")
    L.append("|---|---|")
    for name, title, has_png in rows:
        link = (f"[{name}]({rel(f'carrier/renders/{name}.png')})"
                if has_png else name)
        L.append(f"| {link} | {title.replace('|', '\\|')} |")
    L.append(END)
    return "\n".join(L)


def _compact_section(readme_dir: Path) -> str:
    """The COMPACT block (root README.md): block diagram inline + one line
    linking to the carrier README's full sheet gallery (no duplicated
    table)."""
    def rel(target: str) -> str:
        return os.path.relpath(REPO_ROOT / target, readme_dir)

    n = len(_sheet_rows())
    L: list[str] = [
        BEGIN,
        "<!-- GENERATED by `schgen gallery` — edits between these markers "
        "are overwritten -->",
        "## Generated schematics",
        "",
        f"`schgen board` regenerates the block diagram and all {n} carrier "
        "sheets,",
        "each passing the netlist, ERC and visual gates.",
        "",
        f'<img src="{rel("docs/block_diagram.svg")}" '
        f'alt="Generated block diagram" width="900">',
        "",
        f"See **[carrier/README.md]({rel('carrier/README.md')}#generated-"
        f"schematics)** for the full sheet gallery (thumbnails + "
        f"descriptions).",
        END,
    ]
    return "\n".join(L)


def _splice(readme: Path, section: str) -> bool:
    """Replace the marked section (or append it). True if the file changed."""
    text = readme.read_text() if readme.exists() else ""
    if BEGIN in text and END in text:
        head, _, rest = text.partition(BEGIN)
        _, _, tail = rest.partition(END)
        new = head + section + tail
    else:
        new = text.rstrip("\n") + ("\n\n" if text.strip() else "") \
            + section + "\n"
    if new != text:
        readme.write_text(new)
        return True
    return False


def generate() -> list[Path]:
    """De-duplicated: the FULL gallery goes ONLY into carrier/README.md
    (next to the renders); the root README.md gets the COMPACT block."""
    changed = []
    root = REPO_ROOT / "README.md"
    carrier = REPO_ROOT / "carrier" / "README.md"
    if _splice(root, _compact_section(root.parent)):
        changed.append(root)
    if _splice(carrier, _full_section(carrier.parent)):
        changed.append(carrier)
    return changed


def cmd_gallery(args: argparse.Namespace) -> int:
    changed = generate()
    n = len(_sheet_rows())
    which = (", ".join(str(p.relative_to(REPO_ROOT)) for p in changed)
             or "unchanged")
    print(f"GALLERY: {n} sheets -> README.md + carrier/README.md ({which})")
    return 0
