"""Generated bring-up manual (PLAN.md round 4).

``schgen manual`` (also run by ``schgen board``) writes
``carrier/docs/BRINGUP.md`` — the ordered bring-up procedure DERIVED from
the authored netlists (DIP positions, EN cells, regulator chain, module
load switches, monitors, debug headers all read programmatically via
:mod:`schgen.bringup_facts`); narrative context (current budgets, PD
behaviour, decode tables) is cited to its dossier per section. The manual
cannot drift from the board: regenerating after a netlist change rewrites
every derived fact.

Deterministic: same inputs -> byte-identical output (no timestamps).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from schgen import bringup_facts as bf
from schgen.link import all_subsystem_paths, load_subsystem
from schgen.model import Circuit

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "carrier" / "docs" / "BRINGUP.md"

# PLAN.md round-2 locked input contract (cited, not derived):
PD_CONTRACT = "20 V / 3 A (60 W) USB-C PD"
# power_mon dossier table 1 rail budgets (cited):
RAIL_BUDGET_MA = {"+5V": 3000, "+3V3": 3000, "+1V8": 600, "+VIN": 3000}


def _load_all() -> dict[str, Circuit]:
    return {p.stem: load_subsystem(p.stem).circuit
            for p in all_subsystem_paths()}


def _test_points(circuits: dict[str, Circuit]) -> dict[str, list[str]]:
    """net -> ['sheet.TP1', ...] for any landed test points (a sheet part
    with a TP reference prefix or a TestPoint lib symbol)."""
    tps: dict[str, list[str]] = {}
    for name, c in sorted(circuits.items()):
        for ref, part in sorted(c.parts.items()):
            if not (ref.startswith("TP") or "TestPoint" in part.lib_id):
                continue
            for net in c.nets.values():
                if any(pr.ref == ref for pr in net.pins):
                    tps.setdefault(net.name, []).append(f"{name}.{ref}")
    return tps


def _probe(net: str, tps: dict[str, list[str]]) -> str:
    if net in tps:
        return " / ".join(tps[net])
    return f"net `{net}` (no test point landed yet)"


def _always_on(circuits: dict[str, Circuit]) -> list[tuple[str, str]]:
    """(sheet, 'U1 FUSB302BMPX, ...') for every IC powered from +3V3_SC."""
    rows = []
    for name, c in sorted(circuits.items()):
        if name.startswith("som_j"):
            continue                       # the connectors themselves
        refs = []
        for net in c.nets.values():
            if net.name != "+3V3_SC":
                continue
            for pr in net.pins:
                if pr.ref.startswith("U") and pr.ref not in refs:
                    refs.append(pr.ref)
        if refs:
            refs.sort(key=lambda r: (r[0], int(r[1:])
                                     if r[1:].isdigit() else 0))
            rows.append((name, ", ".join(f"{r} ({c.parts[r].value})"
                                         for r in refs)))
    return rows


def _consumers(circuits: dict[str, Circuit], rail: str,
               exclude: tuple[str, ...]) -> list[str]:
    out = []
    for name, c in sorted(circuits.items()):
        if name in exclude:
            continue
        if rail in c.nets:
            out.append(name)
    return out


def generate(out: Path = DEFAULT_OUT) -> Path:
    circuits = _load_all()
    rails_c = circuits["bringup_rails"]
    power_c = circuits["power"]
    chain = bf.regulator_chain(power_c)
    rail_cells = {c.enable: c for c in bf.en_cells(circuits["bringup_en"])}
    mod_cells = {c.enable: c
                 for c in bf.en_cells(circuits["bringup_en_modules"])}
    gates = bf.module_gates(circuits["bringup_modules"])
    exp = bf.expander(rails_c)
    monitors = bf.ina3221_monitors(circuits["power_mon"])
    dip_map = {ref: bf.dip_positions(rails_c, ref)
               for ref in bf.dip_switch_refs(rails_c)}
    dip_of = {p.net: (p.switch, p.position)
              for ps in dip_map.values() for p in ps}
    boot_dip = bf.dip_positions(circuits["debug_boot"], "SW1")
    tps = _test_points(circuits)
    stm32 = bf.stm32_pin_map()

    # monitor channel per rail: rail (IN- side) -> (monitor index, channel)
    mon_of: dict[str, str] = {}
    for k, m in enumerate(monitors, 1):
        for ch, (inp, inn) in sorted(m.channels.items()):
            if inn != "GND":
                mon_of[inn] = (f"INA3221 #{k} (0x{m.addr:02X}) ch{ch} "
                               f"[{inp} -> {inn}]")

    L: list[str] = []
    L.append("# Zynq carrier bring-up manual")
    L.append("")
    L.append("> GENERATED by `schgen manual` (schgen/manual.py) — DO NOT "
             "EDIT.")
    L.append("> Regenerate: `PYTHONPATH=. python -m schgen manual`. Every "
             "switch")
    L.append("> position, net, voltage, limit and address below is read "
             "from the")
    L.append("> authored netlists in `carrier/subsystems/` at generation "
             "time;")
    L.append("> narrative context cites its research dossier per section.")
    L.append("")
    L.append("Bring-up is staged (carrier/PLAN.md): the board must come up "
             "with")
    L.append("**switches only** — rails first, one at a time, then user IO, "
             "then each")
    L.append("module behind its own current-limited load switch. A blank "
             "(unprogrammed)")
    L.append("system controller is fine for every stage: all software "
             "overrides are")
    L.append("vetoes that default to \"DIP rules\" "
             "(carrier/research/bringup_power_gating.md, section 1).")
    L.append("")

    # ---- stage 0 ---------------------------------------------------------------
    L.append("## Stage 0 — power-off checks")
    L.append("")
    L.append("Sources: `carrier/subsystems/pd_input.py`, "
             "`carrier/subsystems/bringup_rails.py`,")
    L.append("`carrier/subsystems/debug_boot.py`, "
             "`carrier/research/bringup_power_gating.md`.")
    L.append("")
    dips_desc = ", ".join(f"`bringup_rails.{ref}` ({len(ps)} wired "
                          f"positions)" for ref, ps in sorted(dip_map.items()))
    L.append(f"1. **All DIPs OPEN.** Bring-up DIPs {dips_desc},")
    L.append(f"   boot-request DIP `debug_boot.SW1` "
             f"({len(boot_dip)} positions) — every position open.")
    L.append("2. **No dead shorts.** With the board unpowered, check "
             "continuity to `GND` on:")
    rails_to_check = ["+VIN"] + [st.rail_out for st in chain] \
        + sorted({g.rail_out for g in gates}) + ["+3V3_SC"]
    L.append("   " + ", ".join(f"`{r}`" for r in rails_to_check) + ".")
    L.append("   None may read as a short (the TVS `pd_input.D1` on `+VIN` "
             "conducts only")
    L.append("   above its 22 V standoff — a diode-mode reading there is "
             "normal, a dead")
    L.append("   short is not).")
    L.append("3. **Mating check.** SoM seated on J1/J2/J3 (DF40 stack); "
             "no probe wires under")
    L.append("   the module.")
    L.append("")

    # ---- stage 1: first power -------------------------------------------------
    L.append("## Stage 1 — first power: PD negotiation, always-on domain")
    L.append("")
    L.append("Sources: `carrier/subsystems/pd_input.py`, "
             "`carrier/subsystems/usb_pd.py`,")
    L.append("`carrier/research/bringup_power_gating.md` (risk R1), "
             "`carrier/research/power_mon.md`.")
    L.append("")
    L.append(f"Plug a {PD_CONTRACT}-capable supply into the power USB-C "
             f"(`pd_input.J1`). The")
    L.append("board boots on the **default 5 V** USB-C contract; the SoM "
             "generates the")
    L.append("always-on `+3V3_SC` rail from VIN **before** PD negotiation "
             "and before any")
    L.append("carrier rail. The FUSB302B (`usb_pd.U1`, I2C `0x22`) and the "
             "whole bring-up")
    L.append("infrastructure run from `+3V3_SC` for exactly this reason — "
             "PD must negotiate")
    L.append("with every DIP open.")
    L.append("")
    L.append("**Source requirement (SEQ-3).** The 5 V default contract must "
             "supply at least")
    L.append("**3 A at 5 V (>= 15 W)** for the board to come up: the SoM's "
             "pre-PD draw is")
    L.append("~2.2 A on 5 V before any higher-voltage contract is "
             "negotiated. A weak 5 V")
    L.append("charger (e.g. a 0.5-1.5 A phone brick) will brown out / fail "
             "to boot — use a")
    L.append("USB-C source that advertises >= 3 A at 5 V (`pd_input.py`).")
    L.append("")
    L.append("With **all DIPs open**, expect:")
    L.append("")
    L.append(f"- `+VIN` stays at the **5 V default contract** at first power "
             f"and the board")
    L.append("  runs **reduced on 5 V**. The FUSB302B is a PD **PHY only** — "
             "it does NOT")
    L.append("  negotiate by itself; reaching the negotiated "
             f"{PD_CONTRACT} contract requires")
    L.append("  the **SoM system-controller PD-policy firmware** to drive "
             "the FUSB302B through")
    L.append("  the higher-voltage Request. Until the SC runs that policy, "
             "`+VIN` remains at")
    L.append("  5 V (a blank SC = 5 V VIN, board reduced-functional).")
    L.append(f"- Probe: {_probe('+VIN', tps)}.")
    L.append("- Every rail PG LED **off** ("
             + ", ".join(f"`power.{st.pg_led}`" for st in chain)
             + "), every module status LED off.")
    L.append("- The always-on `+3V3_SC` domain is alive (probe: "
             + _probe("+3V3_SC", tps) + "):")
    L.append("")
    L.append("  | sheet | ICs on `+3V3_SC` |")
    L.append("  |---|---|")
    for sheet, ics in _always_on(circuits):
        L.append(f"  | {sheet} | {ics} |")
    L.append("")
    L.append("Rail telemetry is already live at this point: "
             + "/".join(f"`0x{m.addr:02X}`" for m in monitors)
             + " (INA3221, "
             + "/".join(f"`power_mon.{m.ref}`" for m in monitors)
             + ") answer on `STM32_I2C2` with every")
    L.append("monitored rail still down (`carrier/research/power_mon.md` "
             "section 2).")
    L.append("")

    # ---- stage 2: rails ---------------------------------------------------------
    L.append("## Stage 2 — rails, one DIP at a time")
    L.append("")
    L.append("Sources: `carrier/subsystems/bringup_rails.py` (SW1 map), "
             "`carrier/subsystems/bringup_en.py`")
    L.append("(EN cells), `carrier/subsystems/power.py` (regulator chain), "
             "`carrier/subsystems/power_mon.py`")
    L.append("(shunts/monitors), `carrier/research/power_mon.md` (budgets).")
    L.append("")
    L.append("The sequence below is the regulator chain read from the "
             "power netlist —")
    L.append("each stage's input is the previous stage's output, so the "
             "order is not")
    L.append("optional. Close one DIP, verify, then move on. (A "
             "downstream DIP closed")
    L.append("early is benign: its regulator simply has no input yet.)")
    L.append("")
    for k, st in enumerate(chain, 1):
        cell = rail_cells[st.enable]
        sw, pos = dip_of[cell.dip_net]
        budget = RAIL_BUDGET_MA.get(st.rail_out)
        vout = f"{st.vout:.2f} V" if st.vout is not None else "?"
        L.append(f"### 2.{k} `{st.rail_out}` — close `bringup_rails.{sw}` "
                 f"position {pos}")
        L.append("")
        L.append(f"- Path: `{st.rail_in}` -> `power.{st.ref}` "
                 f"({st.value}) -> `{st.rail_out}`.")
        L.append(f"- EN cell: `{cell.sheet}.{cell.gate}` — "
                 f"`{cell.dip_net}` AND `{cell.override_net}` -> "
                 f"`{st.enable}`. A blank SC leaves the override pulled "
                 f"high (veto inactive).")
        L.append(f"- Expect **{vout}** on `{st.rail_out}` "
                 f"(setpoint derived from the netlist: "
                 + ("fixed-output LDO" if "AP2112" in st.value else
                    "FB divider vs the TPS54302 0.596 V reference")
                 + f"). Probe: {_probe(st.rail_out, tps)}.")
        L.append(f"- PG LED `power.{st.pg_led}` lights"
                 + (" (FET-sensed: a red LED cannot run from 1.8 V, so "
                    "Q1 senses the rail — power.py)" if
                    st.rail_out == "+1V8" else "") + ".")
        if budget:
            L.append(f"- Current-limit context: rail budget "
                     f"{budget / 1000:g} A "
                     f"(power_mon dossier table 1; the regulator is the "
                     f"limit — no rail fuse).")
        mon = mon_of.get(st.rail_out)
        if mon:
            L.append(f"- Telemetry: {mon}.")
        L.append("")

    # ---- stage 3: user IO -------------------------------------------------------
    user_gate = next((g for g in gates if g.module == "USER_LED"), None)
    if user_gate is not None:
        cell = mod_cells[user_gate.enable]
        sw, pos = dip_of[cell.dip_net]
        L.append(f"## Stage 3 — user LEDs: close `bringup_rails.{sw}` "
                 f"position {pos}")
        L.append("")
        L.append("Sources: `carrier/subsystems/bringup_modules.py`, "
                 "`carrier/subsystems/user_io.py`.")
        L.append("")
        L.append(f"- The rail DIP's spare position gates "
                 f"`{user_gate.rail_out}` through "
                 f"`bringup_modules.{user_gate.ref}` "
                 f"(SY6280, ILIM {user_gate.ilim_ma} mA).")
        L.append(f"- Status LED `bringup_modules.{user_gate.status_led}` "
                 f"lights; the user LEDs themselves are PL-driven "
                 f"(active-LOW) and stay dark until gateware drives them.")
        L.append("")

    # ---- stage 4: modules --------------------------------------------------------
    L.append("## Stage 4 — module load switches, one DIP at a time")
    L.append("")
    L.append("Sources: `carrier/subsystems/bringup_rails.py` (SW2/SW6 "
             "maps), `carrier/subsystems/bringup_en_modules.py`,")
    L.append("`carrier/subsystems/bringup_modules.py` (SY6280 cells; "
             "ILIM = 6800 / RSET per the Silergy DS).")
    L.append("")
    L.append("Each module rail is current-limited and folds back on a "
             "fault instead of")
    L.append("dragging the source rail down — a sagging status LED points "
             "at the faulty")
    L.append("module. Close one position, watch the status LED, check the "
             "module's sheet.")
    L.append("")
    L.append("| close | module | source | gated rail | ILIM | status LED | "
             "consumer sheets |")
    L.append("|---|---|---|---|---|---|---|")
    bringup_sheets = ("bringup_modules", "bringup_rails", "bringup_en",
                      "bringup_en_modules", "power", "power_mon")
    for g in gates:
        cell = mod_cells.get(g.enable)
        if cell is None or cell.dip_net not in dip_of:
            continue
        sw, pos = dip_of[cell.dip_net]
        if g.module == "USER_LED":
            continue                      # stage 3 above (SW1 spare)
        cons = _consumers(circuits, g.rail_out, bringup_sheets)
        L.append(f"| `{sw}` pos {pos} | {g.module} | `{g.rail_in}` | "
                 f"`{g.rail_out}` | {g.ilim_ma} mA | "
                 f"`bringup_modules.{g.status_led}` | "
                 + (", ".join(cons) if cons else "—") + " |")
    spare = next((c for c in mod_cells.values()
                  if c.enable == "EN_LCD_BL"), None)
    if spare is not None and spare.dip_net in dip_of:
        sw, pos = dip_of[spare.dip_net]
        bit = next((p for p, n in exp.ports.items()
                    if n == spare.override_net), "?")
        L.append("")
        L.append(f"`{sw}` position {pos} is the `EN_LCD_BL` provision: its "
                 f"override rides TCA9535 `{bit}`")
        L.append("through a 100k pull-DOWN, so it stays OFF until SC "
                 "software raises it")
        L.append("(`carrier/subsystems/bringup_rails.py`).")
    L.append("")
    L.append("Software vetoes for the module cells live on the "
             f"TCA9535 expander at I2C `0x{exp.addr:02X}`")
    L.append("(`bringup_rails.{}`; POR state = all inputs = DIP rules). "
             "Port map is generated".format(exp.ref))
    L.append("into `carrier/firmware/zynq_carrier_contract.h` (`schgen "
             "firmware`).")
    L.append("")

    # ---- stage 5: boot + debug -----------------------------------------------------
    L.append("## Stage 5 — boot modes, JTAG, SWD")
    L.append("")
    L.append("Sources: `carrier/subsystems/debug_boot.py`, "
             "`carrier/research/debug_boot_pmod.md`")
    L.append("(all J1 nets verified against the SoM netlist), live U9 pin "
             "extraction (`schgen/bringup_facts.py`).")
    L.append("")
    L.append("### Boot-request DIP (`debug_boot.SW1`)")
    L.append("")
    L.append("The Zynq boot straps live ON the SoM and are driven by the "
             "SC; the carrier")
    L.append("only *requests* a mode. Decode (dossier section (c)): "
             "`BOOTSEL[1:0]` =")
    L.append("`00` JTAG, `01` QSPI, `10` SD, `11` reserved — closed DIP = "
             "LOW.")
    L.append("")
    L.append("| position | net | function |")
    L.append("|---|---|---|")
    boot_fn = {
        "STM32_BOOT0": "closed + reset = STM32 USB DFU (100R vs the SoM "
                       "1k5 pull-down)",
        "STM32_GPIO7": "BOOTSEL0 request strap (10k pull-up to +3V3_SC)",
        "STM32_GPIO8": "BOOTSEL1 request strap (10k pull-up to +3V3_SC)",
        "BOOT_SPARE": "spare (defined-high, reserved)",
    }
    for p in boot_dip:
        L.append(f"| {p.position} | `{p.net}` | "
                 f"{boot_fn.get(p.net, p.net)} |")
    L.append("")
    L.append("### Reset")
    L.append("")
    L.append("`debug_boot.SW2` (and `bringup_rails.SW5`) pull `STM32_NRST` "
             "low — resetting")
    L.append("the SC re-runs its power/boot supervision = whole-system "
             "reset (the SoM owns")
    L.append("the RC debounce).")
    L.append("")
    L.append("### SWD first (works with main rails down)")
    L.append("")
    swd = {n: stm32["nets"][n] for n in ("STM32_GPIO6", "STM32_GPIO5")}
    L.append("ARM 10-pin 1.27 mm header `debug_boot.J2`; VTref = "
             "`+3V3_SC`, so the SC")
    L.append("debugs with every carrier rail off — bring up the SC "
             "firmware before any")
    L.append("DIP is closed. " + "; ".join(
        f"`{n}` (J1.{e.j_pins[0].split('.')[1]}) = P{e.port}{e.pin}"
        for n, e in sorted(swd.items())) + ".")
    L.append("**PA13/PA14 are reserved for SWD** — SC firmware must never "
             "reconfigure them")
    L.append("(`carrier/research/debug_boot_pmod.md` section 0).")
    L.append("")
    L.append("### Zynq JTAG")
    L.append("")
    L.append("Xilinx 2x7 2 mm header `debug_boot.J1`; VREF pin 2 = `+3V3` "
             "(= VCCO_0), so")
    L.append("JTAG needs the `+3V3` rail up (stage 2). TMS/TDI carry 4k7 "
             "insurance")
    L.append("pull-ups (`debug_boot.R1/R2`). Header pin 14 (SRST) is NC — "
             "the SoM does not")
    L.append("export PS_SRST_B; debugger-initiated PS resets go through "
             "the SC (dossier (a)).")
    L.append("")
    L.append("After JTAG enumerates: request boot modes via the BOOTSEL "
             "DIP + SC reset and")
    L.append("verify QSPI/SD boots per the decode table above.")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    return out


def cmd_manual(args: argparse.Namespace) -> int:
    out = generate(getattr(args, "output", None) or DEFAULT_OUT)
    lines = out.read_text().count("\n")
    print(f"BRINGUP MANUAL: {out} ({lines} lines)")
    return 0
