"""TPS54331DDAR — TPS54331DDAR (SOIC-8_L4.9-W3.9-P1.27-LS6.0-BL-EP)

Generated by `schgen part add C90761` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPS54331DDAR'
SAFE_NAME = 'TPS54331DDAR'
LCSC = 'C90761'
DESCRIPTION = 'TPS54331DDAR (SOIC-8_L4.9-W3.9-P1.27-LS6.0-BL-EP)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'SOIC-8_L4.9-W3.9-P1.27-LS6.0-BL-EP'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C90761.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/DC-DC-Converters_TI_TPS54331DDAR_TPS54331DDAR_C90761.html'
LIB_ID = 'TPS54331DDAR:TPS54331DDAR'
FOOTPRINT = 'TPS54331DDAR:TPS54331DDAR'
MODELS_3D = ['TPS54331DDAR.wrl', 'TPS54331DDAR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'BOOT', 'passive'),
    ('2', 'VIN', 'power_in'),
    ('3', 'EN', 'passive'),
    ('4', 'SS', 'passive'),
    ('5', 'VSENSE', 'passive'),
    ('6', 'COMP', 'passive'),
    ('7', 'GND', 'power_in'),
    ('8', 'PH', 'power_in'),
    ('9', 'EP', 'power_in'),
]
