"""CH347T — CH347T (TSSOP-20_L6.5-W4.4-P0.65-LS6.4-BL)

Generated by `schgen part add C5122332` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'CH347T'
SAFE_NAME = 'CH347T'
LCSC = 'C5122332'
DESCRIPTION = 'CH347T (TSSOP-20_L6.5-W4.4-P0.65-LS6.4-BL)'
MANUFACTURER = 'WCH(南京沁恒)'
PACKAGE = 'TSSOP-20_L6.5-W4.4-P0.65-LS6.4-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C5122332.pdf'
PRODUCT_URL = ''
LIB_ID = 'CH347T:CH347T'
FOOTPRINT = 'CH347T:CH347T'
MODELS_3D = ['CH347T.wrl', 'CH347T.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'RST#', 'passive'),
    ('2', 'CTS1/GPIO6', 'passive'),
    ('3', 'TXD1', 'passive'),
    ('4', 'RXD1', 'passive'),
    ('5', 'DSR0/GPIO2/SCS0/TMS', 'passive'),
    ('6', 'CTS0/GPIO0/SCK/TCK', 'passive'),
    ('7', 'RTS0/GPIO1/MISO/TDO', 'passive'),
    ('8', 'TXD0/MOSI/TDI', 'passive'),
    ('9', 'TNOW0/DTR0/GPIO5/SCS1/TRST', 'passive'),
    ('10', 'TNOW1/DTR1', 'passive'),
    ('11', 'RI0/GPIO3/SCL', 'passive'),
    ('12', 'RXD0/SDA', 'passive'),
    ('13', 'RTS1/GPIO7', 'passive'),
    ('14', 'VCC', 'passive'),
    ('15', 'DCD0/GPIO4/ACT', 'passive'),
    ('16', 'UD-', 'passive'),
    ('17', 'UD+', 'passive'),
    ('18', 'GND', 'passive'),
    ('19', 'XI', 'passive'),
    ('20', 'XO', 'passive'),
]
