"""RV-3028-C7-32.768kHz-1ppm-TA-QC — RV-3028-C7 32.768KHZ 1PPM TA QC (OSC-SMD_8P-L3.2-W1.5-P0.90-BL)

Generated by `schgen part add C3019759` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'RV-3028-C7-32.768kHz-1ppm-TA-QC'
SAFE_NAME = 'RV-3028-C7-32.768kHz-1ppm-TA-QC'
LCSC = 'C3019759'
DESCRIPTION = 'RV-3028-C7 32.768KHZ 1PPM TA QC (OSC-SMD_8P-L3.2-W1.5-P0.90-BL)'
MANUFACTURER = 'Micro Crystal(瑞士微晶)'
PACKAGE = 'OSC-SMD_8P-L3.2-W1.5-P0.90-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C3019759.pdf'
PRODUCT_URL = ''
LIB_ID = 'RV-3028-C7-32.768kHz-1ppm-TA-QC:RV-3028-C7-32.768kHz-1ppm-TA-QC'
FOOTPRINT = 'RV-3028-C7-32.768kHz-1ppm-TA-QC:RV-3028-C7-32.768kHz-1ppm-TA-QC'
MODELS_3D = ['RV-3028-C7-32.768kHz-1ppm-TA-QC.wrl', 'RV-3028-C7-32.768kHz-1ppm-TA-QC.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'CLKOUT', 'passive'),
    ('2', 'INT#', 'passive'),
    ('3', 'SCL', 'passive'),
    ('4', 'SDA', 'passive'),
    ('5', 'VSS', 'passive'),
    ('6', 'VBACKUP', 'passive'),
    ('7', 'VDD', 'passive'),
    ('8', 'EVI', 'passive'),
]
