"""TPS54302DDCR — TPS54302DDCR_C311983 (SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BL)

Generated by `schgen part add C311983` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPS54302DDCR'
SAFE_NAME = 'TPS54302DDCR'
LCSC = 'C311983'
DESCRIPTION = 'TPS54302DDCR_C311983 (SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BL)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C311983.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Others_Texas-Instruments_TPS54302DDCR_Texas-Instruments-TI-TPS54302DDCR_C311983.html'
LIB_ID = 'TPS54302DDCR:TPS54302DDCR'
FOOTPRINT = 'TPS54302DDCR:TPS54302DDCR'
MODELS_3D = ['TPS54302DDCR.wrl', 'TPS54302DDCR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'GND', 'passive'),
    ('2', 'SW', 'passive'),
    ('3', 'VIN', 'passive'),
    ('4', 'FB', 'passive'),
    ('5', 'EN', 'passive'),
    ('6', 'BOOT', 'passive'),
]
