"""TPS3823-33DBVR — TPS3823-33DBVR (SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BL)

Generated by `schgen part add C7719` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TPS3823-33DBVR'
SAFE_NAME = 'TPS3823-33DBVR'
LCSC = 'C7719'
DESCRIPTION = 'TPS3823-33DBVR (SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BL)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'SOT-23-5_L3.0-W1.7-P0.95-LS2.8-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C7719.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Microprocessor-Microcontroller-Supervisors_TI_TPS3823-33DBVR_TPS3823-33DBVR_C7719.html'
LIB_ID = 'TPS3823-33DBVR:TPS3823-33DBVR'
FOOTPRINT = 'TPS3823-33DBVR:TPS3823-33DBVR'
MODELS_3D = ['TPS3823-33DBVR.wrl', 'TPS3823-33DBVR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'RESET#', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'MR#', 'passive'),
    ('4', 'WDI', 'passive'),
    ('5', 'VDD', 'passive'),
]
