include_guard(GLOBAL)

# The source gate consumes this build's actual production compile commands.
# No accepted findings, source snapshots or bypass switches are generated.
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
get_filename_component(_schgen_compiler_directory "${CMAKE_CXX_COMPILER}" DIRECTORY)
find_library(SCHGEN_LIBCLANG NAMES clang libclang
    HINTS "${_schgen_compiler_directory}/../lib" /opt/homebrew/opt/llvm/lib)
if(NOT SCHGEN_LIBCLANG)
    message(FATAL_ERROR "Native authoring verification requires libclang; configure SCHGEN_LIBCLANG to its library path")
endif()

function(schgen_purity_json_string input output)
    string(REPLACE "\\" "\\\\" value "${input}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

schgen_purity_json_string("${CMAKE_CXX_COMPILER}" _schgen_purity_compiler)
schgen_purity_json_string("${SCHGEN_LIBCLANG}" _schgen_purity_library)
schgen_purity_json_string("${CMAKE_BINARY_DIR}/compile_commands.json" _schgen_purity_commands)
set(_schgen_purity_includes "")
set(SCHGEN_PURITY_TEST_SYSTEM_ARGUMENTS "")
set(SCHGEN_PURITY_SYSTEM_DIRECTORIES "")
foreach(directory IN LISTS CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES)
    if(IS_DIRECTORY "${directory}")
        schgen_purity_json_string("${directory}" quoted)
        if(NOT _schgen_purity_includes STREQUAL "")
            string(APPEND _schgen_purity_includes ",")
        endif()
        string(APPEND _schgen_purity_includes "${quoted}")
        list(APPEND SCHGEN_PURITY_TEST_SYSTEM_ARGUMENTS --system "${directory}")
        list(APPEND SCHGEN_PURITY_SYSTEM_DIRECTORIES "${directory}")
    endif()
endforeach()
if(_schgen_purity_includes STREQUAL "")
    message(FATAL_ERROR "Compiler supplied no usable system include roots for native authoring verification")
endif()
set(SCHGEN_AUTHORING_PURITY_CONFIGURATION "${CMAKE_CURRENT_BINARY_DIR}/native-authoring-toolchain.json")
file(GENERATE OUTPUT "${SCHGEN_AUTHORING_PURITY_CONFIGURATION}" CONTENT
"{\n  \"schema\": \"schgen.authoring-purity.toolchain.v1\",\n  \"compiler\": ${_schgen_purity_compiler},\n  \"libclang\": ${_schgen_purity_library},\n  \"compile_commands\": ${_schgen_purity_commands},\n  \"production_targets\": [\"schgen_core\",\"schgen\"],\n  \"system_include_directories\": [${_schgen_purity_includes}]\n}\n")
