include_guard(GLOBAL)

function(schgen_register_subsystem_package name)
    if(NOT DEFINED _schgen_expected_package OR NOT "${name}" STREQUAL "${_schgen_expected_package}")
        message(FATAL_ERROR "Subsystem registration is only valid inside explicit package selection")
    endif()
    get_property(registered TARGET "${_schgen_package_target}" PROPERTY SCHGEN_PACKAGE_NAMES)
    if("${name}" IN_LIST registered)
        message(FATAL_ERROR "Duplicate subsystem package registration: ${name}")
    endif()
    foreach(asset "${name}.cpp" "${name}.hpp" "test_${name}.cpp" "${name}.cir" README.md subsystem.json)
        if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${asset}" OR IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${asset}")
            message(FATAL_ERROR "Missing native subsystem asset: ${CMAKE_CURRENT_SOURCE_DIR}/${asset}")
        endif()
    endforeach()
    target_sources("${_schgen_package_target}" PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/${name}.cpp")
    set_property(TARGET "${_schgen_package_target}" APPEND PROPERTY SCHGEN_PACKAGE_NAMES "${name}")
    set_property(TARGET "${_schgen_package_target}" APPEND PROPERTY SCHGEN_PACKAGE_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/${name}.hpp")
    if(BUILD_TESTING)
        add_executable("schgen_subsystem_${name}_test" "${CMAKE_CURRENT_SOURCE_DIR}/test_${name}.cpp")
        target_link_libraries("schgen_subsystem_${name}_test" PRIVATE "${_schgen_package_target}")
        target_compile_features("schgen_subsystem_${name}_test" PRIVATE cxx_std_17)
        target_compile_options("schgen_subsystem_${name}_test" PRIVATE -Wall -Wextra -Wpedantic -Werror -ffp-contract=off)
        add_test(NAME "native_subsystem_${name}" COMMAND "schgen_subsystem_${name}_test"
            "${_schgen_package_repository}" "${SCHGEN_SUBSYSTEM_PART_CATALOG}")
    endif()
endfunction()

function(schgen_configure_subsystem_packages target repository)
    get_property(already TARGET "${target}" PROPERTY SCHGEN_PACKAGES_CONFIGURED)
    if(already)
        message(FATAL_ERROR "Subsystem packages already configured for ${target}")
    endif()
    set_property(TARGET "${target}" PROPERTY SCHGEN_PACKAGES_CONFIGURED TRUE)
    get_filename_component(_schgen_package_repository "${repository}" ABSOLUTE)
    set(SCHGEN_SUBSYSTEM_PACKAGES "" CACHE STRING "Explicit native subsystem package names (semicolon separated)")
    set(SCHGEN_SUBSYSTEM_LIBRARY_ROOT "${_schgen_package_repository}/subsystems" CACHE PATH "Native subsystem asset library")
    set(SCHGEN_SUBSYSTEM_PART_CATALOG "${_schgen_package_repository}/native/catalog.bin" CACHE FILEPATH "Existing live part catalog for local tests")
    if(NOT SCHGEN_SUBSYSTEM_PACKAGES)
        return()
    endif()
    set(_schgen_package_target "${target}")
    set(seen "")
    foreach(name IN LISTS SCHGEN_SUBSYSTEM_PACKAGES)
        string(LENGTH "${name}" name_length)
        if(NOT name MATCHES "^[a-z][a-z0-9_]*$" OR name MATCHES "__" OR name_length GREATER 63 OR
           name MATCHES "^(con|prn|aux|nul|com[1-9]|lpt[1-9])$")
            message(FATAL_ERROR "Invalid portable subsystem package name: ${name}")
        endif()
        if("${name}" IN_LIST seen)
            message(FATAL_ERROR "Duplicate selected subsystem package: ${name}")
        endif()
        list(APPEND seen "${name}")
        set(package "${SCHGEN_SUBSYSTEM_LIBRARY_ROOT}/${name}")
        if(NOT IS_DIRECTORY "${package}" OR IS_SYMLINK "${package}" OR NOT EXISTS "${package}/CMakeLists.txt")
            message(FATAL_ERROR "Missing native subsystem package: ${package}")
        endif()
        if(package MATCHES "[\";\n\r]")
            message(FATAL_ERROR "Unsupported character in native package path")
        endif()
        set(_schgen_expected_package "${name}")
        add_subdirectory("${package}" "${CMAKE_CURRENT_BINARY_DIR}/subsystem-packages/${name}")
        get_property(registered TARGET "${target}" PROPERTY SCHGEN_PACKAGE_NAMES)
        if(NOT "${name}" IN_LIST registered)
            message(FATAL_ERROR "Package did not explicitly register a live factory: ${name}")
        endif()
    endforeach()
    get_property(headers TARGET "${target}" PROPERTY SCHGEN_PACKAGE_HEADERS)
    set(header "#pragma once\n#include \"schgen/subsystem_authoring.hpp\"\n")
    foreach(path IN LISTS headers)
        file(TO_CMAKE_PATH "${path}" path)
        string(APPEND header "#include \"${path}\"\n")
    endforeach()
    string(APPEND header "namespace schgen {\ninline std::vector<SubsystemDefinition> configured_subsystem_packages() {\nreturn {\n")
    foreach(name IN LISTS registered)
        string(APPEND header "subsystem_packages::define_${name}(),\n")
    endforeach()
    string(APPEND header "};\n}\n}\n")
    set(generated "${CMAKE_CURRENT_BINARY_DIR}/subsystem-registration")
    file(MAKE_DIRECTORY "${generated}")
    file(CONFIGURE OUTPUT "${generated}/schgen_configured_subsystems.hpp" CONTENT "${header}" @ONLY)
    target_include_directories("${target}" PRIVATE "${generated}")
    target_compile_definitions("${target}" PRIVATE SCHGEN_CONFIGURED_SUBSYSTEMS=1)
endfunction()
