"""SMBJ28A — SMBJ28A_C42440491 (DO-214AA_L5.6-W4.0-RD)

Generated by `schgen part add C42440491` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'SMBJ28A'
SAFE_NAME = 'SMBJ28A'
LCSC = 'C42440491'
DESCRIPTION = 'SMBJ28A_C42440491 (DO-214AA_L5.6-W4.0-RD)'
MANUFACTURER = 'TECH PUBLIC(台舟)'
PACKAGE = 'DO-214AA_L5.6-W4.0-RD'
JLC_CLASS = ''
PREFIX = 'D'
DATASHEET = 'https://www.lcsc.com/datasheet/C42440491.pdf'
PRODUCT_URL = ''
LIB_ID = 'SMBJ28A:SMBJ28A'
FOOTPRINT = 'SMBJ28A:SMBJ28A'
MODELS_3D = ['SMBJ28A.wrl', 'SMBJ28A.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('2', 'A', 'passive'),
    ('1', 'K', 'passive'),
]
