"""LM61460AANRJRR — LM61460AANRJRR (VQFN-HR-14_L4.0-W3.5-P0.50-TL_TI_RJR-1)

Generated by `schgen part add C2864505` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'LM61460AANRJRR'
SAFE_NAME = 'LM61460AANRJRR'
LCSC = 'C2864505'
DESCRIPTION = 'LM61460AANRJRR (VQFN-HR-14_L4.0-W3.5-P0.50-TL_TI_RJR-1)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'VQFN-HR-14_L4.0-W3.5-P0.50-TL_TI_RJR-1'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C2864505.pdf'
PRODUCT_URL = ''
LIB_ID = 'LM61460AANRJRR:LM61460AANRJRR'
FOOTPRINT = 'LM61460AANRJRR:LM61460AANRJRR'
MODELS_3D = ['LM61460AANRJRR.wrl', 'LM61460AANRJRR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'BIAS', 'passive'),
    ('2', 'VCC', 'passive'),
    ('3', 'AGND', 'passive'),
    ('4', 'FB', 'passive'),
    ('5', 'PGOOD', 'passive'),
    ('6', 'RT', 'passive'),
    ('7', 'EN/SYNC', 'passive'),
    ('8', 'VIN1', 'passive'),
    ('9', 'PGND1', 'passive'),
    ('10', 'SW', 'passive'),
    ('11', 'PGND2', 'passive'),
    ('12', 'VIN2', 'passive'),
    ('13', 'RBOOT', 'passive'),
    ('14', 'CBOOT', 'passive'),
]
