"""TLV75725PDYDR — TLV75725PDYDR (SOT-23-5_L2.8-W1.7-P0.95-BL-EP_TI_DYD)

Generated by `schgen part add C35209004` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TLV75725PDYDR'
SAFE_NAME = 'TLV75725PDYDR'
LCSC = 'C35209004'
DESCRIPTION = 'TLV75725PDYDR (SOT-23-5_L2.8-W1.7-P0.95-BL-EP_TI_DYD)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'SOT-23-5_L2.8-W1.7-P0.95-BL-EP_TI_DYD'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C35209004.pdf'
PRODUCT_URL = ''
LIB_ID = 'TLV75725PDYDR:TLV75725PDYDR'
FOOTPRINT = 'TLV75725PDYDR:TLV75725PDYDR'
MODELS_3D = ['TLV75725PDYDR.wrl', 'TLV75725PDYDR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'IN', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'EN', 'passive'),
    ('4', 'NC', 'passive'),
    ('5', 'OUT', 'passive'),
    ('6', 'EP', 'passive'),
]
