"""SFW15R-1STE1LF — SFW15R-1STE1LF (CONN-SMD_15P-P0.50_SFW15R-1STE1LF)

Generated by `schgen part add C3168538` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'SFW15R-1STE1LF'
SAFE_NAME = 'SFW15R-1STE1LF'
LCSC = 'C3168538'
DESCRIPTION = 'SFW15R-1STE1LF (CONN-SMD_15P-P0.50_SFW15R-1STE1LF)'
MANUFACTURER = 'Amphenol'
PACKAGE = 'CONN-SMD_15P-P0.50_SFW15R-1STE1LF'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C3168538.pdf'
PRODUCT_URL = ''
LIB_ID = 'SFW15R-1STE1LF:SFW15R-1STE1LF'
FOOTPRINT = 'SFW15R-1STE1LF:SFW15R-1STE1LF'
MODELS_3D = ['SFW15R-1STE1LF.wrl', 'SFW15R-1STE1LF.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('2', '2', 'passive'),
    ('3', '3', 'passive'),
    ('4', '4', 'passive'),
    ('5', '5', 'passive'),
    ('6', '6', 'passive'),
    ('7', '7', 'passive'),
    ('8', '8', 'passive'),
    ('9', '9', 'passive'),
    ('10', '10', 'passive'),
    ('11', '11', 'passive'),
    ('12', '12', 'passive'),
    ('13', '13', 'passive'),
    ('14', '14', 'passive'),
    ('15', '15', 'passive'),
    ('16', '16', 'passive'),
    ('17', '17', 'passive'),
]
