"""Carrier SoM J2 mate: PL bank 13 high-speed I/O.

J2 of the Zynq SoM carries the PL bank 13 SelectIO pins, which the
carrier uses for:

  * FMC LPC LA pairs (34 differential pairs)
  * FMC clocks (CLK0_M2C, CLK1_M2C)
  * LVDS LCD interface (4 data lanes + clock)
  * HDMI TX/RX TMDS pairs (3 data + clock each)

Pin map mostly mirrors the FMC and LVDS pin assignments — bank 13's
SelectIO standard (LVDS_25 / DIFF_SSTL18) governs the I/O level. The
full pin-by-pin assignment is generated by Stage 8's
``io_assignment.csv`` from the SoM's actual pinout.
"""

from __future__ import annotations

from zynq_eda.catalog.components import REFCIRCUITS
from zynq_eda.core.model.block import (
    Block,
    ConnectorInstance,
    GroundNet,
    PowerInputNet,
    SignalNet,
)
from zynq_eda.core.model.interface import SheetEdge


def build_som_j2() -> Block:
    return Block(
        name="som_j2",
        title="SoM Mate J2 (PL bank 13 high-speed I/O)",
        paper_size="A3",
        description=(
            "Carrier-side mate to the Zynq SoM J2 connector "
            "(FX10A-168P-SV-91). PL bank 13 SelectIO routes to FMC LPC, "
            "LVDS LCD, and HDMI TX/RX TMDS pairs."
        ),
        connectors=(
            ConnectorInstance(
                reference="J2",
                refcircuit=REFCIRCUITS["FX10A-168P-SV(91)"],
                lib_id="zynq_eda:FX10A_168P",
                edge=SheetEdge.LEFT,
                pin_to_net=_som_j2_pin_to_net(),
            ),
        ),
        external_nets=tuple(_som_j2_external_nets()),
    )


def _som_j2_external_nets():
    yield PowerInputNet("+VCCO_13", edge=SheetEdge.RIGHT)
    yield GroundNet("GND",          edge=SheetEdge.RIGHT)
    # FMC LA pairs (subset shown — full map in io_assignment.csv).
    for index in range(34):
        yield SignalNet(f"ZYNQ_FMC_LA{index:02d}_P", "bidirectional", edge=SheetEdge.RIGHT)
        yield SignalNet(f"ZYNQ_FMC_LA{index:02d}_N", "bidirectional", edge=SheetEdge.RIGHT)
    for label in ("CLK0_M2C_P", "CLK0_M2C_N", "CLK1_M2C_P", "CLK1_M2C_N"):
        yield SignalNet(f"ZYNQ_FMC_{label}", "input", edge=SheetEdge.RIGHT)
    # HDMI TMDS pairs (TX + RX)
    for direction in ("TX", "RX"):
        for lane in range(3):
            yield SignalNet(
                f"ZYNQ_HDMI_{direction}_TMDS_{lane}_P", "bidirectional",
                edge=SheetEdge.RIGHT,
            )
            yield SignalNet(
                f"ZYNQ_HDMI_{direction}_TMDS_{lane}_N", "bidirectional",
                edge=SheetEdge.RIGHT,
            )
        yield SignalNet(f"ZYNQ_HDMI_{direction}_TMDS_CLK_P", "bidirectional", edge=SheetEdge.RIGHT)
        yield SignalNet(f"ZYNQ_HDMI_{direction}_TMDS_CLK_N", "bidirectional", edge=SheetEdge.RIGHT)
    # LVDS LCD pairs
    for lane in range(4):
        yield SignalNet(f"ZYNQ_LCD_LVDS_DA{lane}_P", "output", edge=SheetEdge.RIGHT)
        yield SignalNet(f"ZYNQ_LCD_LVDS_DA{lane}_N", "output", edge=SheetEdge.RIGHT)
    yield SignalNet("ZYNQ_LCD_LVDS_CLK_P", "output", edge=SheetEdge.RIGHT)
    yield SignalNet("ZYNQ_LCD_LVDS_CLK_N", "output", edge=SheetEdge.RIGHT)


def _som_j2_pin_to_net() -> tuple[tuple[str, str], ...]:
    """Representative subset — full FMC + LVDS + HDMI pin schedule lives in io_assignment.csv."""
    pairs: list[tuple[str, str]] = [
        ("A1", "+VCCO_13"), ("A2", "+VCCO_13"),
        ("A3", "GND"),      ("A4", "GND"),
    ]
    base = 5
    for index in range(34):
        pairs.append((f"A{base + index * 2}",   f"ZYNQ_FMC_LA{index:02d}_P"))
        pairs.append((f"A{base + index * 2 + 1}", f"ZYNQ_FMC_LA{index:02d}_N"))
    return tuple(pairs)
