"""M24C02-WMN6TP — EEPROM

Generated by `schgen part add C7562` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'M24C02-WMN6TP'
SAFE_NAME = 'M24C02-WMN6TP'
LCSC = 'C7562'
DESCRIPTION = 'EEPROM'
MANUFACTURER = 'ST(意法半导体)'
PACKAGE = 'SOIC-8_L4.9-W3.9-P1.27-LS6.0-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C7562.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/EEPROM_STMicroelectronics_M24C02-WMN6TP_M24C02-WMN6TP_C7562.html'
LIB_ID = 'M24C02-WMN6TP:M24C02-WMN6TP'
FOOTPRINT = 'M24C02-WMN6TP:M24C02-WMN6TP'
MODELS_3D = ['M24C02-WMN6TP.wrl', 'M24C02-WMN6TP.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'E0', 'passive'),
    ('2', 'E1', 'passive'),
    ('3', 'E2', 'passive'),
    ('4', 'VSS', 'passive'),
    ('5', 'SDA', 'passive'),
    ('6', 'SCL', 'passive'),
    ('7', 'WC#', 'passive'),
    ('8', 'VCC', 'passive'),
]
