"""DSHP04TSGER — DSHP04TSGER_C3293144 (SW-SMD_8P-L6.7-W5.4-P1.27-LS8.4)

Generated by `schgen part add C3293144` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'DSHP04TSGER'
SAFE_NAME = 'DSHP04TSGER'
LCSC = 'C3293144'
DESCRIPTION = 'DSHP04TSGER_C3293144 (SW-SMD_8P-L6.7-W5.4-P1.27-LS8.4)'
MANUFACTURER = '康深'
PACKAGE = 'SW-SMD_8P-L6.7-W5.4-P1.27-LS8.4'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C3293144.pdf'
PRODUCT_URL = ''
LIB_ID = 'DSHP04TSGER:DSHP04TSGER'
FOOTPRINT = 'DSHP04TSGER:DSHP04TSGER'
MODELS_3D = ['DSHP04TSGER.wrl', 'DSHP04TSGER.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('2', '2', 'passive'),
    ('3', '3', 'passive'),
    ('4', '4', 'passive'),
    ('5', '5', 'passive'),
    ('6', '6', 'passive'),
    ('7', '7', 'passive'),
    ('8', '8', 'passive'),
]
