"""AP2112K-3.3TRG1 — AP2112K-3.3TRG1 (SOT-25-5_L2.9-W1.6-P0.95-LS2.8-BL)

Generated by `schgen part add C51118` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'AP2112K-3.3TRG1'
SAFE_NAME = 'AP2112K-3.3TRG1'
LCSC = 'C51118'
DESCRIPTION = 'AP2112K-3.3TRG1 (SOT-25-5_L2.9-W1.6-P0.95-LS2.8-BL)'
MANUFACTURER = 'DIODES(美台)'
PACKAGE = 'SOT-25-5_L2.9-W1.6-P0.95-LS2.8-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C51118.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Low-Dropout-Regulators-LDO_DIODES_AP2112K-3-3TRG1_AP2112K-3-3TRG1_C51118.html'
LIB_ID = 'AP2112K-3.3TRG1:AP2112K-3.3TRG1'
FOOTPRINT = 'AP2112K-3.3TRG1:AP2112K-3.3TRG1'
MODELS_3D = ['AP2112K-3.3TRG1.wrl', 'AP2112K-3.3TRG1.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'VIN', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'EN', 'passive'),
    ('4', 'NC', 'passive'),
    ('5', 'VOUT', 'passive'),
]
