"""AP2112K-1.8TRG1 — AP2112K-1.8TRG1 (SOT-25_L3.0-W1.6-P0.95-LS2.8-BL)

Generated by `schgen part add C176944` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'AP2112K-1.8TRG1'
SAFE_NAME = 'AP2112K-1.8TRG1'
LCSC = 'C176944'
DESCRIPTION = 'AP2112K-1.8TRG1 (SOT-25_L3.0-W1.6-P0.95-LS2.8-BL)'
MANUFACTURER = 'DIODES(美台)'
PACKAGE = 'SOT-25_L3.0-W1.6-P0.95-LS2.8-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C176944.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/presales_Diodes-Incorporated-AP2112K-1-8TRG1_C176944.html'
LIB_ID = 'AP2112K-1.8TRG1:AP2112K-1.8TRG1'
FOOTPRINT = 'AP2112K-1.8TRG1:AP2112K-1.8TRG1'
MODELS_3D = ['AP2112K-1.8TRG1.wrl', 'AP2112K-1.8TRG1.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('5', 'VOUT', 'passive'),
    ('4', 'NC', 'passive'),
    ('3', 'EN', 'passive'),
    ('2', 'GND', 'passive'),
    ('1', 'VIN', 'passive'),
]
