"""TXS02612RTWR — TXS02612RTWR (WQFN-24_L4.0-W4.0-P0.50-TL-EP2.5)

Generated by `schgen part add C140276` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TXS02612RTWR'
SAFE_NAME = 'TXS02612RTWR'
LCSC = 'C140276'
DESCRIPTION = 'TXS02612RTWR (WQFN-24_L4.0-W4.0-P0.50-TL-EP2.5)'
MANUFACTURER = 'TI(德州仪器)'
PACKAGE = 'WQFN-24_L4.0-W4.0-P0.50-TL-EP2.5'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C140276.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Interface-ICs_TI_TXS02612RTWR_TXS02612RTWR_C140276.html'
LIB_ID = 'TXS02612RTWR:TXS02612RTWR'
FOOTPRINT = 'TXS02612RTWR:TXS02612RTWR'
MODELS_3D = ['TXS02612RTWR.wrl', 'TXS02612RTWR.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'DAT2A', 'passive'),
    ('2', 'GND', 'passive'),
    ('3', 'DAT3A', 'passive'),
    ('4', 'CMDA', 'passive'),
    ('5', 'VCCA', 'passive'),
    ('6', 'DAT0A', 'passive'),
    ('7', 'DAT1A', 'passive'),
    ('8', 'DAT2B1', 'passive'),
    ('9', 'CLKA', 'passive'),
    ('10', 'DAT3B1', 'passive'),
    ('11', 'GND', 'passive'),
    ('12', 'CMDB1', 'passive'),
    ('13', 'CLKB1', 'passive'),
    ('14', 'DAT0B1', 'passive'),
    ('15', 'DAT1B1', 'passive'),
    ('16', 'DAT1B0', 'passive'),
    ('17', 'VCCB1', 'passive'),
    ('18', 'DAT0B0', 'passive'),
    ('19', 'CLKB0', 'passive'),
    ('20', 'CMDB0', 'passive'),
    ('21', 'VCCB0', 'passive'),
    ('22', 'DAT3B0', 'passive'),
    ('23', 'DAT2B0', 'passive'),
    ('24', 'SEL', 'passive'),
    ('25', 'EP', 'passive'),
]
