"""0603WAF1001T5E — 1KΩ (1001) ±1%

Generated by `schgen part add C21190` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = '0603WAF1001T5E'
SAFE_NAME = '0603WAF1001T5E'
LCSC = 'C21190'
DESCRIPTION = '1KΩ (1001) ±1%'
MANUFACTURER = 'UNI-ROYAL(厚声)'
PACKAGE = 'R0603'
JLC_CLASS = 'Basic Part'
PREFIX = 'R'
DATASHEET = 'https://www.lcsc.com/datasheet/C21190.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount-UniOhm_1KR-1001-1_C21190.html'
LIB_ID = '0603WAF1001T5E:0603WAF1001T5E'
FOOTPRINT = '0603WAF1001T5E:0603WAF1001T5E'
MODELS_3D = ['0603WAF1001T5E.wrl', '0603WAF1001T5E.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('2', '2', 'passive'),
    ('1', '1', 'passive'),
]
