from __future__ import annotations

import copy
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from schgen.core import native as _nat
from schgen.core import sexpr
from schgen.core.model import Circuit
from schgen.core.sexpr import Sym, _from_tagged
from schgen.core.symbols import Library

PAPER_DEFAULT = "A4"


@dataclass
class PlacedPart:
    ref: str
    lib_id: str
    value: str
    x: float
    y: float
    rotation: int = 0
    footprint: str = ""
    ref_pos: tuple[float, float, int] | None = None
    val_pos: tuple[float, float, int] | None = None


@dataclass
class PlacedPower:
    lib_id: str
    value: str
    ref: str
    x: float
    y: float
    rotation: int = 0
    net: str = ""
    val_pos: tuple[float, float, int] | None = None
    show_value: bool = False

    @property
    def net_name(self) -> str:
        return self.net or self.value


@dataclass
class Wire:
    x0: float
    y0: float
    x1: float
    y1: float


@dataclass
class Junction:
    x: float
    y: float


@dataclass
class HierLabel:
    name: str
    x: float
    y: float
    rotation: int = 0
    shape: str = "bidirectional"


@dataclass
class LocalLabel:
    name: str
    x: float
    y: float
    rotation: int = 0


@dataclass
class NoConnect:
    x: float
    y: float


@dataclass
class SheetPin:
    name: str
    x: float
    y: float
    rotation: int = 180
    shape: str = "bidirectional"


@dataclass
class SheetSymbol:
    name: str
    file: str
    x: float
    y: float
    w: float
    h: float
    uuid: str
    pins: list[SheetPin] = field(default_factory=list)
    page: str = "2"


@dataclass
class PlacedDesign:
    circuit: Circuit
    parts: list[PlacedPart] = field(default_factory=list)
    powers: list[PlacedPower] = field(default_factory=list)
    wires: list[Wire] = field(default_factory=list)
    junctions: list[Junction] = field(default_factory=list)
    hlabels: list[HierLabel] = field(default_factory=list)
    llabels: list[LocalLabel] = field(default_factory=list)
    no_connects: list[NoConnect] = field(default_factory=list)
    sheets: list[SheetSymbol] = field(default_factory=list)
    paper: str = PAPER_DEFAULT
    standalone: bool = True


_NS = uuid.uuid5(uuid.NAMESPACE_DNS, "schgen.kicad-id")


def stable_uuid(*parts: object) -> str:
    return str(uuid.uuid5(_NS, "/".join(str(p) for p in parts)))


class _IdFactory:
    def __init__(self, scope: str) -> None:
        self._scope = scope
        self._n: dict[str, int] = {}

    def __call__(self, kind: str) -> str:
        n = self._n.get(kind, 0)
        self._n[kind] = n + 1
        return stable_uuid(self._scope, kind, n)


def _embed_symbol(lib: Library, lib_id: str) -> list:
    block = copy.deepcopy(lib.get(lib_id).raw)
    block[1] = lib_id
    return block


def emit(design: PlacedDesign, out_path: Path, lib: Library, *,
         instance_path: str | None = None,
         project: str | None = None,
         sheet_uuid: str | None = None) -> Path:
    c = design.circuit
    inst_project = project or c.name
    root_uuid = sheet_uuid or stable_uuid(inst_project, c.name, "sheet")
    # trap: a bare "/" instance path drops every pad-derived net from ERC + netlist
    inst_path = instance_path or f"/{root_uuid}"
    uid = _IdFactory(root_uuid)
    doc: list = [Sym("kicad_sch"),
                 [Sym("version"), 20260306],
                 [Sym("generator"), "schgen"],
                 [Sym("generator_version"), "1.0"],
                 [Sym("uuid"), root_uuid],
                 [Sym("paper"), design.paper],
                 [Sym("title_block"),
                  [Sym("title"), c.title],
                  [Sym("company"), "Zynq SoM Carrier"],
                  [Sym("comment"), 1,
                   f"{c.name} — generated by schgen (do not hand-edit)"]]]

    lib_ids = sorted({p.lib_id for p in design.parts}
                     | {p.lib_id for p in design.powers})
    doc.append([Sym("lib_symbols"), *[_embed_symbol(lib, lid) for lid in lib_ids]])

    for w in design.wires:
        if not _nat.loaded():
            raise RuntimeError("native emit_wire required")
        doc.append(_from_tagged(_nat.module().emit_wire(
            w.x0, w.y0, w.x1, w.y1, uid("wire"))))
    for j in design.junctions:
        if not _nat.loaded():
            raise RuntimeError("native emit_junction required")
        doc.append(_from_tagged(_nat.module().emit_junction(
            j.x, j.y, uid("junction"))))
    for nc in design.no_connects:
        if not _nat.loaded():
            raise RuntimeError("native emit_no_connect required")
        doc.append(_from_tagged(_nat.module().emit_no_connect(
            nc.x, nc.y, uid("no_connect"))))
    for h in design.hlabels:
        just = "right" if h.rotation in (180, 270) else "left"
        tag = "global_label" if design.standalone else "hierarchical_label"
        if not _nat.loaded():
            raise RuntimeError("native emit_sch_label required")
        doc.append(_from_tagged(_nat.module().emit_sch_label(
            tag, h.name, h.shape, h.x, h.y, float(h.rotation), just,
            uid("hlabel"))))
    for ll in design.llabels:
        just = "right bottom" if ll.rotation == 180 else "left bottom"
        if not _nat.loaded():
            raise RuntimeError("native emit_sch_label required")
        doc.append(_from_tagged(_nat.module().emit_sch_label(
            "label", ll.name, "", ll.x, ll.y, float(ll.rotation), just,
            uid("llabel"))))
    for sh in design.sheets:
        if not _nat.loaded():
            raise RuntimeError("native emit_sheet required")
        pins = []
        for sp in sh.pins:
            just = "right" if sp.rotation in (180, 270) else "left"
            pins.append((sp.name, sp.shape, sp.x, sp.y,
                         float(sp.rotation), just, uid("sheet-pin")))
        doc.append(_from_tagged(_nat.module().emit_sheet(
            sh.x, sh.y, sh.w, sh.h, sh.uuid, sh.name, sh.file,
            inst_project, f"/{root_uuid}", sh.page, pins)))

    def _sym_instance(ref: str, lib_id: str, value: str, x: float, y: float,
                      rot: int, footprint: str,
                      ref_pos: tuple[float, float, int] | None,
                      val_pos: tuple[float, float, int] | None,
                      hide_ref: bool, hide_val: bool,
                      extra_fields: dict[str, str] | None = None) -> list:
        extra_fields = dict(extra_fields or {})
        sdef = lib.get(lib_id)
        rp = ref_pos or (x, y - 2.54, 0)
        vp = val_pos or (x, y + 2.54, 0)
        if not _nat.loaded():
            raise RuntimeError("native emit_symbol required")
        fields = [("Datasheet", extra_fields.pop("Datasheet", ""))]
        fields.extend(extra_fields.items())
        symbol_uuid = uid("symbol")
        pin_rows = [(p.number, uid("pin")) for p in sdef.pins]
        return _from_tagged(_nat.module().emit_symbol(
            lib_id, x, y, float(rot), symbol_uuid, ref,
            rp[0], rp[1], float(rp[2]), hide_ref, value,
            vp[0], vp[1], float(vp[2]), hide_val, footprint,
            fields, pin_rows, inst_project, inst_path))

    for p in design.parts:
        part = c.parts.get(p.ref)
        doc.append(_sym_instance(p.ref, p.lib_id, p.value, p.x, p.y, p.rotation,
                                 p.footprint or (part.footprint if part else ""),
                                 p.ref_pos, p.val_pos, False, False,
                                 extra_fields=(part.fields if part else None)))
    for pw in design.powers:
        doc.append(_sym_instance(pw.ref, pw.lib_id, pw.value, pw.x, pw.y,
                                 pw.rotation, "", None, pw.val_pos,
                                 True, not pw.show_value))

    doc.append([Sym("sheet_instances"),
                [Sym("path"), "/", [Sym("page"), "1"]]])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(sexpr.dumps(doc) + "\n")
    return out_path
