from __future__ import annotations

import copy
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from schgen.core import native as _nat
from schgen.core import sexpr
from schgen.core.model import Circuit
from schgen.core.sexpr import Sym, _from_tagged
from schgen.core.symbols import Library

PAPER_DEFAULT = "A4"


@dataclass
class PlacedPart:
    ref: str
    lib_id: str
    value: str
    x: float
    y: float
    rotation: int = 0
    footprint: str = ""
    ref_pos: tuple[float, float, int] | None = None
    val_pos: tuple[float, float, int] | None = None


@dataclass
class PlacedPower:
    lib_id: str
    value: str
    ref: str
    x: float
    y: float
    rotation: int = 0
    net: str = ""
    val_pos: tuple[float, float, int] | None = None
    show_value: bool = False

    @property
    def net_name(self) -> str:
        return self.net or self.value


@dataclass
class Wire:
    x0: float
    y0: float
    x1: float
    y1: float


@dataclass
class Junction:
    x: float
    y: float


@dataclass
class HierLabel:
    name: str
    x: float
    y: float
    rotation: int = 0
    shape: str = "bidirectional"


@dataclass
class LocalLabel:
    name: str
    x: float
    y: float
    rotation: int = 0


@dataclass
class NoConnect:
    x: float
    y: float


@dataclass
class SheetPin:
    name: str
    x: float
    y: float
    rotation: int = 180
    shape: str = "bidirectional"


@dataclass
class SheetSymbol:
    name: str
    file: str
    x: float
    y: float
    w: float
    h: float
    uuid: str
    pins: list[SheetPin] = field(default_factory=list)
    page: str = "2"


@dataclass
class PlacedDesign:
    circuit: Circuit
    parts: list[PlacedPart] = field(default_factory=list)
    powers: list[PlacedPower] = field(default_factory=list)
    wires: list[Wire] = field(default_factory=list)
    junctions: list[Junction] = field(default_factory=list)
    hlabels: list[HierLabel] = field(default_factory=list)
    llabels: list[LocalLabel] = field(default_factory=list)
    no_connects: list[NoConnect] = field(default_factory=list)
    sheets: list[SheetSymbol] = field(default_factory=list)
    paper: str = PAPER_DEFAULT
    standalone: bool = True


_NS = uuid.uuid5(uuid.NAMESPACE_DNS, "schgen.kicad-id")


def stable_uuid(*parts: object) -> str:
    return str(uuid.uuid5(_NS, "/".join(str(p) for p in parts)))


class _IdFactory:
    def __init__(self, scope: str) -> None:
        self._scope = scope
        self._n: dict[str, int] = {}

    def __call__(self, kind: str) -> str:
        n = self._n.get(kind, 0)
        self._n[kind] = n + 1
        return stable_uuid(self._scope, kind, n)


def _effects(size: float = 1.27, hide: bool = False, justify: str | None = None):
    e: list = [Sym("effects"), [Sym("font"), [Sym("size"), size, size]]]
    if justify:
        e.append([Sym("justify"), *[Sym(t) for t in justify.split()]])
    if hide:
        e.append([Sym("hide"), Sym("yes")])
    return e


def _prop(name: str, value: str, x: float, y: float, rot: int = 0,
          hide: bool = False) -> list:
    return [Sym("property"), name, value,
            [Sym("at"), x, y, rot],
            _effects(hide=hide)]


def _embed_symbol(lib: Library, lib_id: str) -> list:
    block = copy.deepcopy(lib.get(lib_id).raw)
    block[1] = lib_id
    return block


def emit(design: PlacedDesign, out_path: Path, lib: Library, *,
         instance_path: str | None = None,
         project: str | None = None,
         sheet_uuid: str | None = None) -> Path:
    c = design.circuit
    inst_project = project or c.name
    root_uuid = sheet_uuid or stable_uuid(inst_project, c.name, "sheet")
    # trap: a bare "/" instance path drops every pad-derived net from ERC + netlist
    inst_path = instance_path or f"/{root_uuid}"
    uid = _IdFactory(root_uuid)
    doc: list = [Sym("kicad_sch"),
                 [Sym("version"), 20260306],
                 [Sym("generator"), "schgen"],
                 [Sym("generator_version"), "1.0"],
                 [Sym("uuid"), root_uuid],
                 [Sym("paper"), design.paper],
                 [Sym("title_block"),
                  [Sym("title"), c.title],
                  [Sym("company"), "Zynq SoM Carrier"],
                  [Sym("comment"), 1,
                   f"{c.name} — generated by schgen (do not hand-edit)"]]]

    lib_ids = sorted({p.lib_id for p in design.parts}
                     | {p.lib_id for p in design.powers})
    doc.append([Sym("lib_symbols"), *[_embed_symbol(lib, lid) for lid in lib_ids]])

    for w in design.wires:
        if _nat.loaded():
            doc.append(_from_tagged(_nat.module().emit_wire(
                w.x0, w.y0, w.x1, w.y1, uid("wire"))))
        else:
            doc.append([Sym("wire"),
                        [Sym("pts"), [Sym("xy"), w.x0, w.y0],
                         [Sym("xy"), w.x1, w.y1]],
                        [Sym("stroke"), [Sym("width"), 0],
                         [Sym("type"), Sym("default")]],
                        [Sym("uuid"), uid("wire")]])
    for j in design.junctions:
        if _nat.loaded():
            doc.append(_from_tagged(_nat.module().emit_junction(
                j.x, j.y, uid("junction"))))
        else:
            doc.append([Sym("junction"), [Sym("at"), j.x, j.y],
                        [Sym("diameter"), 0], [Sym("color"), 0, 0, 0, 0],
                        [Sym("uuid"), uid("junction")]])
    for nc in design.no_connects:
        if _nat.loaded():
            doc.append(_from_tagged(_nat.module().emit_no_connect(
                nc.x, nc.y, uid("no_connect"))))
        else:
            doc.append([Sym("no_connect"), [Sym("at"), nc.x, nc.y],
                        [Sym("uuid"), uid("no_connect")]])
    for h in design.hlabels:
        just = "right" if h.rotation in (180, 270) else "left"
        tag = "global_label" if design.standalone else "hierarchical_label"
        doc.append([Sym(tag), h.name,
                    [Sym("shape"), Sym(h.shape)],
                    [Sym("at"), h.x, h.y, h.rotation],
                    _effects(justify=just),
                    [Sym("uuid"), uid("hlabel")]])
    for ll in design.llabels:
        just = "right bottom" if ll.rotation == 180 else "left bottom"
        doc.append([Sym("label"), ll.name,
                    [Sym("at"), ll.x, ll.y, ll.rotation],
                    _effects(justify=just),
                    [Sym("uuid"), uid("llabel")]])
    for sh in design.sheets:
        node: list = [Sym("sheet"),
                      [Sym("at"), sh.x, sh.y],
                      [Sym("size"), sh.w, sh.h],
                      [Sym("exclude_from_sim"), Sym("no")],
                      [Sym("in_bom"), Sym("yes")],
                      [Sym("on_board"), Sym("yes")],
                      [Sym("dnp"), Sym("no")],
                      [Sym("fields_autoplaced"), Sym("yes")],
                      [Sym("stroke"), [Sym("width"), 0.1524],
                       [Sym("type"), Sym("solid")]],
                      [Sym("fill"), [Sym("color"), 0, 0, 0, 0.0]],
                      [Sym("uuid"), sh.uuid],
                      [Sym("property"), "Sheetname", sh.name,
                       [Sym("at"), sh.x, sh.y - 0.7116, 0],
                       _effects(justify="left bottom")],
                      [Sym("property"), "Sheetfile", sh.file,
                       [Sym("at"), sh.x, sh.y + sh.h + 0.5846, 0],
                       _effects(justify="left top")]]
        for sp in sh.pins:
            just = "right" if sp.rotation in (180, 270) else "left"
            node.append([Sym("pin"), sp.name, Sym(sp.shape),
                         [Sym("at"), sp.x, sp.y, sp.rotation],
                         _effects(justify=just),
                         [Sym("uuid"), uid("sheet-pin")]])
        node.append([Sym("instances"),
                     [Sym("project"), inst_project,
                      [Sym("path"), f"/{root_uuid}",
                       [Sym("page"), sh.page]]]])
        doc.append(node)

    def _sym_instance(ref: str, lib_id: str, value: str, x: float, y: float,
                      rot: int, footprint: str,
                      ref_pos: tuple[float, float, int] | None,
                      val_pos: tuple[float, float, int] | None,
                      hide_ref: bool, hide_val: bool,
                      extra_fields: dict[str, str] | None = None) -> list:
        extra_fields = dict(extra_fields or {})
        sdef = lib.get(lib_id)
        node: list = [Sym("symbol"),
                      [Sym("lib_id"), lib_id],
                      [Sym("at"), x, y, rot],
                      [Sym("unit"), 1],
                      [Sym("exclude_from_sim"), Sym("no")],
                      [Sym("in_bom"), Sym("yes")],
                      [Sym("on_board"), Sym("yes")],
                      [Sym("dnp"), Sym("no")],
                      [Sym("uuid"), uid("symbol")]]
        rp = ref_pos or (x, y - 2.54, 0)
        vp = val_pos or (x, y + 2.54, 0)
        node.append(_prop("Reference", ref, rp[0], rp[1], rp[2], hide=hide_ref))
        node.append(_prop("Value", value, vp[0], vp[1], vp[2], hide=hide_val))
        node.append(_prop("Footprint", footprint, x, y, 0, hide=True))
        node.append(_prop("Datasheet", extra_fields.pop("Datasheet", ""),
                          x, y, 0, hide=True))
        for fname, fval in extra_fields.items():
            node.append(_prop(fname, fval, x, y, 0, hide=True))
        for p in sdef.pins:
            node.append([Sym("pin"), p.number, [Sym("uuid"), uid("pin")]])
        node.append([Sym("instances"),
                     [Sym("project"), inst_project,
                      [Sym("path"), inst_path,
                       [Sym("reference"), ref], [Sym("unit"), 1]]]])
        return node

    for p in design.parts:
        part = c.parts.get(p.ref)
        doc.append(_sym_instance(p.ref, p.lib_id, p.value, p.x, p.y, p.rotation,
                                 p.footprint or (part.footprint if part else ""),
                                 p.ref_pos, p.val_pos, False, False,
                                 extra_fields=(part.fields if part else None)))
    for pw in design.powers:
        doc.append(_sym_instance(pw.ref, pw.lib_id, pw.value, pw.x, pw.y,
                                 pw.rotation, "", None, pw.val_pos,
                                 True, not pw.show_value))

    doc.append([Sym("sheet_instances"),
                [Sym("path"), "/", [Sym("page"), "1"]]])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(sexpr.dumps(doc) + "\n")
    return out_path
