"""XT60PW-M — XT60PW-M (CONN-TH_XT60PW-M)

Generated by `schgen part add C98732` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'XT60PW-M'
SAFE_NAME = 'XT60PW-M'
LCSC = 'C98732'
DESCRIPTION = 'XT60PW-M (CONN-TH_XT60PW-M)'
MANUFACTURER = 'AMASS(艾迈斯)'
PACKAGE = 'CONN-TH_XT60PW-M'
JLC_CLASS = 'Extended Part'
PREFIX = 'CN'
DATASHEET = 'https://www.lcsc.com/datasheet/C98732.pdf'
PRODUCT_URL = ''
LIB_ID = 'XT60PW-M:XT60PW-M'
FOOTPRINT = 'XT60PW-M:XT60PW-M'
MODELS_3D = ['XT60PW-M.wrl', 'XT60PW-M.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '-', 'passive'),
    ('2', '+', 'passive'),
    ('3', '3', 'passive'),
    ('4', '4', 'passive'),
]
