#pragma once

// Fixed prose and portable-C bodies transcribed from the six authored generators.
// These are source templates, never rendered project snapshots. All netlist joins,
// decisions, ordering, values and dynamic sections live in the typed C++ renderers.
namespace schgen::bringup_text {
inline constexpr const char firmware_intro[] = R"BRINGUP(/*
 * zynq_carrier_contract.h — Zynq carrier <-> SoM STM32 system-controller
 * hardware contract.  GENERATED — DO NOT EDIT.
 *
 * generated-by: schgen firmware (schgen/firmware.py)
 * regenerate:   PYTHONPATH=. python -m schgen firmware
 * sources:
)BRINGUP";
inline constexpr const char firmware_live[] = R"BRINGUP( * All GPIO port/pin values are extracted LIVE from the SoM
 * KiCad netlist at generation time — they cannot drift from
 * the hardware.
 */
#ifndef ZYNQ_CARRIER_CONTRACT_H
#define ZYNQ_CARRIER_CONTRACT_H

/* ======================================================================== */
/* !! RESERVED FOR SWD — debug_boot dossier section 0, firmware contract: */
)BRINGUP";
inline constexpr const char firmware_swd_footer[] = R"BRINGUP(/* !! SC firmware must NEVER reconfigure PA13/PA14 — they are the SC's */
/* !! own SWD port (carrier SWD header, debug_boot J2). */
/* !! Reconfiguring them bricks debug until BOOT0-DFU recovery. */
/* ======================================================================== */

/* ---- STM32-facing nets on the SoM mezzanine connectors ---------------- */
/* net <- J pin (carrier/som_interface.json) <- STM32 GPIO (live U9 map) */
)BRINGUP";
inline constexpr const char firmware_internal[] = R"BRINGUP(
/* ---- STM32-driven SoM-INTERNAL control nets (not on J1/J2/J3) -------- */
/* The SC drives Zynq boot mode / resets ON-MODULE; the carrier only */
/* requests via the BOOTSEL straps below (debug_boot dossier section 0). */
)BRINGUP";
inline constexpr const char firmware_bootsel[] = R"BRINGUP(
/* ---- BOOTSEL decode (debug_boot dossier section (c)) ---------------- */
/* Carrier boot-request DIP (debug_boot SW1): pos 2 -> BOOTSEL0, pos 3 -> */
/* BOOTSEL1; closed = LOW, open = HIGH (10k pull-ups to +3V3_SC).        */
/* SC firmware samples BOOTSEL[1:0] at boot and drives ZYNQ_BMODE_0/2    */
/* on-module (constants above).  value = (BOOTSEL1 << 1) | BOOTSEL0      */
)BRINGUP";
inline constexpr const char firmware_i2c[] = R"BRINGUP(/* STM32_BOOT0 (debug_boot SW1 pos 1): closed pulls BOOT0 high through */
/* 100R against the SoM 1k5 pull-down -> closed + reset = USB DFU.      */

/* ---- I2C address map — bus STM32_I2C2, 7-bit addresses -------------- */
/* (power_mon dossier section 2; strapped addresses derived from the    */
/*  netlists at generation time)                                        */
)BRINGUP";
inline constexpr const char firmware_bitbang[] = R"BRINGUP(/* G3: STM32_I2C2 is a firmware BIT-BANG on the DAC pins (PA4/PA5, no   */
/* I2C AF; real I2C2 PA8/PA9 is the on-module SC<->Zynq link) — ~100 kHz */
)BRINGUP";
inline constexpr const char firmware_rail[] = R"BRINGUP(/* ---- Rail bring-up sequence (derived from the power.py regulator     */
/*      chain: each stage feeds the next) + EN-cell mapping             */
/* EN semantics (bringup_en): EN = DIP AND override; override is a VETO  */
/* — drive LOW to force a rail OFF; Hi-Z/HIGH leaves the DIP in charge. */
/* Software can NEVER force a rail ON with its DIP open.                */
)BRINGUP";
inline constexpr const char firmware_expander[] = R"BRINGUP(/* ---- TCA9535 module-override port map — READ from the bringup_rails  */
/*      netlist (P0x/P1x pin -> net), joined to its EN cell + load      */
/*      switch.  Bit index = position in the 16-bit port word           */
/*      (P00=bit0 ... P17=bit15).  POR state = all inputs => DIP rules. */
)BRINGUP";
inline constexpr const char firmware_pmon[] = R"BRINGUP(/* ---- INA3221 rail-telemetry channel map (power_mon netlist) --------- */
)BRINGUP";
inline constexpr const char manual_intro[] = R"BRINGUP(# Zynq carrier bring-up manual

> GENERATED by `schgen manual` (schgen/manual.py) — DO NOT EDIT.
> Regenerate: `PYTHONPATH=. python -m schgen manual`. Every switch
> position, net, voltage, limit and address below is read from the
> authored netlists in `carrier/subsystems/` at generation time;
> narrative context cites its research dossier per section.

Bring-up is staged (carrier/PLAN.md): the board must come up with
**switches only** — rails first, one at a time, then user IO, then each
module behind its own current-limited load switch. A blank (unprogrammed)
system controller is fine for every stage: all software overrides are
vetoes that default to "DIP rules" (carrier/research/bringup_power_gating.md, section 1).

## Stage 0 — power-off checks

Sources: `carrier/subsystems/pd_input/pd_input.py`, `carrier/subsystems/bringup_rails/bringup_rails.py`,
`carrier/subsystems/debug_boot/debug_boot.py`, `carrier/research/bringup_power_gating.md`.

)BRINGUP";
inline constexpr const char manual_stage0_continuity[] = R"BRINGUP(2. **No dead shorts.** With the board unpowered, check continuity to `GND` on:
)BRINGUP";
inline constexpr const char manual_stage1[] = R"BRINGUP(   None may read as a short (the TVS `pd_input.D1` on `+VIN` conducts only
   above its 22 V standoff — a diode-mode reading there is normal, a dead
   short is not).
3. **Mating check.** SoM seated on J1/J2/J3 (DF40 stack); no probe wires under
   the module.

## Stage 1 — first power: PD negotiation, always-on domain

Sources: `carrier/subsystems/pd_input/pd_input.py`, `carrier/subsystems/usb_pd/usb_pd.py`,
`carrier/research/bringup_power_gating.md` (risk R1), `carrier/research/power_mon.md`.

Plug a 20 V / 3 A (60 W) USB-C PD-capable supply into the power USB-C (`pd_input.J1`). The
board boots on the **default 5 V** USB-C contract; the SoM generates the
always-on `+3V3_SC` rail from VIN **before** PD negotiation and before any
carrier rail. The FUSB302B (`usb_pd.U1`, I2C `0x22`) and the whole bring-up
infrastructure run from `+3V3_SC` for exactly this reason — PD must negotiate
with every DIP open.

**Source requirement (SEQ-3).** The 5 V default contract must supply at least
**3 A at 5 V (>= 15 W)** for the board to come up: the SoM's pre-PD draw is
~2.2 A on 5 V before any higher-voltage contract is negotiated. A weak 5 V
charger (e.g. a 0.5-1.5 A phone brick) will brown out / fail to boot — use a
USB-C source that advertises >= 3 A at 5 V (`pd_input.py`).

With **all DIPs open**, expect:

- `+VIN` stays at the **5 V default contract** at first power and the board
  runs **reduced on 5 V**. The FUSB302B is a PD **PHY only** — it does NOT
  negotiate by itself; reaching the negotiated 20 V / 3 A (60 W) USB-C PD contract requires
  the **SoM system-controller PD-policy firmware** to drive the FUSB302B through
  the higher-voltage Request. Until the SC runs that policy, `+VIN` remains at
  5 V (a blank SC = 5 V VIN, board reduced-functional).
)BRINGUP";
inline constexpr const char manual_always_on_table[] = R"BRINGUP(
  | sheet | ICs on `+3V3_SC` |
  |---|---|
)BRINGUP";
inline constexpr const char manual_stage2[] = R"BRINGUP(monitored rail still down (`carrier/research/power_mon.md` section 2).

## Stage 2 — rails, one DIP at a time

Sources: `carrier/subsystems/bringup_rails/bringup_rails.py` (SW1 map), `carrier/subsystems/bringup_en/bringup_en.py`
(EN cells), `carrier/subsystems/power/power.py` (regulator chain), `carrier/subsystems/power_mon/power_mon.py`
(shunts/monitors), `carrier/research/power_mon.md` (budgets).

The sequence below is the regulator chain read from the power netlist —
each stage's input is the previous stage's output, so the order is not
optional. Close one DIP, verify, then move on. (A downstream DIP closed
early is benign: its regulator simply has no input yet.)

)BRINGUP";
inline constexpr const char manual_user_sources[] = R"BRINGUP(
Sources: `carrier/subsystems/bringup_modules/bringup_modules.py`, `carrier/subsystems/user_io/user_io.py`.

)BRINGUP";
inline constexpr const char manual_stage4[] = R"BRINGUP(## Stage 4 — module load switches, one DIP at a time

Sources: `carrier/subsystems/bringup_rails/bringup_rails.py` (SW2/SW6 maps), `carrier/subsystems/bringup_en_modules/bringup_en_modules.py`,
`carrier/subsystems/bringup_modules/bringup_modules.py` (SY6280 cells; ILIM = 6800 / RSET per the Silergy DS).

Each module rail is current-limited and folds back on a fault instead of
dragging the source rail down — a sagging status LED points at the faulty
module. Close one position, watch the status LED, check the module's sheet.

| close | module | source | gated rail | ILIM | status LED | consumer sheets |
|---|---|---|---|---|---|---|
)BRINGUP";
inline constexpr const char manual_spare[] = R"BRINGUP(through a 100k pull-DOWN, so it stays OFF until SC software raises it
(`carrier/subsystems/bringup_rails/bringup_rails.py`).
)BRINGUP";
inline constexpr const char manual_boot[] = R"BRINGUP(into `carrier/firmware/zynq_carrier_contract.h` (`schgen firmware`).

## Stage 5 — boot modes, JTAG, SWD

Sources: `carrier/subsystems/debug_boot/debug_boot.py`, `carrier/research/debug_boot_pmod.md`
(all J1 nets verified against the SoM netlist), live U9 pin extraction (`schgen/bringup_facts.py`).

### Boot-request DIP (`debug_boot.SW1`)

The Zynq boot straps live ON the SoM and are driven by the SC; the carrier
only *requests* a mode. Decode (dossier section (c)): `BOOTSEL[1:0]` =
`00` JTAG, `01` QSPI, `10` SD, `11` reserved — closed DIP = LOW.

| position | net | function |
|---|---|---|
)BRINGUP";
inline constexpr const char manual_reset[] = R"BRINGUP(
### Reset

`debug_boot.SW2` (and `bringup_rails.SW5`) pull `STM32_NRST` low — resetting
the SC re-runs its power/boot supervision = whole-system reset (the SoM owns
the RC debounce).

### SWD first (works with main rails down)

ARM 10-pin 1.27 mm header `debug_boot.J2`; VTref = `+3V3_SC`, so the SC
debugs with every carrier rail off — bring up the SC firmware before any
)BRINGUP";
inline constexpr const char manual_services[] = R"BRINGUP(**PA13/PA14 are reserved for SWD** — SC firmware must never reconfigure them
(`carrier/research/debug_boot_pmod.md` section 0).

### Zynq JTAG

Xilinx 2x7 2 mm header `debug_boot.J1`; VREF pin 2 = `+3V3` (= VCCO_0), so
JTAG needs the `+3V3` rail up (stage 2). TMS/TDI carry 4k7 insurance
pull-ups (`debug_boot.R1/R2`). Header pin 14 (SRST) is NC — the SoM does not
export PS_SRST_B; debugger-initiated PS resets go through the SC (dossier (a)).

After JTAG enumerates: request boot modes via the BOOTSEL DIP + SC reset and
verify QSPI/SD boots per the decode table above.

## Stage 6 — board services (+3V3_AUX expansion, optional)

Sources: `carrier/subsystems/board_aux/board_aux.py`, `carrier/subsystems/board_services/board_services.py`,
`carrier/subsystems/board_qwiic/board_qwiic.py`.

A SELF-CONTAINED manually-gated rail, separate from the central DIP fabric:
`board_aux.U1` (SY6280, 523 mA limit) gates `+3V3` -> `+3V3_AUX`, enabled by
`board_aux.SW1` position 1 (DSHP04 DIP) — it **defaults OFF** (100k pulldown).
Leave it OFF unless you need the board services below.

)BRINGUP";
inline constexpr const char manual_services_steps[] = R"BRINGUP(2. **I2C** reaches the SC bus through the `board_aux.U2` PCA9306 isolator — the
   AUX devices are cut off from `STM32_I2C2` until this rail is up (no
   back-powering). On the AUX segment: `0x51` **ID-EEPROM** (`board_services.U1`
   24AA025E48, A0 strapped high) with a factory **EUI-48 MAC** for the RJ45;
   `0x52` **RTC** (`board_services.U2` RV-3028-C7), `BT1` CR1220 backup. **Keep
   the trickle charger OFF** — `BT1` is a PRIMARY cell (see the firmware contract).
3. **Watchdog** (`board_services.U3` TPS3823): unpowered until this rail is on,
   and WDI floats (watchdog disabled) until the PL drives `WATCHDOG_KICK` (J3.96, bank 33).
   Its reset is a PL EVENT on `WATCHDOG_RST_N` (J3.98, bank 33) — never a hard board
   reset. Arm it only after the fabric is configured.
4. **QWIIC** (`board_qwiic.J1`): the gated 3.3 V + isolated AUX I2C, ESD-clamped
   at the connector. Hot-plug external modules only with this rail enabled.
)BRINGUP";
inline constexpr const char testplan_intro[] = R"BRINGUP(# Zynq carrier acceptance TEST PLAN

> GENERATED by `schgen testplan` (schgen/testplan.py) — DO NOT EDIT.
> Regenerate: `PYTHONPATH=. python -m schgen testplan`. Every expected
> value, min/max limit, net and probe pad below is JOINED from the
> analytic spice gate (`schgen/spice.py`), the test-point coverage gate
> (`schgen/testpoints.py`) and the staged bring-up sequence (`schgen/manual.py`,
> `schgen/bringup_facts.py`) — no value is hand-typed and none is re-derived
> here. Limits that FAIL the spice gate would also fail the board build.

Procedure: work the stages in order (close one bring-up DIP, verify, move
on — see `carrier/docs/BRINGUP.md`). For each step probe the listed pad,
record the measurement in the **measured** column, and tick **pass?** when
the reading sits inside `[min .. max]`. A blank (unprogrammed) system
controller is fine for every electrical step; the I2C scan and functional
checks below need SC firmware running.

)BRINGUP";
inline constexpr const char testplan_electrical[] = R"BRINGUP(
## Electrical acceptance — by bring-up stage

)BRINGUP";
inline constexpr const char testplan_columns[] = R"BRINGUP(
| step | net | probe pad | expected | min | max | measured | pass? |
|---|---|---|---|---|---|---|---|
)BRINGUP";
inline constexpr const char testplan_rationale[] = R"BRINGUP(
<details><summary>step rationale (from the spice gate detail)</summary>

)BRINGUP";
inline constexpr const char testplan_rationale_end[] = R"BRINGUP(
</details>

)BRINGUP";
inline constexpr const char testplan_i2c[] = R"BRINGUP(## I2C-scan expectation (SC firmware running)

With the always-on `+3V3_SC` domain up and SC firmware scanning the bring-up
buses, exactly these 7-bit addresses must ACK. The addresses are derived
from the netlist straps (`schgen/bringup_facts.py`), not hand-typed.

| address | device | ref | when | ACK? |
|---|---|---|---|---|
)BRINGUP";
inline constexpr const char testplan_functional[] = R"BRINGUP(
## Per-module functional checklist

Each module rail comes up behind its own current-limited load switch (Stage 4).
After enabling a module, confirm its status LED and the headline function.

| sheet | gated rail | status LED | functional check |
|---|---|---|---|
)BRINGUP";
inline constexpr const char scfw_hal[] = R"BRINGUP(#ifndef SC_HAL_H
#define SC_HAL_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ======================================================================== */
/* HAL contract                                                             */
/* ======================================================================== */
/* The portable bring-up code (sc_seq.c / sc_pd.c / sc_wdt.c) NEVER    */
/* touches a register or a Zephyr API directly: it calls the ops      */
/* below.  A platform port (sc_hal_zephyr.c for a Zephyr app, or a    */
/* bare-metal sc_hal_stm32.c) provides the bodies.  GPIOs are named   */
/* by the ('port' letter, pin number) pair the hardware contract      */
/* (zynq_carrier_contract.h) already exposes, so the HAL maps a STM32  */
/* (port,pin) onto whatever handle the platform uses.                 */

/* A GPIO line as the contract names it: STM32 port letter 'A'..'G'   */
/* and pin number, exactly the ZC_*_GPIO_PORT / ZC_*_GPIO_PIN pair.   */
typedef struct {
    char port;       /* 'A' .. 'G' (ZC_*_GPIO_PORT) */
    uint8_t pin;     /* 0 .. 15    (ZC_*_GPIO_PIN)  */
} sc_gpio_t;

/* I2C transfer direction. */
typedef enum { SC_I2C_WRITE = 0, SC_I2C_READ = 1 } sc_i2c_dir_t;

/* The platform ops table.  All return 0 on success, <0 on error.     */
/* A Zephyr port fills this from devicetree handles (see sc_hal.h     */
/* footer); a bare-metal port from LL/HAL register writes.            */
typedef struct {
    /* --- timing --- */
    void (*delay_ms)(uint32_t ms);
    uint32_t (*uptime_ms)(void);
    /* --- GPIO --- */
    int (*gpio_configure_output)(sc_gpio_t io, bool open_drain);
    int (*gpio_configure_input)(sc_gpio_t io, bool pull_up);
    int (*gpio_set)(sc_gpio_t io, bool level);
    int (*gpio_get)(sc_gpio_t io, bool *level);
    /* --- I2C (7-bit addressing; bit-bang or peripheral) --- */
    int (*i2c_xfer)(uint8_t addr7, sc_i2c_dir_t dir,
                    uint8_t *buf, size_t len);
    /* --- watchdog (TPS3823 WDI strobe; see sc_wdt.h, C2) --- */
    int (*wdt_strobe)(void);
    /* --- diagnostics (optional; may be NULL) --- */
    void (*log)(const char *msg);
} sc_hal_t;

/* The single HAL instance the portable code calls.  The platform port */
/* sets this before sc_seq_run()/sc_pd_*; the portable code treats it   */
/* as read-only.                                                        */
extern const sc_hal_t *sc_hal;

/* Convenience wrappers (header-only) so call sites stay terse and the  */
/* NULL-op guards live in exactly one place.                            */
static inline void sc_delay_ms(uint32_t ms) { sc_hal->delay_ms(ms); }
static inline uint32_t sc_uptime_ms(void) { return sc_hal->uptime_ms(); }
static inline int sc_gpio_set(sc_gpio_t io, bool lvl) {
    return sc_hal->gpio_set(io, lvl);
}
static inline int sc_gpio_get(sc_gpio_t io, bool *lvl) {
    return sc_hal->gpio_get(io, lvl);
}
static inline int sc_i2c_write(uint8_t a, uint8_t *b, size_t n) {
    return sc_hal->i2c_xfer(a, SC_I2C_WRITE, b, n);
}
static inline int sc_i2c_read(uint8_t a, uint8_t *b, size_t n) {
    return sc_hal->i2c_xfer(a, SC_I2C_READ, b, n);
}
static inline void sc_log(const char *msg) {
    if (sc_hal->log) sc_hal->log(msg);
}

/* ======================================================================== */
/* ZEPHYR PORT NOTE  (how this drops into a Zephyr app)                     */
/* ======================================================================== */
/*
 * The portable code is Zephyr-agnostic; a Zephyr port is one .c file
 * (sc_hal_zephyr.c, shipped here as a COMMENTED reference) plus the
 * board glue below.  Nothing in this directory includes a zephyr/
 * header.
 *
 * 1. Kconfig: the SC app selects
 *      CONFIG_GPIO=y
 *      CONFIG_I2C=y          (or bit-bang: CONFIG_I2C_GPIO=y, since the
 *                             contract bit-bangs I2C2 on PA4/PA5 -- see
 *                             ZC_I2C_BITBANG_ in the contract header)
 *      CONFIG_WATCHDOG=n      (the TPS3823 is EXTERNAL; the SC only
 *                             strobes WDI through a GPIO -- C2)
 *
 * 2. Devicetree overlay (app.overlay): expose the buses/lines the HAL
 *    port resolves with DEVICE_DT_GET / GPIO_DT_SPEC_GET.  A minimal
 *    overlay for THIS board's contract (// = overlay remarks):
 *
 *      / {
 *          sc_ctrl {
 *              compatible = "zynq,carrier-sc";
 *              i2c = <&i2c_sc>;          // bit-bang I2C2 (PA4/PA5)
 *              wdi-gpios = <&gpioX PIN GPIO_ACTIVE_HIGH>;  // TPS3823 WDI
 *          };
 *      };
 *      // GPIO bit-bang I2C on the DAC pins, per ZC_I2C_BITBANG_
 *      i2c_sc: i2c-gpio {
 *          compatible = "i2c-gpio";
 *          sda-gpios = <&gpioa 4 (GPIO_OPEN_DRAIN | GPIO_PULL_UP)>;
 *          scl-gpios = <&gpioa 5 (GPIO_OPEN_DRAIN | GPIO_PULL_UP)>;
 *          #address-cells = <1>;
 *          #size-cells = <0>;
 *      };
 *
 * 3. HAL port (sc_hal_zephyr.c): implement sc_hal_t over the Zephyr
 *    GPIO + I2C APIs and publish `sc_hal`.  The ('port','pin') pair in
 *    sc_gpio_t maps onto a Zephyr gpio_dt_spec via a small lookup the
 *    port owns (one DEVICE_DT_GET per GPIO bank).  A skeleton ships as
 *    sc_hal_zephyr.c.txt in this directory (commented so the tree stays
 *    toolchain-agnostic).
 */

#endif /* SC_HAL_H */
)BRINGUP";
inline constexpr const char scfw_tables_begin[] = R"BRINGUP(#ifndef SC_TABLES_H
#define SC_TABLES_H

#include <stdint.h>
#include <stdbool.h>
#include "sc_hal.h"

/* ======================================================================== */
/* Rail bring-up step table (order = the regulator chain)                   */
/* ======================================================================== */
/* The order below IS the power.py regulator chain: each stage's     */
/* input is the previous stage's output, so it is not optional       */
/* (BRINGUP.md Stage 2).  The always-on rails (+3V3_SC + the inlet)   */
/* are listed separately -- they are up before any sequencing runs.  */
typedef enum {
)BRINGUP";
inline constexpr const char scfw_rail_struct[] = R"BRINGUP(} sc_rail_id_t;

/* One sequenced rail stage.  `en_override` is the SC's VETO GPIO on   */
/* the EN cell (EN = DIP AND override): drive it LOW to force the rail */
/* OFF, leave it HIGH/Hi-Z to let the DIP rule.  Software can NEVER    */
/* force a rail ON with its DIP open (bringup_en semantics).  `pg_*`   */
/* is the INA3221 telemetry the stepper polls to confirm the rail.     */
typedef struct {
    sc_rail_id_t id;
    const char  *name;          /* rail net, e.g. "+5V" */
    uint32_t     vout_mv;       /* expected setpoint [mV] */
    const char  *en_net;        /* EN_* cell output net */
    sc_gpio_t    en_override;   /* SC veto GPIO (port=0 if none) */
    uint16_t     settle_ms;     /* wait after enable before PG poll */
    uint8_t      pmon_addr7;    /* INA3221 7-bit addr (0 = no telem) */
    uint8_t      pmon_channel;  /* INA3221 channel 1..3 */
    uint16_t     shunt_mohm;    /* sense-shunt value [mOhm] */
} sc_rail_step_t;

extern const sc_rail_step_t sc_rail_steps[SC_RAIL_COUNT];

/* The always-on rails -- present before any sequencing (BRINGUP.md    */
/* Stage 1: +3V3_SC is generated from VIN before PD negotiation).      */
)BRINGUP";
inline constexpr const char scfw_module_begin[] = R"BRINGUP(extern const char *const sc_always_on_rails[SC_ALWAYS_ON_COUNT];

/* ======================================================================== */
/* Module load-switch gate table (SY6280, current-limited)                  */
/* ======================================================================== */
/* Each module rail is gated by a SY6280 behind its own EN cell and  */
/* current limit (BRINGUP.md Stage 3/4).  These are enabled AFTER    */
/* the core rails, one at a time, with the same veto semantics.      */
typedef enum {
)BRINGUP";
inline constexpr const char scfw_module_struct[] = R"BRINGUP(} sc_module_id_t;

/* `tca_bit` is the bit index in the TCA9535 16-bit output word that   */
/* drives this module's override (P00=0 .. P17=15); 0xFF = direct GPIO */
/* (none routed through the expander).                                 */
typedef struct {
    sc_module_id_t id;
    const char    *module;      /* "HDMI_TX" ... */
    const char    *rail_in;     /* source rail */
    const char    *rail_out;    /* gated rail */
    const char    *en_net;      /* EN_* cell output */
    uint16_t       ilim_ma;     /* SY6280 current limit [mA] */
    uint8_t        tca_bit;     /* TCA9535 output bit (0xFF if direct) */
} sc_module_gate_t;

extern const sc_module_gate_t sc_module_gates[SC_MOD_COUNT];

/* ======================================================================== */
/* I2C device map (bus = STM32_I2C2; 7-bit addresses)                       */
/* ======================================================================== */
/* The bus is a firmware BIT-BANG on PA4/PA5 (the contract's         */
/* ZC_I2C_BITBANG_* lines): the real I2C2 AF pins are the on-module  */
/* SC<->Zynq link.  Addresses come straight from the contract header.*/
typedef struct {
    const char *name;
    uint8_t     addr7;
} sc_i2c_dev_t;

)BRINGUP";
inline constexpr const char scfw_tables_end[] = R"BRINGUP(extern const sc_i2c_dev_t sc_i2c_devices[SC_I2C_DEV_COUNT];

#endif /* SC_TABLES_H */
)BRINGUP";
inline constexpr const char scfw_seq_h[] = R"BRINGUP(#ifndef SC_SEQ_H
#define SC_SEQ_H

#include <stdint.h>
#include <stdbool.h>
#include "sc_tables.h"

/* The bring-up state machine -- mirrors BRINGUP.md staging:        */
/*   IDLE -> always-on assumed up -> sequence core rails -> modules */
/* Each step enables one rail/gate, waits settle_ms, then confirms  */
/* via telemetry before advancing.  C2: the watchdog is NOT armed   */
/* anywhere in this sequence (see sc_wdt.h).                         */
typedef enum {
    SC_SEQ_IDLE = 0,
    SC_SEQ_RAILS,        /* sequencing the core regulator chain */
    SC_SEQ_MODULES,      /* enabling the module load switches */
    SC_SEQ_DONE,
    SC_SEQ_FAULT,
} sc_seq_phase_t;

typedef struct {
    sc_seq_phase_t phase;
    uint8_t        index;     /* step within the current phase */
    const char    *fault_net; /* set when phase == SC_SEQ_FAULT */
} sc_seq_state_t;

/* Enable policy for a rail/module: the SC VETO defaults to "let the */
/* DIP rule" (override HIGH/Hi-Z).  A caller may force a rail OFF by */
/* returning false here; it can never force one ON (DIP AND ovr).   */
typedef bool (*sc_enable_policy_t)(const char *en_net);

/* Initialise the sequencer state (does NOT touch hardware). */
void sc_seq_init(sc_seq_state_t *st);

/* Advance the sequence by one step.  Returns true while more steps   */
/* remain (call again after the returned settle), false when DONE or  */
/* FAULT.  `policy` may be NULL (then every rail follows its DIP).    */
bool sc_seq_step(sc_seq_state_t *st, sc_enable_policy_t policy);

/* Drive the whole sequence to completion (blocking, uses the HAL     */
/* delay for the per-stage settle).  Returns 0 on SC_SEQ_DONE, <0 on  */
/* SC_SEQ_FAULT.  This is the simplest entry point for a bring-up app.*/
int sc_seq_run(sc_enable_policy_t policy);

#endif /* SC_SEQ_H */
)BRINGUP";
inline constexpr const char scfw_seq_c[] = R"BRINGUP(#include "zynq_carrier_contract.h"
#include "sc_hal.h"
#include "sc_tables.h"
#include "sc_seq.h"

/* Drive a rail/module EN override.  The override is a VETO that is     */
/* ACTIVE-LOW: HIGH/Hi-Z lets the DIP enable the rail, LOW forces OFF.  */
/* A port=0 GPIO means "no SC veto wired" -- the DIP is sole owner.    */
static int sc_drive_override(sc_gpio_t io, bool want_on) {
    if (io.port == 0) return 0;            /* no veto line: DIP rules */
    /* want_on -> release the veto (HIGH); !want_on -> assert (LOW).   */
    return sc_gpio_set(io, want_on);
}

/* Confirm a rail by reading its INA3221 bus-voltage channel, if one is */
/* mapped.  This is a STUB hook: the INA3221 register read lives in the */
/* platform/driver layer -- here we only gate on telemetry presence so  */
/* the portable sequencing logic is complete and testable.  A port may  */
/* override sc_rail_is_good() to do the real read.                      */
bool __attribute__((weak)) sc_rail_is_good(const sc_rail_step_t *step) {
    if (step->pmon_addr7 == 0) return true;   /* untelemetered: trust */
    /* TODO(port): read INA3221 (step->pmon_addr7, step->pmon_channel)  */
    /* bus-voltage reg and compare against step->vout_mv with margin.   */
    (void)step;
    return true;
}

void sc_seq_init(sc_seq_state_t *st) {
    st->phase = SC_SEQ_RAILS;
    st->index = 0;
    st->fault_net = NULL;
}

static bool sc_policy_allows(sc_enable_policy_t policy, const char *en) {
    return policy ? policy(en) : true;
}

bool sc_seq_step(sc_seq_state_t *st, sc_enable_policy_t policy) {
    switch (st->phase) {
    case SC_SEQ_RAILS: {
        if (st->index >= SC_RAIL_COUNT) {
            st->phase = SC_SEQ_MODULES;
            st->index = 0;
            return true;
        }
        const sc_rail_step_t *step = &sc_rail_steps[st->index];
        bool want = sc_policy_allows(policy, step->en_net);
        sc_log(step->name);
        if (sc_drive_override(step->en_override, want) != 0) {
            st->phase = SC_SEQ_FAULT;
            st->fault_net = step->en_net;
            return false;
        }
        if (want) {
            sc_delay_ms(step->settle_ms);
            if (!sc_rail_is_good(step)) {
                st->phase = SC_SEQ_FAULT;
                st->fault_net = step->name;
                return false;
            }
        }
        st->index++;
        return true;
    }
    case SC_SEQ_MODULES: {
        if (st->index >= SC_MOD_COUNT) {
            st->phase = SC_SEQ_DONE;
            return false;
        }
        const sc_module_gate_t *g = &sc_module_gates[st->index];
        bool want = sc_policy_allows(policy, g->en_net);
        sc_log(g->module);
        /* Module overrides ride the TCA9535 output word (g->tca_bit);  */
        /* the expander write lives in the platform layer.  A direct    */
        /* (0xFF) gate would drive a GPIO here instead.  Either way the */
        /* DIP still gates the SY6280 -- the SC only vetoes.            */
        (void)want;
        st->index++;
        return true;
    }
    case SC_SEQ_IDLE:
    case SC_SEQ_DONE:
    case SC_SEQ_FAULT:
    default:
        return false;
    }
}

int sc_seq_run(sc_enable_policy_t policy) {
    sc_seq_state_t st;
    sc_seq_init(&st);
    /* C2: do NOT arm/kick the watchdog here -- bring-up must complete  */
    /* first; the caller arms it afterwards (see sc_wdt.h / sc_app.c).  */
    while (sc_seq_step(&st, policy)) {
        /* settle handled inside the step */
    }
    return (st.phase == SC_SEQ_DONE) ? 0 : -1;
}
)BRINGUP";
inline constexpr const char scfw_wdt_h[] = R"BRINGUP(#ifndef SC_WDT_H
#define SC_WDT_H

#include <stdbool.h>
#include "sc_hal.h"

/* The TPS3823 (board_services) is an EXTERNAL watchdog: the SC keeps  */
/* it happy by STROBING its WDI line.  C2 (project constraint): the    */
/* watchdog must NOT be armed or kicked DURING the power-up sequence,  */
/* only AFTER bring-up has completed -- otherwise a slow rail ramp     */
/* would trip a board reset mid-sequence.  sc_wdt_arm() therefore sets */
/* a latch that sc_wdt_kick() checks; kicks before arming are no-ops.  */

/* Arm the watchdog supervision.  Call ONLY after sc_seq_run() returns  */
/* success -- never inside the bring-up sequence (C2).                  */
void sc_wdt_arm(void);

/* True once armed -- the bring-up code asserts !sc_wdt_is_armed()      */
/* while sequencing.                                                    */
bool sc_wdt_is_armed(void);

/* Strobe the TPS3823 WDI.  A no-op until sc_wdt_arm() has been called  */
/* (C2 guard), so a stray kick during power-up cannot start the timer. */
void sc_wdt_kick(void);

#endif /* SC_WDT_H */
)BRINGUP";
inline constexpr const char scfw_wdt_c[] = R"BRINGUP(#include "sc_hal.h"
#include "sc_wdt.h"

/* C2 latch: false until sc_wdt_arm(); kicks before arming are no-ops. */
static bool s_wdt_armed = false;

void sc_wdt_arm(void) {
    s_wdt_armed = true;
    sc_log("watchdog armed (post-bring-up)");
}

bool sc_wdt_is_armed(void) {
    return s_wdt_armed;
}

void sc_wdt_kick(void) {
    if (!s_wdt_armed) return;          /* C2: no kicks during power-up */
    if (sc_hal->wdt_strobe) sc_hal->wdt_strobe();
}
)BRINGUP";
inline constexpr const char scfw_pd_h[] = R"BRINGUP(#ifndef SC_PD_H
#define SC_PD_H

#include <stdint.h>
#include <stdbool.h>
#include "sc_hal.h"

/* The FUSB302B (usb_pd) is a PD PHY ONLY -- it does not negotiate by  */
/* itself.  Reaching the higher-voltage USB-C contract (so +VIN rises  */
/* from the 5 V default to the negotiated voltage) requires the SC to  */
/* run PD policy through the FUSB302B over I2C (BRINGUP.md Stage 1).   */
/* These are the ENTRY POINTS a PD stack (e.g. the Zephyr USB-C        */
/* subsystem or a vendored tcpm) plugs into; the protocol itself is    */
/* out of scope for this scaffold -- the hooks make the integration    */
/* point explicit and netlist-anchored (address from the contract).    */

/* Bring the FUSB302B out of reset and verify it answers on I2C.       */
/* Returns 0 on success.                                               */
int sc_pd_init(void);

/* Request a power contract of at least `min_mv` / `min_ma`.  Returns 0 */
/* once a matching contract is accepted, <0 on timeout/failure.  The   */
/* body is a STUB -- wire it to your PD policy engine.                  */
int sc_pd_request(uint32_t min_mv, uint32_t min_ma);

/* Service a PD interrupt (the FUSB302B INT is wire-ORed into SC_INT_N */
/* with the TCA9535 INT# -- read BOTH status registers on the IRQ).    */
void sc_pd_on_irq(void);

#endif /* SC_PD_H */
)BRINGUP";
inline constexpr const char scfw_pd_c[] = R"BRINGUP(#include "zynq_carrier_contract.h"
#include "sc_hal.h"
#include "sc_pd.h"

/* FUSB302B 7-bit address straight from the hardware contract.         */
#define SC_PD_FUSB302B_ADDR  ZC_I2C_ADDR_FUSB302B

int sc_pd_init(void) {
    /* A 1-byte read of the Device ID register (0x01) probes presence.  */
    uint8_t reg = 0x01;
    uint8_t id = 0;
    if (sc_i2c_write(SC_PD_FUSB302B_ADDR, &reg, 1) != 0) return -1;
    if (sc_i2c_read(SC_PD_FUSB302B_ADDR, &id, 1) != 0) return -1;
    sc_log("FUSB302B present");
    return 0;
}

int sc_pd_request(uint32_t min_mv, uint32_t min_ma) {
    /* TODO(port): drive a PD Request through the FUSB302B for a source */
    /* capability that meets (min_mv, min_ma).  Until a PD stack runs   */
    /* this, +VIN stays at the 5 V default contract (BRINGUP.md St.1).  */
    (void)min_mv; (void)min_ma;
    return -1;
}

void sc_pd_on_irq(void) {
    /* SC_INT_N is the wire-OR of FUSB302B INT and TCA9535 INT#; the    */
    /* handler reads BOTH devices' status registers (contract note).    */
    /* TODO(port): read FUSB302B Interrupt regs and dispatch to policy. */
}
)BRINGUP";
inline constexpr const char scfw_rtc_h[] = R"BRINGUP(#ifndef SC_RTC_H
#define SC_RTC_H

#include "sc_hal.h"

/* board_services fits a RECHARGEABLE ML1220 (Mn-Li) on the RV-3028's    */
/* VBACKUP for a maintenance-free RTC.  A rechargeable cell only stays    */
/* charged if firmware ENABLES the RV-3028's internal trickle charger     */
/* (TCE + a series resistance in the EEPROM Backup register) -- so the    */
/* cell tops up whenever the board is powered (contract ZC_I2C_ADDR_RTC). */
/* This is the netlist-anchored entry point that makes the ML1220 choice  */
/* real; without it the cell would slowly deplete.                        */

/* Probe the RV-3028 on the AUX I2C and enable the trickle charger.       */
/* Returns 0 on success.  Best-effort: the RTC is on the gated +3V3_AUX   */
/* rail, so call it once that rail + its I2C isolator are up.             */
int sc_rtc_init(void);

/* Enable the trickle charger only (TCE + ~3k + backup switchover),       */
/* committing it to the config EEPROM.  Returns 0 on success.            */
int sc_rtc_trickle_enable(void);

#endif /* SC_RTC_H */
)BRINGUP";
inline constexpr const char scfw_rtc_c[] = R"BRINGUP(#include "zynq_carrier_contract.h"
#include "sc_hal.h"
#include "sc_rtc.h"

#define SC_RTC_ADDR         ZC_I2C_ADDR_RTC   /* RV-3028, 7-bit 0x52 */

/* RV-3028-C7 registers (Micro Crystal Application Manual). */
#define SC_RTC_REG_CTRL1    0x0Fu   /* EERD = bit 3 (auto-refresh dis.) */
#define SC_RTC_REG_EECMD    0x27u   /* EEPROM command */
#define SC_RTC_REG_ID       0x28u   /* device ID (presence probe) */
#define SC_RTC_REG_EEBACKUP 0x37u   /* EEPROM Backup (RAM mirror) */

/* EEPROM Backup register bit fields -- RV-3028-C7 Application Manual
 * Rev 1.4, 'EEPROM Backup Register' (cross-checked against the constiko
 * RV-3028-C7 Arduino library): TCE=bit5, FEDE=bit4, BSM=bits3:2,
 * TCR=bits1:0.  Re-confirm if your part revision differs. */
#define SC_RTC_TCR_MASK     (0x3u << 0)  /* trickle R: 00=3k 01=5k 10=9k 11=15k */
#define SC_RTC_TCR_3K       (0x0u << 0)  /* ~3k -> gentle ML1220 trickle @3.3V */
#define SC_RTC_BSM_LSM      (0x3u << 2)  /* Backup Switchover: Level Switching */
#define SC_RTC_FEDE         (0x1u << 4)  /* Fast Edge Detect (DS default 1) */
#define SC_RTC_TCE          (0x1u << 5)  /* Trickle Charge Enable */

#define SC_RTC_CTRL1_EERD   (0x1u << 3)  /* 1 = disable auto EEPROM refresh */
#define SC_RTC_EECMD_UPDATE 0x11u        /* 'update all configuration EEPROM' */

static int rtc_w(uint8_t reg, uint8_t val) {
    uint8_t b[2] = { reg, val };
    return sc_i2c_write(SC_RTC_ADDR, b, 2);
}
static int rtc_r(uint8_t reg, uint8_t *val) {
    if (sc_i2c_write(SC_RTC_ADDR, &reg, 1) != 0) return -1;
    return sc_i2c_read(SC_RTC_ADDR, val, 1);
}

int sc_rtc_trickle_enable(void) {
    uint8_t bk = 0, c1 = 0;
    /* 1. read the current Backup register (its RAM mirror). */
    if (rtc_r(SC_RTC_REG_EEBACKUP, &bk) != 0) return -1;
    /* 2. set TCE + 3k series + fast-edge + level switchover, preserving
     *    every other bit (read-modify-write, not a raw value). */
    bk &= (uint8_t)~SC_RTC_TCR_MASK;
    bk |= (uint8_t)(SC_RTC_TCE | SC_RTC_FEDE | SC_RTC_BSM_LSM | SC_RTC_TCR_3K);
    /* 3. disable auto config-EEPROM refresh (EERD=1) before the update. */
    if (rtc_r(SC_RTC_REG_CTRL1, &c1) != 0) return -1;
    if (rtc_w(SC_RTC_REG_CTRL1, (uint8_t)(c1 | SC_RTC_CTRL1_EERD)) != 0) return -1;
    /* 4. write the new value into the RAM mirror. */
    if (rtc_w(SC_RTC_REG_EEBACKUP, bk) != 0) return -1;
    /* 5. commit RAM -> EEPROM: EECMD 0x00 then 0x11 (update all config). */
    if (rtc_w(SC_RTC_REG_EECMD, 0x00u) != 0) return -1;
    if (rtc_w(SC_RTC_REG_EECMD, SC_RTC_EECMD_UPDATE) != 0) return -1;
    sc_delay_ms(20);   /* config-EEPROM write latency (~16 ms typ). */
    /* 6. re-enable auto refresh (EERD=0). */
    if (rtc_w(SC_RTC_REG_CTRL1, (uint8_t)(c1 & ~SC_RTC_CTRL1_EERD)) != 0) return -1;
    sc_log("RV-3028 trickle charger enabled (ML1220, ~3k)");
    return 0;
}

int sc_rtc_init(void) {
    uint8_t id = 0;
    if (rtc_r(SC_RTC_REG_ID, &id) != 0) return -1;   /* presence probe */
    sc_log("RV-3028 present");
    return sc_rtc_trickle_enable();
}
)BRINGUP";
inline constexpr const char scfw_app[] = R"BRINGUP(#include "sc_hal.h"
#include "sc_seq.h"
#include "sc_pd.h"
#include "sc_rtc.h"
#include "sc_wdt.h"

/* A reference bring-up flow that ties the scaffold together.  A real  */
/* app supplies its own main() / Zephyr thread and the sc_hal port;    */
/* this shows the C2-correct ORDER: rails -> modules -> THEN arm WDT.  */
int sc_bringup_main(void) {
    sc_log("SC bring-up: sequencing rails (DIP-gated, SC veto only)");
    /* PD negotiation is optional here: the board runs reduced on the  */
    /* 5 V default contract until a PD stack lifts +VIN.               */
    (void)sc_pd_init();

    /* C2: the watchdog is NOT armed yet -- sequence first. */
    if (sc_seq_run(/*policy=*/NULL) != 0) {
        sc_log("bring-up FAULT -- leaving watchdog disarmed");
        return -1;
    }

    /* Bring-up complete: NOW it is safe to arm the watchdog (C2). */
    sc_wdt_arm();

    /* RTC: enable the RV-3028 trickle charger so the rechargeable ML1220 */
    /* backup cell tops up.  Best-effort -- the RTC is on the gated AUX   */
    /* rail, so this only takes once that rail + its I2C isolator are up. */
    (void)sc_rtc_init();

    sc_log("SC bring-up complete; watchdog armed");
    return 0;
}
)BRINGUP";
inline constexpr const char scfw_zephyr[] = R"BRINGUP(/*
 * sc_hal_zephyr.c.txt -- REFERENCE Zephyr HAL port (NOT compiled).
 *
 * GENERATED by `schgen scfw` -- DO NOT EDIT.
 *
 * Shipped with a .txt suffix so the firmware/sc/ tree stays strictly
 * toolchain-agnostic (nothing here includes a zephyr/ header).  Copy
 * it to sc_hal_zephyr.c in your Zephyr app, uncomment, and fix the GPIO
 * bank lookup to your board's devicetree.  It implements sc_hal_t over
 * the Zephyr GPIO + I2C APIs and publishes `sc_hal`.
 */
#if 0   /* enable in a Zephyr build */
#include <zephyr/kernel.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/drivers/i2c.h>
#include "sc_hal.h"

/* One device handle per STM32 GPIO bank the contract uses; the HAL    */
/* maps an sc_gpio_t ('A'..'G', pin) onto (bank, pin).                 */
static const struct device *gpio_bank(char port) {
    switch (port) {
    case 'A': return DEVICE_DT_GET(DT_NODELABEL(gpioa));
    case 'B': return DEVICE_DT_GET(DT_NODELABEL(gpiob));
    case 'C': return DEVICE_DT_GET(DT_NODELABEL(gpioc));
    /* ... D..G as the board provides ... */
    default:  return NULL;
    }
}

static const struct device *i2c_bus =
    DEVICE_DT_GET(DT_NODELABEL(i2c_sc));   /* the bit-bang I2C (PA4/PA5) */

static void z_delay_ms(uint32_t ms) { k_msleep(ms); }
static uint32_t z_uptime_ms(void) { return (uint32_t)k_uptime_get(); }

static int z_gpio_cfg_out(sc_gpio_t io, bool od) {
    gpio_flags_t f = GPIO_OUTPUT | (od ? GPIO_OPEN_DRAIN : 0);
    return gpio_pin_configure(gpio_bank(io.port), io.pin, f);
}
static int z_gpio_cfg_in(sc_gpio_t io, bool pu) {
    gpio_flags_t f = GPIO_INPUT | (pu ? GPIO_PULL_UP : 0);
    return gpio_pin_configure(gpio_bank(io.port), io.pin, f);
}
static int z_gpio_set(sc_gpio_t io, bool lvl) {
    return gpio_pin_set(gpio_bank(io.port), io.pin, lvl);
}
static int z_gpio_get(sc_gpio_t io, bool *lvl) {
    int v = gpio_pin_get(gpio_bank(io.port), io.pin);
    if (v < 0) return v; *lvl = (v != 0); return 0;
}
static int z_i2c_xfer(uint8_t addr7, sc_i2c_dir_t dir,
                      uint8_t *buf, size_t len) {
    return (dir == SC_I2C_READ)
        ? i2c_read(i2c_bus, buf, len, addr7)
        : i2c_write(i2c_bus, buf, len, addr7);
}
static int z_wdt_strobe(void) {
    /* toggle the TPS3823 WDI gpio (wdi-gpios in the overlay) */
    return 0;
}
static void z_log(const char *msg) { printk("[sc] %s\n", msg); }

static const sc_hal_t z_hal = {
    .delay_ms = z_delay_ms, .uptime_ms = z_uptime_ms,
    .gpio_configure_output = z_gpio_cfg_out,
    .gpio_configure_input = z_gpio_cfg_in,
    .gpio_set = z_gpio_set, .gpio_get = z_gpio_get,
    .i2c_xfer = z_i2c_xfer, .wdt_strobe = z_wdt_strobe, .log = z_log,
};
const sc_hal_t *sc_hal = &z_hal;
#endif /* 0 */
)BRINGUP";
inline constexpr const char scfw_readme_intro[] = R"BRINGUP(# SC bring-up firmware scaffold (GENERATED)

> GENERATED by `schgen scfw` (schgen/generate/scfw.py) -- DO NOT EDIT.
> Regenerate: `PYTHONPATH=. python -m schgen scfw`.  Every table value
> is read from the authored carrier netlists via `bringup_facts` (and
> through it the live SoM U9 pin map); nothing is hand-typed.

Portable-C bring-up firmware for the SoM STM32 system controller
)BRINGUP";
inline constexpr const char scfw_readme_roles[] = R"BRINGUP((`../zynq_carrier_contract.h`, from `schgen firmware`) and automates
the staged procedure in `../../docs/BRINGUP.md`.

## Toolchain-agnostic by construction

No file here `#include`s a Zephyr (or any platform) header.  The
portable code calls the `sc_hal` op table (`sc_hal.h`); a platform
port implements that table.  A Zephyr reference port ships as
`sc_hal_zephyr.c.txt` (a `.txt` so the tree stays platform-free) plus
the devicetree-overlay / Kconfig notes in `sc_hal.h`.

## Files

| file | role |
|---|---|
| `sc_hal.h` | the platform-op abstraction + the Zephyr port note |
| `sc_tables.h` / `sc_tables.c` | netlist-derived tables: rail step table, module gates, I2C device map |
| `sc_seq.h` / `sc_seq.c` | the portable rail-sequencing state machine (step table + stepper) |
| `sc_wdt.h` / `sc_wdt.c` | TPS3823 watchdog kick, with the C2 power-up guard |
| `sc_pd.h` / `sc_pd.c` | FUSB302B PD negotiate entry points (hooks) |
| `sc_app.c` | a reference bring-up flow tying it together (C2-correct order) |
| `sc_hal_zephyr.c.txt` | commented reference Zephyr HAL port |

## Derived rail-sequencing order

Read from the `power.py` regulator chain (each stage feeds the next):

)BRINGUP";
inline constexpr const char scfw_readme_modules[] = R"BRINGUP(
Then the SY6280 module load switches, one at a time:

)BRINGUP";
inline constexpr const char scfw_readme_end[] = R"BRINGUP(
## C2 -- watchdog not during power-up

The TPS3823 is an external supervisor; the SC only strobes its WDI.
Per project constraint C2, `sc_wdt_kick()` is a no-op until
`sc_wdt_arm()` is called, and `sc_seq_run()` never arms it -- so a
slow rail ramp cannot trip a reset mid-bring-up.  `sc_app.c` shows the
correct order: sequence rails + modules, **then** `sc_wdt_arm()`.

## Building (host syntax check)

```sh
gcc -std=c11 -fsyntax-only -I. -I.. sc_tables.c sc_seq.c sc_wdt.c \
    sc_pd.c sc_app.c
```

A platform port (`sc_hal_*.c`) provides `sc_hal`; the portable objects
above link against it.

)BRINGUP";
} // namespace schgen::bringup_text
