#include "schgen/firmware_docs.hpp"
#include "schgen/firmware_provenance.hpp"
#include "bringup_internal.hpp"
#include "firmware_docs_templates.hpp"

namespace schgen {
using namespace bringup_detail;
using namespace bringup_text;
namespace {
std::string file_header(const std::string& name,const std::string& what,const FirmwareDocsInput& in) {
    std::ostringstream o;
    o<<"/*\n * "<<name<<" -- "<<what<<"\n *\n * GENERATED by `native/bin/schgen scfw` (native/src/firmware_docs_scfw.cpp) -- DO NOT EDIT.\n * regenerate: "
     <<firmware_native_regeneration_command("scfw")
     <<"\n * Run from the repository root; replace PROJECT_DIR with your project path.\n *\n * system controller: "<<in.stm32.value<<" (from the SoM U9 netlist)\n *\n * Portable C behind the sc_hal abstraction -- this file #includes NO\n * platform/Zephyr headers; a HAL port (e.g. sc_hal_zephyr.c) backs it.\n * sources:\n";
    o<<" *   ../zynq_carrier_contract.h (the SC hardware contract)\n";
    for(const auto& source:in.firmware_sources)o<<" *   "<<source<<'\n';
    o<<" *   ../../docs/BRINGUP.md (the staged procedure this automates)\n";
    o<<" */\n";return o.str();
}
std::string rail_enum(const std::string& rail) {
    auto ident=bringup_c_ident(rail);auto p=ident.find_first_not_of('_');return "SC_RAIL_"+(p==std::string::npos?"":ident.substr(p));
}
std::string module_enum(const std::string& enable) {return "SC_MOD_"+bringup_c_ident(remove_prefix(enable,"EN_"));}
}
std::vector<FirmwareDocArtifact> render_scfw(const FirmwareDocsInput& in) {
    const auto absent=scfw_missing_requirements(in);
    if(!absent.empty())throw FirmwareDocsError("missing required subsystems: "+join(absent,", "));
    const auto& pmon=required(in,"power_mon");
    const auto chain=regulator_chain(required(in,"power"),"+VIN",&pmon);
    const auto rail_cells=cells(sheet(in,"bringup_en"));const auto gates=module_gates(required(in,"bringup_modules"));
    const auto exp=bringup_expander(required(in,"bringup_rails"));const auto monitors=ina3221_monitors(pmon);
    const auto& usb=required(in,"usb_pd");
    if(!std::any_of(usb.parts.begin(),usb.parts.end(),[](const auto& p){return has(p.value,"FUSB302");}))throw FirmwareDocsError("usb_pd netlist no longer carries a FUSB302 -- the PD hooks would be stale");
    const auto& services=required(in,"board_services");
    if(!std::any_of(services.parts.begin(),services.parts.end(),[](const auto& p){return has(p.value,"TPS3823")||has(p.lib_id,"TPS3823");}))throw FirmwareDocsError("board_services no longer carries a TPS3823 -- the watchdog hooks would be stale");
    std::set<std::string> produced,always_on;for(const auto& st:chain){produced.insert(st.rail_out);always_on.insert(st.rail_in);}
    for(const auto& r:produced)always_on.erase(r);always_on.insert("+3V3_SC");
    const auto mod_cells=cells(sheet(in,"bringup_en_modules"));std::map<std::string,int> bits;
    for(const auto& [pname,net]:exp.ports)for(const auto& g:gates) {
        auto cell=mod_cells.find(g.enable);if(cell!=mod_cells.end()&&cell->second.override_net==net)bits[g.enable]=(pname[1]-'0')*8+pname[2]-'0';
    }
    ProjectStrings addresses{{"ZC_I2C_ADDR_TCA9535","bring-up override expander (TCA9535)"},{"ZC_I2C_ADDR_FUSB302B","USB-PD PHY (FUSB302B)"}};
    for(std::size_t k=0;k<monitors.size();++k)addresses.emplace_back("ZC_I2C_ADDR_INA3221_"+std::to_string(k+1),"rail monitor #"+std::to_string(k+1)+" (INA3221)");
    // Scan only devices declared by the generated hardware contract. The FMC
    // connector does not establish a fitted EEPROM or its address; do not
    // invent a mezzanine address. All values below resolve from the real
    // zynq_carrier_contract.h included by sc_tables.c.
    addresses.emplace_back("ZC_I2C_ADDR_ID_EEPROM","board-ID EEPROM (EUI-48 MAC; AUX bus)");addresses.emplace_back("ZC_I2C_ADDR_RTC","RTC RV-3028 (AUX bus)");
    std::vector<FirmwareDocArtifact> out;
    const auto add=[&](const std::string& name,const std::string& what,const std::string& body){out.push_back({name,ascii(file_header(name,what,in)+body)});};
    add("sc_hal.h","SC firmware HAL abstraction (platform ops)",scfw_hal);
    std::ostringstream h;
    h<<scfw_tables_begin;for(const auto& st:chain)h<<"    "<<rail_enum(st.rail_out)<<",\n";
    h<<"    SC_RAIL_COUNT  /* = "<<chain.size()<<" */\n"<<scfw_rail_struct;
    h<<"#define SC_ALWAYS_ON_COUNT "<<always_on.size()<<'\n'<<scfw_module_begin;
    for(const auto& g:gates)h<<"    "<<module_enum(g.enable)<<",\n";
    h<<"    SC_MOD_COUNT  /* = "<<gates.size()<<" */\n"<<scfw_module_struct;
    h<<"#define SC_I2C_DEV_COUNT "<<addresses.size()<<'\n'<<scfw_tables_end;
    add("sc_tables.h","netlist-derived SC tables (rails, I2C, EN map, monitors)",h.str());
    std::ostringstream c;c<<"#include \"zynq_carrier_contract.h\"\n#include \"sc_tables.h\"\n\nconst sc_rail_step_t sc_rail_steps[SC_RAIL_COUNT] = {\n";
    for(std::size_t k=0;k<chain.size();++k) {
        const auto& st=chain[k];auto cell=rail_cells.find(st.enable);std::string ovr="{ .port = 0, .pin = 0 }";
        if(cell!=rail_cells.end()&&!lookup(rail_override_gpio,cell->second.override_net).empty())ovr="{ .port = ZC_RAIL"+std::to_string(k)+"_OVERRIDE_GPIO_PORT, .pin = ZC_RAIL"+std::to_string(k)+"_OVERRIDE_GPIO_PIN }";
        std::string addr="0";int channel=0,shunt=0;bool found=false;
        for(std::size_t m=0;m<monitors.size()&&!found;++m)for(const auto& [ch,nets]:monitors[m].channels)
            if(nets.second==st.rail_out&&!(nets.first=="GND"&&nets.second=="GND")){addr="ZC_I2C_ADDR_INA3221_"+std::to_string(m+1);channel=ch;shunt=bringup_shunt_mohm(pmon,nets.first,nets.second).value_or(0);found=true;break;}
        c<<"    {\n        .id = "<<rail_enum(st.rail_out)<<",\n        .name = \""<<st.rail_out<<"\",\n        .vout_mv = "<<(st.vout?rounded(*st.vout*1000):0)<<",\n        .en_net = \""<<st.enable<<"\",\n        .en_override = "<<ovr<<",\n        .settle_ms = 5,\n        .pmon_addr7 = "<<addr<<",\n        .pmon_channel = "<<channel<<",\n        .shunt_mohm = "<<shunt<<",\n    },\n";
    }
    c<<"};\n\nconst char *const sc_always_on_rails[SC_ALWAYS_ON_COUNT] = {\n";
    for(const auto& r:always_on)c<<"    \""<<r<<"\",\n";
    c<<"};\n\nconst sc_module_gate_t sc_module_gates[SC_MOD_COUNT] = {\n";
    for(const auto& g:gates)c<<"    {\n        .id = "<<module_enum(g.enable)<<",\n        .module = \""<<g.module<<"\",\n        .rail_in = \""<<g.rail_in<<"\",\n        .rail_out = \""<<g.rail_out<<"\",\n        .en_net = \""<<g.enable<<"\",\n        .ilim_ma = "<<g.ilim_ma.value_or(0)<<",\n        .tca_bit = "<<(bits.count(g.enable)?std::to_string(bits.at(g.enable)):"0xFF")<<",\n    },\n";
    c<<"};\n\nconst sc_i2c_dev_t sc_i2c_devices[SC_I2C_DEV_COUNT] = {\n";
    for(const auto& [macro,label]:addresses)c<<"    { \""<<label<<"\", "<<macro<<" },\n";
    c<<"};\n";
    add("sc_tables.c","netlist-derived SC tables (data)",c.str());
    add("sc_seq.h","portable rail-sequencing state machine",scfw_seq_h);
    add("sc_seq.c","portable rail-sequencing state machine (impl)",scfw_seq_c);
    add("sc_wdt.h","TPS3823 external watchdog (WDI strobe)",scfw_wdt_h);
    add("sc_wdt.c","TPS3823 external watchdog (impl)",scfw_wdt_c);
    add("sc_pd.h","FUSB302B USB-PD negotiate hooks",scfw_pd_h);
    add("sc_pd.c","FUSB302B USB-PD negotiate hooks (impl)",scfw_pd_c);
    add("sc_rtc.h","RV-3028 RTC trickle charger (ML1220 backup)",scfw_rtc_h);
    add("sc_rtc.c","RV-3028 RTC trickle charger (impl)",scfw_rtc_c);
    add("sc_app.c","example bring-up app (portable, HAL-backed)",scfw_app);
    out.push_back({"sc_hal_zephyr.c.txt",ascii(scfw_zephyr)});
    std::ostringstream r;r<<scfw_readme_intro<<"(`"<<in.stm32.value<<"`).  It consumes the hardware CONTRACT\n"<<scfw_readme_roles;
    for(std::size_t k=0;k<chain.size();++k){const auto& st=chain[k];r<<k+1<<". `"<<st.rail_in<<"` -> `"<<st.rail_out<<"` ("<<(st.vout?rounded(*st.vout*1000):0)<<" mV, EN `"<<st.enable<<"`)\n";}
    std::vector<std::string> always;for(const auto& rail:always_on)always.push_back("`"+rail+"`");
    r<<"\nAlways-on (pre-PD, up before sequencing): "<<join(always,", ")<<".\n"<<scfw_readme_modules;
    for(const auto& g:gates)r<<"- `"<<g.module<<"`: `"<<g.rail_in<<"` -> `"<<g.rail_out<<"` (EN `"<<g.enable<<"`, ILIM "<<(g.ilim_ma?std::to_string(*g.ilim_ma)+" mA":"?")<<")\n";
    r<<scfw_readme_end;out.push_back({"README.md",ascii(r.str())});return out;
}
} // namespace schgen
