#include "schgen/gallery.hpp"
#include "bringup_unicode.hpp"
#include "gallery_diagram_internal.hpp"
#include <tuple>

namespace schgen {
namespace {
using namespace document_detail;
const std::string begin_marker = "<!-- schgen:gallery -->";
const std::string end_marker = "<!-- /schgen:gallery -->";
const std::string generated = "<!-- GENERATED by "
                              "`schgen gallery`"
                              " — edits between these markers are overwritten -->";
const std::vector<std::pair<std::string, std::string>> views{
    {"3d_persp", "Perspective (front)"},
    {"3d_persp_rear", "Perspective (rear)"},
    {"3d_top", "Top"},
    {"3d_bottom", "Bottom"},
    {"3d_front", "Front edge"},
    {"3d_back", "Back edge"},
    {"3d_left", "Left edge"},
    {"3d_right", "Right edge"}};
bool contained(const fs::path &rel) {
    return !rel.empty() && (rel.begin() == rel.end() || *rel.begin() != "..");
}
std::string project_rel(const GalleryInput &in) {
    auto p = document_detail::absolute(in.project_root);
    auto rel = p.lexically_relative(document_detail::absolute(in.repository_root));
    return contained(rel) ? rel.generic_string() : p.filename().string();
}
std::string relative(const GalleryInput &in, const fs::path &dir, const std::string &target) {
    return (document_detail::absolute(in.repository_root) / target)
        .lexically_normal()
        .lexically_relative(document_detail::absolute(dir))
        .generic_string();
}
std::string image(const std::string &url, const std::string &name, int width) {
    return "[<img src=\"" + url + "\" width=\"" + std::to_string(width) + "\" alt=\"" + name +
           "\">](" + url + ")<br>**" + name + "**";
}
std::vector<std::string> grid(const std::vector<std::string> &cells, std::size_t cols) {
    std::vector<std::string> out{"| " + join(std::vector<std::string>(cols, " "), " | ") + " |"};
    std::string line = "|";
    for (std::size_t i = 0; i < cols; ++i)
        line += "---|";
    out.push_back(line);
    for (std::size_t i = 0; i < cells.size(); i += cols) {
        std::vector<std::string> row(cols, " ");
        for (std::size_t j = 0; j < cols && i + j < cells.size(); ++j)
            row[j] = cells[i + j];
        out.push_back("| " + join(row, " | ") + " |");
    }
    return out;
}
void append(std::vector<std::string> &out, const std::vector<std::string> &lines) {
    out.insert(out.end(), lines.begin(), lines.end());
}
std::vector<GallerySheet> sorted_sheets(const GalleryInput &in) {
    auto rows = in.sheets;
    std::stable_sort(rows.begin(), rows.end(), [](const auto &a, const auto &b) {
        return std::tie(a.name, a.title) < std::tie(b.name, b.title);
    });
    return rows;
}
bool duplicate(const std::string &stem) {
    auto cp = codepoints(stem);
    if (!cp.empty() && cp.back() == '\n')
        cp.pop_back(); // Python regex '$'
    std::size_t i = cp.size();
    while (i && bringup_detail::decimal_digit(cp[i - 1]) >= 0)
        --i;
    return i < cp.size() && i && cp[i - 1] == ' ';
}
std::vector<std::string> ratsnest_stems(const GalleryInput &in) {
    std::vector<std::string> out;
    for (const auto &name : in.ratsnest_files) {
        fs::path p(name);
        if (p.extension() != ".png" && name != ".png")
            continue;
        const auto stem = p.stem().string();
        if (stem != "som" && !duplicate(stem))
            out.push_back(stem);
    }
    std::sort(out.begin(), out.end());
    return out;
}
bool has(const GalleryInput &in, const std::string &stem) {
    return in.render_files.count(stem + ".png") != 0;
}
std::vector<std::string> view_lines(const GalleryInput &in, const fs::path &dir) {
    std::vector<std::string> out{"## Generated 3D board views", ""}, cells;
    for (const auto &[stem, label] : views)
        if (has(in, stem))
            cells.push_back(image(relative(in, dir, project_rel(in) + "/renders/" + stem + ".png"),
                                  label, 200));
    if (cells.empty()) {
        append(out, {"*(3D board renders pending — run "
                     "`schgen board`"
                     ".)*",
                     ""});
        return out;
    }
    out.push_back("The placed board rendered from " + std::to_string(cells.size()) +
                  " angles by "
                  "`schgen board`"
                  " (kicad-cli, the real component 3D models) — "
                  "regenerated and committed every build, just like the sheets below.");
    out.push_back("");
    append(out, grid(cells, 4));
    out.push_back("");
    return out;
}
std::vector<std::string> ratsnest_lines(const GalleryInput &in, const fs::path &dir) {
    std::vector<std::string> out{"## Ratsnest views", ""}, cells;
    const auto prefix = project_rel(in) + "/renders/";
    for (const auto &[stem, label] : std::vector<std::pair<std::string, std::string>>{
             {"ratsnest_top", "Board (top)"}, {"ratsnest_bottom", "Board (bottom)"}})
        if (has(in, stem))
            cells.push_back(image(relative(in, dir, prefix + stem + ".png"), label, 420));
    if (std::find(in.ratsnest_files.begin(), in.ratsnest_files.end(), "som.png") !=
        in.ratsnest_files.end())
        cells.push_back(image(relative(in, dir, prefix + "ratsnest/som.png"), "SoM region", 420));
    const auto sheets = ratsnest_stems(in);
    if (cells.empty() && sheets.empty()) {
        append(out, {"*(ratsnest renders pending — run "
                     "`schgen board`"
                     ".)*",
                     ""});
        return out;
    }
    append(out, {"Placed-board airwires, regenerated by "
                 "`schgen board`"
                 ": "
                 "blue/orange = the subsystem's parts (top/bottom side), steel = SoM, green = "
                 "intra-subsystem, red = to the SoM. "
                 "`wired`"
                 " = in "
                 "`placement.wired_sheets`"
                 ".",
                 ""});
    if (!cells.empty()) {
        append(out, grid(cells, 2));
        out.push_back("");
    }
    cells.clear();
    for (const auto &name : sheets)
        cells.push_back(image(relative(in, dir, prefix + "ratsnest/" + name + ".png"), name, 200) +
                        (in.wired_sheets.count(name) ? " "
                                                       "`wired`"
                                                     : ""));
    if (!cells.empty()) {
        append(out, grid(cells, 4));
        out.push_back("");
    }
    return out;
}
std::string universal_newlines(const std::string &raw) {
    (void)codepoints(raw);
    std::string text;
    for (std::size_t i = 0; i < raw.size(); ++i) {
        if (raw[i] != '\r') {
            text += raw[i];
            continue;
        }
        text += '\n';
        if (i + 1 < raw.size() && raw[i + 1] == '\n')
            ++i;
    }
    return text;
}
} // namespace

GalleryInput load_gallery_input(const ProjectPaths &paths,
                                const std::vector<ProjectCircuit> &sheets) {
    GalleryInput out;
    out.repository_root = paths.repository_root;
    out.project_root = paths.project_root;
    out.is_default_project = paths.is_default_project;
    for (const auto &s : sheets)
        out.sheets.push_back({s.circuit.name, s.circuit.title});
    const auto renders = paths.project_root / "renders", rats = renders / "ratsnest";
    if (fs::is_directory(renders))
        for (const auto &p : fs::directory_iterator(renders))
            if (fs::exists(p.path()))
                out.render_files.insert(p.path().filename().string());
    if (fs::is_directory(rats))
        for (const auto &p : fs::directory_iterator(rats))
            if ((p.path().extension() == ".png" || p.path().filename() == ".png") &&
                (p.path().filename() != "som.png" || fs::exists(p.path())))
                out.ratsnest_files.push_back(p.path().filename().string());
    const auto project = paths.project_root / "project.json";
    // Python consults placement.wired_sheets only when sheet thumbnails exist.
    if (!ratsnest_stems(out).empty() && fs::exists(project)) {
        const auto data = parse_json_file(project.string());
        if (const auto *placement = object_field(data, "placement")) {
            if (placement->kind != JsonKind::Object)
                throw ProjectError("gallery: placement must be object");
            if (const auto *wired = object_field(*placement, "wired_sheets")) {
                if (wired->kind != JsonKind::Array)
                    throw ProjectError("gallery: wired_sheets must be array");
                for (const auto &v : wired->array_value) {
                    if (v.kind != JsonKind::String)
                        throw ProjectError("gallery: wired sheet must be string");
                    out.wired_sheets.insert(v.string_value);
                }
            }
        }
    }
    return out;
}
GalleryInput load_gallery_input(const ProjectPaths &paths) {
    return load_gallery_input(paths, load_project_circuits(paths));
}
std::string render_gallery_full(const GalleryInput &in, const fs::path &dir) {
    const auto proj = project_rel(in);
    const auto rel = [&](const std::string &t) { return relative(in, dir, t); };
    const auto rows = sorted_sheets(in);
    std::vector<std::string> out{begin_marker, generated};
    append(out, view_lines(in, dir));
    append(out, ratsnest_lines(in, dir));
    append(out, {"## Generated schematics", "",
                 "Block diagram and all " + std::to_string(rows.size()) + " " + proj +
                     " sheets, regenerated by "
                     "`schgen board`"
                     " —",
                 "every PNG below passed the netlist, ERC and visual gates.", "",
                 "<img src=\"" + rel(proj + "/docs/block_diagram.svg") +
                     "\" alt=\"Generated block diagram\" width=\"900\">",
                 ""});
    std::vector<std::string> cells;
    for (const auto &row : rows)
        cells.push_back(has(in, row.name)
                            ? image(rel(proj + "/renders/" + row.name + ".png"), row.name, 220)
                            : "**" + row.name + "**<br>*(render pending)*");
    append(out, grid(cells, 3));
    append(out, {"", "| sheet | description |", "|---|---|"});
    for (const auto &row : rows) {
        const auto link = has(in, row.name) ? "[" + row.name + "](" +
                                                  rel(proj + "/renders/" + row.name + ".png") + ")"
                                            : row.name;
        std::string title;
        for (char c : row.title) {
            if (c == '|')
                title += '\\';
            title += c;
        }
        out.push_back("| " + link + " | " + title + " |");
    }
    out.push_back(end_marker);
    return join(out, "\n");
}
std::string render_gallery_compact(const GalleryInput &in, const fs::path &dir) {
    const auto proj = project_rel(in);
    const auto rel = [&](const std::string &t) { return relative(in, dir, t); };
    std::size_t count = 0;
    for (const auto &v : views)
        if (has(in, v.first))
            ++count;
    std::vector<std::string> out{
        begin_marker,
        generated,
        "## Generated board + schematics",
        "",
        "`schgen board`"
        " regenerates the placed-board 3D views, the block diagram and all " +
            std::to_string(in.sheets.size()) + " " + proj + " sheets,",
        "each PNG passing the netlist, ERC and visual gates.",
        ""};
    if (has(in, "3d_persp"))
        append(out, {"<img src=\"" + rel(proj + "/renders/3d_persp.png") +
                         "\" alt=\"Generated 3D board render (perspective)\" width=\"900\">",
                     ""});
    append(out, {"<img src=\"" + rel(proj + "/docs/block_diagram.svg") +
                     "\" alt=\"Generated block diagram\" width=\"900\">",
                 ""});
    if (has(in, "ratsnest_top")) {
        const auto readme = rel(proj + "/README.md") + "#ratsnest-views";
        append(out, {"[<img src=\"" + rel(proj + "/renders/ratsnest_top.png") +
                         "\" alt=\"Board ratsnest (top)\" width=\"420\">](" + readme +
                         ")<br>**[Ratsnest views](" + readme + ")** — airwires per subsystem.",
                     ""});
    }
    append(out, {"See **[" + proj + "/README.md](" + rel(proj + "/README.md") +
                     "#generated-3d-board-views)** for all " + std::to_string(count) +
                     " board views + the full sheet gallery (thumbnails + descriptions).",
                 end_marker});
    return join(out, "\n");
}
std::string gallery_readme_targets(const GalleryInput &in) {
    return (in.is_default_project ? "README.md + " : "") + project_rel(in) + "/README.md";
}
GallerySplice splice_gallery(const std::string &original, const std::string &section) {
    const auto text = universal_newlines(original);
    const auto start = text.find(begin_marker);
    std::string next;
    if (start != text.npos && text.find(end_marker) != text.npos) {
        const auto end = text.find(end_marker, start + begin_marker.size());
        next = text.substr(0, start) + section +
               (end == text.npos ? "" : text.substr(end + end_marker.size()));
    } else {
        const auto last = text.find_last_not_of('\n');
        next = last == text.npos ? "" : text.substr(0, last + 1);
        const auto cps = codepoints(text);
        if (std::any_of(cps.begin(), cps.end(), [](auto c) { return !space(c); }))
            next += "\n\n";
        next += section + "\n";
    }
    const bool changed = next != text;
    return {changed ? next : original, changed};
}
std::vector<fs::path> write_gallery(const GalleryInput &in) {
    std::vector<std::pair<fs::path, std::string>> outputs;
    if (in.is_default_project)
        outputs.emplace_back(in.repository_root / "README.md",
                             render_gallery_compact(in, in.repository_root));
    outputs.emplace_back(in.project_root / "README.md", render_gallery_full(in, in.project_root));
    std::vector<fs::path> changed;
    for (const auto &[path, section] : outputs) {
        if (!fs::is_directory(path.parent_path()))
            throw ProjectError("gallery: README directory does not exist: " +
                               path.parent_path().string());
        const auto result = splice_gallery(fs::exists(path) ? read(path) : "", section);
        if (result.changed) {
            publish(path, result.bytes);
            changed.push_back(path);
        }
    }
    return changed;
}
std::vector<fs::path> generate_gallery(const ProjectPaths &paths) {
    return write_gallery(load_gallery_input(paths));
}
std::string gallery_summary(const GalleryInput &in, const std::vector<fs::path> &changed) {
    std::vector<std::string> names;
    for (const auto &path : changed) {
        const auto rel = document_detail::absolute(path).lexically_relative(
            document_detail::absolute(in.repository_root));
        if (!contained(rel))
            throw ProjectError("gallery: changed README outside repository");
        names.push_back(rel.generic_string());
    }
    return "GALLERY: " + std::to_string(in.sheets.size()) + " sheets -> " +
           gallery_readme_targets(in) + " (" + (names.empty() ? "unchanged" : join(names, ", ")) +
           ")";
}
} // namespace schgen
