#include "schgen/manufacturing_checks.hpp"
#include "schgen/atomic_file.hpp"
#include "manufacturing_exports_internal.hpp"

namespace schgen {
using namespace manufacturing_detail;
namespace {
const JsonNode& field(const JsonNode& n,const std::string& name,JsonKind kind) {
    const auto p=object_field(n,name);if(!p||p->kind!=kind)throw ProjectError("manufacturing metadata: invalid "+name);return *p;
}
std::string text(const JsonNode& n,const std::string& key) {return field(n,key,JsonKind::String).string_value;}
long long count(const JsonNode& n) {
    if(n.kind==JsonKind::Bool)return n.bool_value?1:0;
    if(n.kind==JsonKind::Number){if(!std::isfinite(n.number_value)||n.number_value< -9223372036854775808.0||n.number_value>=9223372036854775808.0)throw ProjectError("fallback count out of range");return static_cast<long long>(n.number_value);}
    if(n.kind==JsonKind::String){const auto s=verification::strip(n.string_value);std::size_t used=0;const auto value=std::stoll(s,&used);if(used!=s.size())throw ProjectError("invalid fallback count");return value;}
    throw ProjectError("invalid fallback count");
}
ManufacturingCounts counts(const JsonNode& n) {
    if(n.kind!=JsonKind::Object)throw ProjectError("fallback counts must be an object");ManufacturingCounts out;for(const auto& [k,v]:n.object_value)out[k]=count(v);return out;
}
std::optional<ManufacturingCounts> load_counts(const std::filesystem::path& path) {
    try {auto n=parse_json_file(path.string());return counts(field(n,"counts",JsonKind::Object));}
    catch(const std::bad_alloc&){throw;}catch(const std::exception&){return std::nullopt;}
}
void write_counts(const std::filesystem::path& path,const ManufacturingCounts& counts) {
    std::string text="{\n \"counts\": {";bool first=true;
    for(const auto& [name,n]:counts){text+=first?"\n":",\n";first=false;text+="  "+quote(name)+": "+std::to_string(n);}
    if(!counts.empty())text+="\n ";text+="},\n \"note\": \"fallback ratchet ceilings — a build whose count EXCEEDS its ceiling FAILS; ceilings only ever DECREASE (pinned from a measured build, reviewed in git). A name absent here is allowed zero firings.\"\n}\n";
    // Python json.dumps defaults to ASCII escaping.
    auto at=text.find("—");if(at!=text.npos)text.replace(at,std::string("—").size(),"\\u2014");
    write_atomic_file(path.string(),{text.begin(),text.end()});
}
}
ManufacturingPipelineInput manufacturing_pipeline_from_json(const JsonNode& n) {
    ManufacturingPipelineInput out;
    for(const auto& s:field(n,"stages",JsonKind::Array).array_value)out.stages.push_back({text(s,"name"),text(s,"domain"),text(s,"validated_by"),text(s,"desc"),field(s,"may_move",JsonKind::Bool).bool_value,field(s,"tracked",JsonKind::Bool).bool_value});
    for(const auto& q:field(n,"quantization",JsonKind::Array).array_value)out.quantization.push_back({text(q,"name"),text(q,"value_text"),text(q,"klass"),text(q,"basis")});
    for(const auto& f:field(n,"fallbacks",JsonKind::Array).array_value)out.fallbacks.push_back({text(f,"name"),text(f,"stage"),text(f,"meaning")});
    for(const auto& [name,b]:field(n,"baselines",JsonKind::Object).object_value)out.baselines[name]=counts(b);
    return out;
}
ManufacturingBaselines manufacturing_pipeline_baselines(const std::filesystem::path& root) {
    ManufacturingBaselines out;for(const auto& entry:std::filesystem::directory_iterator(root))if(entry.is_directory()&&std::filesystem::exists(entry.path()/"project.json"))if(auto c=load_counts(entry.path()/"reports/fallback_baseline.json"))out[entry.path().filename().string()]=*c;return out;
}
std::string render_manufacturing_pipeline(const ManufacturingPipelineInput& in) {
    std::ostringstream o;o<<R"(# GEOMETRY PIPELINE

GENERATED by `schgen board` from the live stage manifest (`schgen/generate/pcb/stages.py`), the quantization registry (`schgen/core/quantize.py`) and the fallback registry (`schgen/core/fallbacks.py`). Do not edit by hand — edit the registries and rebuild.

## Placement stages (`build_model`, declared order)

Movement in a `may_move: no` stage raises `StageMovementError` at build time (always-on tripwire; one snapshot hash per boundary). `tracked: no` stages run before absolute positions exist.

| # | stage | may_move | tracked | validated by |
|---|-------|----------|---------|--------------|
)";
    std::set<std::string> seen;std::size_t n=0;for(const auto& s:in.stages){if(!seen.insert(s.name).second)throw ProjectError("duplicate pipeline stage: "+s.name);o<<"| "<<++n<<" | `"<<s.name<<"` — "<<s.desc<<" | "<<(s.may_move?"yes":"NO")<<" | "<<(s.tracked?"yes":"no")<<" ("<<s.domain<<") | "<<s.validated_by<<" |\n";}
    o<<R"(
## Quantization registry

Every live geometry-touching snap/round/pad/credit is a NAMED transform; the census lint (`schgen/verify/quantize_census.py`) hard-fails the board on any raw quantization site in the geometry data flow outside this registry (baseline: empty).

| name | value | class | basis |
|------|-------|-------|-------|
)";
    auto qs=in.quantization;std::sort(qs.begin(),qs.end(),[](const auto& a,const auto& b){return a.name<b.name;});seen.clear();
    for(const auto& q:qs){if(!seen.insert(q.name).second)throw ProjectError("duplicate quantization: "+q.name);o<<"| `"<<q.name<<"` | `"<<q.value<<"` | "<<q.klass<<" | "<<q.basis<<" |\n";}
    o<<R"(
## Fallback registry + committed ratchet baselines

Every degraded path is a NAMED event; the ratchet gate (`schgen/verify/fallback_gate.py`) fails the board when any count exceeds its committed per-project ceiling (ceilings only ever decrease). Live counts print in the build report and in `board_verdicts.json` (`fallbacks`).

| name | stage | )";
    std::vector<std::string> headers,separators;for(const auto& [p,b]:in.baselines){(void)b;headers.push_back(p+" ceiling");separators.push_back("---------");}o<<join(headers," | ")<<" | meaning |\n|------|-------|"<<join(separators,"|")<<"|---------|\n";
    auto fs=in.fallbacks;std::sort(fs.begin(),fs.end(),[](const auto& a,const auto& b){return a.name<b.name;});seen.clear();
    for(const auto& f:fs){if(!seen.insert(f.name).second)throw ProjectError("duplicate fallback: "+f.name);std::vector<std::string> cells;for(const auto& [p,b]:in.baselines){(void)p;auto c=b.find(f.name);cells.push_back(std::to_string(c==b.end()?0:c->second));}o<<"| `"<<f.name<<"` | "<<f.stage<<" | "<<join(cells," | ")<<" | "<<f.meaning<<" |\n";}
    return o.str();
}
std::string ManufacturingFallbackResult::summary()const {
    std::string out="FALLBACK RATCHET: "+std::string(ok?"PASS":"FAIL")+" — "+std::to_string(n_names)+" registered paths, "+std::to_string(n_fired)+" firing"+(pinned?" (baseline PINNED this build)":"");
    for(const auto& r:regressions)out+="\n  REGRESSION: "+r;return out;
}
ManufacturingFallbackResult check_manufacturing_fallbacks(const ManufacturingCounts& census,const std::optional<ManufacturingCounts>& baseline) {
    ManufacturingFallbackResult r;r.n_names=census.size();for(const auto& [name,n]:census){(void)name;r.n_fired+=n!=0;}
    if(!baseline){r.pinned=true;return r;}
    for(const auto& [name,n]:census){auto it=baseline->find(name);auto ceiling=it==baseline->end()?0:it->second;if(n>ceiling){r.ok=false;r.regressions.push_back(name+": fired "+std::to_string(n)+" > baseline "+std::to_string(ceiling)+" — a degraded path bound more often than the committed ceiling");}}
    return r;
}
ManufacturingFallbackResult run_manufacturing_fallbacks(const ManufacturingCounts& census,const std::filesystem::path& path) {
    const auto baseline=load_counts(path);auto r=check_manufacturing_fallbacks(census,baseline);
    if(!baseline)write_counts(path,census);else if(r.ok){auto lowered=*baseline;for(auto& [k,v]:lowered){auto n=census.find(k);v=std::min(v,n==census.end()?0:n->second);}if(lowered!=*baseline)write_counts(path,lowered);}return r;
}
} // namespace schgen
