#include "schgen/model3d.hpp"
#include "render_models_internal.hpp"
#include <limits>

namespace schgen {
namespace {
using namespace render_models_detail;
std::string pyfloat(double v) {
    char b[768]; const auto r=std::to_chars(b,b+sizeof b,std::abs(v),std::chars_format::scientific);
    if (r.ec!=std::errc{}) throw std::runtime_error("OBJ coordinate out of range");
    std::string s(b,r.ptr),sign=std::signbit(v)?"-":"";
    const auto e=s.find('e'); const int exponent=std::stoi(s.substr(e+1));
    if (exponent< -4 || exponent>=16) return sign+s;
    std::string digits=s.substr(0,e); const auto dot=digits.find('.'); if (dot!=digits.npos) digits.erase(dot,1);
    const int point=exponent+1;
    if (point<=0) return sign+"0."+std::string(static_cast<std::size_t>(-point),'0')+digits;
    if (point>=static_cast<int>(digits.size())) return sign+digits+std::string(static_cast<std::size_t>(point)-digits.size(),'0')+".0";
    digits.insert(static_cast<std::size_t>(point),"."); return sign+digits;
}
}
std::optional<std::string> model3d_obj_to_wrl(const std::string& obj) {
    using namespace render_models_detail;
    struct Material { std::string kd="0.6 0.6 0.6",tr="0"; };
    std::map<std::string,Material> mats;
    for (std::size_t start=0;(start=obj.find("newmtl ",start))!=obj.npos;) {
        const auto end=obj.find("endmtl",start); if (end==obj.npos) break;
        const auto block=lines(obj.substr(start,end-start+6)); const auto header=words(block.front());
        if (header.size()<2) throw std::runtime_error("OBJ material name missing");
        Material mat;
        for (const auto& line:block) {
            const auto p=words(line);
            if (line.compare(0,2,"Kd")==0) { std::vector<std::string> kd; for (std::size_t i=1;i<std::min<std::size_t>(4,p.size());++i) kd.push_back(p[i]); mat.kd=join(kd," "); }
            else if (line.compare(0,2,"d ")==0) { if (p.size()<2) throw std::runtime_error("OBJ transparency missing"); mat.tr=p[1]; }
        }
        mats[header[1]]=mat; start=end+6;
    }
    std::vector<std::array<double,3>> verts;
    for (const auto& line:lines(obj)) { const auto p=words(line); if (p.size()>=4&&p[0]=="v") verts.push_back({number(p[1]),number(p[2]),number(p[3])}); }
    if (verts.empty()) return std::nullopt;
    auto low=verts.front(),high=verts.front();
    for (const auto& v:verts) for (std::size_t i=0;i<3;++i) { low[i]=std::min(low[i],v[i]); high[i]=std::max(high[i],v[i]); }
    const std::array<double,3> origin{(low[0]+high[0])/2,(low[1]+high[1])/2,low[2]};
    for (auto& v:verts) for (std::size_t i=0;i<3;++i) v[i]=number(fixed((v[i]-origin[i])/2.54,4));
    std::vector<std::string> out{"#VRML V2.0 utf8","# generated by schgen part add"};
    for (std::size_t start=obj.find("usemtl");start!=obj.npos;) {
        start+=6; const auto end=obj.find("usemtl",start);
        const auto block=lines(obj.substr(start,end==obj.npos?obj.npos:end-start)); start=end;
        if (block.empty()) throw std::runtime_error("OBJ material name missing");
        const auto found=mats.find(trim(block.front())); const auto mat=found==mats.end()?Material{}:found->second;
        std::map<long long,std::size_t> index; std::vector<std::string> coords,faces;
        for (std::size_t i=1;i<block.size();++i) {
            const auto p=words(block[i]); if (p.empty()||p[0]!="f") continue;
            std::vector<std::string> face;
            for (std::size_t j=1;j<p.size();++j) {
                const auto token=p[j].substr(0,p[j].find('/')); std::size_t used=0; const auto vi=std::stoll(token,&used);
                if (used!=token.size() || vi==std::numeric_limits<long long>::min()) throw std::runtime_error("OBJ vertex index invalid");
                if (!index.count(vi)) {
                    // Preserve legacy sv[vi-1], including Python negative-index semantics.
                    auto ix=vi-1; if (ix<0) ix+=static_cast<long long>(verts.size());
                    if (ix<0 || static_cast<unsigned long long>(ix)>=verts.size()) throw std::runtime_error("OBJ vertex index out of range");
                    index[vi]=coords.size(); const auto& v=verts[static_cast<std::size_t>(ix)];
                    coords.push_back(pyfloat(v[0])+" "+pyfloat(v[1])+" "+pyfloat(v[2]));
                }
                face.push_back(std::to_string(index.at(vi)));
            }
            faces.push_back(join(face,",")+",-1");
        }
        if (!faces.empty()) out.push_back("Shape{appearance Appearance{material Material{diffuseColor "+mat.kd+" transparency "+mat.tr+"}}geometry IndexedFaceSet{ccw TRUE solid FALSE coord Coordinate{point ["+join(coords,", ")+"]} coordIndex ["+join(faces,",")+"]}}");
    }
    if (out.size()==2) return std::nullopt;
    return join(out,"\n");
}
}
