// Literal design-settings policy migrated from emit.py::_design_settings.
// This constructs native data; it is not a frozen project/output payload.
#pragma once
#include "pcb_emit_internal.hpp"
namespace schgen::pcb_emission {
inline PcbProjectDocument design_settings(const PcbEmitPolicy &policy) {
    PcbProjectDocument out;
    out.data = jo(
        {{"defaults", jo({{"apply_defaults_to_fp_barcodes", jb(false)},
                          {"apply_defaults_to_fp_dimensions", jb(false)},
                          {"apply_defaults_to_fp_fields", jb(false)},
                          {"apply_defaults_to_fp_shapes", jb(false)},
                          {"apply_defaults_to_fp_text", jb(false)},
                          {"board_outline_line_width", j(0.1)},
                          {"copper_line_width", j(0.2)},
                          {"copper_text_italic", jb(false)},
                          {"copper_text_size_h", j(1.5)},
                          {"copper_text_size_v", j(1.5)},
                          {"copper_text_thickness", j(0.3)},
                          {"copper_text_upright", jb(false)},
                          {"courtyard_line_width", j(0.05)},
                          {"dimension_precision", j(4)},
                          {"dimension_units", j(3)},
                          {"dimensions", jo({{"arrow_length", j(1270000)},
                                             {"extension_offset", j(500000)},
                                             {"keep_text_aligned", jb(true)},
                                             {"suppress_zeroes", jb(false)},
                                             {"text_position", j(0)},
                                             {"units_format", j(1)}})},
                          {"fab_line_width", j(0.1)},
                          {"fab_text_italic", jb(false)},
                          {"fab_text_size_h", j(1.0)},
                          {"fab_text_size_v", j(1.0)},
                          {"fab_text_thickness", j(0.15)},
                          {"fab_text_upright", jb(false)},
                          {"other_line_width", j(0.15)},
                          {"other_text_italic", jb(false)},
                          {"other_text_size_h", j(1.0)},
                          {"other_text_size_v", j(1.0)},
                          {"other_text_thickness", j(0.15)},
                          {"other_text_upright", jb(false)},
                          {"pads", jo({{"drill", j(0.0)}, {"height", j(1.8)}, {"width", j(1.0)}})},
                          {"silk_line_width", j(0.15)},
                          {"silk_text_italic", jb(false)},
                          {"silk_text_size_h", j(1.0)},
                          {"silk_text_size_v", j(1.0)},
                          {"silk_text_thickness", j(0.15)},
                          {"silk_text_upright", jb(false)},
                          {"zones", jo({{"border_display_style", j(2)},
                                        {"border_hatch_pitch", j(0.5)},
                                        {"corner_radius", j(0.0)},
                                        {"corner_smoothing", j(0)},
                                        {"fill_mode", j(0)},
                                        {"hatch_gap", j(1.5)},
                                        {"hatch_orientation", j(0.0)},
                                        {"hatch_smoothing_level", j(0)},
                                        {"hatch_smoothing_value", j(0.1)},
                                        {"hatch_thickness", j(1.0)},
                                        {"min_clearance", j(0.127)},
                                        {"min_island_area", j(10.0)},
                                        {"min_thickness", j(0.25)},
                                        {"pad_connection", j(1)},
                                        {"remove_islands", j(0)},
                                        {"thermal_relief_gap", j(0.5)},
                                        {"thermal_relief_spoke_width", j(0.5)}})}})},
         {"diff_pair_dimensions",
          ja({jo({{"gap", j(0.0)}, {"via_gap", j(0.0)}, {"width", j(0.0)}}),
              jo({{"gap", j(0.2)}, {"via_gap", j(0.5)}, {"width", j(0.1)}}),
              jo({{"gap", j(0.25)}, {"via_gap", j(0.5)}, {"width", j(0.1)}}),
              jo({{"gap", j(0.25)}, {"via_gap", j(0.5)}, {"width", j(0.104)}}),
              jo({{"gap", j(0.3)}, {"via_gap", j(0.5)}, {"width", j(0.11)}}),
              jo({{"gap", j(0.2)}, {"via_gap", j(0.5)}, {"width", j(0.12)}})})},
         {"drc_exclusions", ja({})},
         {"meta", jo({{"version", j(2)}})},
         {"rule_severities", jo({{"annular_width", j(std::string("error"))},
                                 {"clearance", j(std::string("error"))},
                                 {"connection_width", j(std::string("warning"))},
                                 {"copper_edge_clearance", j(std::string("error"))},
                                 {"copper_sliver", j(std::string("warning"))},
                                 {"courtyards_overlap", j(std::string("error"))},
                                 {"creepage", j(std::string("error"))},
                                 {"diff_pair_gap_out_of_range", j(std::string("error"))},
                                 {"diff_pair_uncoupled_length_too_long", j(std::string("error"))},
                                 {"drill_out_of_range", j(std::string("error"))},
                                 {"duplicate_footprints", j(std::string("warning"))},
                                 {"extra_footprint", j(std::string("warning"))},
                                 {"footprint", j(std::string("error"))},
                                 {"footprint_filters_mismatch", j(std::string("ignore"))},
                                 {"footprint_symbol_field_mismatch", j(std::string("warning"))},
                                 {"footprint_symbol_mismatch", j(std::string("warning"))},
                                 {"footprint_type_mismatch", j(std::string("ignore"))},
                                 {"hole_clearance", j(std::string("error"))},
                                 {"hole_near_hole", j(std::string("error"))},
                                 {"hole_to_hole", j(std::string("error"))},
                                 {"holes_co_located", j(std::string("warning"))},
                                 {"invalid_outline", j(std::string("error"))},
                                 {"isolated_copper", j(std::string("warning"))},
                                 {"item_on_disabled_layer", j(std::string("error"))},
                                 {"items_not_allowed", j(std::string("error"))},
                                 {"length_out_of_range", j(std::string("error"))},
                                 {"lib_footprint_issues", j(std::string("warning"))},
                                 {"lib_footprint_mismatch", j(std::string("warning"))},
                                 {"malformed_courtyard", j(std::string("error"))},
                                 {"microvia_drill_out_of_range", j(std::string("error"))},
                                 {"mirrored_text_on_front_layer", j(std::string("warning"))},
                                 {"missing_courtyard", j(std::string("ignore"))},
                                 {"missing_footprint", j(std::string("warning"))},
                                 {"missing_tuning_profile", j(std::string("warning"))},
                                 {"net_conflict", j(std::string("warning"))},
                                 {"nonmirrored_text_on_back_layer", j(std::string("warning"))},
                                 {"npth_inside_courtyard", j(std::string("ignore"))},
                                 {"padstack", j(std::string("warning"))},
                                 {"pth_inside_courtyard", j(std::string("ignore"))},
                                 {"shorting_items", j(std::string("error"))},
                                 {"silk_edge_clearance", j(std::string("warning"))},
                                 {"silk_over_copper", j(std::string("warning"))},
                                 {"silk_overlap", j(std::string("warning"))},
                                 {"skew_out_of_range", j(std::string("error"))},
                                 {"solder_mask_bridge", j(std::string("error"))},
                                 {"starved_thermal", j(std::string("error"))},
                                 {"text_height", j(std::string("warning"))},
                                 {"text_on_edge_cuts", j(std::string("error"))},
                                 {"text_thickness", j(std::string("warning"))},
                                 {"through_hole_pad_without_hole", j(std::string("error"))},
                                 {"too_many_vias", j(std::string("error"))},
                                 {"track_angle", j(std::string("error"))},
                                 {"track_dangling", j(std::string("warning"))},
                                 {"track_not_centered_on_via", j(std::string("ignore"))},
                                 {"track_on_post_machined_layer", j(std::string("error"))},
                                 {"track_segment_length", j(std::string("error"))},
                                 {"track_width", j(std::string("error"))},
                                 {"tracks_crossing", j(std::string("error"))},
                                 {"tuning_profile_track_geometries", j(std::string("ignore"))},
                                 {"unconnected_items", j(std::string("error"))},
                                 {"unresolved_variable", j(std::string("error"))},
                                 {"via_dangling", j(std::string("warning"))},
                                 {"zones_intersect", j(std::string("error"))}})},
         {"rules", jo({{"max_error", j(0.005)},
                       {"min_clearance", j(0.09)},
                       {"min_connection", j(0.0)},
                       {"min_copper_edge_clearance", j(0.3)},
                       {"min_groove_width", j(0.0)},
                       {"min_hole_clearance", j(0.2)},
                       {"min_hole_to_hole", j(0.25)},
                       {"min_microvia_diameter", j(0.2)},
                       {"min_microvia_drill", j(0.1)},
                       {"min_resolved_spokes", j(2)},
                       {"min_silk_clearance", j(0.0)},
                       {"min_text_height", j(0.8)},
                       {"min_text_thickness", j(0.08)},
                       {"min_through_hole_diameter", j(0.2)},
                       {"min_track_width", j(0.09)},
                       {"min_via_annular_width", j(0.05)},
                       {"min_via_diameter", j(0.3)},
                       {"solder_mask_clearance", j(0.0)},
                       {"solder_mask_min_width", j(0.0)},
                       {"solder_mask_to_copper_clearance", j(0.0)},
                       {"use_height_for_length_calcs", jb(true)}})},
         {"teardrop_options", ja({jo({{"td_onpthpad", jb(true)},
                                      {"td_onroundshapesonly", jb(false)},
                                      {"td_onsmdpad", jb(true)},
                                      {"td_ontrackend", jb(false)},
                                      {"td_onvia", jb(true)}})})},
         {"teardrop_parameters", ja({jo({{"td_allow_use_two_tracks", jb(true)},
                                         {"td_curve_segcount", j(0)},
                                         {"td_height_ratio", j(1.0)},
                                         {"td_length_ratio", j(0.5)},
                                         {"td_maxheight", j(2.0)},
                                         {"td_maxlen", j(1.0)},
                                         {"td_on_pad_in_zone", jb(false)},
                                         {"td_target_name", j(std::string("td_round_shape"))},
                                         {"td_width_to_size_filter_ratio", j(0.9)}}),
                                     jo({{"td_allow_use_two_tracks", jb(true)},
                                         {"td_curve_segcount", j(0)},
                                         {"td_height_ratio", j(1.0)},
                                         {"td_length_ratio", j(0.5)},
                                         {"td_maxheight", j(2.0)},
                                         {"td_maxlen", j(1.0)},
                                         {"td_on_pad_in_zone", jb(false)},
                                         {"td_target_name", j(std::string("td_rect_shape"))},
                                         {"td_width_to_size_filter_ratio", j(0.9)}}),
                                     jo({{"td_allow_use_two_tracks", jb(true)},
                                         {"td_curve_segcount", j(0)},
                                         {"td_height_ratio", j(1.0)},
                                         {"td_length_ratio", j(0.5)},
                                         {"td_maxheight", j(2.0)},
                                         {"td_maxlen", j(1.0)},
                                         {"td_on_pad_in_zone", jb(false)},
                                         {"td_target_name", j(std::string("td_track_end"))},
                                         {"td_width_to_size_filter_ratio", j(0.9)}})})},
         {"track_widths",
          ja({j(0.0), j(0.1), j(0.11), j(0.135), j(0.15), j(0.2), j(0.25), j(0.3), j(0.5)})},
         {"tuning_pattern_settings",
          jo({{"diff_pair_defaults", jo({{"corner_radius_percentage", j(50)},
                                         {"corner_style", j(0)},
                                         {"max_amplitude", j(1.2)},
                                         {"min_amplitude", j(0.1)},
                                         {"single_sided", jb(true)},
                                         {"spacing", j(0.6)}})},
              {"diff_pair_skew_defaults", jo({{"corner_radius_percentage", j(100)},
                                              {"corner_style", j(1)},
                                              {"max_amplitude", j(1.0)},
                                              {"min_amplitude", j(0.05)},
                                              {"single_sided", jb(false)},
                                              {"spacing", j(0.3)}})},
              {"single_track_defaults", jo({{"corner_radius_percentage", j(50)},
                                            {"corner_style", j(0)},
                                            {"max_amplitude", j(1.0)},
                                            {"min_amplitude", j(0.1)},
                                            {"single_sided", jb(true)},
                                            {"spacing", j(0.4)}})}})},
         {"via_dimensions", ja({jo({{"diameter", j(0.0)}, {"drill", j(0.0)}}),
                                jo({{"diameter", j(0.3)}, {"drill", j(0.2)}}),
                                jo({{"diameter", j(0.35)}, {"drill", j(0.2)}}),
                                jo({{"diameter", j(0.4)}, {"drill", j(0.25)}}),
                                jo({{"diameter", j(0.4)}, {"drill", j(0.3)}}),
                                jo({{"diameter", j(0.45)}, {"drill", j(0.3)}}),
                                jo({{"diameter", j(0.55)}, {"drill", j(0.4)}})})},
         {"zones_allow_external_fillets", jb(true)}});
    out.float_paths = {"/defaults/board_outline_line_width",
                       "/defaults/copper_line_width",
                       "/defaults/copper_text_size_h",
                       "/defaults/copper_text_size_v",
                       "/defaults/copper_text_thickness",
                       "/defaults/courtyard_line_width",
                       "/defaults/fab_line_width",
                       "/defaults/fab_text_size_h",
                       "/defaults/fab_text_size_v",
                       "/defaults/fab_text_thickness",
                       "/defaults/other_line_width",
                       "/defaults/other_text_size_h",
                       "/defaults/other_text_size_v",
                       "/defaults/other_text_thickness",
                       "/defaults/pads/drill",
                       "/defaults/pads/height",
                       "/defaults/pads/width",
                       "/defaults/silk_line_width",
                       "/defaults/silk_text_size_h",
                       "/defaults/silk_text_size_v",
                       "/defaults/silk_text_thickness",
                       "/defaults/zones/border_hatch_pitch",
                       "/defaults/zones/corner_radius",
                       "/defaults/zones/hatch_gap",
                       "/defaults/zones/hatch_orientation",
                       "/defaults/zones/hatch_smoothing_value",
                       "/defaults/zones/hatch_thickness",
                       "/defaults/zones/min_clearance",
                       "/defaults/zones/min_island_area",
                       "/defaults/zones/min_thickness",
                       "/defaults/zones/thermal_relief_gap",
                       "/defaults/zones/thermal_relief_spoke_width",
                       "/diff_pair_dimensions/0/gap",
                       "/diff_pair_dimensions/0/via_gap",
                       "/diff_pair_dimensions/0/width",
                       "/diff_pair_dimensions/1/gap",
                       "/diff_pair_dimensions/1/via_gap",
                       "/diff_pair_dimensions/1/width",
                       "/diff_pair_dimensions/2/gap",
                       "/diff_pair_dimensions/2/via_gap",
                       "/diff_pair_dimensions/2/width",
                       "/diff_pair_dimensions/3/gap",
                       "/diff_pair_dimensions/3/via_gap",
                       "/diff_pair_dimensions/3/width",
                       "/diff_pair_dimensions/4/gap",
                       "/diff_pair_dimensions/4/via_gap",
                       "/diff_pair_dimensions/4/width",
                       "/diff_pair_dimensions/5/gap",
                       "/diff_pair_dimensions/5/via_gap",
                       "/diff_pair_dimensions/5/width",
                       "/rules/max_error",
                       "/rules/min_clearance",
                       "/rules/min_connection",
                       "/rules/min_copper_edge_clearance",
                       "/rules/min_groove_width",
                       "/rules/min_hole_clearance",
                       "/rules/min_hole_to_hole",
                       "/rules/min_microvia_diameter",
                       "/rules/min_microvia_drill",
                       "/rules/min_silk_clearance",
                       "/rules/min_text_height",
                       "/rules/min_text_thickness",
                       "/rules/min_through_hole_diameter",
                       "/rules/min_track_width",
                       "/rules/min_via_annular_width",
                       "/rules/min_via_diameter",
                       "/rules/solder_mask_clearance",
                       "/rules/solder_mask_min_width",
                       "/rules/solder_mask_to_copper_clearance",
                       "/teardrop_parameters/0/td_height_ratio",
                       "/teardrop_parameters/0/td_length_ratio",
                       "/teardrop_parameters/0/td_maxheight",
                       "/teardrop_parameters/0/td_maxlen",
                       "/teardrop_parameters/0/td_width_to_size_filter_ratio",
                       "/teardrop_parameters/1/td_height_ratio",
                       "/teardrop_parameters/1/td_length_ratio",
                       "/teardrop_parameters/1/td_maxheight",
                       "/teardrop_parameters/1/td_maxlen",
                       "/teardrop_parameters/1/td_width_to_size_filter_ratio",
                       "/teardrop_parameters/2/td_height_ratio",
                       "/teardrop_parameters/2/td_length_ratio",
                       "/teardrop_parameters/2/td_maxheight",
                       "/teardrop_parameters/2/td_maxlen",
                       "/teardrop_parameters/2/td_width_to_size_filter_ratio",
                       "/track_widths/0",
                       "/track_widths/1",
                       "/track_widths/2",
                       "/track_widths/3",
                       "/track_widths/4",
                       "/track_widths/5",
                       "/track_widths/6",
                       "/track_widths/7",
                       "/track_widths/8",
                       "/tuning_pattern_settings/diff_pair_defaults/max_amplitude",
                       "/tuning_pattern_settings/diff_pair_defaults/min_amplitude",
                       "/tuning_pattern_settings/diff_pair_defaults/spacing",
                       "/tuning_pattern_settings/diff_pair_skew_defaults/max_amplitude",
                       "/tuning_pattern_settings/diff_pair_skew_defaults/min_amplitude",
                       "/tuning_pattern_settings/diff_pair_skew_defaults/spacing",
                       "/tuning_pattern_settings/single_track_defaults/max_amplitude",
                       "/tuning_pattern_settings/single_track_defaults/min_amplitude",
                       "/tuning_pattern_settings/single_track_defaults/spacing",
                       "/via_dimensions/0/diameter",
                       "/via_dimensions/0/drill",
                       "/via_dimensions/1/diameter",
                       "/via_dimensions/1/drill",
                       "/via_dimensions/2/diameter",
                       "/via_dimensions/2/drill",
                       "/via_dimensions/3/diameter",
                       "/via_dimensions/3/drill",
                       "/via_dimensions/4/diameter",
                       "/via_dimensions/4/drill",
                       "/via_dimensions/5/diameter",
                       "/via_dimensions/5/drill",
                       "/via_dimensions/6/diameter",
                       "/via_dimensions/6/drill"};
    for (auto &[key, val] : out.data.object_value)
        if (key == "rules")
            set(val, "min_hole_to_hole", j(policy.minimum_hole_to_hole));
    return out;
}
} // namespace schgen::pcb_emission
