#include "schgen/vivado.hpp"

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <sstream>
#include <stdexcept>

namespace schgen {
namespace {
void require_tcl_atom(const std::string& value, const char* label) {
    if (value.empty() || value.find_first_not_of(
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_./+-")
            != std::string::npos) {
        throw std::runtime_error(std::string("unsafe or empty Tcl ") + label + ": " + value);
    }
}
std::string period_text(double value) {
    if (!std::isfinite(value) || value <= 0.0)
        throw std::runtime_error("clock period must be finite and positive");
    std::ostringstream out;
    out.imbue(std::locale::classic());
    if (value == std::floor(value)) out << std::fixed << std::setprecision(0) << value;
    else out << std::setprecision(6) << value;
    return out.str();
}
}

std::string render_vivado(const XdcOutput& xdc, const std::string& device,
                          const std::string& zynq_ref, const std::string& xdc_relative,
                          const std::vector<std::string>& refs,
                          const std::map<std::string, double>& clock_periods) {
    require_tcl_atom(device, "device");
    // Relative paths are inserted into a Tcl word. Reject command substitution,
    // whitespace and control characters instead of emitting executable input.
    require_tcl_atom(xdc_relative, "constraint path");
    for (const auto& [name, period] : clock_periods) {
        require_tcl_atom(name, "clock name");
        (void)period_text(period);
    }
    std::vector<const XdcPin*> clocks;
    for (const auto& pin : xdc.entries) {
        const auto [capable, positive] = xdc_pin_traits(pin.pin_name);
        if (!capable.empty() && positive) clocks.push_back(&pin);
    }
    std::sort(clocks.begin(), clocks.end(), [](auto a, auto b) { return a->net < b->net; });
    std::ostringstream out;
    out.imbue(std::locale::classic());
    const std::string rule(78, '#');
    out << rule << "\n"
        "# create_project.tcl — GENERATED by `schgen vivado`. DO NOT EDIT.\n"
        "#\n"
        "# One-shot Vivado project from the schgen-generated pin constraints:\n"
        "#     cd carrier/fpga\n"
        "#     vivado -mode batch -source create_project.tcl\n"
        "#\n"
        "# Device: " << device << " (" << zynq_ref << " on the SoM, "
        "live kicad-cli extraction — never hard-coded)\n"
        "# Pin constraints: " << xdc_relative << " (" << xdc.entries.size()
        << " ports, generated by `schgen xdc`)\n"
        "# Determinism: device + pins + clocks all derive from the SoM netlist;\n"
        "# no timestamps, sorted ordering -> byte-identical on re-run.\n"
        << rule << "\n\n"
        "# Resolve paths relative to THIS script so it sources from any cwd.\n"
        "set script_dir [file dirname [file normalize [info script]]]\n\n"
        "set project_name zynq_carrier\n"
        "set part " << device << "\n\n"
        "# ---- project ----------------------------------------------------\n"
        "# In-memory project under the script dir; -force overwrites a prior run.\n"
        "create_project -force $project_name $script_dir/$project_name -part $part\n"
        "set_property part $part [current_project]\n\n"
        "# ---- pin + IO constraints (schgen xdc, proved against the SoM) --\n"
        "set xdc_file [file normalize $script_dir/" << xdc_relative << "]\n"
        "if {![file exists $xdc_file]} {\n"
        "    error \"missing constraints: $xdc_file — run `schgen xdc` (or `schgen board`) first\"\n"
        "}\n"
        "add_files -fileset constrs_1 -norecurse $xdc_file\n"
        "read_xdc $xdc_file\n\n"
        "# ---- clocks -----------------------------------------------------\n"
        "# MRCC/SRCC-capable PL ports the XDC flags as clock candidates.\n";
    const auto promoted = std::count_if(clocks.begin(), clocks.end(), [&](auto pin) {
        return clock_periods.count(pin->net) != 0;
    });
    if (promoted != 0) {
        out << "# Promoted to real constraints (documented fixed source period):\n";
        for (auto pin : clocks) {
            const auto it = clock_periods.find(pin->net);
            if (it == clock_periods.end()) continue;
            out << "create_clock -name " << pin->net << " -period " << period_text(it->second)
                << " [get_ports {" << pin->net << "}]  ;# " << pin->jpin << " "
                << pin->pin_name << " (" << xdc_pin_traits(pin->pin_name).first << ")\n";
        }
    }
    if (static_cast<std::size_t>(promoted) != clocks.size()) {
        out << "# No documented fixed period for these (source-synchronous / recovered /\n"
               "# FPGA-driven). Left as TEMPLATES — uncomment and set <ns> for the real\n"
               "# source frequency before timing closure (matches the XDC templates).\n";
        for (auto pin : clocks) {
            if (clock_periods.count(pin->net)) continue;
            out << "# create_clock -name " << pin->net << " -period <ns> [get_ports {"
                << pin->net << "}]  ;# " << pin->jpin << " " << pin->pin_name
                << " (" << xdc_pin_traits(pin->pin_name).first << ")\n";
        }
    }
    if (clocks.empty()) {
        out << "# (no clock-capable PL ports bound through ";
        for (std::size_t i = 0; i < refs.size(); ++i) out << (i ? "/" : "") << refs[i];
        out << ")\n";
    }
    out << "\n"
        "# ---- Zynq7 Processing System (PS) — COMMENTED STUB ---------------\n"
        "# The PS DDR/MIO preset is SoM-revision intent and does NOT live in\n"
        "# the carrier netlist, so the PS is left for you to instantiate.\n"
        "# Uncomment to start a block design with a PS7, then APPLY THE SoM'S\n"
        "# PS PRESET (DDR3 timing, MIO, clocks) before generating the wrapper.\n"
        "#\n"
        "# create_bd_design system\n"
        "# set ps [create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0]\n"
        "# # TODO: apply the SoM PS7 preset (board-specific DDR3/MIO/clock config):\n"
        "# #   set_property -dict [list CONFIG.preset {<SoM_preset.xml or board file>}] $ps\n"
        "# #   or: apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \\\n"
        "# #         -config {make_external \"FIXED_IO, DDR\" apply_board_preset \"1\"} $ps\n"
        "# validate_bd_design\n"
        "# save_bd_design\n"
        "# make_wrapper -files [get_files system.bd] -top\n"
        "# add_files -norecurse $script_dir/$project_name/$project_name.srcs/sources_1/bd/system/hdl/system_wrapper.v\n\n"
        "puts \"schgen: project '$project_name' created for part $part; pin constraints loaded from [file tail $xdc_file].\"\n";
    return out.str();
}
}
