"""MPQ4423HGQ-Z — MPQ4423HGQ-Z (QFN-8_L3.0-W3.0-P0.65-TL-MPQ4423HGQ-Z)

Generated by `schgen part add C3192119` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'MPQ4423HGQ-Z'
SAFE_NAME = 'MPQ4423HGQ-Z'
LCSC = 'C3192119'
DESCRIPTION = 'MPQ4423HGQ-Z (QFN-8_L3.0-W3.0-P0.65-TL-MPQ4423HGQ-Z)'
MANUFACTURER = 'MPS(芯源)'
PACKAGE = 'QFN-8_L3.0-W3.0-P0.65-TL-MPQ4423HGQ-Z'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C3192119.pdf'
PRODUCT_URL = ''
LIB_ID = 'MPQ4423HGQ-Z:MPQ4423HGQ-Z'
FOOTPRINT = 'MPQ4423HGQ-Z:MPQ4423HGQ-Z'
MODELS_3D = []

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', 'FB', 'passive'),
    ('2', 'VCC', 'passive'),
    ('3', 'EN/SYNC', 'passive'),
    ('4', 'BST', 'passive'),
    ('5', 'GND', 'passive'),
    ('6', 'SW', 'passive'),
    ('7', 'IN', 'passive'),
    ('8', 'PG', 'passive'),
    ('9', 'EP', 'passive'),
]
