"""RLM12FTCMR020 — RLM12FTCMR020 (R1206)

Generated by `schgen part add C393094` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'RLM12FTCMR020'
SAFE_NAME = 'RLM12FTCMR020'
LCSC = 'C393094'
DESCRIPTION = 'RLM12FTCMR020 (R1206)'
MANUFACTURER = '大毅科技'
PACKAGE = 'R1206'
JLC_CLASS = 'Extended Part'
PREFIX = 'R'
DATASHEET = 'https://www.lcsc.com/datasheet/C393094.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/New-Arrivals_TA-I-Tech-RLM12FTCMR020_C393094.html'
LIB_ID = 'RLM12FTCMR020:RLM12FTCMR020'
FOOTPRINT = 'RLM12FTCMR020:RLM12FTCMR020'
MODELS_3D = ['RLM12FTCMR020.wrl', 'RLM12FTCMR020.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('2', '2', 'passive'),
]
