"""USBLC6-2SC6 — USBLC6-2SC6

Generated by `schgen part add C7519` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'USBLC6-2SC6'
SAFE_NAME = 'USBLC6-2SC6'
LCSC = 'C7519'
DESCRIPTION = 'USBLC6-2SC6'
MANUFACTURER = 'ST(意法半导体)'
PACKAGE = 'SOT-23-6_L2.9-W1.6-P0.95-LS2.8-BL'
JLC_CLASS = 'Extended Part'
PREFIX = 'D'
DATASHEET = 'https://www.lcsc.com/datasheet/C7519.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Diodes-ESD_STMicroelectronics_USBLC6-2SC6_USBLC6-2SC6_C7519.html'
LIB_ID = 'USBLC6-2SC6:USBLC6-2SC6'
FOOTPRINT = 'USBLC6-2SC6:USBLC6-2SC6'
MODELS_3D = ['USBLC6-2SC6.wrl', 'USBLC6-2SC6.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'input'),
    ('2', '2', 'input'),
    ('3', '3', 'input'),
    ('4', '4', 'input'),
    ('5', '5', 'input'),
    ('6', '6', 'input'),
]
