"""CC0603KRX7R9BB104 — 100nF (104) ±10% 50V

Generated by `schgen part add C14663` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'CC0603KRX7R9BB104'
SAFE_NAME = 'CC0603KRX7R9BB104'
LCSC = 'C14663'
DESCRIPTION = '100nF (104) ±10% 50V'
MANUFACTURER = 'YAGEO(国巨)'
PACKAGE = 'C0603'
JLC_CLASS = 'Basic Part'
PREFIX = 'C'
DATASHEET = 'https://www.lcsc.com/datasheet/C14663.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_100nF-104-10-50V_C14663.html'
LIB_ID = 'CC0603KRX7R9BB104:CC0603KRX7R9BB104'
FOOTPRINT = 'CC0603KRX7R9BB104:CC0603KRX7R9BB104'
MODELS_3D = ['CC0603KRX7R9BB104.wrl', 'CC0603KRX7R9BB104.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('2', '2', 'passive'),
]
