"""TYPE-C-31-M-12 — TYPE-C-31-M-12 (USB-C_SMD-TYPE-C-31-M-12_1)

Generated by `schgen part add C165948` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'TYPE-C-31-M-12'
SAFE_NAME = 'TYPE-C-31-M-12'
LCSC = 'C165948'
DESCRIPTION = 'TYPE-C-31-M-12 (USB-C_SMD-TYPE-C-31-M-12_1)'
MANUFACTURER = '韩国韩荣'
PACKAGE = 'USB-C_SMD-TYPE-C-31-M-12_1'
JLC_CLASS = 'Extended Part'
PREFIX = 'USBC'
DATASHEET = 'https://www.lcsc.com/datasheet/C165948.pdf'
PRODUCT_URL = 'https://lcsc.com/product-detail/USB-Type-C_Korean-Hroparts-Elec-TYPE-C-31-M-12_C165948.html'
LIB_ID = 'TYPE-C-31-M-12:TYPE-C-31-M-12'
FOOTPRINT = 'TYPE-C-31-M-12:TYPE-C-31-M-12'
MODELS_3D = ['TYPE-C-31-M-12.wrl', 'TYPE-C-31-M-12.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('A1B12', 'GND', 'passive'),
    ('A4B9', 'VBUS', 'passive'),
    ('B8', 'SBU2', 'passive'),
    ('A5', 'CC1', 'passive'),
    ('B7', 'DN2', 'passive'),
    ('A6', 'DP1', 'passive'),
    ('A7', 'DN1', 'passive'),
    ('B6', 'DP2', 'passive'),
    ('A8', 'SBU1', 'passive'),
    ('B5', 'CC2', 'passive'),
    ('B4A9', 'VBUS', 'passive'),
    ('B1A12', 'GND', 'passive'),
    ('4', 'EH', 'passive'),
    ('3', 'EH', 'passive'),
    ('2', 'EH', 'passive'),
    ('1', 'EH', 'passive'),
]
