"""DS1024-2x6R2 — DS1024-2X6R2 (HDR-TH_12P-P2.54-H-F-R2-C6-S2.54-W10.2)

Generated by `schgen part add C49284652` — DO NOT hand-edit
(carrier/PLAN.md: assets are ALWAYS generated; re-run part add to update).
"""

MPN = 'DS1024-2x6R2'
SAFE_NAME = 'DS1024-2x6R2'
LCSC = 'C49284652'
DESCRIPTION = 'DS1024-2X6R2 (HDR-TH_12P-P2.54-H-F-R2-C6-S2.54-W10.2)'
MANUFACTURER = 'CONNFLY'
PACKAGE = 'HDR-TH_12P-P2.54-H-F-R2-C6-S2.54-W10.2'
JLC_CLASS = 'Extended Part'
PREFIX = 'U'
DATASHEET = 'https://www.lcsc.com/datasheet/C49284652.pdf'
PRODUCT_URL = ''
LIB_ID = 'DS1024-2x6R2:DS1024-2x6R2'
FOOTPRINT = 'DS1024-2x6R2:DS1024-2x6R2'
MODELS_3D = ['DS1024-2x6R2.wrl', 'DS1024-2x6R2.step']

# (number, name, electrical type) — KiCad etypes, from the EasyEDA pin table.
PINS = [
    ('1', '1', 'passive'),
    ('12', '12', 'passive'),
    ('3', '3', 'passive'),
    ('10', '10', 'passive'),
    ('5', '5', 'passive'),
    ('8', '8', 'passive'),
    ('7', '7', 'passive'),
    ('6', '6', 'passive'),
    ('9', '9', 'passive'),
    ('4', '4', 'passive'),
    ('11', '11', 'passive'),
    ('2', '2', 'passive'),
]
